# ==============================================================================
# HtmlReportGenerator.ps1 — Modern Interactive Diagnostic Dashboard for MES_V2
# ==============================================================================

class MesHtmlReportGenerator {
    static [string] GenerateBarcodeReport([hashtable]$traceData, [string]$barcode) {
        $timestamp = (Get-Date).ToString("yyyy-MM-dd HH:mm:ss")
        $setRows = ""
        if ($traceData.SetInfo -and $traceData.SetInfo.Rows.Count -gt 0) {
            foreach ($r in $traceData.SetInfo.Rows) {
                $setRows += "<tr><td>$($r.Barcode)</td><td>$($r.MaterialCode)</td><td>$($r.PONo)</td><td>$($r.DayPlanNo)</td><td>$($r.InputLineCode)</td><td>$($r.CurrentRouteCode)</td><td>$($r.LotDecisionResult)</td></tr>"
            }
        }

        $lotRows = ""
        if ($traceData.MaterialLot -and $traceData.MaterialLot.Rows.Count -gt 0) {
            foreach ($r in $traceData.MaterialLot.Rows) {
                $lotRows += "<tr><td>$($r.LotID)</td><td>$($r.LotNo)</td><td>$($r.MaterialCode)</td><td>$($r.MaterialWarehouseCode)</td><td>$($r.CurrentQty)</td><td>$($r.PackingID)</td><td>$($r.LotAttr10)</td></tr>"
            }
        }

        $routeRows = ""
        if ($traceData.RouteHistory -and $traceData.RouteHistory.Rows.Count -gt 0) {
            foreach ($r in $traceData.RouteHistory.Rows) {
                $routeRows += "<tr><td>$($r.RouteCode)</td><td>$($r.ProdQty)</td><td>$($r.CompleteRoute)</td><td>$($r.WorkerCode)</td><td>$($r.MachineCode)</td><td>$($r.CreateDateTime)</td></tr>"
            }
        }

        $html = @"
<!DOCTYPE html>
<html lang="vi">
<head>
    <meta charset="UTF-8">
    <title>MES V2 Diagnostic Report - $barcode</title>
    <style>
        :root { --primary: #0284c7; --bg: #0f172a; --card: #1e293b; --text: #f8fafc; --accent: #38bdf8; --border: #334155; }
        body { font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif; background: var(--bg); color: var(--text); padding: 24px; margin: 0; }
        .header { display: flex; justify-content: space-between; align-items: center; border-bottom: 2px solid var(--border); padding-bottom: 16px; margin-bottom: 24px; }
        h1 { color: var(--accent); margin: 0; font-size: 24px; }
        .badge { background: #0369a1; padding: 4px 12px; border-radius: 9999px; font-weight: 600; font-size: 14px; }
        .card { background: var(--card); border: 1px solid var(--border); border-radius: 12px; padding: 20px; margin-bottom: 24px; box-shadow: 0 4px 6px -1px rgba(0,0,0,0.3); }
        h2 { color: #e2e8f0; font-size: 18px; margin-top: 0; border-bottom: 1px solid var(--border); padding-bottom: 8px; }
        table { width: 100%; border-collapse: collapse; margin-top: 12px; }
        th { background: #0f172a; color: #94a3b8; text-align: left; padding: 10px 12px; font-size: 13px; text-transform: uppercase; border-bottom: 2px solid var(--border); }
        td { padding: 10px 12px; border-bottom: 1px solid var(--border); font-size: 14px; }
        tr:hover { background: #334155; }
        .footer { text-align: center; color: #64748b; font-size: 12px; margin-top: 40px; }
    </style>
</head>
<body>
    <div class="header">
        <div>
            <h1>⚡ VINATECH MES V2 DIAGNOSTIC DASHBOARD</h1>
            <div style="color: #94a3b8; margin-top: 4px;">Target Key: <strong style="color: #fff;">$barcode</strong> | Generated: $timestamp</div>
        </div>
        <span class="badge">360° Live Trace</span>
    </div>

    <div class="card">
        <h2>1. Thông Tin Sản Xuất (STB_SetInfo)</h2>
        <table>
            <thead><tr><th>Barcode</th><th>MaterialCode</th><th>PONo</th><th>DayPlanNo</th><th>Line</th><th>Route</th><th>OQC Decision</th></tr></thead>
            <tbody>$setRows</tbody>
        </table>
    </div>

    <div class="card">
        <h2>2. Quản Lý Tồn Kho (STB_MaterialLotInfo)</h2>
        <table>
            <thead><tr><th>LotID</th><th>LotNo</th><th>MaterialCode</th><th>Kho</th><th>CurrentQty</th><th>PackingID</th><th>Ngày SX Vendor</th></tr></thead>
            <tbody>$lotRows</tbody>
        </table>
    </div>

    <div class="card">
        <h2>3. Tiến Trình Sản Xuất (STB_ProdRouteHist)</h2>
        <table>
            <thead><tr><th>RouteCode</th><th>ProdQty</th><th>CompleteRoute</th><th>Worker</th><th>Machine</th><th>CreateDateTime</th></tr></thead>
            <tbody>$routeRows</tbody>
        </table>
    </div>

    <div class="footer">
        Generated by Vinatech MES_V2 Engine • Enterprise High-Performance Diagnostic
    </div>
</body>
</html>
"@
        return $html
    }
}
