CREATE TABLE [dbo].[DDLChangeLog_260213] (
    [LogID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [EventType] NVARCHAR(100) NULL DEFAULT ,
    [PostTime] DATETIME NULL DEFAULT ,
    [LoginName] NVARCHAR(256) NULL DEFAULT ,
    [UserName] NVARCHAR(256) NULL DEFAULT ,
    [DatabaseName] NVARCHAR(256) NULL DEFAULT ,
    [ObjectName] NVARCHAR(256) NULL DEFAULT ,
    [CommandText] NVARCHAR(MAX) NULL DEFAULT ,
    [EventXML] XML NULL DEFAULT ,
    [IpAddr] VARCHAR(45) NULL DEFAULT 
);
GO

