CREATE TABLE [dbo].[SpecOverResultTemp] (
    [MaterialCode] VARCHAR(50) NULL DEFAULT ,
    [MaterialName] NVARCHAR(100) NULL DEFAULT ,
    [TestValue] NUMERIC(20,5) NULL DEFAULT ,
    [LSL] NUMERIC(20,5) NULL DEFAULT ,
    [USL] NUMERIC(20,5) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [Barcode] VARCHAR(20) NULL DEFAULT 
);
GO

