CREATE TABLE [dbo].[STB_BomDetail_20190313] (
    [MaterialCode] VARCHAR(50) NOT NULL DEFAULT ,
    [BomVersion] VARCHAR(20) NOT NULL DEFAULT ,
    [ChildMaterialCode] VARCHAR(50) NOT NULL DEFAULT ,
    [ChildBomVersion] VARCHAR(20) NOT NULL DEFAULT ,
    [BomUnit] VARCHAR(10) NULL DEFAULT ,
    [UsedQty] NUMERIC(20,5) NULL DEFAULT ,
    [RouteCode] VARCHAR(20) NULL DEFAULT ,
    [IsOptionItem] BIT NULL DEFAULT ,
    [BomDetailDesc] VARCHAR(200) NULL DEFAULT ,
    [StdCombSec] INT NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT 
);
GO

