CREATE TABLE [dbo].[STB_LineInfo_20200810] (
    [LineCode] VARCHAR(20) NOT NULL DEFAULT ,
    [CompanyCode] VARCHAR(20) NULL DEFAULT ,
    [WorkCenterCode] VARCHAR(20) NULL DEFAULT ,
    [LineName] NVARCHAR(50) NULL DEFAULT ,
    [LineDesc] NVARCHAR(200) NULL DEFAULT ,
    [LineType] VARCHAR(10) NULL DEFAULT ,
    [ErpCode] VARCHAR(20) NULL DEFAULT ,
    [MonitoringGroup] NVARCHAR(50) NULL DEFAULT ,
    [MonitoringName] NVARCHAR(50) NULL DEFAULT ,
    [IsUsed] BIT NULL DEFAULT ,
    [TotalLossTime] NUMERIC(10,3) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT 
);
GO

