CREATE TABLE [dbo].[STB_DefectRepairInfo_20220418] (
    [DefectSummaryNo] VARCHAR(20) NOT NULL DEFAULT ,
    [CompanyCode] VARCHAR(20) NULL DEFAULT ,
    [WorkCenterCode] VARCHAR(20) NULL DEFAULT ,
    [ControlNo] VARCHAR(20) NULL DEFAULT ,
    [PONo] VARCHAR(20) NULL DEFAULT ,
    [DayPlanNo] VARCHAR(20) NULL DEFAULT ,
    [FindJobdate] DATE NULL DEFAULT ,
    [FindShiftCode] VARCHAR(1) NULL DEFAULT ,
    [FindTimeCode] VARCHAR(2) NULL DEFAULT ,
    [FindLineCode] VARCHAR(20) NULL DEFAULT ,
    [FindRouteCode] VARCHAR(20) NULL DEFAULT ,
    [FindSubRouteCode] VARCHAR(20) NULL DEFAULT ,
    [FindFacilityRouteCode] VARCHAR(20) NULL DEFAULT ,
    [CauseJobDate] DATE NULL DEFAULT ,
    [CauseShiftCode] VARCHAR(1) NULL DEFAULT ,
    [CauseTimeCode] VARCHAR(2) NULL DEFAULT ,
    [CauseLineCode] VARCHAR(20) NULL DEFAULT ,
    [CauseFacilityRouteCode] VARCHAR(20) NULL DEFAULT ,
    [MaterialCode] VARCHAR(50) NULL DEFAULT ,
    [BomVersion] VARCHAR(10) NULL DEFAULT ,
    [FindDateTime] DATETIME NULL DEFAULT ,
    [DefectCauseType] VARCHAR(1) NULL DEFAULT ,
    [DutyCostCenterCode] VARCHAR(20) NULL DEFAULT ,
    [DutyVendorCode] VARCHAR(20) NULL DEFAULT ,
    [DefectCode] VARCHAR(20) NULL DEFAULT ,
    [DefectCauseCode] VARCHAR(20) NULL DEFAULT ,
    [DefectCauseDetailCode] VARCHAR(20) NULL DEFAULT ,
    [DefectExtDesc] NVARCHAR(200) NULL DEFAULT ,
    [RepairType] VARCHAR(10) NULL DEFAULT ,
    [RepairUserID] VARCHAR(20) NULL DEFAULT ,
    [RepairDateTime] DATETIME NULL DEFAULT ,
    [RepairDesc] NVARCHAR(MAX) NULL DEFAULT ,
    [DefectQty] NUMERIC(20,5) NULL DEFAULT ,
    [RepairQty] NUMERIC(20,5) NULL DEFAULT ,
    [LossQty] NUMERIC(20,5) NULL DEFAULT ,
    [FileID] BIGINT NULL DEFAULT ,
    [DRIExtText01] NVARCHAR(200) NULL DEFAULT ,
    [DRIExtText02] NVARCHAR(200) NULL DEFAULT ,
    [DRIExtText03] NVARCHAR(200) NULL DEFAULT ,
    [IsDelete] VARCHAR(1) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT 
);
GO

