CREATE TABLE [dbo].[ScreenLayoutInfoLog] (
    [LogID] BIGINT IDENTITY(1,1) NOT NULL DEFAULT ,
    [EventType] NVARCHAR(100) NULL DEFAULT ,
    [PostTime] DATETIME NULL DEFAULT (getdate()),
    [Name] VARCHAR(50) NOT NULL DEFAULT ,
    [Version] INT NOT NULL DEFAULT ,
    [DeveloperVersion] VARCHAR(20) NULL DEFAULT ,
    [BefLayout] VARBINARY(MAX) NULL DEFAULT ,
    [AftLayout] VARBINARY(MAX) NULL DEFAULT ,
    [BefXmlLayout] NVARCHAR(MAX) NULL DEFAULT ,
    [AftXmlLayout] NVARCHAR(MAX) NULL DEFAULT ,
    [Description] NVARCHAR(MAX) NULL DEFAULT ,
    [Snapshot] VARBINARY(MAX) NULL DEFAULT 
);
GO

