CREATE TABLE [dbo].[STB_VendorScreenInfo_20220410] (
    [SystemCode] VARCHAR(20) NOT NULL DEFAULT ,
    [Name] VARCHAR(50) NOT NULL DEFAULT ,
    [TCode] VARCHAR(10) NULL DEFAULT ,
    [IsFolder] BIT NULL DEFAULT ,
    [IsNeverClose] BIT NULL DEFAULT ,
    [ParentName] VARCHAR(50) NULL DEFAULT ,
    [Caption] NVARCHAR(100) NOT NULL DEFAULT ,
    [ShowAfterStart] BIT NULL DEFAULT ,
    [ShowInMenu] BIT NULL DEFAULT ,
    [CurrentVersion] INT NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT ,
    [IsDelete] BIT NULL DEFAULT ,
    [DeleteDateTime] DATETIME NULL DEFAULT ,
    [DeleteUserID] VARCHAR(20) NULL DEFAULT ,
    [AccessType] VARCHAR(50) NULL DEFAULT ,
    [Icon] VARBINARY(MAX) NULL DEFAULT ,
    [CheckOutUserID] VARCHAR(20) NULL DEFAULT 
);
GO

