CREATE TABLE [dbo].[STB_DDLHistory] (
    [SeqNo] BIGINT IDENTITY(1,1) NOT NULL DEFAULT ,
    [EventDate] DATETIME NULL DEFAULT (getdate()),
    [EventType] NVARCHAR(100) NULL DEFAULT ,
    [EventDDL] NVARCHAR(MAX) NULL DEFAULT ,
    [DatabaseName] NVARCHAR(255) NULL DEFAULT ,
    [SchemaName] NVARCHAR(255) NULL DEFAULT ,
    [ObjectName] NVARCHAR(255) NULL DEFAULT ,
    [HostName] NVARCHAR(255) NULL DEFAULT ,
    [IPAddress] VARCHAR(32) NULL DEFAULT ,
    [ProgramName] NVARCHAR(255) NULL DEFAULT ,
    [LoginName] NVARCHAR(255) NULL DEFAULT 
);
GO

