CREATE TABLE [dbo].[STB_ScreenObjects] (
    [Id] BIGINT IDENTITY(1,1) NOT NULL DEFAULT ,
    [ScreenName] VARCHAR(50) NOT NULL DEFAULT ,
    [ObjectType] VARCHAR(50) NOT NULL DEFAULT ,
    [ObjectName] VARCHAR(255) NOT NULL DEFAULT ,
    [Caption] NVARCHAR(MAX) NULL DEFAULT ,
    [Description] NVARCHAR(MAX) NULL DEFAULT 
);
GO

