CREATE TABLE [dbo].[STB_PopupGrid] (
    [Name] NVARCHAR(50) NOT NULL DEFAULT ,
    [Description] NVARCHAR(MAX) NOT NULL DEFAULT ,
    [Layout] VARBINARY(MAX) NOT NULL DEFAULT ,
    [XmlLayout] NVARCHAR(MAX) NOT NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT 
);
GO

