CREATE TABLE [dbo].[STB_UserType] (
    [UserType] VARCHAR(20) NOT NULL DEFAULT ,
    [UserTypeName] NVARCHAR(50) NOT NULL DEFAULT ,
    [IsUse] BIT NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT 
);
GO

