CREATE TABLE [dbo].[STB_PDAMenu] (
    [Name] VARCHAR(50) NOT NULL DEFAULT ,
    [ParentName] VARCHAR(50) NULL DEFAULT ,
    [DefaultCaption] NVARCHAR(20) NULL DEFAULT ,
    [TypeName] VARCHAR(50) NULL DEFAULT ,
    [IsUse] BIT NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT 
);
GO

