CREATE TABLE [dbo].[STB_VOC] (
    [SeqNo] BIGINT NOT NULL DEFAULT ,
    [UserID] VARCHAR(20) NULL DEFAULT ,
    [Phone] VARCHAR(20) NULL DEFAULT ,
    [Email] NVARCHAR(100) NULL DEFAULT ,
    [Title] NVARCHAR(200) NULL DEFAULT ,
    [Contents] NVARCHAR(MAX) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [ReplyUserID] VARCHAR(20) NULL DEFAULT ,
    [ReplyContents] NVARCHAR(MAX) NULL DEFAULT ,
    [ReplyDateTime] DATETIME NULL DEFAULT ,
    [Snapshot] VARBINARY(MAX) NULL DEFAULT 
);
GO

