CREATE TABLE [dbo].[STB_Help] (
    [Id] VARCHAR(20) NOT NULL DEFAULT ,
    [ParentId] VARCHAR(20) NULL DEFAULT ,
    [Title] NVARCHAR(100) NOT NULL DEFAULT ,
    [Contents] VARBINARY(MAX) NULL DEFAULT ,
    [IsFolder] BIT NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] NCHAR(10) NULL DEFAULT 
);
GO

