CREATE TABLE [dbo].[STB_BoardComment] (
    [CommentNo] VARCHAR(20) NOT NULL DEFAULT ,
    [ThreadNo] VARCHAR(20) NOT NULL DEFAULT ,
    [OrgCommentNo] VARCHAR(20) NULL DEFAULT ,
    [Comment] NVARCHAR(MAX) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(20) NULL DEFAULT 
);
GO

