CREATE TABLE [dbo].[STB_Diagrams] (
    [SeqNo] BIGINT NOT NULL DEFAULT ,
    [SystemCode] VARCHAR(20) NULL DEFAULT ,
    [Title] NVARCHAR(200) NULL DEFAULT ,
    [FileID] BIGINT NULL DEFAULT ,
    [Description] NVARCHAR(MAX) NULL DEFAULT ,
    [Keywords] NVARCHAR(MAX) NULL DEFAULT ,
    [IsDelete] BIT NULL DEFAULT ((0)),
    [DeleteDateTime] DATETIME NULL DEFAULT ,
    [DeleteUserID] VARCHAR(20) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT 
);
GO

