CREATE TABLE [dbo].[STB_SlackMessage] (
    [Id] BIGINT IDENTITY(1,1) NOT NULL DEFAULT ,
    [Url] VARCHAR(200) NOT NULL DEFAULT ,
    [Title] NVARCHAR(200) NULL DEFAULT ,
    [Text] NVARCHAR(100) NULL DEFAULT ,
    [Author] NVARCHAR(50) NULL DEFAULT ,
    [User] NVARCHAR(50) NULL DEFAULT ,
    [BarColor] VARCHAR(20) NULL DEFAULT ,
    [Fields] NVARCHAR(MAX) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [IsSend] BIT NULL DEFAULT ,
    [SendDateTime] DATETIME NULL DEFAULT 
);
GO

