CREATE TABLE [dbo].[STB_Message] (
    [MessageId] VARCHAR(20) NOT NULL DEFAULT ,
    [TargetUserID] VARCHAR(20) NULL DEFAULT ,
    [MessageType] VARCHAR(20) NULL DEFAULT ,
    [Title] NVARCHAR(100) NULL DEFAULT ,
    [Message] NVARCHAR(MAX) NULL DEFAULT ,
    [IsRead] BIT NULL DEFAULT ,
    [IPAddress] VARCHAR(20) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(20) NULL DEFAULT 
);
GO

