CREATE PROC us_VN_ADD_HONGKONG
@pPARTNO NVARCHAR(50) = NULL,
@pLOTNO NVARCHAR(50) = NULL,
@pPARTNAME NVARCHAR(50) = NULL,
@pQTY INT = NULL,
@pVENDOR NVARCHAR(50) = NULL,
@pPRODUCTIONDATE NVARCHAR(50) = NULL,
@pGROSSWEIGHT NVARCHAR(50) = NULL,
@pPONOLINE NVARCHAR(50) = NULL,
@pProcessUserID VARCHAR(20) = NULL
AS
BEGIN
		IF @pLOTNO IS NOT NULL
	BEGIN

	INSERT INTO STB_VN_STAMP_HONGKONG
					(
						PARTNO,
						LOTNO,
						PARTNAME,
						QTY,
						VENDOR,
						PRODUCTIONDATE,
						GROSSWEIGHT,
						PONOLINE,
						CREATEUSERID,
						CREATEDATETIME
					)
					VALUES
					(
						@pPARTNO,
						@pLOTNO,
						@pPARTNAME,
						@pQTY,
						@pVENDOR,
						@pPRODUCTIONDATE,
						@pGROSSWEIGHT,
						@pPONOLINE,
						@pProcessUserID,
						GETDATE()
					)

	END

	
	SELECT TOP(1) PARTNO,
	LOTNO,
	PARTNAME,
	QTY,
	VENDOR,
	PRODUCTIONDATE,
	GROSSWEIGHT,
	PONOLINE,
	0 AS LabelQty,
	'Report' AS CommandType,
	CREATEDATETIME,
	CREATEUSERID
	FROM STB_VN_STAMP_HONGKONG WITH(NOLOCK)
	ORDER BY CREATEDATETIME DESC


END

--SELECT * FROM STB_VN_STAMP_HONGKONG