import json

master_data = {
  "systemInfo": {
    "name": "HikCentral Professional — Vinatech ELV Infrastructure Portal",
    "factory": "VINATECH VINA (Hưng Yên Factory)",
    "address": "Lô CN7.4-5 Khu công nghiệp sạch, Xã Xuân Trúc, Tỉnh Hưng Yên",
    "designer": "DOUL ASIA CO., LTD",
    "contractor": "WORLDSTAR INTERNATIONAL J.S.C",
    "drawingVersion": "v5.2 (Release 2026.06.15)",
    "serverIp": "192.168.184.250",
    "webPort": 443,
    "dbServer": "192.168.184.250,1433",
    "dbName": "HCP_DATA",
    "dbUser": "hikcentral",
    "totalDevices": 22,
    "activeEmployees": 14,
    "defaultShift": "HC (08:00 - 17:30)"
  },
  "devices": [
    # 1F FACTORY TA/AC (Sheet 42/30)
    {
      "id": "AC-01",
      "code": "AC_1",
      "name": "Cửa Phòng Trưng Bày & Sảnh Đón Khách (101)",
      "nameEn": "Showroom Entrance Door (101)",
      "floor": "1F",
      "floorName": "Tầng 1 Nhà Xưởng",
      "room": "101 SHOW ROOM / Sảnh Chính (Trục 1X-3X / 1Y-3Y)",
      "type": "AC",
      "typeLabel": "Kiểm Soát Cửa (Access Control)",
      "icon": "🚪",
      "lockType": "Khóa Hút Từ (Magnetic Lock 280kg)",
      "accessories": ["Nút Exit Cảm Ứng", "Cảm Biến Cửa", "Nút Khẩn Cấp Break Glass"],
      "controller": "RACK Rack_1 (VP Xưởng 3)",
      "serialNo": "GS8090991",
      "ipAddress": "192.168.184.101",
      "status": "online",
      "x": 86,
      "y": 68
    },
    {
      "id": "AC-02",
      "code": "AC_2",
      "name": "Cửa Phòng Điều Khiển Sản Xuất (128)",
      "nameEn": "Control Room Door (128)",
      "floor": "1F",
      "floorName": "Tầng 1 Nhà Xưởng",
      "room": "128 CONTROL / 129 MIXER 1 (Trục 4X-6X / 1Y-3Y)",
      "type": "AC",
      "typeLabel": "Kiểm Soát Cửa (Access Control)",
      "icon": "🎛️",
      "lockType": "Khóa Thả Chốt (Drop Bolt Lock)",
      "accessories": ["Nút Exit", "Cảm Biến Cửa", "Nút Đập Khẩn Cấp"],
      "controller": "RACK_02 (P. Điều Khiển)",
      "serialNo": "GS8090992",
      "ipAddress": "192.168.184.102",
      "status": "online",
      "x": 64.5,
      "y": 52
    },
    {
      "id": "AC-03",
      "code": "AC_3",
      "name": "Cửa Phòng Trực PCCC & QC Room (151)",
      "nameEn": "Fire Control & QC Room Door (151)",
      "floor": "1F",
      "floorName": "Tầng 1 Nhà Xưởng",
      "room": "151 FFT ROOM (P. Trực PCCC) / 136 QC ROOM (Trục 15X-18X / 1Y-3Y)",
      "type": "AC",
      "typeLabel": "Kiểm Soát Cửa (Access Control)",
      "icon": "🧯",
      "lockType": "Khóa Hút Từ (Magnetic Lock)",
      "accessories": ["Nút Exit", "Cảm Biến Trạng Thái Cửa"],
      "controller": "RACK Rack_3 (Khu QC/PCCC)",
      "serialNo": "GS8090995",
      "ipAddress": "192.168.184.103",
      "status": "online",
      "x": 46,
      "y": 74
    },
    {
      "id": "TA-01",
      "code": "TA_1",
      "name": "Máy Chấm Công Sảnh Chính (171 STAIR-1)",
      "nameEn": "Main Lobby Time Attendance",
      "floor": "1F",
      "floorName": "Tầng 1 Nhà Xưởng",
      "room": "171 STAIR-1 / Cầu Thang 1 & Showroom 101",
      "type": "TA",
      "typeLabel": "Chấm Công Chuyên Dụng (Time Attendance)",
      "icon": "⏱️",
      "lockType": "Không gắn khóa (Ghi nhận chấm công)",
      "accessories": ["Chân đế treo tường 1.2m", "Nguồn dự phòng UPS"],
      "controller": "RACK Rack_1",
      "serialNo": "GS8090998",
      "ipAddress": "192.168.184.121",
      "status": "online",
      "x": 86,
      "y": 44
    },
    {
      "id": "TA-02",
      "code": "TA_2",
      "name": "Máy Chấm Công Căn Tin & Nghỉ Ca (115A)",
      "nameEn": "Canteen & Rest Room Time Attendance (115A)",
      "floor": "1F",
      "floorName": "Tầng 1 Nhà Xưởng",
      "room": "115A PHÒNG PHỤ TRỢ (P. Nghỉ Ca Nam/Nữ & Căn Tin)",
      "type": "TA",
      "typeLabel": "Chấm Công Chuyên Dụng (Time Attendance)",
      "icon": "🍽️",
      "lockType": "Không gắn khóa",
      "accessories": ["Treo tường 1.2m", "Cáp UTP Cat6"],
      "controller": "RACK_02",
      "serialNo": "GS8090999",
      "ipAddress": "192.168.184.122",
      "status": "online",
      "x": 35,
      "y": 74
    },
    {
      "id": "TA-03",
      "code": "TA_3",
      "name": "Máy Chấm Công Locker & P. Thay Đồ (116)",
      "nameEn": "Locker & Changing Room Time Attendance (116)",
      "floor": "1F",
      "floorName": "Tầng 1 Nhà Xưởng",
      "room": "116 LOCKER (P. Thay Đồ) / 136 SHOES LOCKER",
      "type": "TA",
      "typeLabel": "Chấm Công Chuyên Dụng (Time Attendance)",
      "icon": "🧪",
      "lockType": "Không gắn khóa",
      "accessories": ["Treo tường 1.2m"],
      "controller": "RACK_02",
      "serialNo": "GS8091000",
      "ipAddress": "192.168.184.123",
      "status": "online",
      "x": 40.5,
      "y": 34
    },
    {
      "id": "TA-04",
      "code": "TA_4",
      "name": "Máy Chấm Công Kho 1 (104 WAREHOUSE)",
      "nameEn": "Warehouse 1 Time Attendance (104)",
      "floor": "1F",
      "floorName": "Tầng 1 Nhà Xưởng",
      "room": "104 WAREHOUSE (Kho 1)",
      "type": "TA",
      "typeLabel": "Chấm Công Chuyên Dụng (Time Attendance)",
      "icon": "📦",
      "lockType": "Không gắn khóa",
      "accessories": ["Treo tường 1.2m"],
      "controller": "RACK Rack_3",
      "serialNo": "GS8091001",
      "ipAddress": "192.168.184.124",
      "status": "online",
      "x": 15,
      "y": 64
    },
    {
      "id": "TA-05",
      "code": "TA_5",
      "name": "Máy Chấm Công Logistics Dock (105)",
      "nameEn": "Logistics Dock Time Attendance (105)",
      "floor": "1F",
      "floorName": "Tầng 1 Nhà Xưởng",
      "room": "105 LOGISTIC DOCK (Kho Xuất Nhập)",
      "type": "TA",
      "typeLabel": "Chấm Công Chuyên Dụng (Time Attendance)",
      "icon": "🚚",
      "lockType": "Không gắn khóa",
      "accessories": ["Treo tường 1.2m chống bụi IP54"],
      "controller": "RACK Rack_3",
      "serialNo": "GS8091003",
      "ipAddress": "192.168.184.125",
      "status": "online",
      "x": 15,
      "y": 38
    },

    # 1.5F FACTORY TA/AC (Sheet 42/31)
    {
      "id": "AC-04",
      "code": "AC_4",
      "name": "Cửa Khối Văn Phòng 1.5F (201 OFFICE)",
      "nameEn": "1.5F Office Entrance Door (201)",
      "floor": "1.5F",
      "floorName": "Tầng 1.5 Nhà Xưởng",
      "room": "201 OFFICE / 202 DIRECTOR (P. Giám Đốc)",
      "type": "AC",
      "typeLabel": "Kiểm Soát Cửa (Access Control)",
      "icon": "🏢",
      "lockType": "Khóa Hút Từ (Magnetic Lock)",
      "accessories": ["Nút Exit Cảm Ứng", "Cảm Biến Cửa", "Nút Khẩn Cấp"],
      "controller": "RACK Rack_Main (Tầng 2 via Riser)",
      "serialNo": "GS8090994",
      "ipAddress": "192.168.184.104",
      "status": "online",
      "x": 50,
      "y": 55
    },

    # 2F FACTORY TA/AC (Sheet 42/32)
    {
      "id": "AC-05",
      "code": "AC_5",
      "name": "Cửa Phòng IT & Máy Chủ Server (304 IT ROOM)",
      "nameEn": "IT & Server Room Door (304)",
      "floor": "2F",
      "floorName": "Tầng 2 Nhà Xưởng",
      "room": "304 IT ROOM (Nơi đặt RACK MAIN 42U)",
      "type": "AC",
      "typeLabel": "Kiểm Soát Cửa (Access Control)",
      "icon": "💻",
      "lockType": "Khóa Thả Chốt An Ninh Cao (High-Security Drop Bolt)",
      "accessories": ["Nút Exit", "Cảm Biến Báo Động", "Nút Khẩn Cấp"],
      "controller": "RACK Rack_Main (Local 42U)",
      "serialNo": "GS8090993",
      "ipAddress": "192.168.184.105",
      "status": "active_traffic",
      "x": 29,
      "y": 55
    },
    {
      "id": "AC-06",
      "code": "AC_6",
      "name": "Cửa Khối Văn Phòng Chính 2F (302 OFFICE)",
      "nameEn": "2F Main Office Door (302)",
      "floor": "2F",
      "floorName": "Tầng 2 Nhà Xưởng",
      "room": "302 OFFICE (HR, Kế toán, Mua hàng) / 303 DIRECTOR",
      "type": "AC",
      "typeLabel": "Kiểm Soát Cửa (Access Control)",
      "icon": "👔",
      "lockType": "Khóa Hút Từ (Magnetic Lock 280kg)",
      "accessories": ["Nút Exit Cảm Ứng", "Cảm Biến Trạng Thái Cửa"],
      "controller": "RACK Rack_Main (Local 42U)",
      "serialNo": "GS8091002",
      "ipAddress": "192.168.184.106",
      "status": "active_traffic",
      "x": 69,
      "y": 55
    },

    # FLAP BARRIER E-PARKING (Sheet 42/35)
    {
      "id": "AC-10",
      "code": "AC_10",
      "name": "Cổng Flap Barrier CHIỀU VÀO Làn 1",
      "floor": "PARKING",
      "floorName": "Nhà Xe E-Parking",
      "room": "Nhà Xe E-Parking (Làn Vào 1)",
      "type": "BARRIER",
      "typeLabel": "Mở Cổng Flap Barrier",
      "icon": "🚧",
      "lockType": "Cơ cấu Barrier mở tự động (Motor Servo)",
      "accessories": ["Cảm biến hồng ngoại", "Đèn LED chỉ hướng"],
      "controller": "RACK Rack_5 (E-Parking)",
      "serialNo": "GS8091010",
      "ipAddress": "192.168.184.150",
      "status": "standby",
      "x": 18,
      "y": 34
    },
    {
      "id": "AC-11",
      "code": "AC_11",
      "name": "Cổng Flap Barrier CHIỀU VÀO Làn 2",
      "floor": "PARKING",
      "floorName": "Nhà Xe E-Parking",
      "room": "Nhà Xe E-Parking (Làn Vào 2)",
      "type": "BARRIER",
      "typeLabel": "Mở Cổng Flap Barrier",
      "icon": "🚧",
      "lockType": "Cơ cấu Barrier mở tự động",
      "accessories": ["Cảm biến hồng ngoại"],
      "controller": "RACK Rack_5 (E-Parking)",
      "serialNo": "GS8091011",
      "ipAddress": "192.168.184.151",
      "status": "standby",
      "x": 34,
      "y": 34
    },
    {
      "id": "AC-12",
      "code": "AC_12",
      "name": "Cổng Flap Barrier CHIỀU VÀO Làn 3",
      "floor": "PARKING",
      "floorName": "Nhà Xe E-Parking",
      "room": "Nhà Xe E-Parking (Làn Vào 3)",
      "type": "BARRIER",
      "typeLabel": "Mở Cổng Flap Barrier",
      "icon": "🚧",
      "lockType": "Cơ cấu Barrier mở tự động",
      "accessories": ["Cảm biến hồng ngoại"],
      "controller": "RACK Rack_5 (E-Parking)",
      "serialNo": "GS8091012",
      "ipAddress": "192.168.184.152",
      "status": "standby",
      "x": 50,
      "y": 34
    },
    {
      "id": "AC-13",
      "code": "AC_13",
      "name": "Cổng Flap Barrier CHIỀU VÀO Làn 4",
      "floor": "PARKING",
      "floorName": "Nhà Xe E-Parking",
      "room": "Nhà Xe E-Parking (Làn Vào 4)",
      "type": "BARRIER",
      "typeLabel": "Mở Cổng Flap Barrier",
      "icon": "🚧",
      "lockType": "Cơ cấu Barrier mở tự động",
      "accessories": ["Cảm biến hồng ngoại"],
      "controller": "RACK Rack_5 (E-Parking)",
      "serialNo": "GS8091013",
      "ipAddress": "192.168.184.153",
      "status": "standby",
      "x": 66,
      "y": 34
    },
    {
      "id": "AC-14",
      "code": "AC_14",
      "name": "Cổng Flap Barrier CHIỀU VÀO Làn 5 (VIP)",
      "floor": "PARKING",
      "floorName": "Nhà Xe E-Parking",
      "room": "Nhà Xe E-Parking (Làn Vào 5 - VIP/Khách)",
      "type": "BARRIER",
      "typeLabel": "Mở Cổng Flap Barrier",
      "icon": "⭐",
      "lockType": "Cơ cấu Barrier mở tự động",
      "accessories": ["Cảm biến hồng ngoại"],
      "controller": "RACK Rack_5 (E-Parking)",
      "serialNo": "GS8091014",
      "ipAddress": "192.168.184.154",
      "status": "standby",
      "x": 82,
      "y": 34
    },
    {
      "id": "AC-15",
      "code": "AC_15",
      "name": "Cổng Flap Barrier CHIỀU RA Làn 1",
      "floor": "PARKING",
      "floorName": "Nhà Xe E-Parking",
      "room": "Nhà Xe E-Parking (Làn Ra 1)",
      "type": "BARRIER",
      "typeLabel": "Mở Cổng Flap Barrier",
      "icon": "🚧",
      "lockType": "Cơ cấu Barrier mở tự động",
      "accessories": ["Cảm biến hồng ngoại"],
      "controller": "RACK Rack_5 (E-Parking)",
      "serialNo": "GS8091015",
      "ipAddress": "192.168.184.155",
      "status": "standby",
      "x": 18,
      "y": 77
    },
    {
      "id": "AC-16",
      "code": "AC_16",
      "name": "Cổng Flap Barrier CHIỀU RA Làn 2",
      "floor": "PARKING",
      "floorName": "Nhà Xe E-Parking",
      "room": "Nhà Xe E-Parking (Làn Ra 2)",
      "type": "BARRIER",
      "typeLabel": "Mở Cổng Flap Barrier",
      "icon": "🚧",
      "lockType": "Cơ cấu Barrier mở tự động",
      "accessories": ["Cảm biến hồng ngoại"],
      "controller": "RACK Rack_5 (E-Parking)",
      "serialNo": "GS8091016",
      "ipAddress": "192.168.184.156",
      "status": "standby",
      "x": 34,
      "y": 77
    },
    {
      "id": "AC-17",
      "code": "AC_17",
      "name": "Cổng Flap Barrier CHIỀU RA Làn 3",
      "floor": "PARKING",
      "floorName": "Nhà Xe E-Parking",
      "room": "Nhà Xe E-Parking (Làn Ra 3)",
      "type": "BARRIER",
      "typeLabel": "Mở Cổng Flap Barrier",
      "icon": "🚧",
      "lockType": "Cơ cấu Barrier mở tự động",
      "accessories": ["Cảm biến hồng ngoại"],
      "controller": "RACK Rack_5 (E-Parking)",
      "serialNo": "GS8091017",
      "ipAddress": "192.168.184.157",
      "status": "standby",
      "x": 50,
      "y": 77
    },
    {
      "id": "AC-18",
      "code": "AC_18",
      "name": "Cổng Flap Barrier CHIỀU RA Làn 4",
      "floor": "PARKING",
      "floorName": "Nhà Xe E-Parking",
      "room": "Nhà Xe E-Parking (Làn Ra 4)",
      "type": "BARRIER",
      "typeLabel": "Mở Cổng Flap Barrier",
      "icon": "🚧",
      "lockType": "Cơ cấu Barrier mở tự động",
      "accessories": ["Cảm biến hồng ngoại"],
      "controller": "RACK Rack_5 (E-Parking)",
      "serialNo": "GS8091018",
      "ipAddress": "192.168.184.158",
      "status": "standby",
      "x": 66,
      "y": 77
    },
    {
      "id": "AC-19",
      "code": "AC_19",
      "name": "Cổng Flap Barrier CHIỀU RA Làn 5 (VIP)",
      "floor": "PARKING",
      "floorName": "Nhà Xe E-Parking",
      "room": "Nhà Xe E-Parking (Làn Ra 5 - VIP/Khách)",
      "type": "BARRIER",
      "typeLabel": "Mở Cổng Flap Barrier",
      "icon": "⭐",
      "lockType": "Cơ cấu Barrier mở tự động",
      "accessories": ["Cảm biến hồng ngoại"],
      "controller": "RACK Rack_5 (E-Parking)",
      "serialNo": "GS8091019",
      "ipAddress": "192.168.184.159",
      "status": "standby",
      "x": 82,
      "y": 77
    },
    {
      "id": "USB-01",
      "code": "USB_1",
      "name": "Trạm Đăng Ký Khuôn Mặt & Thẻ USB (P. IT)",
      "floor": "2F",
      "floorName": "Tầng 2 Nhà Xưởng",
      "room": "304 IT ROOM (Phòng IT & Máy Chủ)",
      "type": "AC",
      "typeLabel": "Đầu Đọc Đăng Ký USB (Enrollment)",
      "icon": "🔌",
      "lockType": "Đầu đọc cắm bàn làm việc USB 3.0",
      "accessories": ["Cáp kết nối USB", "Chân đế bàn"],
      "controller": "Workstation IT Client",
      "serialNo": "GS8091099",
      "ipAddress": "Local USB (192.168.184.250)",
      "status": "online",
      "x": 52,
      "y": 55
    }
  ],
  "itRacks": [
    {
      "id": "RACK_MAIN",
      "code": "RACK-MAIN-42U",
      "name": "Tủ RACK IT & Server Trung Tâm (42U D1000)",
      "floor": "2F",
      "floorName": "Tầng 2 Nhà Xưởng",
      "room": "304 IT ROOM (Phòng IT & Server Room) [Trục 1X–2X / 2Y–3Y]",
      "type": "IT_RACK",
      "typeLabel": "Tủ Server Trung Tâm 42U",
      "icon": "🖥️",
      "dimensions": "600x1000x2100mm (42U)",
      "equipment": [
        "Firewall Fortinet FortiGate 100E (HA Ready)",
        "Core Switch L3 24-Port GbE + 4 SFP+",
        "Distribution Switch Cisco L2 48-Port",
        "Switch L2 24-Port",
        "Switch Access Control L2 08-Port",
        "Switch Flap Barrier L2 16-Port",
        "Tổng Đài IP PBX Server (100 Extensions)",
        "ODF Cáp Quang 52-Port + ISP ODF 08-Port",
        "Bộ Lưu Điện Online UPS 10kVA"
      ],
      "ipAddress": "192.168.184.250",
      "power": "220V Dual Feed + Online UPS 10kVA",
      "status": "online",
      "temp": "21.0°C",
      "x": 18,
      "y": 62
    },
    {
      "id": "RACK_PA",
      "code": "RACK-PA-27U",
      "name": "Tủ RACK Âm Thanh PA Trung Tâm (27U D800)",
      "floor": "2F",
      "floorName": "Tầng 2 Nhà Xưởng",
      "room": "304 IT ROOM — Cạnh RACK MAIN 42U",
      "type": "IT_RACK",
      "typeLabel": "Tủ Âm Thanh PA 27U",
      "icon": "📢",
      "dimensions": "600x800x1400mm (27U)",
      "equipment": [
        "Program Timer TT-104B (Hẹn Giờ Chuông Tự Động)",
        "CD / Media Player BGM",
        "Main Power Amplifier 1000W 100V Line",
        "Amplifier Extension",
        "Remote Microphone Selector",
        "Monitor Panel & ODF Quang 4-Port"
      ],
      "ipAddress": "192.168.184.240",
      "power": "220V UPS Backup",
      "status": "online",
      "temp": "22.0°C",
      "x": 20,
      "y": 62
    },
    {
      "id": "RACK_01",
      "code": "RACK-01-1F",
      "name": "Tủ Phân Phối Tầng 1 — VP Xưởng 3 (10U)",
      "floor": "1F",
      "floorName": "Tầng 1 Nhà Xưởng",
      "room": "109 W.S OFFICE 3 / 171 STAIR-1 [Trục 7X–11X / 8Y–10Y]",
      "type": "IT_RACK",
      "typeLabel": "Tủ Treo Tường Tầng 1 (10U)",
      "icon": "🗄️",
      "dimensions": "625x550x600mm (10U)",
      "equipment": [
        "NW-CCTV ODF 08-Port",
        "Cisco L2 Switch 48-Port",
        "L2 Switch 08-Port"
      ],
      "ipAddress": "192.168.184.201",
      "power": "220V UPS Backup",
      "status": "online",
      "temp": "24.2°C",
      "x": 52,
      "y": 15
    },
    {
      "id": "RACK_02",
      "code": "RACK-02-1F",
      "name": "Tủ Phân Phối Tầng 1 — P. Điều Khiển (10U)",
      "floor": "1F",
      "floorName": "Tầng 1 Nhà Xưởng",
      "room": "128 CONTROL / 129 MIXER 1 [Trục 4X–6X / 1Y–3Y]",
      "type": "IT_RACK",
      "typeLabel": "Tủ Treo Tường Tầng 1 (10U)",
      "icon": "🗄️",
      "dimensions": "625x550x600mm (10U)",
      "equipment": [
        "NW-CCTV ODF 08-Port",
        "L2 Switch 08-Port"
      ],
      "ipAddress": "192.168.184.202",
      "power": "220V UPS Backup",
      "status": "online",
      "temp": "25.0°C",
      "x": 27,
      "y": 48
    },
    {
      "id": "RACK_03",
      "code": "RACK-03-1F",
      "name": "Tủ Phân Phối Tầng 1 — QC & PCCC (10U)",
      "floor": "1F",
      "floorName": "Tầng 1 Nhà Xưởng",
      "room": "136 QC ROOM / 151 FFT ROOM (P. Trực PCCC) [Trục 15X–18X / 1Y–3Y]",
      "type": "IT_RACK",
      "typeLabel": "Tủ Treo Tường Tầng 1 (10U)",
      "icon": "🗄️",
      "dimensions": "625x550x600mm (10U)",
      "equipment": [
        "NW-CCTV ODF 12-Port",
        "L2 Switch 24-Port",
        "AC L2 Switch 08-Port",
        "L2 Switch 08-Port"
      ],
      "ipAddress": "192.168.184.203",
      "power": "220V UPS Backup",
      "status": "online",
      "temp": "24.5°C",
      "x": 92,
      "y": 58
    },
    {
      "id": "RACK_04",
      "code": "RACK-04-2F",
      "name": "Tủ Phân Phối Tầng 2 — Module Working (10U)",
      "floor": "2F",
      "floorName": "Tầng 2 Nhà Xưởng",
      "room": "311 MODULE WORKING / 313 W.S OFFICE 2 [Trục 6X–11X / 7Y–10Y]",
      "type": "IT_RACK",
      "typeLabel": "Tủ Treo Tường Tầng 2 (10U)",
      "icon": "🗄️",
      "dimensions": "625x550x600mm (10U)",
      "equipment": [
        "NW-CCTV ODF 08-Port",
        "Cisco L2 Switch 48-Port"
      ],
      "ipAddress": "192.168.184.204",
      "power": "220V UPS Backup",
      "status": "online",
      "temp": "23.8°C",
      "x": 43,
      "y": 21
    },
    {
      "id": "RACK_05",
      "code": "RACK-05-EPARK",
      "name": "Tủ Phân Phối Nhà Xe E-Parking (10U)",
      "floor": "PARKING",
      "floorName": "Nhà Xe E-Parking",
      "room": "Nhà Xe E-Parking (Mặt Trước Xưởng)",
      "type": "IT_RACK",
      "typeLabel": "Tủ Nhà Xe (10U)",
      "icon": "🅿️",
      "dimensions": "625x550x600mm (10U)",
      "equipment": [
        "NW-CCTV ODF 16-Port",
        "L2 Switch 08-Port",
        "AC L2 Switch 16-Port (10 Làn Flap Barrier)"
      ],
      "ipAddress": "192.168.184.205",
      "power": "220V UPS Backup",
      "status": "online",
      "temp": "27.0°C",
      "x": 52,
      "y": 35
    },
    {
      "id": "RACK_06",
      "code": "RACK-06-GH1",
      "name": "Tủ RACK Nhà Bảo Vệ 1 — Cổng Chính (10U)",
      "floor": "PARKING",
      "floorName": "Cổng Chính (Main Gate)",
      "room": "Nhà Bảo Vệ 1 (Cổng Chính Đường KCN)",
      "type": "IT_RACK",
      "typeLabel": "Tủ Nhà Bảo Vệ 1 (10U)",
      "icon": "🛡️",
      "dimensions": "625x550x600mm (10U)",
      "equipment": [
        "NW-CCTV ODF 08-Port",
        "Cisco L2 Switch 08-Port"
      ],
      "ipAddress": "192.168.184.206",
      "power": "220V UPS Backup",
      "status": "online",
      "temp": "26.5°C",
      "x": 57,
      "y": 39
    },
    {
      "id": "RACK_07",
      "code": "RACK-07-GH2",
      "name": "Tủ RACK Nhà Bảo Vệ 2 — Cổng Logistics (10U)",
      "floor": "PARKING",
      "floorName": "Cổng Logistics",
      "room": "Nhà Bảo Vệ 2 (Cổng Xe Tải Kho 104)",
      "type": "IT_RACK",
      "typeLabel": "Tủ Nhà Bảo Vệ 2 (10U)",
      "icon": "🚛",
      "dimensions": "625x550x600mm (10U)",
      "equipment": [
        "NW-CCTV ODF 16-Port",
        "L2 Switch 08-Port"
      ],
      "ipAddress": "192.168.184.207",
      "power": "220V UPS Backup",
      "status": "online",
      "temp": "26.8°C",
      "x": 39,
      "y": 68
    },
    {
      "id": "RACK_08",
      "code": "RACK-08-GH3",
      "name": "Tủ RACK Nhà Bảo Vệ 3 — Cổng Xe Máy (10U)",
      "floor": "PARKING",
      "floorName": "Cổng Xe Máy",
      "room": "Nhà Bảo Vệ 3 (Lối vào Nhà Xe E-Parking)",
      "type": "IT_RACK",
      "typeLabel": "Tủ Nhà Bảo Vệ 3 (10U)",
      "icon": "🏍️",
      "dimensions": "625x550x600mm (10U)",
      "equipment": [
        "NW-CCTV ODF 08-Port",
        "Cisco L2 Switch 08-Port"
      ],
      "ipAddress": "192.168.184.208",
      "power": "220V UPS Backup",
      "status": "online",
      "temp": "27.2°C",
      "x": 22,
      "y": 68
    },
    {
      "id": "RACK_09",
      "code": "RACK-09-UTIL",
      "name": "Tủ RACK Trạm Tiện Ích & XLNT (10U IP66)",
      "floor": "PARKING",
      "floorName": "Khu Tiện Ích",
      "room": "Trạm Xử Lý Nước Thải & Trạm Bơm PCCC",
      "type": "IT_RACK",
      "typeLabel": "Tủ Tiện Ích Ngoài Trời (10U)",
      "icon": "♻️",
      "dimensions": "625x550x600mm (10U IP66)",
      "equipment": [
        "CCTV ODF 04-Port",
        "L2 Switch 24-Port"
      ],
      "ipAddress": "192.168.184.209",
      "power": "220V UPS Backup",
      "status": "online",
      "temp": "28.0°C",
      "x": 51,
      "y": 52
    }
  ],
  "wifiAccessPoints": [
    {
      "id": "AP-01",
      "code": "AP-01",
      "name": "Wi-Fi AP Sảnh Chính & Showroom 101",
      "floor": "1F",
      "room": "101 SHOW ROOM / Sảnh Đón Khách",
      "ipAddress": "192.168.184.71",
      "status": "online",
      "x": 86,
      "y": 25,
      "clients": 18
    },
    {
      "id": "AP-02",
      "code": "AP-02",
      "name": "Wi-Fi AP Căn Tin & Khu Nghỉ Ca 115A",
      "floor": "1F",
      "room": "115A P. Nghỉ Ca & Căn Tin",
      "ipAddress": "192.168.184.72",
      "status": "online",
      "x": 55,
      "y": 80,
      "clients": 42
    },
    {
      "id": "AP-03",
      "code": "AP-03",
      "name": "Wi-Fi AP Khối Xưởng 1.5F (P. 201)",
      "floor": "1.5F",
      "room": "201 OFFICE (Văn Phòng 1.5F)",
      "ipAddress": "192.168.184.73",
      "status": "online",
      "x": 50,
      "y": 45,
      "clients": 24
    },
    {
      "id": "AP-04",
      "code": "AP-04",
      "name": "Wi-Fi AP P. Giám Đốc 1.5F (P. 202)",
      "floor": "1.5F",
      "room": "202 DIRECTOR (P. Giám Đốc 1.5F)",
      "ipAddress": "192.168.184.74",
      "status": "online",
      "x": 75,
      "y": 35,
      "clients": 8
    },
    {
      "id": "AP-05",
      "code": "AP-05",
      "name": "Wi-Fi AP P. Họp 1.5F (P. 201)",
      "floor": "1.5F",
      "room": "P. HỌP 1 & 2 (1.5F)",
      "ipAddress": "192.168.184.75",
      "status": "online",
      "x": 35,
      "y": 60,
      "clients": 16
    },
    {
      "id": "AP-06",
      "code": "AP-06",
      "name": "Wi-Fi AP Khối Văn Phòng 2F Khu A (302)",
      "floor": "2F",
      "room": "302 OFFICE (Văn Phòng Chính 2F)",
      "ipAddress": "192.168.184.76",
      "status": "online",
      "x": 70,
      "y": 35,
      "clients": 36
    },
    {
      "id": "AP-07",
      "code": "AP-07",
      "name": "Wi-Fi AP Khối Văn Phòng 2F Khu B (302)",
      "floor": "2F",
      "room": "302 OFFICE & 303 DIRECTOR (P. Giám Đốc 2F)",
      "ipAddress": "192.168.184.77",
      "status": "online",
      "x": 80,
      "y": 70,
      "clients": 28
    },
    {
      "id": "AP-08",
      "code": "AP-08",
      "name": "Wi-Fi AP Khu Nhà Xe E-Parking",
      "floor": "PARKING",
      "room": "Nhà Xe E-Parking",
      "ipAddress": "192.168.184.78",
      "status": "online",
      "x": 40,
      "y": 50,
      "clients": 19
    }
  ],
  "networkOutlets": [
    # 1F Floor Outlets (58 SET total, Sheet 42/06)
    {
      "id": "OUT-FL-1F-1",
      "code": "58x OUTLET_FL",
      "name": "58 Cụm Ổ Cắm Mạng Âm Sàn (Floor Outlets Tầng 1)",
      "floor": "1F",
      "room": "Xưởng Sản Xuất (Lắp Ráp 1, 2, Định Hình 1 & QC)",
      "type": "OUTLET_FLOOR",
      "typeLabel": "Ổ Cắm Âm Sàn (58 SET Floor Outlet 01 LAN)",
      "icon": "🔌",
      "qty": 58,
      "ports": "58x RJ45 Cat6 UTP",
      "mountType": "Hộp Đồng Âm Sàn Nắp Mở (Floor Box)",
      "rack": "Cấp từ RACK_01 (43 port) & RACK_04 (15 port)",
      "x": 50,
      "y": 50,
      "status": "active"
    },
    # 1F Wall Outlets (Sheet 42/06)
    {
      "id": "OUT-WL-1F-1",
      "code": "4x OUTLET_2L",
      "name": "4 Cụm Ổ Cắm Đôi Âm Tường (Outlet 02 LAN)",
      "floor": "1F",
      "room": "Phòng Điều Khiển 128 & PCCC 151",
      "type": "OUTLET_WALL",
      "typeLabel": "Ổ Cắm Âm Tường Đôi (02 LAN)",
      "icon": "🖧",
      "qty": 4,
      "ports": "8x RJ45 Cat6 UTP",
      "mountType": "Mặt Nạ 2 Port Âm Tường",
      "rack": "RACK_02 & RACK_03",
      "x": 64.5,
      "y": 30,
      "status": "active"
    },
    {
      "id": "OUT-WL-1F-2",
      "code": "22x OUTLET_1L",
      "name": "22 Ổ Cắm Mạng Đơn Âm Tường (Outlet 01 LAN)",
      "floor": "1F",
      "room": "Kho 104, Dock 105, Showroom 101, VP Xưởng 1, 2, 3, 4",
      "type": "OUTLET_WALL",
      "typeLabel": "Ổ Cắm Âm Tường Đơn (01 LAN)",
      "icon": "🖧",
      "qty": 22,
      "ports": "22x RJ45 Cat6 UTP",
      "mountType": "Mặt Nạ 1 Port Âm Tường",
      "rack": "RACK_01, RACK_02, RACK_03",
      "x": 30,
      "y": 60,
      "status": "active"
    },
    # 1.5F Outlets (Sheet 42/06)
    {
      "id": "OUT-15F-1",
      "code": "4x OUTLET_4L",
      "name": "4 Cụm Ổ Cắm 4 Port Bàn Làm Việc 1.5F (P. 201)",
      "floor": "1.5F",
      "room": "201 OFFICE (Khối Văn Phòng 1.5F)",
      "type": "OUTLET_WALL",
      "typeLabel": "Cụm Ổ Cắm 4 Port (04 LAN)",
      "icon": "🖧",
      "qty": 4,
      "ports": "16x RJ45 Cat6 UTP",
      "mountType": "Hộp Bàn Làm Việc 4 Port",
      "rack": "RACK_MAIN via Riser",
      "x": 50,
      "y": 50,
      "status": "active"
    },
    {
      "id": "OUT-15F-2",
      "code": "6x OUTLET_1L",
      "name": "6 Ổ Cắm Mạng Âm Tường 1.5F (P. 202 Giám Đốc)",
      "floor": "1.5F",
      "room": "202 DIRECTOR & P. Họp 1.5F",
      "type": "OUTLET_WALL",
      "typeLabel": "Ổ Cắm Âm Tường (01 LAN)",
      "icon": "🖧",
      "qty": 6,
      "ports": "6x RJ45 Cat6 UTP",
      "mountType": "Mặt Nạ 1 Port Âm Tường",
      "rack": "RACK_MAIN via Riser",
      "x": 75,
      "y": 35,
      "status": "active"
    },
    # 2F Outlets (Sheet 42/06)
    {
      "id": "OUT-2F-1",
      "code": "2x OUTLET_4L",
      "name": "2 Cụm Ổ Cắm 4 Port Bàn Làm Việc 2F (P. 302)",
      "floor": "2F",
      "room": "302 OFFICE (Khối Văn Phòng Chính 2F)",
      "type": "OUTLET_WALL",
      "typeLabel": "Cụm Ổ Cắm 4 Port (04 LAN)",
      "icon": "🖧",
      "qty": 2,
      "ports": "8x RJ45 Cat6 UTP",
      "mountType": "Hộp Bàn Làm Việc 4 Port",
      "rack": "RACK_MAIN 42U",
      "x": 70,
      "y": 55,
      "status": "active"
    },
    {
      "id": "OUT-2F-2",
      "code": "1x OUTLET_6L",
      "name": "1 Cụm Ổ Cắm 6 Port Bàn Họp Chính 2F",
      "floor": "2F",
      "room": "Phòng Họp Lớn 2F (P. 305)",
      "type": "OUTLET_WALL",
      "typeLabel": "Cụm Ổ Cắm Bàn Họp (06 LAN)",
      "icon": "🖧",
      "qty": 1,
      "ports": "6x RJ45 Cat6 UTP",
      "mountType": "Hộp Đa Năng Bàn Họp 6 Port",
      "rack": "RACK_MAIN 42U",
      "x": 45,
      "y": 62,
      "status": "active"
    },
    {
      "id": "OUT-2F-3",
      "code": "15x OUTLET_1L",
      "name": "15 Ổ Cắm Mạng Âm Tường P. IT 304 & P. Giám Đốc 303",
      "floor": "2F",
      "room": "304 IT ROOM & 303 DIRECTOR",
      "type": "OUTLET_WALL",
      "typeLabel": "Ổ Cắm Âm Tường (01 LAN)",
      "icon": "🖧",
      "qty": 15,
      "ports": "15x RJ45 Cat6 UTP",
      "mountType": "Mặt Nạ 1 Port Âm Tường",
      "rack": "RACK_MAIN 42U",
      "x": 28,
      "y": 55,
      "status": "active"
    },
    # Guardhouse Outlets (3 SET Outlet 01 LAN - 01 TEL, Sheet 42/06)
    {
      "id": "OUT-GH-1",
      "code": "1x LAN+TEL (GH1)",
      "name": "Ổ Cắm Mạng & Thoại IP Phone Nhà Bảo Vệ 1 (Cổng Chính)",
      "floor": "PARKING",
      "room": "Nhà Bảo Vệ 1 (Cổng Chính Đường KCN)",
      "type": "OUTLET_TEL",
      "typeLabel": "Ổ Cắm Mạng + Thoại (01 LAN + 01 TEL)",
      "icon": "☎️",
      "qty": 1,
      "ports": "1x LAN RJ45 + 1x TEL RJ11",
      "mountType": "Mặt Nạ 2 Port Âm Tường",
      "rack": "RACK_06 (Guardhouse 1)",
      "x": 20,
      "y": 75,
      "status": "active"
    },
    {
      "id": "OUT-GH-2",
      "code": "1x LAN+TEL (GH2)",
      "name": "Ổ Cắm Mạng & Thoại IP Phone Nhà Bảo Vệ 2 (Cổng Logistics)",
      "floor": "PARKING",
      "room": "Nhà Bảo Vệ 2 (Cổng Xe Tải Kho 104)",
      "type": "OUTLET_TEL",
      "typeLabel": "Ổ Cắm Mạng + Thoại (01 LAN + 01 TEL)",
      "icon": "☎️",
      "qty": 1,
      "ports": "1x LAN RJ45 + 1x TEL RJ11",
      "mountType": "Mặt Nạ 2 Port Âm Tường",
      "rack": "RACK_07 (Guardhouse 2)",
      "x": 5,
      "y": 50,
      "status": "active"
    },
    {
      "id": "OUT-GH-3",
      "code": "1x LAN+TEL (GH3)",
      "name": "Ổ Cắm Mạng & Thoại IP Phone Nhà Bảo Vệ 3 (Cổng Xe Máy)",
      "floor": "PARKING",
      "room": "Nhà Bảo Vệ 3 (Lối vào Nhà Xe E-Parking)",
      "type": "OUTLET_TEL",
      "typeLabel": "Ổ Cắm Mạng + Thoại (01 LAN + 01 TEL)",
      "icon": "☎️",
      "qty": 1,
      "ports": "1x LAN RJ45 + 1x TEL RJ11",
      "mountType": "Mặt Nạ 2 Port Âm Tường",
      "rack": "RACK_08 (Guardhouse 3)",
      "x": 80,
      "y": 75,
      "status": "active"
    }
  ],
  "employees": [
    {"id": "12", "name": "Đức_Vinatech", "dept": "WSI", "role": "Kỹ Sư Hệ Thống / Admin", "face": True, "access": "Door_2F, All Door", "attGroup": "OFFICE"},
    {"id": "31904003", "name": "Hợp Nguyễn Thị", "dept": "HS Team", "role": "Nhân Viên Vận Hành", "face": True, "access": "Door_2F", "attGroup": "OFFICE"},
    {"id": "5908432579", "name": "Huy Khang_Vinatech", "dept": "WSI", "role": "Kỹ Sư Phát Triển", "face": True, "access": "Door_2F, All Door", "attGroup": "OFFICE"},
    {"id": "1", "name": "binhwsi", "dept": "WSI", "role": "Kỹ Thuật Viên", "face": True, "access": "Door_2F", "attGroup": "WSI Standard"},
    {"id": "4", "name": "cao cuong wsi", "dept": "WSI", "role": "Kỹ Thuật Viên", "face": True, "access": "Door_2F", "attGroup": "WSI Standard"},
    {"id": "6", "name": "hieu.wsi", "dept": "WSI", "role": "Kỹ Thuật Viên", "face": True, "access": "Door_2F", "attGroup": "WSI Standard"},
    {"id": "5", "name": "quan.wsi", "dept": "WSI", "role": "Kỹ Thuật Viên", "face": True, "access": "Door_2F", "attGroup": "WSI Standard"},
    {"id": "8", "name": "tibh.wsi", "dept": "WSI", "role": "Kỹ Thuật Viên", "face": True, "access": "Door_2F", "attGroup": "WSI Standard"},
    {"id": "11", "name": "chuc", "dept": "WSI", "role": "Kỹ Thuật Viên", "face": True, "access": "Door_2F", "attGroup": "WSI Standard"},
    {"id": "3", "name": "hung", "dept": "WSI", "role": "Kỹ Thuật Viên", "face": True, "access": "Door_2F", "attGroup": "WSI Standard"},
    {"id": "10", "name": "tuobg", "dept": "WSI", "role": "Kỹ Thuật Viên", "face": True, "access": "Door_2F", "attGroup": "WSI Standard"},
    {"id": "4027883121", "name": "hhhh", "dept": "WSI", "role": "Nhân Viên Thử Nghiệm", "face": True, "access": "Door_2F", "attGroup": "WSI Standard"},
    {"id": "1234567890", "name": "Jack Dawson", "dept": "All Department", "role": "Chuyên Viên Quốc Tế", "face": False, "access": "All Door", "attGroup": "General"}
  ],
  "sopSteps": [
    {"step": 1, "title": "Đăng nhập Hệ thống Quản trị", "titleEn": "System Login", "icon": "🔐", "desc": "Truy cập giao diện Web Client (https://192.168.184.250/#/portal) bằng tài khoản quản trị (admin / vinatech@2026)."},
    {"step": 2, "title": "Khai báo Nhân sự & Sinh trắc học", "titleEn": "Personnel Registration", "icon": "👤", "desc": "Vào mục Con người (Person) -> Thêm nhân viên -> Nhập Mã NV, Họ tên, Phòng ban, nạp ảnh Face ID hoặc quẹt thẻ qua đầu đọc USB (USB_1)."},
    {"step": 3, "title": "Cấu hình Phân quyền Cửa (Access Level)", "titleEn": "Access Level Configuration", "icon": "🚪", "desc": "Gán quyền mở cửa theo vị trí làm việc (ví dụ: Door_2F gồm AC_5 và AC_6). Hệ thống tự đồng bộ xuống các bộ điều khiển RACK_MAIN, Rack_1, Rack_2, Rack_3, Rack_5."},
    {"step": 4, "title": "Khởi tạo Nhóm Chấm công & Lịch trình", "titleEn": "Attendance Group & Schedule", "icon": "⏰", "desc": "Khai báo ca Hành chính (HC: 08:00 - 17:30) kèm thời gian giải lao trưa và chọn các máy chấm công có hiệu lực (TA_1..TA_5)."},
    {"step": 5, "title": "Cơ chế Tự động Tính công 04:00 AM", "titleEn": "Auto Calculation", "icon": "🤖", "desc": "HikCentral tự động tính toán tổng giờ công và giờ OT vào 04:00 AM mỗi ngày, cho phép xuất file báo cáo Excel/CSV."}
  ]
}

with open("data.json", "w", encoding="utf-8") as f:
    json.dump(master_data, f, ensure_ascii=False, indent=2)

print("Saved 100% verified master data to data.json")
