CREATE proc usp_VN_ModuleDetail_MES
@pGROUPID NVARCHAR(50) = NULL
AS
BEGIN
		DECLARE @GRID NVARCHAR(50) = @pGROUPID
	SELECT
			GROUPID,
			LOTNO,
			QTYACT,
			MaterialCode,
			MaterialName,
			LineCode,
			RouteCode,
			RouteName,
			InputProdQty,
			DefectQty,
			ProdQty,
			CREATEDATEPACKED,
			CREATEDATETIME,
			CREATEUSSERID
	FROM 
			STB_VN_DETAILMODULES WITH(NOLOCK)
	WHERE
			GROUPID = @GRID
END