
CREATE PROC [dbo].[usp_Update_Group_VN_SCRAP_WEIGHSCALE_PRODUCTIONS] --EXEC  usp_Update_Group_VN_SCRAP_WEIGHSCALE_PRODUCTIONS '2022-06-08','92005006','92005006'
@CREATEGROUPID NVARCHAR(50),
@UID NVARCHAR(50),
@BARCODE NVARCHAR(200)
AS
BEGIN

      UPDATE STB_VN_SCRAP_WEIGHSCALE_PRODUCTIONS

	  SET 
			FLAG = 1,
		    GROUPID = 'VINATECH'+@CREATEGROUPID+@UID

	  WHERE

			BARCODE = @BARCODE
END


--SELECT * FROM STB_VN_SCRAP_WEIGHSCALE_PRODUCTIONS WHERE USERID = '92005006'

-- DELETE  STB_VN_SCRAP_WEIGHSCALE_PRODUCTIONS WHERE USERID = '92005006'