CREATE PROC usp_VN_CheckLine_Currently
@EMPLOYEESID NVARCHAR(50),
@CODELINE NVARCHAR(50)
AS
BEGIN
		SELECT
				EMPLOYEESID,
				EMPLOYEESNAME,
				LINECURRENTLY,
				LINETRANSFER,
				START_DATES,
				START_TIME,
				END_DATES,
				END_TIME
		FROM 
				STB_VN_EMPLOYEESTRANSFER WITH(NOLOCK)
		WHERE
				EMPLOYEESID = @EMPLOYEESID AND END_DATES IS NULL AND CODELINETRANSFER <> @CODELINE
END