CREATE PROC [dbo].[usp_VN_QC_LOTNO_MODULE_DETAIL] -- exec usp_VN_QC_LOTNO_MODULE_DETAIL 'MVVKQ033R010515'
@pBarcode NVARCHAR(50) = NULL
AS
BEGIN
		DECLARE @Bar VARCHAR(100) = CASE WHEN ISNULL(@pBarcode,'') = '' THEN '%' ELSE @pBarcode END

		SELECT
				T1.ID,
				T1.LOTNO,
				T1.NAMETYPE,
				T1.NUMBERTYPE,
				T1.STATUSPSS
		FROM
			STB_VN_QC_LOTNO_MODULE_DETAIL T1 WITH(NOLOCK)
		
		WHERE
			T1.LOTNO = @Bar 

		GROUP BY 
				T1.ID,
				T1.LOTNO,
				T1.NAMETYPE,
				T1.NUMBERTYPE,
				T1.STATUSPSS
		
		--AND  T1.STATUSPSS = N'Pass'
END

--select * from STB_VN_QC_LOTNO_MODULE_DETAIL
-- delete  STB_VN_QC_LOTNO_MODULE_DETAIL where lotno ='MVVKQ033R010515'
-- delete STB_QC_LOTNO_MODULE where lotno ='MVVKQ033R010515'


-- select * from STB_QC_LOTNO_MODULE where lotno ='MVVKQ033R010515'