CREATE PROC usp_Delete_VN_SCRAP_WEIGHSCALE_PRODUCTIONS
@BARCODE NVARCHAR(200),
@UID NVARCHAR(50),
@TIMEDELETE NVARCHAR(50)
AS
BEGIN
		UPDATE STB_VN_SCRAP_WEIGHSCALE_PRODUCTIONS
		SET STATUSDELETE = N'Bản ghi dữ liệu này đã được xóa bởi' + ' ' + @UID + N', vào thời gian là:' + ' ' + @TIMEDELETE
		WHERE
				BARCODE = @BARCODE
END