CREATE PROC [dbo].[usp_VN_Import_Module]
AS
BEGIN
		SELECT
				GROUPID,
				LOTNO,
				QTY,
				VOL,
				FWAR,
				PARTNO,
				SIZE,
				EXPORT,
				TYPEACTION_EXPORT,
				DESCRIPTIONS_EXPORT,
				IMPORT,
				TYPEACTION_IMPORT,
				DESCRIPTIONS_IMPORT,
				COUNTRY
		FROM

			STB_VN_MODULE_EXPORT_IMPORT WITH (NOLOCK)

			WHERE 
					EXPORT = 1 AND TYPEACTION_EXPORT = N'Xuất'
END


--select * from STB_VN_MODULE_EXPORT_IMPORT