CREATE PROC [dbo].[usp_VN_EmployeesTransfer] -- exec usp_VN_EmployeesTransfer'32107012'
@EMPLOYEESID NVARCHAR(50)
AS
BEGIN
		SELECT
			  EMPLOYEESID,
			  EMPLOYEESNAME,
			  DEPARTMENTNAME,
			  CodeDepartment
		FROM
			 STB_VN_Employees WITH(NOLOCK)
		WHERE
			 EMPLOYEESID = @EMPLOYEESID
END