CREATE PROC [dbo].[usp_VN_department]
AS
BEGIN
		CREATE TABLE #T (DEPARTMENT NVARCHAR(50) NULL, Isused BIT NULL)

		INSERT INTO #T  (DEPARTMENT, Isused) VALUES (N'SẢN XUẤT',1)
		INSERT INTO #T  (DEPARTMENT, Isused) VALUES (N'QUẢN LÝ SẢN XUẤT',1)
		INSERT INTO #T  (DEPARTMENT, Isused) VALUES (N'KỸ THUẬT SẢN PHẨM',1)
		INSERT INTO #T  (DEPARTMENT, Isused) VALUES (N'CHẤT LƯỢNG',1)
		INSERT INTO #T  (DEPARTMENT, Isused) VALUES (N'THIẾT BỊ',1)
		INSERT INTO #T  (DEPARTMENT, Isused) VALUES (N'R&D',1)

		SELECT DEPARTMENT FROM #T WHERE Isused = 1

		DROP TABLE #T
END