CREATE PROC usp_View_SecurityBN
@SECURITYAPPERVOER_BN NVARCHAR(50)
AS
BEGIN
		SELECT
				GROUPID,
				Barcode,
				RouteCode,
				RouteName,
				MaterialCode,
				MaterialName,
				LineCode,
				LineName,
				ProdQty,
				PERSONAPPROVER_BG,
				CASE
						WHEN PERSONSTATUSAPPROVER_BG = 1 THEN N'Đã duyệt'
				ELSE ''
				END AS 'PERSONSTATUSAPPROVER_BG'
		FROM
			STB_VN_STAGES_TRANSFER WITH(NOLOCK)
		WHERE
				PERSONSTATUSAPPROVER_BG = 1 AND SECURITYAPPERVOER_BG = @SECURITYAPPERVOER_BN
END

