
CREATE PROC [dbo].[usp_view_groupfinished] -- EXEC usp_view_groupfinished 'VNBN790826202503050940'
@pGROUPID NVARCHAR(50) = NULL
AS
BEGIN
	IF(@pGROUPID IS NOT NULL)
		BEGIN
				SELECT 
				 T1.GROUPID,
				 COUNT(T1.GROUPID) AS TOTALBOX,
				 SUM(CAST(T1.PACKQTY AS INT)) AS QTY,
				 T1.CUSTOMERS,
				 T1.SOINVOICES
			--INTO #Tbl_SumTotal
			FROM STB_VN_FINISHGOOD_OUT_TEMPORARY T1
			WHERE T1.GROUPID = @pGROUPID
			GROUP BY t1.GROUPID,CUSTOMERS,SOINVOICES
		END
	ELSE
		BEGIN
			SELECT 
					 T1.GROUPID,
					 COUNT(T1.GROUPID) AS TOTALBOX,
					 SUM(CAST(T1.PACKQTY AS INT)) AS QTY,
					  T1.CUSTOMERS,
					T1.SOINVOICES
				--INTO #Tbl_SumTotal
				FROM STB_VN_FINISHGOOD_OUT_TEMPORARY T1
				WHERE T1.GROUPID IS NOT NULL
				GROUP BY t1.GROUPID,CUSTOMERS,SOINVOICES
		END
END