CREATE PROC usp_VN_OuterInter
AS
BEGIN
		CREATE TABLE #Tbl(NAMES NVARCHAR(50) NOT NULL PRIMARY KEY(NAMES))
		INSERT INTO #Tbl (NAMES) VALUES (N'Outer BOX PACKING STICKER')
		INSERT INTO #Tbl (NAMES) VALUES (N'Inter BOX PACKING STICKER')

		SELECT * FROM #Tbl

		DROP TABLE #Tbl
END