CREATE PROC [dbo].[usp_View_PlanVN] --- exec usp_View_PlanVN '2023-01-01','2023-12-31',''
@pFrom DATETIME = null,
@pTo DATETIME = null,
@pType NVARCHAR(50) = NULL
AS
BEGIN
IF @pType IS NOT NULL
BEGIN
SELECT 
				ID,
				DATEPLAN,
				MONTHPLAN,
				MODEL,
				GROUPSIZE,
				DAILYTARGET,
				REMARK,
				TYPEDATA,
				CREATEDATETIME,
				CREATEUSERID,
				CHANGEDATETIME,
				CHANGEUSERID
				
		FROM
		
				STB_PLAN_VN WITH(NOLOCK)

		WHERE

			CONVERT(DATE,CREATEDATETIME) BETWEEN @pFrom AND @pTo AND TYPEDATA =  @pType
END
ELSE 
BEGIN

SELECT 
				ID,
				DATEPLAN,
				MONTHPLAN,
				MODEL,
				GROUPSIZE,
				DAILYTARGET,
				REMARK,
				TYPEDATA,
				CREATEDATETIME,
				CREATEUSERID,
				CHANGEDATETIME,
				CHANGEUSERID
		FROM
		
				STB_PLAN_VN WITH(NOLOCK)

		WHERE

				CREATEDATETIME BETWEEN @pFrom AND @pTo
END
		
				
END


-- select * from  STB_PLAN_VN where createuserid = 'nguyennha'

-- SELECT * FROM STB_PLAN_VN WHERE MONTHPLAN = '12'

-- UPDATE STB_PLAN_VN SET CreateDateTime= '2023-01-30 11:50:03.817' WHERE ID = '4737'

-- SELECT * FROM STB_PLAN_VN WHERE CREATEDATETIME BETWEEN '2023-01-01' AND '2023-12-31' 

-- DELETE STB_PLAN_VN

-- update STB_PLAN_VN SET CREATEDATETIME = '' WHERE ID = ''