CREATE PROC usp_DoCreateCursorSyntax
AS
BEGIN
	SELECT 'DECLARE cur CURSOR FOR' UNION ALL
	SELECT '' UNION ALL
	SELECT '{대상쿼리}' UNION ALL
	SELECT 'OPEN cur' UNION ALL
	SELECT '' UNION ALL
	SELECT 'FETCH NEXT FROM cur INTO {대상변수}' UNION ALL
	SELECT '' UNION ALL
	SELECT 'WHILE @@FETCH_STATUS = 0' UNION ALL
	SELECT 'BEGIN' UNION ALL
	SELECT '	{처리로직}' UNION ALL
	SELECT '' UNION ALL
	SELECT '	FETCH NEXT FROM cur INTO {대상변수}' UNION ALL
	SELECT 'END' UNION ALL
	SELECT '' UNION ALL
	SELECT 'CLOSE cur' UNION ALL
	SELECT 'DEALLOCATE cur'
END