CREATE PROC [dbo].[usp_VN_Update_EmpMove]
@EMPLOYEESID NVARCHAR(50),
@CODELINETRANSFER NVARCHAR(50),
@END_DATES NVARCHAR(50),
@END_TIME NVARCHAR(20),
@CHANGEBY NVARCHAR(50),
@CHANGEDATE NVARCHAR(50),
@TOTALMINUTES NVARCHAR(50),
@TOTALHOUR NVARCHAR(50)
AS
BEGIN
		DECLARE @CNT INT
		SELECT @CNT = COUNT(*) FROM STB_VN_EMPLOYEESTRANSFER WHERE EMPLOYEESID = @EMPLOYEESID AND END_DATES IS NULL AND CODELINETRANSFER = @CODELINETRANSFER

		IF @CNT > 0

			BEGIN
					DECLARE @STARTTIME DATETIME
			SELECT 
					@STARTTIME = START_TIME

			FROM    STB_VN_EMPLOYEESTRANSFER

			WHERE   EMPLOYEESID = @EMPLOYEESID AND END_DATES IS NULL AND CODELINETRANSFER = @CODELINETRANSFER

					UPDATE STB_VN_EMPLOYEESTRANSFER

					SET END_DATES = @END_DATES, END_TIME =  @END_TIME,
						CHANGEBY = @CHANGEBY, DATECHAGE = @CHANGEDATE,
						 TOTALMINUTES = @TOTALMINUTES,--CAST(DATEDIFF(ss, @STARTTIME, @END_TIME) / 3600 AS VARCHAR(10)) + CAST((DATEDIFF(ss, @STARTTIME, @END_TIME) -  3600 * (DATEDIFF(ss, @STARTTIME, @END_TIME) / 3600)) / 60 AS VARCHAR(10)),
						--DATEDIFF(HOUR,RIGHT(@END_DATES,8),RIGHT(@STARTTIME,8)),
						TOTALHOUR  = @TOTALHOUR --CONVERT(INT, '' + replace(CAST(DATEDIFF(ss, @STARTTIME, @END_TIME) / 3600 AS VARCHAR(10)) + CAST((DATEDIFF(ss, @STARTTIME, @END_TIME) -  3600 * (DATEDIFF(ss, @STARTTIME, @END_TIME) / 3600)) / 60 AS VARCHAR(10)), '0', '')) / 60.0

					WHERE  EMPLOYEESID = @EMPLOYEESID AND END_DATES IS NULL

			END
END

-- SELECT * FROM STB_VN_EMPLOYEESTRANSFER
-- DELETE STB_VN_EMPLOYEESTRANSFER

--select convert(decimal(12,4),getdate()) 

--select cast(

-- cast(datepart(year,getdate()) as varchar) + -- get the year

-- right('0' + cast (datepart(month,getdate()) as varchar),2) + --get the month and zero pad

-- right('0' + cast (datepart(day,getdate()) as varchar),2) --get the day and zero pad

--as numeric(10,0)) -- convert back to a numeric(10,0)

--  select    from STB_VN_EMPLOYEESTRANSFER

--alter table 

--ALTER TABLE STB_VN_EMPLOYEESTRANSFER
--ALTER COLUMN TOTALHOUR NVARCHAR(50);


--UPDATE STB_VN_FINISHGOODS SET CreateDate = '2022-01-11 16:48:57.890' WHERE IDCODE IN ('10032','10034','10033','10031','10030','10029','10028','10042','10041','10040','10039','10038','10037','10036','10035')


-- SELECT * FROM STB_VN_EMPLOYEESTRANSFER

--DELETE STB_VN_EMPLOYEESTRANSFER WHERE ID = '586'