CREATE PROC [dbo].[usp_view_details_fisgood_TemB751]
@pGROUPID NVARCHAR(50) = NULL
AS
BEGIN
SELECT
		 T1.GROUPID,
		 COUNT(T1.GROUPID) AS TOTALBOX,
		 SUM(CAST(T1.PACKQTY AS INT)) AS QTY,
		 T1.PRODUCTIONSIZE,
		 T1.MATERIALCODE,
		 T1.PARTNO,
		 T1.CUSTOMERS,
		 'PartLabel' AS LabelType,                        --2020.04.08
		'FoxConn자재라벨' AS LabelFormatName,			
		'Report' AS CommandType,
		 (SELECT COUNT(GROUPID) FROM STB_VN_FINISHGOOD_OUT_TEMPORARY WHERE GROUPID = T1.GROUPID) AS TOT_TOTALBOX,
		 (SELECT SUM(CAST(PACKQTY AS INT)) FROM STB_VN_FINISHGOOD_OUT_TEMPORARY WHERE GROUPID = T1.GROUPID) AS TOT_QTY
	FROM STB_VN_FINISHGOOD_OUT_TEMPORARY T1
	WHERE T1.GROUPID IS NOT NULL AND T1.STATUSPRINTER IS NULL AND T1.GROUPID = @pGROUPID
	GROUP BY T1.PRODUCTIONSIZE,t1.GROUPID,T1.MATERIALCODE,T1.PARTNO,T1.CUSTOMERS

END