CREATE PROC [dbo].[usp_VN_LABLEWAHOUSEEXPORT]
AS
BEGIN
DECLARE @LABLEFRIST NVARCHAR(50)
DECLARE @SECONDS NVARCHAR(50)
DECLARE @FOU NVARCHAR(50)
DECLARE @DES NVARCHAR(50)
DECLARE @NOS  NVARCHAR(100)
DECLARE @Years NVARCHAR(5)
DECLARE @Moth NVARCHAR(10)
DECLARE @Day NVARCHAR(5)
DECLARE @Dates NVARCHAR(20)
DECLARE @IDS INT 

SET LANGUAGE English
SELECT @Moth = DATENAME(MM, GETDATE())
SELECT @Years = DATEPART(year, CURRENT_TIMESTAMP);


SELECT Cast(
Day( Getdate() ) AS VARCHAR(10)) +
CASE WHEN Day( Getdate() ) % 10 = 1 AND Day( Getdate() ) % 100 <> 11 THEN 'st'
WHEN Day( Getdate() ) % 10 = 2 AND Day( Getdate() ) % 100 <> 12 THEN 'nd'
WHEN Day( Getdate() ) % 10 = 3 AND Day( Getdate() ) % 100 <> 13 THEN 'rd'
ELSE 'TH'
END AS Day_Place
INTO #T1
SELECT @Day = Day_Place FROM #T1


		SELECT 
		TOP(1)
		@IDS = ID,
		@LABLEFRIST ='Outer BOX PACKING STICKER',
		@SECONDS = 'GENUS POWER INFRASTUCTURES LIMITED',
		@FOU = 'VINATECH CO.,LTD',
		@DES  = 'Make: Vinatech',
		@NOS = 'Note: All information is Availablein Lastest Gennus PO &N Drawing',
		@Dates = @Day + ', ' + @Moth + ', ' + @Years
		FROM 
			STB_VN_LABLEWAHOUSEEXPORT WITH(NOLOCK)

		ORDER BY CreateDateTime DESC

		UPDATE STB_VN_LABLEWAHOUSEEXPORT

		SET
				FIRSTLABLE = @LABLEFRIST,
				FIRSTSECOND = @SECONDS,
				FRISTFOURS = @FOU,
				DESCRIPTIONS = @DES,
				NOTES = @NOS--,
				--DATES = @Dates

		WHERE ID = @IDS

		SELECT 
		TOP(1)
		FIRSTLABLE,
		FIRSTSECOND,
		FIRSTTHREE,
		FRISTFOURS,
		INVOICENO,
		DATES,
		DESCRIPTIONS,
		MODEL,
		DRNOWITHREV,
		SAPCODE,
		PKTQTY,
		LOTQTY,
		NUMBERPINTERED,
		NOTES,
		'Report' AS CommandType
		FROM 
			STB_VN_LABLEWAHOUSEEXPORT WITH(NOLOCK)

		ORDER BY CreateDateTime DESC
END


 -- select * from  STB_VN_LABLEWAHOUSEEXPORT

