CREATE PROC [dbo].[usp_VN_Guise_Sapcode]
AS
BEGIN
		CREATE TABLE #T2(NAMES NVARCHAR(50))
		INSERT INTO #T2 (NAMES) VALUES ('RMCAP00001249')
		INSERT INTO #T2 (NAMES) VALUES ('RMCAP00001252')

		SELECT * FROM #T2

		DROP TABLE #T2

END