---- SELECT TOP(100)* FROM STB_VN_FINISHGOODS WHERE Statusout IS NULL AND  CreateDate > ='2025-02-19'
---- SELECT * FROM  STB_VN_FINISHGOOD_OUT_TEMPORARY
-- delete STB_VN_FINISHGOOD_OUT_TEMPORARY

CREATE PROC [dbo].[usp_View_Scan]  -- EXEC usp_View_Scan 'PKPK1300177','nha'
@PKID NVARCHAR(50),
@CREATEUSERID NVARCHAR(50)
AS
BEGIN

SET NOCOUNT ON;
CREATE TABLE #Tms(MS NVARCHAR(MAX))

		IF EXISTS (SELECT PACKINGID FROM STB_VN_FINISHGOOD_OUT_TEMPORARY WITH(NOLOCK) WHERE PACKINGID = @PKID)
			BEGIN
				DECLARE @DLC NVARCHAR(MAX)                                                                                                                                                                 
				SET @DLC = N'Mã này đã tồn tại không thể thêm mới'
				 INSERT INTO #Tms(MS)VALUES(@DLC)
				 SELECT MS FROM #Tms 

			END

	   ELSE IF NOT EXISTS (SELECT PackingID FROM STB_VN_FINISHGOODS WITH(NOLOCK) WHERE PackingID = @PKID)
			BEGIN
								
								  DECLARE @MSS NVARCHAR(MAX)
								  SET @MSS = N'Đã nhập vào kho thành phầm FG01 đâu mà xuất sang kho tạm, không tin à, vào FG01 mà xem.!'
								  INSERT INTO #Tms(MS)VALUES(@MSS)
								  SELECT MS FROM #Tms 

			END
	 ELSE IF  (@PKID = '' OR @PKID IS NULL)
			BEGIN
								
								  DECLARE @NLLPKID NVARCHAR(MAX)
								  SET @NLLPKID = N'Vui lòng không rỗng mã PackingID.!'
								  INSERT INTO #Tms(MS)VALUES(@NLLPKID)
								  SELECT MS FROM #Tms 
								  
								 
			END
	ELSE
		
			BEGIN
								
											DECLARE @IDFG NVARCHAR(20)
											DECLARE @PACKINGID NVARCHAR(30)
											DECLARE @LOTNO NVARCHAR(30)
											DECLARE @MATERIALCODE NVARCHAR(20)
											DECLARE @MATERIALNAME NVARCHAR(40)
											DECLARE @PACKQTY NVARCHAR(10)
											DECLARE @PARTNO NVARCHAR(30)
											DECLARE @PUBLICCODE NVARCHAR(30)
											DECLARE @TYPEPRODUCTION NVARCHAR(30)
											DECLARE @PRODUCTIONSIZE NVARCHAR(30)

											SELECT TOP(1) @IDFG = ID, @PACKINGID = PackingID, @LOTNO = LotNo, @MATERIALCODE = MaterialCode, @MATERIALNAME = MaterialName,
												   @PACKQTY = PackQty, @PARTNO = PartNo, @PUBLICCODE = PublicCode, @TYPEPRODUCTION = TypeProduction, @PRODUCTIONSIZE = ProductionSize
											FROM STB_VN_FINISHGOODS WITH(NOLOCK)
											WHERE Statusout IS NULL AND PackingID = @PKID

								 INSERT INTO STB_VN_FINISHGOOD_OUT_TEMPORARY(IDFG,PACKINGID,LOTNO,MATERIALCODE,MATERIALNAME,PACKQTY,PARTNO,PUBLICCODE,TYPEPRODUCTION,PRODUCTIONSIZE,CREATEUSERID,CREATEDATEIN,STATUSIN)VALUES(@IDFG,@PACKINGID,@LOTNO,@MATERIALCODE,@MATERIALNAME,@PACKQTY,@PARTNO,@PUBLICCODE,@TYPEPRODUCTION,@PRODUCTIONSIZE,@CREATEUSERID,GETDATE(),'1')

			
								  DECLARE @Rsl NVARCHAR(MAX)
								  SET @Rsl = N'Thêm mới thành công, bạn đã xuất từ FG01 ra kho tạm thành công.!'
								  INSERT INTO #Tms(MS)VALUES(@Rsl)
								  SELECT MS FROM #Tms 
								  -- Author:Nguyễn Hải Triều (04/04/2025)
								  --SELECT * FROM STB_VN_FINISHGOOD_OUT_TEMPORARY WHERE CREATEUSERID = @CREATEUSERID AND STATUSOUT IS NULL

								
			END
	
END
