CREATE PROC [dbo].[usp_VN_ViewCategories]
AS
BEGIN
		SELECT
		DISTINCT 
				INPUT,
				TYPEINPUT,
				UNIT
		FROM 
				STB_VN_CATEGORIES WITH(NOLOCK)
		WHERE
				IsUse = '1'
END


--select * from STB_VN_CATEGORIES WITH(NOLOCK)

-- INSERT INTO STB_VN_CATEGORIES (INPUT,TYPEINPUT,UNIT) VALUES (N'CREYO85',N'Điện cực YP 200 Cuộn âm- chưa cắt',N'M')

--INSERT INTO STB_VN_CATEGORIES (INPUT,TYPEINPUT,UNIT) VALUES (N'CREYO85',N'Điện cực YP 200 Cuộn  dương- chưa cắt',N'M')

--DELETE  STB_VN_CATEGORIES where INPUT = ''

--select * from STB_VN_CATEGORIES where INPUT = ''
--SET
--IsUse = 1
--where IsUse IS NULL
