CREATE PROC [dbo].[usp_VN_New_Lable_Customer]
@pProcessUserID VARCHAR(20) = NULL,
@pNAMEBARCODE1 NVARCHAR(50) = NULL,
@pNAMEBARCODE2  NVARCHAR(50) = NULL,
@pEXTENSION NVARCHAR(50) = NULL,
@pLableQty INT = NULL
AS
BEGIN
			DECLARE @ProcessUserID NVARCHAR(50) = @pProcessUserID
			DECLARE @NAMEBARCODE1 NVARCHAR(50) = @pNAMEBARCODE1
			DECLARE @NAMEBARCODE2 NVARCHAR(50) = @pNAMEBARCODE2
			DECLARE @EXTENSION  NVARCHAR(50) = @pEXTENSION
			DECLARE @LableQty INT = @pLableQty
		
		IF (@NAMEBARCODE1 IS NOT NULL AND @NAMEBARCODE2 IS NOT NULL AND  @EXTENSION IS NOT NULL AND @LableQty IS NOT NULL)
			
			BEGIN

				   INSERT INTO STB_VN_LABLE_CUSTOMER (NAMEBARCODE1,NAMEBARCODE2,EXTENSIONs,LableQtys,CreateUserID,CreateDateTime) VALUES (@NAMEBARCODE1,@NAMEBARCODE2,@EXTENSION,@pLableQty,@ProcessUserID,DATEADD(HH, -2, GETDATE()))		
	END	
					SELECT
							TOP(1)
							NAMEBARCODE1,
							NAMEBARCODE2,
							EXTENSIONs,
							LableQtys,
							CreateUserID,
							CONVERT(DATE,CreateDateTime) AS CreateDateTime,
							RIGHT(CreateDateTime,8) AS TimeIn,
							'Report' AS CommandType
					FROM 

						   STB_VN_LABLE_CUSTOMER WITH(NOLOCK)

					WHERE
							CreateUserID = @ProcessUserID

					ORDER BY CreateDateTime DESC,TimeIn Desc
END


--delete STB_VN_LABLE_CUSTOMER