CREATE PROC [dbo].[usp_VN_QC_LOTNO_MODULE_VALUES]
@pLOTNO NVARCHAR(50) = NULL,
@pNameType NVARCHAR(50) = NULL
AS
BEGIN
		DECLARE @LOTNO VARCHAR(100) = CASE WHEN ISNULL(@pLOTNO,'') = '' THEN '%' ELSE @pLOTNO END
		DECLARE @NameType VARCHAR(100) = CASE WHEN ISNULL(@pNameType,'') = '' THEN '%' ELSE @pNameType END

		SELECT 
				ID,
				VALUESCHECK
		FROM
				STB_QC_LOTNO_MODULE_VALUES WITH(NOLOCK)
		WHERE 
				LOTNO = @LOTNO AND NAMETYPE =  @NameType 
END