CREATE PROC [dbo].[usp_ViewTypenamesproduction] -- EXEC usp_ViewTypenames 'NVL' EXEC usp_ViewTypenamesproduction 'NVL_ Vỏ nhôm'
@TYPESNAME NVARCHAR(50)
AS
BEGIN
		SELECT DISTINCT CODENAME,NAMEPRODUCTION INTO #T1 FROM  TYPESCRAP WITH(NOLOCK) WHERE TYPENAMES = @TYPESNAME 

		SELECT * FROM #T1 ORDER BY NAMEPRODUCTION ASC

		DROP TABLE #T1
END

--SELECT  CODENAME,NAMEPRODUCTION FROM TYPESCRAP WITH(NOLOCK)  ORDER BY NAMEPRODUCTION ASC