CREATE PROC [dbo].[usp_VN_Employees_Transfer_Line] -- exec usp_VN_Employees_Transfer_Line '2022-03-28' ,'2022-03-29'
@pFromDate DATETIME = NULL,
@pToDate DATETIME =  NULL,
@pLine  NVARCHAR(50) = NULL
AS
BEGIN
		DECLARE @FromDate DATE = @pFromdate
		DECLARE @ToDate DATE = @pToDate
		DECLARE @Line NVARCHAR(50)

		IF @FromDate IS NOT NULL AND @ToDate IS NOT NULL AND @Line IS NULL
		BEGIN
			SELECT
					 EMPLOYEESID
					,EMPLOYEESNAME
					,CODELINECURRENTLY
					,LINECURRENTLY
					,CODELINETRANSFER
					,LINETRANSFER
					,LEFT(START_DATES,11) AS START_DATES
					,START_TIME
					,LEFT(END_DATES,11) AS END_DATES
					,END_TIME
					,'' + replace(TOTALMINUTES, '0', '') AS TOTALMINUTE
					,TOTALHOUR
					,CREATEBY
					,CREATEDATE
					,CHANGEBY
					,DATECHAGE
					,Shifts
			FROM 
					STB_VN_EMPLOYEESTRANSFER ---WITH(NOLOCK)
			WHERE
					LEFT(CREATEDATE,11) BETWEEN @FromDate AND @ToDate
		END
		
		IF @Line IS NOT NULL AND @FromDate IS NOT NULL AND @ToDate IS NOT NULL
		BEGIN

		SELECT
					 EMPLOYEESID
					,EMPLOYEESNAME
					,CODELINECURRENTLY
					,LINECURRENTLY
					,CODELINETRANSFER
					,LINETRANSFER
					,LEFT(START_DATES,11) AS START_DATES
					,START_TIME
					,LEFT(END_DATES,11) AS END_DATES
					,END_TIME
					,'' + replace(TOTALMINUTES, '0', '') AS TOTALMINUTE
					,TOTALHOUR
					,CREATEBY
					,CREATEDATE
					,CHANGEBY
					,DATECHAGE
					,Shifts
			FROM 
					STB_VN_EMPLOYEESTRANSFER WITH(NOLOCK)
			WHERE
					LEFT(CREATEDATE,11) BETWEEN @FromDate AND @ToDate
					AND
						CODELINETRANSFER = @Line
		END
END

-- select * from  STB_VN_EMPLOYEESTRANSFER

-- SELECT DATEDIFF(HOUR,END_TIME,START_TIME)/60 FROM STB_VN_EMPLOYEESTRANSFER;
--,DATEDIFF(hh, END_TIME, START_TIME) as TOTALHOUR 
					--,CAST(DATEDIFF(hh, END_TIME, START_TIME) as NUMERIC(18,4)) AS TOTALHOUR 
					----, CAST((END_TIME-START_TIME)AS decimal(2,2)) * 24.0 as TOTALHOUR
					--, datepart(Mi,END_TIME) -  datepart(mi,START_TIME) as TOTALMINUTE
					--,CAST(DATEDIFF(mi, END_TIME, START_TIME) AS NUMERIC(8,4)) / 60 AS [HrsDiff]


					 -- select * from  STB_VN_ATTENDANCE_TIME where WORK_DATE = '2022-11-22'

					 -- select * from  STB_VN_EMPLOYEESTRANSFER WHERE EMPLOYEESID = ''
					
