create proc usp_typescrapimport
@TYPES NVARCHAR(50) NULL,
@TYPENAMES NVARCHAR(50),
@CODENAME NVARCHAR(50),
@NAMEPRODUCTION NVARCHAR(50),
@UNITS NVARCHAR(20)
as
begin
	INSERT INTO TYPESCRAP (TYPES,TYPENAMES,CODENAME,NAMEPRODUCTION,UNITS) VALUES (@TYPES,@TYPENAMES,@CODENAME,@NAMEPRODUCTION,@UNITS)
end