CREATE PROC [dbo].[usp_View_Tem_fg]
AS
BEGIN
SET NOCOUNT ON;

	--SELECT
	--	 T1.GROUPID,
	--	 COUNT(T1.GROUPID) AS TOTALBOX,
	--	 SUM(CAST(T1.PACKQTY AS INT)) AS QTY,
	--	 T1.PRODUCTIONSIZE,
	--	 T1.MATERIALCODE,
	--	 T1.PARTNO
	--	 --INTO #Tbl_Sum
	--FROM STB_VN_FINISHGOOD_OUT_TEMPORARY T1
	--WHERE T1.GROUPID IS NOT NULL AND T1.STATUSPRINTER IS NULL
	--GROUP BY T1.PRODUCTIONSIZE,t1.GROUPID,T1.MATERIALCODE,T1.PARTNO

	--CREATE TABLE #Tpublic(TOTALPALET NVARCHAR(50),TOTALQTYPALET INT,GROUPID NVARCHAR(50), TOTALBOX INT,QTY INT,PRODUCTIONSIZE NVARCHAR(50),MATERIALCODE NVARCHAR(50), PARTNO NVARCHAR(50))

	--INSERT INTO #Tpublic(GROUPID,TOTALBOX,QTY,PRODUCTIONSIZE,MATERIALCODE,PARTNO)
	--SELECT
	--GROUPID,TOTALBOX,QTY,PRODUCTIONSIZE,MATERIALCODE,PARTNO
	--FROM #Tbl_Sum

		--SELECT * FROM #Tbl_Sum
	
	--SELECT TOP(1) *
	--FROM #Tpublic

	SELECT 
		 T1.GROUPID,
		 COUNT(T1.GROUPID) AS TOTALBOX,
		 SUM(CAST(T1.PACKQTY AS INT)) AS QTY
	--INTO #Tbl_SumTotal
	FROM STB_VN_FINISHGOOD_OUT_TEMPORARY T1
	WHERE T1.GROUPID IS NOT NULL AND T1.STATUSPRINTER IS NULL
	GROUP BY t1.GROUPID

	--UPDATE #Tpublic
	--SET TOTALPALET = #Tbl_SumTotal.TOTALBOX,  TOTALQTYPALET = #Tbl_SumTotal.QTY
	--FROM #Tpublic
	--INNER JOIN #Tbl_SumTotal ON #Tpublic.GROUPID = #Tbl_SumTotal.GROUPID
	

	--SELECT * FROM #Tpublic ORDER BY GROUPID DESC 

	--SELECT * FROM #Tbl_SumTotal tst

	
	--DROP TABLE #Tbl_Sum
	--DROP TABLE #Tbl_SumTotal
	--DROP TABLE #Tpublic

	--SELECT * FROM STB_VN_FINISHGOOD_OUT_TEMPORARY

END

