CREATE PROC [dbo].[usp_vn_codenameB726]
@pTYPEINPUT NVARCHAR(50) = NULL
AS
BEGIN
 SELECT  CODENAME,max(NAMEPRODUCTION) AS INPUT,max(UNITS) AS UNIT FROM TYPESCRAP WITH(NOLOCK) WHERE TYPENAMES = @pTYPEINPUT
 group by CODENAME
END
