CREATE PROC usp_VN_Show_STATUSMACHINES
@pCODESTATUSMACHINES NVARCHAR(50) = NULL,
@pNAMESTATUS NVARCHAR(50) = NULL
AS
BEGIN

			DECLARE @CODESTATUSMACHINES VARCHAR(100) = CASE WHEN ISNULL(@pCODESTATUSMACHINES,'') = '' THEN '%' ELSE @pCODESTATUSMACHINES END,
				@NAMESTATUS VARCHAR(100)= CASE WHEN ISNULL (@pNAMESTATUS, '') = '' THEN '%' ELSE @pNAMESTATUS END

		SELECT
				CODESTATUSMACHINES,
				NAMESTATUS,
				Descptions,
				IsUsed,
				CreateDateTime AS Dates,
				RIGHT(CreateDateTime,8) Times,
				CreateUserID,
				ChangeDateTime AS DateChanges,
				RIGHT(ChangeDateTime,8) AS TimeChanges,
				ChangeUserID
				
		FROM
				STB_VN_STATUSMACHINES WITH(NOLOCK)
		WHERE
				(CODESTATUSMACHINES LIKE @CODESTATUSMACHINES)
				OR
				(NAMESTATUS LIKE @NAMESTATUS)
END