CREATE PROC usp_VN_Show_STOREMACHINES
@pCODESTOREMACHINES NVARCHAR(50) = NULL,
@pNAMESTORE NVARCHAR(50) = NULL
AS
BEGIN

				DECLARE @CODESTOREMACHINES VARCHAR(100) = CASE WHEN ISNULL(@pCODESTOREMACHINES,'') = '' THEN '%' ELSE @pCODESTOREMACHINES END,
				@NAMESTORE VARCHAR(100)= CASE WHEN ISNULL (@pNAMESTORE, '') = '' THEN '%' ELSE @pNAMESTORE END

		SELECT 
				ID,
				CODESTOREMACHINES,
				NAMESTORE,
				Locations,
				Descptions,
				IsUsed

		FROM
				STB_VN_STOREMACHINES WITH(NOLOCK)

		WHERE 
				(CODESTOREMACHINES LIKE @CODESTOREMACHINES)
				OR
				(NAMESTORE LIKE @NAMESTORE)
END