-- =============================================
-- Author: Jackaroe(yjyu@vina.co.kr)
-- Create date: 2023-05-02
-- Browsable : true
-- Group : 스마트팩토리
-- Description:	다이렉트코터 상태정보를 조회합니다.
-- Modified:
-- =============================================
CREATE PROC [dbo].[usp_DCStatusInfo_get]
	@pProcessUserID VARCHAR(20)
   ,@pProcessLanguage VARCHAR(20)
   ,@pFromDate DATE
   ,@pToDate DATE
AS
BEGIN
	Declare @FromDate DATETIME = CONVERT(CHAR(10), @pFromDate, 121) + ' 00:00:00'
	       ,@ToDate DATETIME = CONVERT(CHAR(10), @pToDate, 121) + ' 23:59:59'

		SELECT DSI.DCStatusSerialNo
              ,DSI.MachineID
              ,DSI.LotNo
              ,DSI.Barcode
              ,DSI.OperationRun
              ,DSI.OperationStop
              ,DSI.AlarmReset
              ,DSI.BuzzerReset
              ,DSI.TouchMode
              ,DSI.GapMode
              ,DSI.TouchRollIn
              ,DSI.TouchRollOut
              ,DSI.WindingLengthReset
              ,DSI.NwfUwTopCoat
              ,DSI.NwfUwDownCoat
              ,DSI.UwTopCoat
              ,DSI.UwDownCoat
              ,DSI.PfUwTopCoat
              ,DSI.PfUwDownCoat
              ,DSI.PfRwUpperside
              ,DSI.PfRwLowerside
              ,DSI.NwfRwUppersize
              ,DSI.NwfRwLowerside
              ,DSI.RwUpperside
              ,DSI.RwLowerside
              ,DSI.EmergencyStop
              ,DSI.ServoAlarm
              ,DSI.InverterAlarm
              ,DSI.ChuckingAlarm
              ,DSI.SupplyExhaustAbnormal
              ,DSI.OverTempDetect
              ,DSI.GasAbnormal
              ,DSI.FlameDetect
              ,DSI.LengthReached
              ,DSI.SuctionRollServoOn
              ,DSI.SuctionRollServoOff
              ,DSI.DryerConveyorServoOn
              ,DSI.DryerConveyorServoOff
              ,DSI.XrfConveyorServoOn
              ,DSI.XrfConveyorServoOff
              ,DSI.OutfeedServoOn
              ,DSI.OutfeedServoOff
              ,DSI.TouchRollServoOn
              ,DSI.TouchRollServoOff
              ,DSI.NwfUwInverterOn
              ,DSI.NwfUwInverterOff
              ,DSI.UwInverterOn
              ,DSI.UwInverterOff
              ,DSI.PfUwInverterOn
              ,DSI.PfUwInverterOff
              ,DSI.PfRwInverterOn
              ,DSI.PfRwInverterOff
              ,DSI.NwfRwInverterOn
              ,DSI.NwfRwInverterOff
              ,DSI.RwInverterOn
              ,DSI.RwInverterOff
              ,DSI.MainSectionInverterOn
              ,DSI.MainSectionInverterOff
              ,DSI.Dryer1BlowerInverterOn
              ,DSI.Dryer1BlowerInverterOff
              ,DSI.Dryer2BlowerInverterOn
              ,DSI.Dryer2BlowerInverterOff
              ,DSI.XrfBlowerInverterOn
              ,DSI.XrfBlowerInverterOff
              ,DSI.TurnbarLeftBlowerInverterOn
              ,DSI.TurnbarLeftBlowerInverterOff
              ,DSI.TurnbarRightBlowerInverterOn
              ,DSI.TurnbarRightBlowerInverterOff
              ,DSI.DustCollector1InverterOn
              ,DSI.DustCollector1InverterOff
              ,DSI.DustCollector2InverterOn
              ,DSI.DustCollector2InverterOff
              ,DSI.DustCollector3InverterOn
              ,DSI.DustCollector3InverterOff
              ,DSI.Cleaner1On
              ,DSI.Cleaner1Off
              ,DSI.Cleaner2On
              ,DSI.Cleaner2Off
              ,DSI.Cleaner3On
              ,DSI.Cleaner3Off
              ,DSI.AntistaticBarSimplexDuplex
              ,DSI.AntistaticBarSimplexOn
              ,DSI.AntistaticBarSimplexOff
              ,DSI.NwfUnwinderManualAutomatic
              ,DSI.NwfUnwinderManual
              ,DSI.NwfUnwinderAutomatic
              ,DSI.NwfUnwinderCenter
              ,DSI.NwfUnwinderLimit
              ,DSI.UnwinderManualAutomatic
              ,DSI.UnwinderManual
              ,DSI.UnwinderAutomatic
              ,DSI.UnwinderCenter
              ,DSI.UnwinderLimit
              ,DSI.PfUnwinderManualAutomatic
              ,DSI.PfUnwinderManual
              ,DSI.PfUnwinderAutomatic
              ,DSI.PfUnwinderCenter
              ,DSI.PfUnwinderLimit
              ,DSI.PfRewinderManualAutomatic
              ,DSI.PfRewinderManual
              ,DSI.PfRewinderAutomatic
              ,DSI.PfRewinderCenter
              ,DSI.PfRewinderLimit
              ,DSI.NwfRewinderManualAutomatic
              ,DSI.NwfRewinderManual
              ,DSI.NwfRewinderAutomatic
              ,DSI.NwfRewinderCenter
              ,DSI.NwfRewinderLimit
              ,DSI.RewinderManualAutomatic
              ,DSI.RewinderManual
              ,DSI.RewinderAutomatic
              ,DSI.RewinderCenter
              ,DSI.RewinderLimit
              ,DSI.CoatingUnitEdge
              ,DSI.CoatingUnitCam
              ,DSI.NwfUwLengthSetupUseYn
              ,DSI.NwfUwLengthReset
              ,DSI.UwLengthSetupUseYn
              ,DSI.UwLengthReset
              ,DSI.PfUwLengthSetupUseYn
              ,DSI.PfUwLengthReset
              ,DSI.PfRwLengthSetupUseYn
              ,DSI.PfRwLengthReset
              ,DSI.NwfRwLengthSetupUseYn
              ,DSI.NwfRwLengthReset
              ,DSI.RewinderLengthSetupUseYn
              ,DSI.RewinderLengthReset
              ,DSI.ArchChamberExhaustOn
              ,DSI.ArchChamberExhaustOff
              ,DSI.Dryer1ExhaustOn
              ,DSI.Dryer1ExhaustOff
              ,DSI.Dryer2ExhaustOn
              ,DSI.Dryer2ExhaustOff
              ,DSI.ArchChamberSupplyOn
              ,DSI.ArchChamberSupplyOff
              ,DSI.Dryer1SupplyOn
              ,DSI.Dryer1SupplyOff
              ,DSI.Dryer2SupplyOn
              ,DSI.Dryer2SupplyOff
              ,DSI.Dryer3SupplyOn
              ,DSI.Dryer3SupplyOff
              ,DSI.Dryer4SupplyOn
              ,DSI.Dryer4SupplyOff
              ,DSI.Dryer1HeaterOn
              ,DSI.Dryer1HeaterOff
              ,DSI.Dryer2_1HeaterOn
              ,DSI.Dryer2_1HeaterOff
              ,DSI.Dryer2_2HeaterOn
              ,DSI.Dryer2_2HeaterOff
              ,DSI.Dryer2_3HeaterOn
              ,DSI.Dryer2_3HeaterOff
              ,DSI.Dryer2_4HeaterOn
              ,DSI.Dryer2_4HeaterOff
              ,DSI.BothUp
              ,DSI.BothDown
              ,DSI.OperationsideUp
              ,DSI.OperationsideDown
              ,DSI.DrivesideUp
              ,DSI.DrivesideDown
              ,DSI.OperationServoNormal
              ,DSI.DriveServoNormal
              ,DSI.OperationsideServoUpperLimit
              ,DSI.OperationsideServoLowerLimit
              ,DSI.DrivesideServoUpperLimit
              ,DSI.DrivesideServoLowerLimit
              ,DSI.SlotDieIn
              ,DSI.SlotDieOut
              ,DSI.Niproll1Close
              ,DSI.Niproll1Open
              ,DSI.Niproll2Close
              ,DSI.Niproll2Open
              ,DSI.Niproll3Close
              ,DSI.Niproll3Open
              ,DSI.PinchrollClose
              ,DSI.PinchrollOpen
              ,DSI.FFUOn
              ,DSI.FFUOff
              ,DSI.BoothLampOn
              ,DSI.BoothLampOff
              ,DSI.SuctionrollJogReverse
              ,DSI.SuctionrollJogStop
              ,DSI.SuctionrollJogForward
              ,DSI.DryerConveyorJogReverse
              ,DSI.DryerConveyorJogStop
              ,DSI.DryerConveyorJogForward
              ,DSI.XrfConveyorJogReverse
              ,DSI.XrfConveyorJogStop
              ,DSI.XrfConveyorJogForward
              ,DSI.OutfeedJogReverse
              ,DSI.OutfeedJogStop
              ,DSI.OutfeedJogForward
              ,DSI.VisionSimplex
              ,DSI.VisionDuplex
              ,DSI.VisionSimplexRun
              ,DSI.VisionSimplexStop
              ,DSI.VisionSimplexRunLP
              ,DSI.VisionSimplexStopLP
              ,DSI.VisionPlcClockLP
              ,DSI.VisionPlcReadyLP
              ,DSI.VisionPlcGoodLP
              ,DSI.VisionPlcDefectLP
              ,DSI.XrfSimplex
              ,DSI.XrfDuplex
              ,DSI.XrfSimplexRun
              ,DSI.XrfSimplexStop
              ,DSI.XrfSimplexRunLP
              ,DSI.XrfSimplexStopLP
              ,DSI.XrfPlcReadyLP
              ,DSI.XrfPlcGoodLP
              ,DSI.XrfPlcDefectLP
              ,DSI.BarcodeSimplex
              ,DSI.BarcodeDuplex
              ,DSI.BarcodeSimplexRun
              ,DSI.BarcodeSimplexRunLP
              ,DSI.BarcodePlcReadyLP
              ,DSI.BarcodePlcErrorLP
              ,DSI.CreateDateTime
		  FROM STB_DCStatusInfo DSI
		  LEFT OUTER JOIN STB_InterfaceMachineInfo IMI
	        ON IMI.MachineID = DSI.MachineID
		 WHERE DSI.CreateDateTime BETWEEN @FromDate AND @ToDate
		 ORDER BY DSI.DCStatusSerialNo DESC
END