CREATE PROCEDURE [dbo].[usp_updatestatus]
@pProcessLanguage VARCHAR(20),
@pDocNo	NVARCHAR(50) = null
AS
BEGIN
DECLARE @CursorTestID VARCHAR(20);
DECLARE @RunningTotal BIGINT = 0;
 

--check typeinout is output
	DECLARE @typeinout VARCHAR(50)
	SET @typeinout = (select distinct T1.TYPEINOUT from STB_TYPEINOUT T1,
								STB_FINALPRODUCTINFO T2 
								WHERE T1.DOCTYPE = T2.DOCTYPE
								AND T1.DOCTYPE IN (SELECT DOCTYPE FROM STB_FINALPRODUCTINFO WHERE DOCNO=@pDocNo));
IF @typeinout='OUTPUT'
BEGIN
		DECLARE @INVENTORY NUMERIC
		DECLARE @PRODUCTCODE VARCHAR(50)
		DECLARE @QUANTITY NUMERIC

		DECLARE CUR_TEST CURSOR FAST_FORWARD FOR
			SELECT DISTINCT PRODUCTCODE 
			FROM   STB_FINALPRODUCTDETAIL 
			WHERE DOCNO =@pDocNo
			ORDER BY PRODUCTCODE;
 
		OPEN CUR_TEST
		FETCH NEXT FROM CUR_TEST INTO @CursorTestID
 
		WHILE @@FETCH_STATUS = 0
		BEGIN
		   
		  -- SET @PRODUCTCODE = (SELECT PRODUCTCODE FROM STB_FINALPRODUCTDETAIL WHERE ID=@CursorTestID)
		   SET @QUANTITY = (SELECT SUM(Quantity) FROM STB_FINALPRODUCTDETAIL WHERE PRODUCTCODE=@CursorTestID AND DocNo = @pDocNo)
		   SET @INVENTORY =  (SELECT COALESCE(SUM(
					CASE WHEN T3.TYPEINOUT ='INPUT' THEN T1.Quantity
						 WHEN T3.TYPEINOUT='OUTPUT' THEN -T1.Quantity
						 ELSE 0
						 END),0) AS INVENTORY
						 --, T1.ProductCode, T4.MaterialUnit
					FROM
						STB_FINALPRODUCTDETAIL T1,
						STB_FINALPRODUCTINFO T2,
						STB_TYPEINOUT T3,
						STB_MaterialMaster  T4
					WHERE   T1.DOCNO = T2.DOCNO
							AND T2.DOCTYPE = T3.DOCTYPE
							AND T1.ProductCode = T4.MaterialCode
							AND T1.ProductCode = @CursorTestID
							AND T2.DocStatus='FINISH'
						--	AND T1.ProductCode ='ECVT27-247'
					--		GROUP BY T1.ProductCode,T4.MaterialUnit
							);
			
		IF @INVENTORY < @QUANTITY
		BEGIN	
			        DECLARE @NotEnoughStockError NVARCHAR(MAX)
					EXEC usp_GetSystemStringResource	@pProcessLanguage,
														N'KHÔNG ĐỦ TỒN KHO',
														@NotEnoughStockError OUTPUT

					RAISERROR(@NotEnoughStockError,16,1)
					RETURN			

				
		  
		END
			FETCH NEXT FROM CUR_TEST INTO @CursorTestID	 
		

		END
		CLOSE CUR_TEST
		DEALLOCATE CUR_TEST
		
END
	UPDATE STB_FINALPRODUCTINFO SET DOCSTATUS='FINISH' WHERE DocNo = @pDocNo
END
