CREATE PROC [dbo].[usp_VN_UpdateTimeMove]
@EmpID NVARCHAR(50),
@LineCode NVARCHAR(30)
AS
BEGIN
		SELECT 
				 EMPLOYEESID
				,EMPLOYEESNAME
				,CODELINECURRENTLY
				,LINECURRENTLY
				,CODELINETRANSFER
				,LINETRANSFER
				,START_DATES
				,START_TIME
				,END_DATES
				END_TIME
			
		FROM 
				STB_VN_EMPLOYEESTRANSFER WITH(NOLOCK)
		WHERE
				EMPLOYEESID = @EmpID AND CODELINETRANSFER = @LineCode AND END_TIME IS NULL
				
END


-- select * from STB_VN_EMPLOYEESTRANSFER