CREATE PROC [dbo].[usp_vn_codename]
@pTYPEINPUT NVARCHAR(50) = NULL
AS
BEGIN
 SELECT  CODENAME,(NAMEPRODUCTION) AS INPUT,(UNITS) AS UNIT FROM TYPESCRAP WITH(NOLOCK) WHERE TYPENAMES = @pTYPEINPUT
 and TYPENAMES not like 'del-%'
END
