CREATE PROC [dbo].[usp_VN_KPIMACHINES]
	AS
	BEGIN
			SELECT 
						ID,
						OPERATIONTIME,
						TACKTIME,
						PRODUCTIONOK,
						PRODUCTIONNG,
						RUNDOWN,
						DOWNTIME,
						QUANTITYTAGET,
						QUANTITYACTUAL,
						RUNTIME,
						LOSSTIME,
						TYLEVANHANHTHIETBI,
						TYLEDATDUOCMUCTIEU,
						HIEUSUATTINHNANG,
						TYLEDITHANG

					--	CASE

					--	WHEN 
					--			QUANTITYTAGET IS NULL THEN CAST((OPERATIONTIME * 0.8 * 60) / TACKTIME AS FLOAT)

					--	ELSE 0.000

					--	END AS QUANTITYTAGET,
					
					--CASE

					--	WHEN 
					--			QUANTITYACTUAL IS NULL THEN CAST(PRODUCTIONNG + PRODUCTIONOK AS FLOAT)

					--	ELSE 0.000

					--	END AS QUANTITYACTUAL,

					--CASE

					--	WHEN
					--			RUNTIME IS NULL THEN CAST(OPERATIONTIME - (RUNDOWN + DOWNTIME) AS FLOAT)

					--	ELSE 0.000
					
					--END AS RUNTIME,

					--CASE
						
					--	WHEN 
					--			LOSSTIME IS NULL THEN CAST(RUNDOWN + DOWNTIME AS FLOAT)

					--	ELSE 0.000

					--END AS LOSSTIME,

					--CASE
						
					--	WHEN
					--			TYLEVANHANHTHIETBI IS NULL THEN  CAST(RUNTIME/OPERATIONTIME AS FLOAT)

					--ELSE 0.000
					
					--END AS TYLEVANHANHTHIETBI,

					--CASE
						 
					--	 WHEN
					--			TYLEDATDUOCMUCTIEU  IS NULL THEN CAST(PRODUCTIONOK / QUANTITYTAGET AS FLOAT)
					
					--ELSE 0.000

					--END AS TYLEDATDUOCMUCTIEU,

					--CASE

					--	WHEN 
					--			HIEUSUATTINHNANG IS  NULL THEN  CAST(TYLEVANHANHTHIETBI / TYLEDITHANG AS FLOAT)
								
					--ELSE 0.000

					--END AS HIEUSUATTINHNANG,

					--CASE 
						
					--	WHEN 
					--			PRODUCTIONNG IS  NULL THEN CAST(PRODUCTIONOK / PRODUCTIONNG AS FLOAT) 
							
					--	ELSE 0.000

					--	END AS	TYLEDITHANG

			FROM 
					STB_VN_KPIMACHINES WITH(NOLOCK)
	END
