-- SELECT * FROM  STB_VN_STAGES_TRANSFER


CREATE PROC [dbo].[usp_VN_UpdateApprover] -- exec usp_VN_UpdateApprover '31707007202404020717','31811044','VVT_F1'
@GROUPID NVARCHAR(50),
@USERID NVARCHAR(50),
@CODE NVARCHAR(30)
AS
BEGIN
	

		IF @CODE = 'VVT_F1'

			BEGIN

		--SELECT 
		--		 PERSONAPPROVER_BN
		--FROM 
		--		STB_VN_STAGES_TRANSFER WITH(NOLOCK)
		--WHERE 
		--		GROUPID = @GROUPID AND PERSONAPPROVER_BN = @USERID 

					UPDATE STB_VN_STAGES_TRANSFER

					SET
						PERSONAPPROVERDATE_BN = GETDATE(),
						PERSONSTATUSAPPROVER_BN = 'TRUE'

					WHERE
							GROUPID = @GROUPID AND PERSONAPPROVER_BN = @USERID
			END

		ELSE

		 BEGIN

		--SELECT 

		--		 PERSONAPPROVER_BN

		--FROM 
		--		STB_VN_STAGES_TRANSFER WITH(NOLOCK)
		--WHERE 
		--		GROUPID = @GROUPID AND PERSONAPPROVER_BG = @USERID

					UPDATE STB_VN_STAGES_TRANSFER

					SET

						PERSONAPPROVERDATE_BG = GETDATE(),
					    PERSONSTATUSAPPROVER_BG	= 'TRUE'

					WHERE
							GROUPID = @GROUPID AND PERSONAPPROVER_BG = @USERID
						
			 END
END