CREATE PROC [dbo].[usp_Chart_Weigh] -- EXEC usp_Chart_Weigh '2022-09-22'
@pDATES DATE = null
AS
BEGIN 

CREATE TABLE #Tpulbic
(
	ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY(ID),
	LINECODE NVARCHAR(30),
	LINENAME NVARCHAR(30),
    MODEL NVARCHAR(30),
	TIMES NVARCHAR(30),
	NG FLOAT, 
	OK  FLOAT
)

DECLARE @AM01 NVARCHAR(30),
		@AM02 NVARCHAR(30),
		@AM03 NVARCHAR(30),
		@AM04 NVARCHAR(30),
		@AM05 NVARCHAR(30),
		@AM06 NVARCHAR(30),
		@AM07 NVARCHAR(30),
		@AM08 NVARCHAR(30),
		@AM09 NVARCHAR(30),
		@AM010 NVARCHAR(30),
		@AM11 NVARCHAR(30),
		@AM12 NVARCHAR(30),
		@PM13 NVARCHAR(30),
		@PM14 NVARCHAR(30),
		@PM15 NVARCHAR(30),
		@PM16 NVARCHAR(30),
		@PM17 NVARCHAR(30),
		@PM18 NVARCHAR(30),
		@PM19 NVARCHAR(30),
		@PM20 NVARCHAR(30),
		@PM21 NVARCHAR(30),
		@PM22 NVARCHAR(30),
		@PM23 NVARCHAR(30),
		@AM00 NVARCHAR(30)

SET @AM01 = CONVERT(VARCHAR(8), DATEADD(HH, 0, '01:00:00'),108)
SET @AM02 = CONVERT(VARCHAR(8), DATEADD(HH, 0, '02:00:00'),108)
SET @AM03 = CONVERT(VARCHAR(8), DATEADD(HH, 0, '03:00:00'),108)
SET @AM04 = CONVERT(VARCHAR(8), DATEADD(HH, 0, '04:00:00'),108)
SET @AM05 = CONVERT(VARCHAR(8), DATEADD(HH, 0, '05:00:00'),108)
SET @AM06 = CONVERT(VARCHAR(8), DATEADD(HH, 0, '06:00:00'),108)
SET @AM07 = CONVERT(VARCHAR(8), DATEADD(HH, 0, '07:00:00'),108)
SET @AM08 = CONVERT(VARCHAR(8), DATEADD(HH, 0, '08:00:00'),108)
SET @AM09 = CONVERT(VARCHAR(8), DATEADD(HH, 0, '09:00:00'),108)
SET @AM010 = CONVERT(VARCHAR(8), DATEADD(HH, 0, '10:00:00'),108)
SET @AM11 = CONVERT(VARCHAR(8), DATEADD(HH, 0, '11:00:00'),108)
SET @AM12 = CONVERT(VARCHAR(8), DATEADD(HH, 0, '12:00:00'),108)
SET @PM13 = CONVERT(VARCHAR(8), DATEADD(HH, 0, '13:00:00'),108)
SET @PM14 = CONVERT(VARCHAR(8), DATEADD(HH, 0, '14:00:00'),108)
SET @PM15 = CONVERT(VARCHAR(8), DATEADD(HH, 0, '15:00:00'),108)
SET @PM16 = CONVERT(VARCHAR(8), DATEADD(HH, 0, '16:00:00'),108)
SET @PM17 = CONVERT(VARCHAR(8), DATEADD(HH, 0, '17:00:00'),108)
SET @PM18 = CONVERT(VARCHAR(8), DATEADD(HH, 0, '18:00:00'),108)
SET @PM19 = CONVERT(VARCHAR(8), DATEADD(HH, 0, '19:00:00'),108)
SET @PM20 = CONVERT(VARCHAR(8), DATEADD(HH, 0, '20:00:00'),108)
SET @PM21 = CONVERT(VARCHAR(8), DATEADD(HH, 0, '21:00:00'),108)
SET @PM22 = CONVERT(VARCHAR(8), DATEADD(HH, 0, '22:00:00'),108)
SET @PM23 = CONVERT(VARCHAR(8), DATEADD(HH, 0, '23:00:00'),108)
SET @AM00 = CONVERT(VARCHAR(8), DATEADD(HH, 0, '00:00:00'),108)


-- Từ 00 giời tới 01 giời

SELECT 
		LINECODE,
		LINENAME,
		MODEL,
		'00:00 ~ 01:00' AS TIMES,
	CASE
			WHEN WEIGH < 12 AND WEIGH > 2.4 THEN SUM(WEIGH)
		   
	ELSE ''

	END AS 'NG',

	CASE
		    WHEN WEIGH >= 12.0 THEN SUM(WEIGH)
	ELSE ''

	END AS 'OK'

	INTO #T24

FROM
		STB_VN_Weigh WITH(NOLOCK)

		
WHERE
		CONVERT(DATE,CREATEDATE) = @pDATES AND CONVERT(VARCHAR(8), DATEADD(HH, 0, CREATEDATE),108) >= @AM00 AND CONVERT(VARCHAR(8), DATEADD(HH, 0, CREATEDATE),108) <= @AM01

GROUP BY LINECODE,LINENAME,MODEL,WEIGH,CONVERT(DATE,CREATEDATE)

INSERT INTO #Tpulbic (LINECODE,LINENAME,MODEL,TIMES,NG,OK)
SELECT LINECODE,LINENAME,MODEL,TIMES,SUM(NG) AS NG, SUM(OK) AS OK FROM #T24
GROUP BY  LINECODE,LINENAME,MODEL,TIMES


-- Từ 1 giời tới 2 giời

SELECT 
		LINECODE,
		LINENAME,
		MODEL,
		'01:00 ~ 02:00' AS TIMES,
	CASE
			WHEN WEIGH < 12 AND WEIGH > 2.4 THEN SUM(WEIGH)
		   
	ELSE ''

	END AS 'NG',

	CASE
		    WHEN WEIGH >= 12.0 THEN SUM(WEIGH)
	ELSE ''

	END AS 'OK'

	INTO #T23

FROM
		STB_VN_Weigh WITH(NOLOCK)

		
WHERE
		CONVERT(DATE,CREATEDATE) = @pDATES AND CONVERT(VARCHAR(8), DATEADD(HH, 0, CREATEDATE),108) >= @AM01 AND CONVERT(VARCHAR(8), DATEADD(HH, 0, CREATEDATE),108) <= @AM02

GROUP BY LINECODE,LINENAME,MODEL,WEIGH,CONVERT(DATE,CREATEDATE)


INSERT INTO #Tpulbic (LINECODE,LINENAME,MODEL,TIMES,NG,OK)
SELECT LINECODE,LINENAME,MODEL,TIMES,SUM(NG) AS NG, SUM(OK) AS OK FROM #T23
GROUP BY  LINECODE,LINENAME,MODEL,TIMES




-- Từ 2 giời tới 3 giời

SELECT 
		LINECODE,
		LINENAME,
		MODEL,
		'02:00 ~ 03:00' AS TIMES,
	CASE
			WHEN WEIGH < 12 AND WEIGH > 2.4 THEN SUM(WEIGH)
		   
	ELSE ''

	END AS 'NG',

	CASE
		    WHEN WEIGH >= 12.0 THEN SUM(WEIGH)
	ELSE ''

	END AS 'OK'

	INTO #T22

FROM
		STB_VN_Weigh WITH(NOLOCK)

		
WHERE
		CONVERT(DATE,CREATEDATE) = @pDATES AND CONVERT(VARCHAR(8), DATEADD(HH, 0, CREATEDATE),108) >= @AM02 AND CONVERT(VARCHAR(8), DATEADD(HH, 0, CREATEDATE),108) <= @AM03

GROUP BY LINECODE,LINENAME,MODEL,WEIGH,CONVERT(DATE,CREATEDATE)


INSERT INTO #Tpulbic (LINECODE,LINENAME,MODEL,TIMES,NG,OK)
SELECT LINECODE,LINENAME,MODEL,TIMES,SUM(NG) AS NG, SUM(OK) AS OK FROM #T22
GROUP BY  LINECODE,LINENAME,MODEL,TIMES



-- Từ 3 giời tới 4 giời

SELECT 
		LINECODE,
		LINENAME,
		MODEL,
		'03:00 ~ 04:00' AS TIMES,
	CASE
			WHEN WEIGH < 12 AND WEIGH > 2.4 THEN SUM(WEIGH)
		   
	ELSE ''

	END AS 'NG',

	CASE
		    WHEN WEIGH >= 12.0 THEN SUM(WEIGH)
	ELSE ''

	END AS 'OK'

	INTO #T21

FROM
		STB_VN_Weigh WITH(NOLOCK)

		
WHERE
		CONVERT(DATE,CREATEDATE) = @pDATES AND CONVERT(VARCHAR(8), DATEADD(HH, 0, CREATEDATE),108) >= @AM03 AND CONVERT(VARCHAR(8), DATEADD(HH, 0, CREATEDATE),108) <= @AM04

GROUP BY LINECODE,LINENAME,MODEL,WEIGH,CONVERT(DATE,CREATEDATE)


INSERT INTO #Tpulbic (LINECODE,LINENAME,MODEL,TIMES,NG,OK)
SELECT LINECODE,LINENAME,MODEL,TIMES,SUM(NG) AS NG, SUM(OK) AS OK FROM #T21
GROUP BY  LINECODE,LINENAME,MODEL,TIMES




-- Từ 4 giời tới 5 giời

SELECT 
		LINECODE,
		LINENAME,
		MODEL,
		'04:00 ~ 05:00' AS TIMES,
	CASE
			WHEN WEIGH < 12 AND WEIGH > 2.4 THEN SUM(WEIGH)
		   
	ELSE ''

	END AS 'NG',

	CASE
		    WHEN WEIGH >= 12.0 THEN SUM(WEIGH)
	ELSE ''

	END AS 'OK'

	INTO #T19

FROM
		STB_VN_Weigh WITH(NOLOCK)

		
WHERE
		CONVERT(DATE,CREATEDATE) = @pDATES AND CONVERT(VARCHAR(8), DATEADD(HH, 0, CREATEDATE),108) >= @AM04 AND CONVERT(VARCHAR(8), DATEADD(HH, 0, CREATEDATE),108) <= @AM05

GROUP BY LINECODE,LINENAME,MODEL,WEIGH,CONVERT(DATE,CREATEDATE)


INSERT INTO #Tpulbic (LINECODE,LINENAME,MODEL,TIMES,NG,OK)
SELECT LINECODE,LINENAME,MODEL,TIMES,SUM(NG) AS NG, SUM(OK) AS OK FROM #T19
GROUP BY  LINECODE,LINENAME,MODEL,TIMES



-- Từ 5 giời tới 6 giời

SELECT 
		LINECODE,
		LINENAME,
		MODEL,
		'05:00 ~ 06:00' AS TIMES,
	CASE
			WHEN WEIGH < 12 AND WEIGH > 2.4 THEN SUM(WEIGH)
		   
	ELSE ''

	END AS 'NG',

	CASE
		    WHEN WEIGH >= 12.0 THEN SUM(WEIGH)
	ELSE ''

	END AS 'OK'

	INTO #T18

FROM
		STB_VN_Weigh WITH(NOLOCK)

		
WHERE
		CONVERT(DATE,CREATEDATE) = @pDATES AND CONVERT(VARCHAR(8), DATEADD(HH, 0, CREATEDATE),108) >= @AM05 AND CONVERT(VARCHAR(8), DATEADD(HH, 0, CREATEDATE),108) <= @AM06

GROUP BY LINECODE,LINENAME,MODEL,WEIGH,CONVERT(DATE,CREATEDATE)


INSERT INTO #Tpulbic (LINECODE,LINENAME,MODEL,TIMES,NG,OK)
SELECT LINECODE,LINENAME,MODEL,TIMES,SUM(NG) AS NG, SUM(OK) AS OK FROM #T18
GROUP BY  LINECODE,LINENAME,MODEL,TIMES





-- Từ 6 giời tới 7 giời

SELECT 
		LINECODE,
		LINENAME,
		MODEL,
		'06:00 ~ 07:00' AS TIMES,
	CASE
			WHEN WEIGH < 12 AND WEIGH > 2.4 THEN SUM(WEIGH)
		   
	ELSE ''

	END AS 'NG',

	CASE
		    WHEN WEIGH >= 12.0 THEN SUM(WEIGH)
	ELSE ''

	END AS 'OK'

	INTO #T17

FROM
		STB_VN_Weigh WITH(NOLOCK)

		
WHERE
		CONVERT(DATE,CREATEDATE) = @pDATES AND CONVERT(VARCHAR(8), DATEADD(HH, 0, CREATEDATE),108) >= @AM06 AND CONVERT(VARCHAR(8), DATEADD(HH, 0, CREATEDATE),108) <= @AM07

GROUP BY LINECODE,LINENAME,MODEL,WEIGH,CONVERT(DATE,CREATEDATE)


INSERT INTO #Tpulbic (LINECODE,LINENAME,MODEL,TIMES,NG,OK)
SELECT LINECODE,LINENAME,MODEL,TIMES,SUM(NG) AS NG, SUM(OK) AS OK FROM #T17
GROUP BY  LINECODE,LINENAME,MODEL,TIMES



-- Từ 7 giời tới 8 giời

SELECT 
		LINECODE,
		LINENAME,
		MODEL,
		'07:00 ~ 08:00' AS TIMES,
	CASE
			WHEN WEIGH < 12 AND WEIGH > 2.4 THEN SUM(WEIGH)
		   
	ELSE ''

	END AS 'NG',

	CASE
		    WHEN WEIGH >= 12.0 THEN SUM(WEIGH)
	ELSE ''

	END AS 'OK'

	INTO #T1

FROM
		STB_VN_Weigh WITH(NOLOCK)

		
WHERE
		CONVERT(DATE,CREATEDATE) = @pDATES AND CONVERT(VARCHAR(8), DATEADD(HH, 0, CREATEDATE),108) >= @AM07 AND CONVERT(VARCHAR(8), DATEADD(HH, 0, CREATEDATE),108) <= @AM08

GROUP BY LINECODE,LINENAME,MODEL,WEIGH,CONVERT(DATE,CREATEDATE)


INSERT INTO #Tpulbic (LINECODE,LINENAME,MODEL,TIMES,NG,OK)
SELECT LINECODE,LINENAME,MODEL,TIMES,SUM(NG) AS NG, SUM(OK) AS OK FROM #T1
GROUP BY  LINECODE,LINENAME,MODEL,TIMES


-- Từ 8 giời tới 9 giời
SELECT 
		LINECODE,
		LINENAME,
		MODEL,
		'08:00 ~ 09:00' AS TIMES,
	CASE
			WHEN WEIGH < 12 AND WEIGH > 2.4 THEN SUM(WEIGH)
		   
	ELSE ''

	END AS 'NG',

	CASE
		    WHEN WEIGH >= 12.0 THEN SUM(WEIGH)
	ELSE ''

	END AS 'OK'

	INTO #T2

FROM
		STB_VN_Weigh WITH(NOLOCK)

		
WHERE
		CONVERT(DATE,CREATEDATE) = @pDATES AND CONVERT(VARCHAR(8), DATEADD(HH, 0, CREATEDATE),108) >= @AM08 AND CONVERT(VARCHAR(8), DATEADD(HH, 0, CREATEDATE),108) <= @AM09

GROUP BY LINECODE,LINENAME,MODEL,WEIGH,CONVERT(DATE,CREATEDATE)


INSERT INTO #Tpulbic (LINECODE,LINENAME,MODEL,TIMES,NG,OK)
SELECT LINECODE,LINENAME,MODEL,TIMES,SUM(NG) AS NG, SUM(OK) AS OK FROM #T2
GROUP BY  LINECODE,LINENAME,MODEL,TIMES


-- Từ 9 giời tới 10 giời
SELECT 
		LINECODE,
		LINENAME,
		MODEL,
		'09:00 ~ 10:00' AS TIMES,
	CASE
			WHEN WEIGH < 12 AND WEIGH > 2.4 THEN SUM(WEIGH)
		   
	ELSE ''

	END AS 'NG',

	CASE
		    WHEN WEIGH >= 12.0 THEN SUM(WEIGH)
	ELSE ''

	END AS 'OK'

	INTO #T3

FROM
		STB_VN_Weigh WITH(NOLOCK)
		
WHERE
		CONVERT(DATE,CREATEDATE) = @pDATES AND CONVERT(VARCHAR(8), DATEADD(HH, 0, CREATEDATE),108) >= @AM09 AND CONVERT(VARCHAR(8), DATEADD(HH, 0, CREATEDATE),108) <= @AM010

GROUP BY LINECODE,LINENAME,MODEL,WEIGH,CONVERT(DATE,CREATEDATE)


INSERT INTO #Tpulbic (LINECODE,LINENAME,MODEL,TIMES,NG,OK)
SELECT LINECODE,LINENAME,MODEL,TIMES,SUM(NG) AS NG, SUM(OK) AS OK FROM #T3
GROUP BY  LINECODE,LINENAME,MODEL,TIMES


-- Từ 10 giời tới 11 giời
SELECT 
		LINECODE,
		LINENAME,
		MODEL,
		'10:00 ~ 11:00' AS TIMES,
	CASE
			WHEN WEIGH < 12 AND WEIGH > 2.4 THEN SUM(WEIGH)
		   
	ELSE ''

	END AS 'NG',

	CASE
		    WHEN WEIGH >= 12.0 THEN SUM(WEIGH)
	ELSE ''

	END AS 'OK'

	INTO #T4

FROM
		STB_VN_Weigh WITH(NOLOCK)
		
WHERE
		CONVERT(DATE,CREATEDATE) = @pDATES AND CONVERT(VARCHAR(8), DATEADD(HH, 0, CREATEDATE),108) >= @AM010 AND CONVERT(VARCHAR(8), DATEADD(HH, 0, CREATEDATE),108) <= @AM11

GROUP BY LINECODE,LINENAME,MODEL,WEIGH,CONVERT(DATE,CREATEDATE)


INSERT INTO #Tpulbic (LINECODE,LINENAME,MODEL,TIMES,NG,OK)
SELECT LINECODE,LINENAME,MODEL,TIMES,SUM(NG) AS NG, SUM(OK) AS OK FROM #T4
GROUP BY  LINECODE,LINENAME,MODEL,TIMES



-- Từ 11 giời tới 12 giời
SELECT 
		LINECODE,
		LINENAME,
		MODEL,
		'11:00 ~ 12:00' AS TIMES,
	CASE
			WHEN WEIGH < 12 AND WEIGH > 2.4 THEN SUM(WEIGH)
		   
	ELSE ''

	END AS 'NG',

	CASE
		    WHEN WEIGH >= 12.0 THEN SUM(WEIGH)
	ELSE ''

	END AS 'OK'

	INTO #T5

FROM
		STB_VN_Weigh WITH(NOLOCK)
		
WHERE
		CONVERT(DATE,CREATEDATE) = @pDATES AND CONVERT(VARCHAR(8), DATEADD(HH, 0, CREATEDATE),108) >= @AM11 AND CONVERT(VARCHAR(8), DATEADD(HH, 0, CREATEDATE),108) <= @AM12

GROUP BY LINECODE,LINENAME,MODEL,WEIGH,CONVERT(DATE,CREATEDATE)


INSERT INTO #Tpulbic (LINECODE,LINENAME,MODEL,TIMES,NG,OK)
SELECT LINECODE,LINENAME,MODEL,TIMES,SUM(NG) AS NG, SUM(OK) AS OK FROM #T5
GROUP BY  LINECODE,LINENAME,MODEL,TIMES


-- Từ 12 giời tới 13 giời
SELECT 
		LINECODE,
		LINENAME,
		MODEL,
		'12:00 ~ 13:00' AS TIMES,
	CASE
			WHEN WEIGH < 12 AND WEIGH > 2.4 THEN SUM(WEIGH)
		   
	ELSE ''

	END AS 'NG',

	CASE
		    WHEN WEIGH >= 12.0 THEN SUM(WEIGH)
	ELSE ''

	END AS 'OK'

	INTO #T6

FROM
		STB_VN_Weigh WITH(NOLOCK)
		
WHERE
		CONVERT(DATE,CREATEDATE) = @pDATES AND CONVERT(VARCHAR(8), DATEADD(HH, 0, CREATEDATE),108) >= @AM12 AND CONVERT(VARCHAR(8), DATEADD(HH, 0, CREATEDATE),108) <= @PM13

GROUP BY LINECODE,LINENAME,MODEL,WEIGH,CONVERT(DATE,CREATEDATE)


INSERT INTO #Tpulbic (LINECODE,LINENAME,MODEL,TIMES,NG,OK)
SELECT LINECODE,LINENAME,MODEL,TIMES,SUM(NG) AS NG, SUM(OK) AS OK FROM #T6
GROUP BY  LINECODE,LINENAME,MODEL,TIMES



-- Từ 13 giời tới 14 giời
SELECT 
		LINECODE,
		LINENAME,
		MODEL,
		'13:00 ~ 14:00' AS TIMES,
	CASE
			WHEN WEIGH < 12 AND WEIGH > 2.4 THEN SUM(WEIGH)
		   
	ELSE ''

	END AS 'NG',

	CASE
		    WHEN WEIGH >= 12.0 THEN SUM(WEIGH)
	ELSE ''

	END AS 'OK'

	INTO #T7

FROM
		STB_VN_Weigh WITH(NOLOCK)
		
WHERE
		CONVERT(DATE,CREATEDATE) = @pDATES AND CONVERT(VARCHAR(8), DATEADD(HH, 0, CREATEDATE),108) >= @PM13 AND CONVERT(VARCHAR(8), DATEADD(HH, 0, CREATEDATE),108) <= @PM14

GROUP BY LINECODE,LINENAME,MODEL,WEIGH,CONVERT(DATE,CREATEDATE)


INSERT INTO #Tpulbic (LINECODE,LINENAME,MODEL,TIMES,NG,OK)
SELECT LINECODE,LINENAME,MODEL,TIMES,SUM(NG) AS NG, SUM(OK) AS OK FROM #T7
GROUP BY  LINECODE,LINENAME,MODEL,TIMES



-- Từ 14 giời tới 15 giời
SELECT 
		LINECODE,
		LINENAME,
		MODEL,
		'14:00 ~ 15:00' AS TIMES,
	CASE
			WHEN WEIGH < 12 AND WEIGH > 2.4 THEN SUM(WEIGH)
		   
	ELSE ''

	END AS 'NG',

	CASE
		    WHEN WEIGH >= 12.0 THEN SUM(WEIGH)
	ELSE ''

	END AS 'OK'

	INTO #T8

FROM
		STB_VN_Weigh WITH(NOLOCK)
		
WHERE
		CONVERT(DATE,CREATEDATE) = @pDATES AND CONVERT(VARCHAR(8), DATEADD(HH, 0, CREATEDATE),108) >= @PM14 AND CONVERT(VARCHAR(8), DATEADD(HH, 0, CREATEDATE),108) <= @PM15

GROUP BY LINECODE,LINENAME,MODEL,WEIGH,CONVERT(DATE,CREATEDATE)


INSERT INTO #Tpulbic (LINECODE,LINENAME,MODEL,TIMES,NG,OK)
SELECT LINECODE,LINENAME,MODEL,TIMES,SUM(NG) AS NG, SUM(OK) AS OK FROM #T8
GROUP BY  LINECODE,LINENAME,MODEL,TIMES



-- Từ 15 giời tới 16 giời
SELECT 
		LINECODE,
		LINENAME,
		MODEL,
		'15:00 ~ 16:00' AS TIMES,
	CASE
			WHEN WEIGH < 12 AND WEIGH > 2.4 THEN SUM(WEIGH)
		   
	ELSE ''

	END AS 'NG',

	CASE
		    WHEN WEIGH >= 12.0 THEN SUM(WEIGH)
	ELSE ''

	END AS 'OK'

	INTO #T9

FROM
		STB_VN_Weigh WITH(NOLOCK)
		
WHERE
		CONVERT(DATE,CREATEDATE) = @pDATES AND CONVERT(VARCHAR(8), DATEADD(HH, 0, CREATEDATE),108) >= @PM15 AND CONVERT(VARCHAR(8), DATEADD(HH, 0, CREATEDATE),108) <= @PM16

GROUP BY LINECODE,LINENAME,MODEL,WEIGH,CONVERT(DATE,CREATEDATE)


INSERT INTO #Tpulbic (LINECODE,LINENAME,MODEL,TIMES,NG,OK)
SELECT LINECODE,LINENAME,MODEL,TIMES,SUM(NG) AS NG, SUM(OK) AS OK FROM #T9
GROUP BY  LINECODE,LINENAME,MODEL,TIMES


-- Từ 16 giời tới 17 giời
SELECT 
		LINECODE,
		LINENAME,
		MODEL,
		'16:00 ~ 17:00' AS TIMES,
	CASE
			WHEN WEIGH < 12 AND WEIGH > 2.4 THEN SUM(WEIGH)
		   
	ELSE ''

	END AS 'NG',

	CASE
		    WHEN WEIGH >= 12.0 THEN SUM(WEIGH)
	ELSE ''

	END AS 'OK'

	INTO #T10

FROM
		STB_VN_Weigh WITH(NOLOCK)
		
WHERE
		CONVERT(DATE,CREATEDATE) = @pDATES AND CONVERT(VARCHAR(8), DATEADD(HH, 0, CREATEDATE),108) >= @PM16 AND CONVERT(VARCHAR(8), DATEADD(HH, 0, CREATEDATE),108) <= @PM17

GROUP BY LINECODE,LINENAME,MODEL,WEIGH,CONVERT(DATE,CREATEDATE)


INSERT INTO #Tpulbic (LINECODE,LINENAME,MODEL,TIMES,NG,OK)
SELECT LINECODE,LINENAME,MODEL,TIMES,SUM(NG) AS NG, SUM(OK) AS OK FROM #T10
GROUP BY  LINECODE,LINENAME,MODEL,TIMES



-- Từ 17 giời tới 18 giời
SELECT 
		LINECODE,
		LINENAME,
		MODEL,
		'17:00 ~ 18:00' AS TIMES,
	CASE
			WHEN WEIGH < 12 AND WEIGH > 2.4 THEN SUM(WEIGH)
		   
	ELSE ''

	END AS 'NG',

	CASE
		    WHEN WEIGH >= 12.0 THEN SUM(WEIGH)
	ELSE ''

	END AS 'OK'

	INTO #T11

FROM
		STB_VN_Weigh WITH(NOLOCK)
		
WHERE
		CONVERT(DATE,CREATEDATE) = @pDATES AND CONVERT(VARCHAR(8), DATEADD(HH, 0, CREATEDATE),108) >= @PM17 AND CONVERT(VARCHAR(8), DATEADD(HH, 0, CREATEDATE),108) <= @PM18

GROUP BY LINECODE,LINENAME,MODEL,WEIGH,CONVERT(DATE,CREATEDATE)


INSERT INTO #Tpulbic (LINECODE,LINENAME,MODEL,TIMES,NG,OK)
SELECT LINECODE,LINENAME,MODEL,TIMES,SUM(NG) AS NG, SUM(OK) AS OK FROM #T11
GROUP BY  LINECODE,LINENAME,MODEL,TIMES



-- Từ 18 giời tới 19 giời
SELECT 
		LINECODE,
		LINENAME,
		MODEL,
		'18:00 ~ 19:00' AS TIMES,
	CASE
			WHEN WEIGH < 12 AND WEIGH > 2.4 THEN SUM(WEIGH)
		   
	ELSE ''

	END AS 'NG',

	CASE
		    WHEN WEIGH >= 12.0 THEN SUM(WEIGH)
	ELSE ''

	END AS 'OK'

	INTO #T12

FROM
		STB_VN_Weigh WITH(NOLOCK)
		
WHERE
		CONVERT(DATE,CREATEDATE) = @pDATES AND CONVERT(VARCHAR(8), DATEADD(HH, 0, CREATEDATE),108) >= @PM18 AND CONVERT(VARCHAR(8), DATEADD(HH, 0, CREATEDATE),108) <= @PM19

GROUP BY LINECODE,LINENAME,MODEL,WEIGH,CONVERT(DATE,CREATEDATE)


INSERT INTO #Tpulbic (LINECODE,LINENAME,MODEL,TIMES,NG,OK)
SELECT LINECODE,LINENAME,MODEL,TIMES,SUM(NG) AS NG, SUM(OK) AS OK FROM #T12
GROUP BY  LINECODE,LINENAME,MODEL,TIMES




-- Từ 19 giời tới 20 giời
SELECT 
		LINECODE,
		LINENAME,
		MODEL,
		'19:00 ~ 20:00' AS TIMES,
	CASE
			WHEN WEIGH < 12 AND WEIGH > 2.4 THEN SUM(WEIGH)
		   
	ELSE ''

	END AS 'NG',

	CASE
		    WHEN WEIGH >= 12.0 THEN SUM(WEIGH)
	ELSE ''

	END AS 'OK'

	INTO #T13

FROM
		STB_VN_Weigh WITH(NOLOCK)
		
WHERE
		CONVERT(DATE,CREATEDATE) = @pDATES AND CONVERT(VARCHAR(8), DATEADD(HH, 0, CREATEDATE),108) >= @PM19 AND CONVERT(VARCHAR(8), DATEADD(HH, 0, CREATEDATE),108) <= @PM20

GROUP BY LINECODE,LINENAME,MODEL,WEIGH,CONVERT(DATE,CREATEDATE)


INSERT INTO #Tpulbic (LINECODE,LINENAME,MODEL,TIMES,NG,OK)
SELECT LINECODE,LINENAME,MODEL,TIMES,SUM(NG) AS NG, SUM(OK) AS OK FROM #T13
GROUP BY  LINECODE,LINENAME,MODEL,TIMES


-- Từ 20 giời tới 21 giời
SELECT 
		LINECODE,
		LINENAME,
		MODEL,
		'20:00 ~ 21:00' AS TIMES,
	CASE
			WHEN WEIGH < 12 AND WEIGH > 2.4 THEN SUM(WEIGH)
		   
	ELSE ''

	END AS 'NG',

	CASE
		    WHEN WEIGH >= 12.0 THEN SUM(WEIGH)
	ELSE ''

	END AS 'OK'

	INTO #T14

FROM
		STB_VN_Weigh WITH(NOLOCK)
		
WHERE
		CONVERT(DATE,CREATEDATE) = @pDATES AND CONVERT(VARCHAR(8), DATEADD(HH, 0, CREATEDATE),108) >= @PM20 AND CONVERT(VARCHAR(8), DATEADD(HH, 0, CREATEDATE),108) <= @PM21

GROUP BY LINECODE,LINENAME,MODEL,WEIGH,CONVERT(DATE,CREATEDATE)


INSERT INTO #Tpulbic (LINECODE,LINENAME,MODEL,TIMES,NG,OK)
SELECT LINECODE,LINENAME,MODEL,TIMES,SUM(NG) AS NG, SUM(OK) AS OK FROM #T14
GROUP BY  LINECODE,LINENAME,MODEL,TIMES


-- Từ 21 giời tới 22 giời
SELECT 
		LINECODE,
		LINENAME,
		MODEL,
		'21:00 ~ 22:00' AS TIMES,
	CASE
			WHEN WEIGH < 12 AND WEIGH > 2.4 THEN SUM(WEIGH)
		   
	ELSE ''

	END AS 'NG',

	CASE
		    WHEN WEIGH >= 12.0 THEN SUM(WEIGH)
	ELSE ''

	END AS 'OK'

	INTO #T15

FROM
		STB_VN_Weigh WITH(NOLOCK)
		
WHERE
		CONVERT(DATE,CREATEDATE) = @pDATES AND CONVERT(VARCHAR(8), DATEADD(HH, 0, CREATEDATE),108) >= @PM21 AND CONVERT(VARCHAR(8), DATEADD(HH, 0, CREATEDATE),108) <= @PM22

GROUP BY LINECODE,LINENAME,MODEL,WEIGH,CONVERT(DATE,CREATEDATE)


INSERT INTO #Tpulbic (LINECODE,LINENAME,MODEL,TIMES,NG,OK)
SELECT LINECODE,LINENAME,MODEL,TIMES,SUM(NG) AS NG, SUM(OK) AS OK FROM #T15
GROUP BY  LINECODE,LINENAME,MODEL,TIMES



-- Từ 22 giời tới 23 giời
SELECT 
		LINECODE,
		LINENAME,
		MODEL,
		'22:00 ~ 23:00' AS TIMES,
	CASE
			WHEN WEIGH < 12 AND WEIGH > 2.4 THEN SUM(WEIGH)
		   
	ELSE ''

	END AS 'NG',

	CASE
		    WHEN WEIGH >= 12.0 THEN SUM(WEIGH)
	ELSE ''

	END AS 'OK'

	INTO #T16

FROM
		STB_VN_Weigh WITH(NOLOCK)
		
WHERE
		CONVERT(DATE,CREATEDATE) = @pDATES AND CONVERT(VARCHAR(8), DATEADD(HH, 0, CREATEDATE),108) >= @PM22 AND CONVERT(VARCHAR(8), DATEADD(HH, 0, CREATEDATE),108) <= @PM23

GROUP BY LINECODE,LINENAME,MODEL,WEIGH,CONVERT(DATE,CREATEDATE)

INSERT INTO #Tpulbic (LINECODE,LINENAME,MODEL,TIMES,NG,OK)
SELECT LINECODE,LINENAME,MODEL,TIMES,SUM(NG) AS NG, SUM(OK) AS OK FROM #T16
GROUP BY  LINECODE,LINENAME,MODEL,TIMES


-- Từ 23 giời tới 00 giời

SELECT 
		LINECODE,
		LINENAME,
		MODEL,
		'23:00 ~ 00:00' AS TIMES,
	CASE
			WHEN WEIGH < 12 AND WEIGH > 2.4 THEN SUM(WEIGH)
		   
	ELSE ''

	END AS 'NG',

	CASE
		    WHEN WEIGH >= 12.0 THEN SUM(WEIGH)
	ELSE ''

	END AS 'OK'

	INTO #T20

FROM
		STB_VN_Weigh WITH(NOLOCK)
		
WHERE -- @pDATES
		CONVERT(DATE,CREATEDATE) = '2022-09-22'  AND CONVERT(VARCHAR(8), DATEADD(HH, 0, CREATEDATE),108) >= @PM23 AND CONVERT(VARCHAR(8), DATEADD(HH, 0, CREATEDATE),108) <= @AM00

GROUP BY LINECODE,LINENAME,MODEL,WEIGH,CONVERT(DATE,CREATEDATE)

INSERT INTO #Tpulbic (LINECODE,LINENAME,MODEL,TIMES,NG,OK)
SELECT LINECODE,LINENAME,MODEL,TIMES,SUM(NG) AS NG, SUM(OK) AS OK FROM #T20
GROUP BY  LINECODE,LINENAME,MODEL,TIMES


SELECT LINECODE,LINENAME,MODEL,TIMES,CAST(NG AS FLOAT) AS NG,CAST(OK AS FLOAT) AS OK FROM #Tpulbic


DROP TABLE #T1
DROP TABLE #T2
DROP TABLE #T3
DROP TABLE #T4
DROP TABLE #T5
DROP TABLE #T6
DROP TABLE #T7
DROP TABLE #T8
DROP TABLE #T9
DROP TABLE #T10
DROP TABLE #T11
DROP TABLE #T12
DROP TABLE #T13
DROP TABLE #T14
DROP TABLE #T15
DROP TABLE #T16
DROP TABLE #T17
DROP TABLE #T18
DROP TABLE #T19
DROP TABLE #T20
DROP TABLE #T21
DROP TABLE #T22
DROP TABLE #T23
DROP TABLE #T24
DROP TABLE #Tpulbic

END