CREATE PROC [dbo].[usp_VN_STATUSMACHINE]
@CODEIDM NVARCHAR(50),
@CODEID NVARCHAR(50),
@LINECODE NVARCHAR(50),
@CREATECHECK NVARCHAR(50),
@CHECKDATE DATETIME,
@CONTENTABNORMAL NVARCHAR(500),
@STATUSMACHINE BIT,
@SHIFT NVARCHAR(20)
AS
BEGIN
DECLARE @CODEM NVARCHAR(50)
SELECT 
@CODEM = CODEIDM
FROM STB_VN_STAGEMACHINES_DETAIL WITH(NOLOCK)
WHERE CODEID = @CODEID
	
		INSERT INTO STB_VN_STATUSMACHINE(CODEIDM,CODEID,LINECODE,CREATECHECK,CHECKDATE,CONTENTABNORMAL,STATUSMACHINE,SHIFTS,CREATEDATE)
		VALUES(@CODEM,@CODEID,@LINECODE,@CREATECHECK,@CHECKDATE,@CONTENTABNORMAL,@STATUSMACHINE,@SHIFT,GETDATE())
END

-- select * from  STB_VN_STATUSMACHINE

--SELECT * FROM STB_VN_STAGEMACHINES_DETAIL

-- delete STB_VN_STATUSMACHINE

--alter table STB_VN_STATUSMACHINE
--add
--	CREATEDATE DATETIME NULL