CREATE PROC [dbo].[usp_view_full_B751]
@pGROUPID NVARCHAR(50) = NULL
AS
BEGIN
		SELECT 
			  GROUPID,
			  PACKINGID,
			  LOTNO,
			  MATERIALCODE,
			  MATERIALNAME,
			  PACKQTY,
			  PARTNO,
			  PUBLICCODE,
			  TYPEPRODUCTION,
			  PRODUCTIONSIZE,
			  CREATEUSERID,
			  CREATEDATEIN,
			  CREATEDATEOUT,
			  STATUSPRINTER,
			  STATUSOUT,
			  CREATEDATEGROUPID,
			  CUSTOMERS,
			  SOINVOICES
		FROM STB_VN_FINISHGOOD_OUT_TEMPORARY WITH(NOLOCK)
		WHERE GROUPID = @pGROUPID
END