CREATE proc [dbo].[usp_DeparmentScrap]
AS
BEGIN
		CREATE TABLE #T1(ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY(ID), DEPARTMENTNAME NVARCHAR(50) NULL, IsUsed BIT NULL)

		--INSERT INTO #T1(DEPARTMENTNAME,IsUsed) VALUES (N'Kĩ thuật sản phẩm','1')
		--INSERT INTO #T1(DEPARTMENTNAME,IsUsed) VALUES (N'Quản lý sản xuất','1')
		INSERT INTO #T1(DEPARTMENTNAME,IsUsed) VALUES (N'TQC','1')
		INSERT INTO #T1(DEPARTMENTNAME,IsUsed) VALUES (N'OQC','1')
		INSERT INTO #T1(DEPARTMENTNAME,IsUsed) VALUES (N'FOQC','1')
		--INSERT INTO #T1(DEPARTMENTNAME,IsUsed) VALUES (N'Sản xuất','1')
		--INSERT INTO #T1(DEPARTMENTNAME,IsUsed) VALUES (N'Thiết bị','1')

		--Chu tich Hung yeu cau them tieng Han vao ten bo phan , Mr.Tung on 06-July-2022
		INSERT INTO #T1(DEPARTMENTNAME,IsUsed) VALUES (N'SẢN XUẤT_생산_BẮC NINH','1')
		INSERT INTO #T1(DEPARTMENTNAME,IsUsed) VALUES (N'SẢN XUẤT_생산_BẮC GIANG','1')
		INSERT INTO #T1(DEPARTMENTNAME,IsUsed) VALUES (N'QUẢN LÝ SẢN XUẤT_생관','1')
		INSERT INTO #T1(DEPARTMENTNAME,IsUsed) VALUES (N'KỸ THUẬT SẢN PHẨM_기술','1')
		INSERT INTO #T1(DEPARTMENTNAME,IsUsed) VALUES (N'CHẤT LƯỢNG_품질','1')
		INSERT INTO #T1(DEPARTMENTNAME,IsUsed) VALUES (N'THIẾT BỊ_설비','1')
		INSERT INTO #T1(DEPARTMENTNAME,IsUsed) VALUES (N'RND','1')

		SELECT 
				DEPARTMENTNAME
		FROM
			#T1
		WHERE
				IsUsed = 1


		DROP TABLE #T1
END