CREATE PROC [dbo].[usp_VN_errorAgaing]
AS
BEGIN
		CREATE TABLE #TBL
		(
			ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY(ID),
			NAMES NVARCHAR(50) NULL
		)

			
		INSERT INTO #TBL (NAMES) VALUES (N'BẸP ĐÁY')

		INSERT INTO #TBL (NAMES) VALUES (N'RÁCH VỎ');
		INSERT INTO #TBL (NAMES) VALUES (N'XƯỚC CHÂN')
		INSERT INTO #TBL (NAMES) VALUES (N'TANCHA BIẾN SẮC')
		INSERT INTO #TBL (NAMES) VALUES (N'BẸP VỎ NHÔM')
		INSERT INTO #TBL (NAMES) VALUES (N'NGƯỢC CỰC')
		INSERT INTO #TBL (NAMES) VALUES (N'CONG CHÂN');
		INSERT INTO #TBL (NAMES) VALUES (N'DỊ VẬT')

		INSERT INTO #TBL (NAMES) VALUES (N'TRÀN DỊCH');
		INSERT INTO #TBL (NAMES) VALUES (N'BIẾN SẮC ĐÁY');
		INSERT INTO #TBL (NAMES) VALUES (N'RÁCH CAO SU');
		INSERT INTO #TBL (NAMES) VALUES (N'LỒI ĐÁY');
		INSERT INTO #TBL (NAMES) VALUES (N'NG MARKING');
		INSERT INTO #TBL (NAMES) VALUES (N'THIẾU SỐ LƯỢNG');
		INSERT INTO #TBL (NAMES) VALUES (N'NG TAPE');
		INSERT INTO #TBL (NAMES) VALUES (N'LỖI KHÁC');

		SELECT
				NAMES
		FROM
			#TBL

	DROP TABLE #TBL
END