CREATE PROC [dbo].[usp_DoCheckPartnerOrProduct] 
	@pCompanyCode VARCHAR(20)
   ,@pFromDate DATE
   ,@pToDate DATE
AS
BEGIN
	Declare @CompanyCode VARCHAR(20) = @pCompanyCode
	       ,@FromDate DATE = @pFromDate
		   ,@ToDate DATE = @pToDate

	SELECT QH.CD_PARTNER , MP.LN_PARTNER, QD.CD_ITEM, MPI.NM_ITEM, 'New Partner' AS Remark
	  FROM NEOE.NEOE.MM_QTIOH QH
	  LEFT OUTER JOIN NEOE.NEOE.MA_PARTNER MP
	    ON QH.CD_PARTNER = MP.CD_PARTNER
	   AND QH.CD_COMPANY = MP.CD_COMPANY
	  LEFT OUTER JOIN NEOE.NEOE.MM_QTIO QD
	    ON QD.CD_COMPANY = QH.CD_COMPANY
	   AND QH.NO_IO = QD.NO_IO
	  LEFT OUTER JOIN NEOE.NEOE.MA_PITEM MPI
	    ON MPI.CD_COMPANY = QD.CD_COMPANY
	   AND MPI.CD_ITEM = QD.CD_ITEM
	 WHERE QH.CD_COMPANY = @CompanyCode
	   AND QH.DT_IO BETWEEN @FromDate AND @ToDate
	   AND ISNULL(QH.CD_PARTNER, '') NOT IN (
								SELECT ISNULL(CD_PARTNER, '')
								  FROM NEOE.NEOE.MM_QTIOH
								 WHERE DT_IO < @FromDate
								   AND CD_COMPANY = @CompanyCode
							)
	UNION ALL
	SELECT QD.CD_PARTNER, MP.LN_PARTNER, QD.CD_ITEM, NM_ITEM, 'New Product' 
	  FROM NEOE.NEOE.MM_QTIO QD
	  LEFT OUTER JOIN NEOE.NEOE.MA_PARTNER MP
	    ON MP.CD_PARTNER = QD.CD_PARTNER
	   AND MP.CD_COMPANY = QD.CD_COMPANY
	  LEFT OUTER JOIN NEOE.NEOE.MA_PITEM MPI
	    ON MPI.CD_COMPANY = QD.CD_COMPANY
	   AND MPI.CD_ITEM = QD.CD_ITEM
	 WHERE QD.CD_COMPANY = @CompanyCode
	   AND QD.DT_IO BETWEEN @FromDate AND @ToDate
	   AND ISNULL(QD.CD_ITEM + QD.CD_PARTNER, '') NOT IN (
										SELECT ISNULL(CD_ITEM + CD_PARTNER, '')
										  FROM NEOE.NEOE.MM_QTIO QD
										 WHERE CD_COMPANY = @CompanyCode
										   AND DT_IO < @FromDate
									   )
END