CREATE PROC [dbo].[usp_View_VN_SCRAP_WEIGHSCALE_PRODUCTIONS] --exec usp_View_VN_SCRAP_WEIGHSCALE_PRODUCTIONS 'Nguyễn Văn Nha','2022-05-16'
@USERID NVARCHAR(50),
@DATEWEIGH NVARCHAR(50)
AS
BEGIN
	  SELECT
			
	        IMAGEBARCODE,
			BARCODE,
			LINECODE,
			NAMELINE,
			WEIGHSCALE,
			CASE
			WHEN TYPESCRAP= N'NVL' THEN N'Nguyên vật liệu'
			WHEN TYPESCRAP= N'BTP' THEN N'Bán thành phẩm'
			WHEN TYPESCRAP= N'TP' THEN N'Thành phẩm'
			ELSE ''
			END AS TYPESCRAP,
			CASE
					WHEN FLAG = 0 AND STATUSDELETE IS NULL THEN  N'Chờ in tem'
		   ELSE ''
			END AS FLAG,
			USERID,
			DATEWEIGH,
			NAMEERROR,
			QUANTITY
			
	  FROM
			STB_VN_SCRAP_WEIGHSCALE_PRODUCTIONS WITH(NOLOCK)

	   WHERE

			USERID = @USERID AND FLAG = 0 AND DATEWEIGH = @DATEWEIGH  AND STATUSDELETE IS NULL

	  ORDER BY CREATEDATE DESC
END

--SELECT * FROM STB_VN_SCRAP_WEIGHSCALE_PRODUCTIONS