CREATE PROC usp_VN_INVENTORY_MODULES
AS
BEGIN
--	WITH cte AS
--	(
--		SELECT 
--				DISTINCT ROW_NUMBER() OVER(PARTITION BY A.PARTNO ORDER BY A.PARTNO) rn,
--				A.PARTNO,
--				A.SIZE,
--				B.TOTALOUT,
--				C.TOTALIMPORT,
--				B.TOTALOUT - C.TOTALIMPORT AS TotalCurrently
--		FROM
--				STB_VN_MASTERMODULES A
		

--		LEFT OUTER JOIN
--		(
--			SELECT

--				PARTNO, SUM(TOTALQTY) AS TOTALOUT

--			FROM 

--				 STB_VN_MASTERMODULES WITH(NOLOCK)

--			WHERE

--				 TYPEEXPORT = N'Xuất' --AND ISUSED = '1' --AND TOTALQTY IS NOT NULL AND DIVIDETHENUMBER IS NOT NULL

--			GROUP BY PARTNO)B

--			ON A.PARTNO = B.PARTNO

--		INNER JOIN 
--		(
--			SELECT

--				  PARTNO, SUM(TOTALQTY) AS TOTALIMPORT

--			FROM

--				 STB_VN_MASTERMODULES WITH(NOLOCK)

--			WHERE

--				 TYPEIMPORT = N'Nhập' AND ISUSED = '1' AND TOTALQTY IS NOT NULL AND DIVIDETHENUMBER IS NOT NULL

--			GROUP BY PARTNO)C
		
--		    ON A.PARTNO = C.PARTNO
--)	

--	SELECT
--			DISTINCT
--				PARTNO,
--				SIZE,
--				TOTALOUT,
--				TOTALIMPORT,
--				TotalCurrently,
--				CASE 
--					WHEN TOTALIMPORT  IS NULL THEN TOTALOUT
--					ELSE TotalCurrently
--				END AS Result
							
--	FROM
--		 cte

SELECT 
				DISTINCT ROW_NUMBER() OVER(PARTITION BY A.PARTNO ORDER BY A.PARTNO) rn,
				A.PARTNO,
				A.SIZE,
				SUM(A.TOTALQTY) AS TOTALOUT
				INTO #T1
		FROM
				STB_VN_MASTERMODULES A

				
	WHERE

				 TYPEEXPORT = N'Xuất' AND ISUSED = '1' AND TOTALQTY IS NOT NULL AND DIVIDETHENUMBER IS NOT NULL
				 GROUP BY PARTNO,SIZE


SELECT

				  PARTNO, SUM(TOTALQTY) AS TOTALIMPORT
				  INTO #T2
			FROM

				 STB_VN_MASTERMODULES WITH(NOLOCK)

				 

			WHERE

				 TYPEIMPORT = N'Nhập' AND ISUSED = '1' AND TOTALQTY IS NOT NULL AND DIVIDETHENUMBER IS NOT NULL

			GROUP BY PARTNO


		SELECT
				#T1.PARTNO,
				#T1.SIZE,
				SUM(#T1.TOTALOUT) AS TOTALOUT,
				SUM(#T2.TOTALIMPORT) AS TOTALIMPORT,
				SUM(#T1.TOTALOUT - #T2.TOTALIMPORT) AS 'INVENTORY'

				INTO #T3
		FROM
			 #T1

			LEFT JOIN #T2
			ON #T2.PARTNO = #T1.PARTNO

			GROUP BY #T1.PARTNO,#T1.SIZE


			SELECT
				 PARTNO,
				 SIZE,
				 TOTALOUT,
				 TOTALIMPORT,
				 INVENTORY,
				 CASE
					WHEN TOTALIMPORT IS NULL THEN TOTALOUT
					ELSE INVENTORY
				END AS Result
						
			FROM
				#T3

		DROP TABLE #T1
		DROP TABLE #T2
		DROP TABLE #T3
END

-- SELECT * FROM STB_VN_MASTERMODULES

--UPDATE STB_VN_MASTERMODULES
--SET TYPEEXPORT = N'Xuất'
--where ID = ID
--- usp_Summary_Modules