CREATE PROC usp_VN_View_Stages
@pProcessUserID VARCHAR(20),
@pFrom DATETIME,
@pTo DATETIME
AS
BEGIN
 SET @pProcessUserID = 'sieusao'
 SELECT * FROM STB_VN_STAGE_PRODUCTION WHERE CONVERT(DATE,CREATEDATETIME) BETWEEN @pFrom AND @pTo AND  CREATEUSERID = @pProcessUserID
END