
CREATE PROC [dbo].[usp_VN_Add_EmployeesMove]
@EMPLOYEESID NVARCHAR(50),
@CODELINETRANSFER NVARCHAR(50),
@LINETRANSFER NVARCHAR(100),
@START_DATES DATETIME,
@START_TIME DATETIME,
@CREATEBY NVARCHAR(50),
@CREATEDATE DATETIME,
@TOTALMINUTES NVARCHAR(50),
@TOTALHOUR NVARCHAR(50)
AS
BEGIN
				DECLARE @CNT INT
									SELECT @CNT = COUNT(*) FROM STB_VN_EMPLOYEESTRANSFER WHERE EMPLOYEESID = @EMPLOYEESID AND END_DATES IS NULL AND END_TIME IS NULL AND  START_DATES IS NOT NULL AND START_TIME IS NOT NULL
			    IF @CNT > 0

				BEGIN
						UPDATE STB_VN_EMPLOYEESTRANSFER
						SET END_DATES =  DATEADD(dd, -2, DATEDIFF(dd, -2, GETDATE())), END_TIME =   DATEADD(HH, -2, GETDATE()),
						CHANGEBY = @CREATEBY, DATECHAGE = DATEADD(HH, -2, GETDATE()),
						 TOTALMINUTES = @TOTALMINUTES,
						TOTALHOUR  = @TOTALHOUR 
						WHERE EMPLOYEESID = @EMPLOYEESID AND END_DATES IS NULL AND END_TIME IS NULL AND  START_DATES IS NOT NULL AND START_TIME IS NOT NULL

						DECLARE @Codedep NVARCHAR(30)
						DECLARE @DepartName NVARCHAR(50)
						DECLARE @EmpName NVARCHAR(50)
						DECLARE @Ontime NVARCHAR(50)
				END

				
				    SELECT @Codedep = CODEDEPARTMENT, @DepartName = DEPARTMENTNAME, @EmpName = EMPLOYEESNAME FROM STB_VN_Employees WHERE EMPLOYEESID = @EMPLOYEESID
					INSERT INTO STB_VN_EMPLOYEESTRANSFER (EMPLOYEESID,EMPLOYEESNAME,CODELINECURRENTLY,LINECURRENTLY,CODELINETRANSFER,LINETRANSFER,START_DATES,START_TIME,CREATEBY,CREATEDATE,Shifts)
					VALUES (@EMPLOYEESID,@EmpName,@Codedep,@DepartName,@CODELINETRANSFER,@LINETRANSFER,@START_DATES,@START_TIME,@CREATEBY,@CREATEDATE,@Ontime)

			
END


-- SELECT * FROM STB_VN_EMPLOYEESTRANSFER
--SELECT DATEADD(dd, -2, DATEDIFF(dd, -2, GETDATE()))

--delete STB_VN_EMPLOYEESTRANSFER where EMPLOYEESID = '92005006'

