
CREATE PROC usp_VN_LocationMachines
@pCODELOCATIONMACHINES NVARCHAR(50) = NULL,
@pNAMELOCATION NVARCHAR(50) = NULL
AS
BEGIN

			DECLARE @CODELOCATIONMACHINES VARCHAR(100) = CASE WHEN ISNULL(@pCODELOCATIONMACHINES,'') = '' THEN '%' ELSE @pCODELOCATIONMACHINES END,
				@NAMELOCATION NVARCHAR(100)= CASE WHEN ISNULL (@pNAMELOCATION, '') = '' THEN '%' ELSE @pNAMELOCATION END
SELECT 
		ID,
		CODELOCATIONMACHINES,
		NAMELOCATION,
		Descptions,
		IsUsed,
		CreateDateTime AS Dates,
		RIGHT(CreateDateTime,8) AS Times,
		CreateUserID,
		ChangeDateTime AS DateChange,
		RIGHT(ChangeDateTime,8) AS TimeChanges,
		ChangeUserID
FROM 
		STB_VN_LOCATIONMACHINES WITH(NOLOCK)

WHERE
		(CODELOCATIONMACHINES LIKE @CODELOCATIONMACHINES)
		AND
		(NAMELOCATION LIKE @NAMELOCATION)
END
