CREATE PROC usp_VN_Import_Employees
@CODEDEPARTMENT NVARCHAR(50),
@DEPARTMENTNAME NVARCHAR(50),
@EMPLOYEESID NVARCHAR(50),
@EMPLOYEESNAME NVARCHAR(50),
@POSITTION NVARCHAR(50)
AS
BEGIN
		DECLARE @CNT INT
		SELECT @CNT = COUNT(*) FROM STB_VN_Employees WHERE EMPLOYEESID = @EMPLOYEESID

		IF @CNT > 0
			BEGIN
					UPDATE STB_VN_Employees

							SET CODEDEPARTMENT = @CODEDEPARTMENT,
								DEPARTMENTNAME = @DEPARTMENTNAME,
								EMPLOYEESNAME = @EMPLOYEESNAME,
								POSITTION = @POSITTION

					WHERE EMPLOYEESID = @EMPLOYEESID
			END
	ELSE
			BEGIN
					INSERT INTO STB_VN_Employees (EMPLOYEESID,CODEDEPARTMENT,DEPARTMENTNAME,EMPLOYEESNAME,POSITTION) VALUES (@EMPLOYEESID,@CODEDEPARTMENT,@DEPARTMENTNAME,@EMPLOYEESNAME,@POSITTION)
			END
END
