CREATE PROC [dbo].[usp_view_Bigtem] -- EXEC usp_view_Bigtem '360899' ,'aaaa'
@ID NVARCHAR(50),
@GRID NVARCHAR(50),
@CUSTOMERS NVARCHAR(50),
@USID NVARCHAR(50),
@SoInVoice NVARCHAR(50)
AS
BEGIN
SET NOCOUNT ON;


					
					--DECLARE @PACKINGID NVARCHAR(30)
					--DECLARE @LOTNO NVARCHAR(30)
					--DECLARE @MATERIALCODE NVARCHAR(30)
					--DECLARE @MATERIALNAMES NVARCHAR(30)
					--DECLARE @PACKQTY NVARCHAR(10)
					--DECLARE @PARTNO NVARCHAR(30)
					--DECLARE @PUBLICCODE NVARCHAR(30)
					--DECLARE @TYPEPRODUCTION NVARCHAR(30)
					--DECLARE @PRODUCTIONSIZE NVARCHAR(30)

					--SELECT 
					--	 @PACKINGID = PackingID,
					--	 @LOTNO = LotNo,
					--	 @MATERIALCODE = MaterialCode,
					--	 @MATERIALNAMES = MaterialName,
					--	 @PACKQTY = PackQty,
					--	 @PARTNO = PartNo,
					--	 @PUBLICCODE = PublicCode,
					--	 @TYPEPRODUCTION = TypeProduction,
					--	 @PRODUCTIONSIZE = ProductionSize
					--FROM STB_VN_FINISHGOODS WITH(NOLOCK)
					--WHERE Statusout IS NULL AND ID = @ID

					--INSERT INTO STB_VN_FINISHGOOD_OUT_TEMPORARY
					--(
						
					--	CREATEDATEGROUPID,
					--	STATUSIN,
					--	CREATEUSERID,
					--	CREATEDATEIN,
					--	PACKINGID,
					--	LOTNO,
					--	MATERIALCODE,
					--	MATERIALNAME,
					--	PACKQTY,
					--	PARTNO,
					--	PUBLICCODE,
					--	TYPEPRODUCTION,
					--	PRODUCTIONSIZE,
					--	GROUPID,
					--	IDFG
					--)
					--VALUES
					--(
					--	GETDATE(),
					--	'1',
					--	@USID,
					--	GETDATE(),
					--	@PACKINGID,
					--	@LOTNO,
					--	@MATERIALCODE,
					--	@MATERIALNAMES,
					--	@PACKQTY,
					--	@PARTNO,
					--	@PUBLICCODE,
					--	@TYPEPRODUCTION,
					--	@PRODUCTIONSIZE,
					--	@GRID,
					--	@ID
					--)

			IF (@ID IS NOT NULL)
			BEGIN
				
		 UPDATE STB_VN_FINISHGOODS
			SET CUSTOMERNAME = @CUSTOMERS,
			DateExport = GETDATE(),
			Statusout = N'Xuất',
			MethodActions1 = N'Xuất bằng cách đưa ra kho tạm',
			PersonExport = @USID,
			TYPEEXPORT ='XB',
			SoInVoice = @SoInVoice
		WHERE  ID = @ID

			END
		

		UPDATE STB_VN_FINISHGOOD_OUT_TEMPORARY
		SET CUSTOMERS = @CUSTOMERS,
			CREATEDATEGROUPID = GETDATE(),
			GROUPID = @GRID,
			SOINVOICES = @SoInVoice
		WHERE  IDFG = @ID


		-- SELECT TOP(100)* FROM STB_VN_FINISHGOODS WHERE Statusout IS NULL AND  CreateDate > ='2025-02-18'
-- SELECT TOP(100)* FROM STB_VN_FINISHGOODS WHERE ID = 361315
-- SELECT TOP(100)* FROM STB_VN_FINISHGOODS WHERE ID = 361316
-- SELECT * FROM  STB_VN_FINISHGOOD_OUT_TEMPORARY
-- delete STB_VN_FINISHGOOD_OUT_TEMPORARY

END


--	UPDATE STB_VN_FINISHGOODS
--		SET CUSTOMERNAME = null,
--			DateExport = null,
--			Statusout = null,
--			MethodActions1 = NULL,
--			PersonExport = null
--		WHERE  ID IN

--	(
--'361536'
--)

-- SELECT * FROM  STB_VN_FINISHGOOD_OUT_TEMPORARY
 --SELECT * FROM STB_VN_FINISHGOODS WHERE PersonExport = 'nguyennha' AND CONVERT(DATE,DateExport) = '2025-02-20'

-- SELECT TOP(10)* FROM STB_VN_FINISHGOODS

-- DELETE STB_VN_FINISHGOOD_OUT_TEMPORARY