CREATE PROC [dbo].[usp_VN_LoaiHinhToKhai]
AS
BEGIN
		CREATE TABLE #T1
		(
			NAMES NVARCHAR(50) PRIMARY KEY(NAMES) NOT NULL,
			DESCPTIONS NVARCHAR(50)
		)

		INSERT INTO #T1 (NAMES) VALUES ('E31')
		INSERT INTO #T1 (NAMES) VALUES ('A12')
		INSERT INTO #T1 (NAMES) VALUES ('h21')
		INSERT INTO #T1 (NAMES) VALUES ('H11')
		INSERT INTO #T1 (NAMES) VALUES (' ')  --Add by Mr.Tung on 2021-07-17 , request by Mr.Hop Kho

		SELECT 
				NAMES
		FROM 
				#T1

	DROP TABLE #T1

END