CREATE PROC usp_transfer_TimeSupport
AS
BEGIN

DECLARE @EMPLOYEESID NVARCHAR(50)
DECLARE @CODELINETRANSFER NVARCHAR(50)
DECLARE @LINETRANSFER NVARCHAR(100)
DECLARE @START_DATES DATETIME
DECLARE @START_TIME NVARCHAR(50)
DECLARE @END_DATES DATETIME
DECLARE @END_TIME NVARCHAR(50)
DECLARE @TOTALMINUTES NVARCHAR(50)
DECLARE @TOTALHOUR NVARCHAR(50)
DECLARE @Shifts NVARCHAR(50)
DECLARE @CREATEBY NVARCHAR(50)
DECLARE @CREATEDATE_TRANSFER DATETIME
DECLARE @CHANGEBY_TRANSFER NVARCHAR(50)
DECLARE @DATECHAGE DATETIME
DECLARE @CNT INT

DECLARE Cusproduction CURSOR FOR

SELECT
		 EMPLOYEESID
		 ,CODELINETRANSFER
		 ,LINETRANSFER
         ,LEFT(START_DATES,11) AS START_DATES
		  ,START_TIME
		  ,LEFT(END_DATES,11) AS END_DATES
		   ,END_TIME
		,'' + replace(TOTALMINUTES, '0', '') AS TOTALMINUTE
		,TOTALHOUR
		,Shifts
		,CREATEBY
		,CREATEDATE
		,CHANGEBY
		,DATECHAGE

FROM  

	STB_VN_EMPLOYEESTRANSFER WITH(NOLOCK)


OPEN Cusproduction

FETCH NEXT FROM Cusproduction

		INTO @EMPLOYEESID,@CODELINETRANSFER,@LINETRANSFER,@START_DATES,@START_TIME,@END_DATES,@END_TIME,@TOTALMINUTES,@TOTALHOUR,@Shifts,@CREATEBY,@CREATEDATE_TRANSFER,@CHANGEBY_TRANSFER,@DATECHAGE

		WHILE @@FETCH_STATUS = 0

		BEGIN
				SELECT @CNT = COUNT(*) FROM STB_VN_ATTENDANCE_TIME  WHERE EMPLOYEES_ID = @EMPLOYEESID AND LEFT(WORK_DATE,12) = @START_DATES

		IF @CNT > 0

		BEGIN

				UPDATE STB_VN_ATTENDANCE_TIME

				SET
						EMPLOYEES_ID = @EMPLOYEESID,
						CODELINETRANSFER = @CODELINETRANSFER,
						LINETRANSFER = @LINETRANSFER ,
						START_DATES = @START_DATES,
						START_TIME = @START_TIME,
						END_DATES = @END_DATES,
						END_TIME = @END_TIME,
						TOTALMINUTES = @TOTALMINUTES,
						TOTALHOUR = @TOTALHOUR,
						Shifts = @Shifts,
						CREATEBY = @CREATEBY,
						CREATEDATE_TRANSFER = @CREATEDATE_TRANSFER,
						CHANGEBY_TRANSFER = @CHANGEBY_TRANSFER,
						DATECHAGE = @DATECHAGE

				WHERE
						EMPLOYEES_ID = @EMPLOYEESID AND LEFT(WORK_DATE,12) = @START_DATES
		END

		FETCH NEXT FROM Cusproduction

		INTO @EMPLOYEESID,@CODELINETRANSFER,@LINETRANSFER,@START_DATES,@START_TIME,@END_DATES,@END_TIME,@TOTALMINUTES,@TOTALHOUR,@Shifts,@CREATEBY,@CREATEDATE_TRANSFER,@CHANGEBY_TRANSFER,@DATECHAGE

		END

		CLOSE Cusproduction              
		DEALLOCATE Cusproduction   


END


--SELECT * FROM STB_VN_ATTENDANCE_TIME
-- EXEC usp_transfer_TimeSupport


--SELECT * FROM STB_VN_EMPLOYEESTRANSFER