CREATE PROC usp_view_detail_fin
@PKID NVARCHAR(50),
@CREATEUSERID NVARCHAR(30)
AS
BEGIN

					IF EXISTS (SELECT PACKINGID FROM STB_VN_FINISHGOOD_OUT_TEMPORARY WITH(NOLOCK) WHERE PACKINGID = @PKID)

						BEGIN 
								SELECT
										PACKINGID,
										LOTNO,
										MATERIALCODE,
										MATERIALNAME,
										PACKQTY,
										PARTNO,
										PUBLICCODE,
										TYPEPRODUCTION,
										PRODUCTIONSIZE,
										CREATEUSERID,
									CASE 
									WHEN STATUSPRINTER IS NULL THEN N'Chưa in tem QR to'
									WHEN STATUSPRINTER IS NOT NULL THEN N'Đã in tem QR to'
									ELSE  ''
									END 'STATUSPRINTER',

									CASE 
									WHEN STATUSIN = 1 THEN N'Đã nhập vào kho tạm'
									ELSE ''
									END  'STATUSIN',

									CASE 
									WHEN STATUSOUT IS NULL THEN N'Đang chờ bế lên công te lơ'
									WHEN STATUSOUT IS NOT NULL THEN N'Đã được bế lên công te lơ'
									ELSE ''
									END 'STATUSOUT'
										
								FROM STB_VN_FINISHGOOD_OUT_TEMPORARY WITH(NOLOCK)

								WHERE PACKINGID = @PKID 
									
						END 
		ELSE
		

			BEGIN

											DECLARE @IDFG NVARCHAR(20)
											DECLARE @PACKINGID NVARCHAR(30)
											DECLARE @LOTNO NVARCHAR(30)
											DECLARE @MATERIALCODE NVARCHAR(20)
											DECLARE @MATERIALNAME NVARCHAR(40)
											DECLARE @PACKQTY NVARCHAR(10)
											DECLARE @PARTNO NVARCHAR(30)
											DECLARE @PUBLICCODE NVARCHAR(30)
											DECLARE @TYPEPRODUCTION NVARCHAR(30)
											DECLARE @PRODUCTIONSIZE NVARCHAR(30)

											SELECT @IDFG = ID, @PACKINGID = PackingID, @LOTNO = LotNo, @MATERIALCODE = MaterialCode, @MATERIALNAME = MaterialName,
												   @PACKQTY = PackQty, @PARTNO = PartNo, @PUBLICCODE = PublicCode, @TYPEPRODUCTION = TypeProduction, @PRODUCTIONSIZE = ProductionSize
											FROM STB_VN_FINISHGOODS WITH(NOLOCK)
											WHERE Statusout IS NULL AND PackingID = @PKID

											INSERT INTO STB_VN_FINISHGOOD_OUT_TEMPORARY(IDFG,PACKINGID,LOTNO,MATERIALCODE,MATERIALNAME,PACKQTY,PARTNO,PUBLICCODE,TYPEPRODUCTION,PRODUCTIONSIZE,CREATEUSERID,CREATEDATEIN,STATUSIN)VALUES(@IDFG,@PACKINGID,@LOTNO,@MATERIALCODE,@MATERIALNAME,@PACKQTY,@PARTNO,@PUBLICCODE,@TYPEPRODUCTION,@PRODUCTIONSIZE,@CREATEUSERID,GETDATE(),'1')

			END
END