CREATE PROC [dbo].[usp_VN_ATTENDANCE_REALTIME] -- exec usp_VN_ATTENDANCE_REALTIME '92011009','abc'
@EMPLOYEES_ID NVARCHAR(50),
@CREATEUSSERID NVARCHAR(50),
@CODELINEMOVE NVARCHAR(50),
@NAMELINEMOVE NVARCHAR(50)
AS
BEGIN
		DECLARE @EMPLOYEESNAME NVARCHAR(50)
	
		DECLARE @CNT INT
		DECLARE @STIMES TIME
		SET @STIMES = CAST(DATEADD(HH, -2, GETDATE()) AS TIME)
	
			
					SELECT

					  TOP(1)
						@EMPLOYEESNAME = EMPLOYEESNAME
						
					FROM

						STB_VN_Employees WITH(NOLOCK)

					WHERE

						EMPLOYEESID = @EMPLOYEES_ID

				    ORDER BY 

						CREATEDATE DESC 


						
		INSERT INTO STB_VN_ATTENDANCE_TIME
		(
			EMPLOYEES_ID,
			EMPLOYEES_NAME,
			CODE_LINE,
			NAME_LINE,
			WORK_DATE,
			START_TIME,
			STARTSTATUS,
			CREATEDATETIME,
			CREATEUSSERID
		)
		VALUES
		(
			@EMPLOYEES_ID,
			@EMPLOYEESNAME,
			@CODELINEMOVE,
			@NAMELINEMOVE,
			DATEADD(dd, 0, DATEDIFF(dd, 0,DATEADD(HH, -2, GETDATE()))),
			CONVERT(VARCHAR(5), @STIMES, 108),
			N'Thời gian bắt đầu',
		    DATEADD(HH, -2, GETDATE()),
			@CREATEUSSERID
		)
	
			
END

 -- select * from  STB_VN_ATTENDANCE_TIME where CREATEUSSERID = 'Nha'

-- select * from STB_VN_ATTENDANCE_TIME where employees_id = '92011009' and STARTSTATUS = N'Thời gian bắt đầu'


--	delete STB_VN_ATTENDANCE_TIME   where employees_id = '32009001' and STARTSTATUS = N'Thời gian bắt đầu'


--select * from STB_VN_EMPLOYEESTRANSFERLINE where EMPLOYEESID = '31809030'


