CREATE PROC [dbo].[usp_vn_Update_att_time]
@EMPLOYEES_ID NVARCHAR(50),
@START_TIME NVARCHAR(50),
@CREATEUSSERID NVARCHAR(50)
AS
BEGIN
			DECLARE @TIMES TIME
			SET @TIMES = CAST(DATEADD(HH, -2, GETDATE()) AS TIME)
		    DECLARE @TST NVARCHAR(10)

					UPDATE STB_VN_ATTENDANCE_TIME

					SET

						END_TIME = CONVERT(VARCHAR(5), @TIMES, 108),
						TOTAL_TIME = DATEDIFF(MINUTE, @START_TIME, CONVERT(VARCHAR(5), @TIMES, 108)),
						CHANGEDATETIME = DATEADD(HH, -2, GETDATE()),
						ENDSTATUS = N'Thời gian kết thúc',
						CHANGEUSERID = @CREATEUSSERID

					
					WHERE
							EMPLOYEES_ID = @EMPLOYEES_ID AND END_TIME IS NULL  AND ENDSTATUS IS NULL

END


-- select * from  STB_VN_ATTENDANCE_TIME where EMPLOYEES_ID = N'FSDFASFDFÁDFASDF'

-- delete STB_VN_ATTENDANCE_TIME where EMPLOYEES_ID = N'92011009'

--select * from delete STB_VN_EMPLOYEESTRANSFER where EMPLOYEESID  = N'32009001'