CREATE PROC usp_vn_bom_logittic
@PRODUCTIONNAME NVARCHAR(50),
@ONCELLSIZE NVARCHAR(50),
@PRODUCTIONCODE NVARCHAR(50),
@PART NVARCHAR(50),
@MATERIALNAME NVARCHAR(50),
@MATERIALCODE NVARCHAR(50),
@USAGE NVARCHAR(50),
@UNIT NVARCHAR(50),
@TYPEBOM NVARCHAR(50) = NULL,
@NOTES NVARCHAR(500),
@CreateUserID NVARCHAR(50)
AS
BEGIN
		INSERT INTO STB_VN_BOM_LOGITIC (PRODUCTIONNAME,ONCELLSIZE,PRODUCTIONCODE,PART,MATERIALNAME,MATERIALCODE,USAGE,UNIT,TYPEBOM,NOTES,CreateUserID,CreateDateTime) VALUES (@PRODUCTIONNAME,@ONCELLSIZE,@PRODUCTIONCODE,@PART,@MATERIALNAME,@MATERIALCODE,@USAGE,@UNIT,@TYPEBOM,@NOTES,@CreateUserID,DATEADD(HH, -2, GETDATE()))
END