CREATE PROC usp_TypeVNKR
AS
BEGIN
		CREATE TABLE #T
		(
			NAMES NVARCHAR(50) NOT NULL PRIMARY KEY(NAMES)
		)

		INSERT INTO #T (NAMES) VALUES (N'Điện cực Việt Nam')
		INSERT INTO #T (NAMES) VALUES (N'Điện cực Hàn Quốc')

		SELECT * FROM #T

		DROP TABLE #T
END