
CREATE PROC [dbo].[usp_VN_showThailanstamp]
@pProcessUserID NVARCHAR(50),
@pLotNo NVARCHAR(50) = NULL,
@pPNCELESTICA NVARCHAR(50) = NULL,
@pPNSUPPLIERS NVARCHAR(50) = NULL,
@pQTY NVARCHAR(50) = NULL
AS
BEGIN
DECLARE @LOTNO NVARCHAR(50)
DECLARE @DATEMAKE NVARCHAR(50)
DECLARE @MADESS NVARCHAR(50)
DECLARE @DATES NVARCHAR(50)
DECLARE @WEEK NVARCHAR(50)
DECLARE @YY NVARCHAR(50)
DECLARE @YYWK NVARCHAR(50)
DECLARE @CODEVENDOR NVARCHAR(50)

SELECT 
		@LOTNO = LotNo,
		@DATEMAKE = CONVERT(DATE,PrintTime),
		@DATES = LEFT(@DATEMAKE,4),
		@WEEK = DATEPART(WEEK,CONVERT(DATE,PrintTime)),
		@YY = RIGHT(@DATES,2),
		@YYWK = --@YY+ + '0'+@WEEK
		case 
					when @WEEK >= 10
						then
						@YY+@WEEK
					else
						@YY+'0'+@WEEK
					end
		,
		@CODEVENDOR = '0000238214',
		@MADESS = 'VN'
FROM
		STB_SavePackingTime_VVT WITH(NOLOCK)
WHERE 

		LotNo = @pLotNo

		
IF @LOTNO IS NOT NULL

BEGIN
		 INSERT INTO STB_VN_THAILANSTAMP (PNCELESTICA,PNSUPPLIERS,CODEVENDOR,LOTNO,DATEPRODUCTION,MADESBY,CreateUserID,CreateDateTime,QTY)
		 VALUES (@pPNCELESTICA,@pPNSUPPLIERS,@CODEVENDOR,@LOTNO,@YYWK,@MADESS,@pProcessUserID,DATEADD(HH, -2, GETDATE()),@pQTY)

SELECT
			TOP(1)
			 PNCELESTICA AS PNCELESTICA,
			 PNSUPPLIERS AS PNSUPPLIERS,
			CODEVENDOR,
			LOTNO AS LOTNO,
			DATEPRODUCTION AS DATEPRODUCTION,
			QTY,
			 MADESBY AS MADESBY,
			LABLELQTY,

			'1P' + PNCELESTICA AS SCAN_PNCELESTICA,
			'P' + PNSUPPLIERS AS SCAN_PNSUPPLIERS,
			'1T'+ LOTNO AS SCAN_LOTNO,
			'10D' + DATEPRODUCTION AS SCAN_DATEPRODUCTION,
			'V' + CODEVENDOR AS SCAN_CODEVENDOR,
			'Q' + QTY AS SCAN_QTY,
			'4L' + MADESBY AS SCAN_MADESBY,
			'Report' AS CommandType
			
FROM

		   STB_VN_THAILANSTAMP WITH(NOLOCK)

WHERE
			CreateUserID = @pProcessUserID
	
ORDER BY 
			CreateDateTime DESC
END

END
--SELECT * FROM STB_SavePackingTime_VVT WHERE LotNo = 'VVNM063R025636'

--SELECT TOP 10 (PrintTime) FROM STB_SavePackingTime_VVT

--alter PROC usp_VN_stampThailan
--AS
--BEGIN
--		CREATE TABLE #T1 (PNCELESTICA NVARCHAR(50) PRIMARY KEY(PNCELESTICA), PNSUPPLIERS NVARCHAR(50))
--		INSERT INTO #T1 (PNCELESTICA,PNSUPPLIERS) VALUES ('WEC2R7106QG','100-0778-00N6E')
--		INSERT INTO #T1 (PNCELESTICA,PNSUPPLIERS) VALUES ('WEC2R7256QG','100-0781-00N6E')

--		SELECT * FROM #T1

--		DROP TABLE #T1
--END

-- SELECT * FROM  STB_VN_THAILANSTAMP

--DELETE STB_VN_THAILANSTAMP