CREATE PROC [dbo].[usp_VN_CodeFinishedGood]
AS
BEGIN
SELECT CODEACC, COUNT(*)
  FROM STB_VN_CODEGOODFINISED WITH (NOLOCK)
 GROUP BY CODEACC
 HAVING COUNT(*) > 1
	
END



--SELECT IDCODE, COUNT(*)
--FROM STB_VN_FINISHGOODS
--GROUP BY IDCODE
--HAVING COUNT(*) > 1

--ALTER PROC [dbo].[usp_VN_COUNTRYFINISHEDGOOD]
--AS
--BEGIN
--		SELECT
--				CountryName
--		FROM 
--				STB_VN_COUNTRY WITH (NOLOCK)
--END

-- select * from STB_VN_FINISHGOODS where USERID ='nguyennha'

-- select * from STB_VN_CODEGOODFINISED 

-- select * from STB_VN_COUNTRY


--add CODEACC NVARCHAR(50)

--SELECT *
--  FROM STB_VN_CODEGOODFINISED WITH (NOLOCK)
------  where CODEACC ='VNVEC30-008'

--delete STB_VN_CODEGOODFINISED where CODEACC  IS NULL