CREATE PROC [dbo].[usp_VN_STB_VN_CLASSIFY]
	@pProcessLanguage VARCHAR(20),
	@pProcessUserID VARCHAR(20)
AS
BEGIN
		SET NOCOUNT ON;
		
		SELECT
				IDS,
				NameCLASSIFY

		FROM 
				STB_VN_CLASSIFY WITH (NOLOCK)
		WHERE 
				Actives=1
END