CREATE PROC [dbo].[usp_VN_TYPESTAPPINGBENNDING] 
@pRework INT = 0
AS
BEGIN
		CREATE TABLE #T
		(
			ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY(ID),
			NANMES NVARCHAR(50)
		)



				INSERT INTO #T (NANMES) VALUES ('Tapping')
				INSERT INTO #T (NANMES) VALUES ('Bending')
				INSERT INTO #T (NANMES) VALUES ('Cutting')
				INSERT INTO #T (NANMES) VALUES ('Rework')
				INSERT INTO #T (NANMES) VALUES ('Sorting')


		SELECT
			 NANMES
		FROM		
			 #T

		DROP TABLE #T
END