
CREATE PROC [dbo].[usp_VN_Weigh] --EXEC  [usp_VN_Weigh] 'A','A','A','10.56','2022-05-05'
@WEIGH NVARCHAR(50),
@CREATEDATE NVARCHAR(50)
AS
BEGIN

  DECLARE @TimeServer NVARCHAR(50)

  SET @TimeServer =  @CREATEDATE + ' ' + CONVERT(VARCHAR(8), DATEADD(HH, -2, GETDATE()),108)

		INSERT INTO STB_VN_Weigh (LINECODE,LINENAME,MODEL,WEIGH,CREATEDATE) VALUES ('VVC-21','Cell Line # 21','1840',@WEIGH,@TimeServer)
END

-- SELECT * FROM STB_VN_Weigh