-- =============================================
-- Author : Jackaroe(yjyu@vina.co.kr)
-- Group : 생산관리
-- Browsable : true
-- Create date : 2019-12-09
-- Description : 
-- Modified :
-- =============================================
CREATE PROCEDURE usp_CheckScheduleStatus_get
	@pProcessUserID VARCHAR(20),
	@pProcessLanguage VARCHAR(20),
	@pFromDate DATETIME,
	@pToDate DATETIME
AS

BEGIN

	Declare @FromDate DATETIME = CONVERT(VARCHAR(10), @pFromDate, 121) + ' 08:30:00'
		   ,@ToDate DATETIME = CONVERT(VARCHAR(10), DATEADD(day, 1, @pToDate), 121) + ' 08:29:59'

	SELECT CSI2.LineCode
		  ,LI.LineName
		  ,CASE WHEN CONVERT(VARCHAR(8), CSI2.CheckTime, 108) BETWEEN '08:30:00' AND '20:29:59' THEN 1
				ELSE 2 END AS TimeShiftCode
		  ,CASE WHEN CASE WHEN CONVERT(VARCHAR(8), CSI2.CheckTime, 108) BETWEEN '08:30:00' AND '20:29:59' THEN 1
				ELSE 2 END = 1 THEN '주간' ELSE '야간' END AS TimeShiftName
		  ,COUNT(CASE WHEN CSI2.CheckClassNo = 'DLC0001' THEN 1 ELSE NULL END) AS DLC0001T
		  ,COUNT(CASE WHEN CSI2.CheckClassNo = 'DLC0001' AND CONVERT(VARCHAR(10), CSI.CheckDate, 121) + ' ' + CONVERT(VARCHAR(8), CSI2.CheckTime, 108) > CONVERT(VARCHAR(19), GETDATE(), 121) THEN 1 ELSE NULL END) AS DLC0001B
		  ,COUNT(CASE WHEN CSI2.CheckClassNo = 'DLC0001' AND CONVERT(VARCHAR(10), CSI.CheckDate, 121) + ' ' + CONVERT(VARCHAR(8), CSI2.CheckTime, 108) <= CONVERT(VARCHAR(19), GETDATE(), 121) AND CSI.CheckYn IS NULL THEN 1 ELSE NULL END) AS DLC0001M
		  ,COUNT(CASE WHEN CSI2.CheckClassNo = 'DLC0001' AND CSI.CheckYn = 0 THEN 1 ELSE NULL END) AS DLC0001N

		  ,COUNT(CASE WHEN CSI2.CheckClassNo = 'DLC0002' THEN 1 ELSE NULL END) AS DLC0002T
		  ,COUNT(CASE WHEN CSI2.CheckClassNo = 'DLC0002' AND CONVERT(VARCHAR(10), CSI.CheckDate, 121) + ' ' + CONVERT(VARCHAR(8), CSI2.CheckTime, 108) > CONVERT(VARCHAR(19), GETDATE(), 121) THEN 1 ELSE NULL END) AS DLC0002B
		  ,COUNT(CASE WHEN CSI2.CheckClassNo = 'DLC0002' AND CONVERT(VARCHAR(10), CSI.CheckDate, 121) + ' ' + CONVERT(VARCHAR(8), CSI2.CheckTime, 108) <= CONVERT(VARCHAR(19), GETDATE(), 121) AND CSI.CheckYn IS NULL THEN 1 ELSE NULL END) AS DLC0002M
		  ,COUNT(CASE WHEN CSI2.CheckClassNo = 'DLC0002' AND CSI.CheckYn = 0 THEN 1 ELSE NULL END) AS DLC0002N

		  ,COUNT(CASE WHEN CSI2.CheckClassNo = 'DLC0005' THEN 1 ELSE NULL END) AS DLC0005T
		  ,COUNT(CASE WHEN CSI2.CheckClassNo = 'DLC0005' AND CONVERT(VARCHAR(10), CSI.CheckDate, 121) + ' ' + CONVERT(VARCHAR(8), CSI2.CheckTime, 108) > CONVERT(VARCHAR(19), GETDATE(), 121) THEN 1 ELSE NULL END) AS DLC0005B
		  ,COUNT(CASE WHEN CSI2.CheckClassNo = 'DLC0005' AND CONVERT(VARCHAR(10), CSI.CheckDate, 121) + ' ' + CONVERT(VARCHAR(8), CSI2.CheckTime, 108) <= CONVERT(VARCHAR(19), GETDATE(), 121) AND CSI.CheckYn IS NULL THEN 1 ELSE NULL END) AS DLC0005M
		  ,COUNT(CASE WHEN CSI2.CheckClassNo = 'DLC0005' AND CSI.CheckYn = 0 THEN 1 ELSE NULL END) AS DLC0005N

		  ,COUNT(CASE WHEN CSI2.CheckClassNo = 'DLC0003' THEN 1 ELSE NULL END) AS DLC0003T
		  ,COUNT(CASE WHEN CSI2.CheckClassNo = 'DLC0003' AND CONVERT(VARCHAR(10), CSI.CheckDate, 121) + ' ' + CONVERT(VARCHAR(8), CSI2.CheckTime, 108) > CONVERT(VARCHAR(19), GETDATE(), 121) THEN 1 ELSE NULL END) AS DLC0003B
		  ,COUNT(CASE WHEN CSI2.CheckClassNo = 'DLC0003' AND CONVERT(VARCHAR(10), CSI.CheckDate, 121) + ' ' + CONVERT(VARCHAR(8), CSI2.CheckTime, 108) <= CONVERT(VARCHAR(19), GETDATE(), 121) AND CSI.CheckYn IS NULL THEN 1 ELSE NULL END) AS DLC0003M
		  ,COUNT(CASE WHEN CSI2.CheckClassNo = 'DLC0003' AND CSI.CheckYn = 0 THEN 1 ELSE NULL END) AS DLC0003N
	  FROM STB_CheckScheduleInfo CSI
	  LEFT OUTER JOIN STB_CheckStandardInfo CSI2
		ON CSI.CheckStandardNo = CSI2.CheckStandardNo
	  LEFT OUTER JOIN STB_LineInfo LI
		ON LI.LineCode = CSI2.LineCode
	 WHERE CONVERT(VARCHAR(10), CSI.CheckDate, 121) + ' ' + CONVERT(VARCHAR(8), CSI2.CheckTime, 108) BETWEEN @FromDate AND @ToDate
	   AND CSI.IsUsed = 1
	 GROUP BY CSI2.LineCode, LI.LineName
			,CASE WHEN CONVERT(VARCHAR(8), CSI2.CheckTime, 108) BETWEEN '08:30:00' AND '20:29:59' THEN 1
				  ELSE 2 END
			,CASE WHEN CASE WHEN CONVERT(VARCHAR(8), CSI2.CheckTime, 108) BETWEEN '08:30:00' AND '20:29:59' THEN 1
				  ELSE 2 END = 1 THEN '주간' ELSE '야간' END
	  ORDER BY LineCode, TimeShiftCode
END