CREATE PROC [dbo].[usp_View_GroupIDscan]
@GRID NVARCHAR(50)
AS
BEGIN

IF(@GRID IS NOT NULL)
	BEGIN
			UPDATE STB_VN_FINISHGOOD_OUT_TEMPORARY
			SET CREATEDATEOUT = GETDATE(), STATUSOUT = 1
			WHERE GROUPID = @GRID

			SELECT 
				IDFG,
				PACKINGID,
				LOTNO,
				MATERIALCODE,
				MATERIALNAME,
				PACKQTY,
				PARTNO,
				PUBLICCODE,
				TYPEPRODUCTION,
				PRODUCTIONSIZE,
				CREATEUSERID,
				CREATEDATEOUT,
				CASE
					WHEN STATUSIN IS NULL THEN N'Chưa được bế vào kho tạm.!'

				    WHEN STATUSIN IS NOT NULL THEN N'Đã được bế vào kho tạm.'

				ELSE ''

				END 'STATUSIN',

				CASE
					WHEN STATUSOUT IS NULL THEN N'Chưa được bế lên công te lơ.!'
					WHEN STATUSOUT IS NOT NULL THEN N'Đã được bế lên công te lơ.!'
				
				ELSE ''

				END 'STATUSOUT',

				CUSTOMERS

		FROM STB_VN_FINISHGOOD_OUT_TEMPORARY WITH(NOLOCK)

		WHERE GROUPID = @GRID AND GROUPID IS NOT NULL --AND STATUSOUT IS NOT NULL

	END
		
END

-- SELECT * FROM STB_VN_FINISHGOOD_OUT_TEMPORARY
-- DELETE STB_VN_FINISHGOOD_OUT_TEMPORARY

