
CREATE proc usp_vn_show_gridview
@EMPLOYEES_ID nvarchar(50)
as
begin

SELECT
			TOP(1)
			EMPLOYEES_ID,
			EMPLOYEES_NAME,
			NAME_LINE,
			WORK_DATE,
			START_TIME,

			CASE
					WHEN END_TIME IS NULL THEN N'Hệ thống vẫn chờ bạn kết thúc giời làm việc'
			ELSE ''
			END AS END_TIME,

			CREATEDATETIME,
			CREATEBY
		FROM
				STB_VN_ATTENDANCE_TIME WITH(NOLOCK)

		WHERE
				EMPLOYEES_ID = @EMPLOYEES_ID AND  END_TIME IS NULL  AND ENDSTATUS IS NULL

	
end

--SELECT * FROM STB_VN_ATTENDANCE_TIME