CREATE PROC [dbo].[usp_ViewPrinter_VN_SCRAP_WEIGHSCALE_PRODUCTIONS] -- exec usp_ViewPrinter_VN_SCRAP_WEIGHSCALE_PRODUCTIONS '92005006'
@BARCODE NVARCHAR(200)
AS
BEGIN
 SELECT
			--ID,
	        IMAGEBARCODE,
			LINECODE,
			NAMELINE,
			WEIGHSCALE,
			USERID,
			DATEWEIGH,
			TYPESCRAP,
			TYPENAMES,
			NAMEPRODUCTION,
			SHIFTS,
			CODENAME,
			QUANTITY
			
			
	  FROM
			STB_VN_SCRAP_WEIGHSCALE_PRODUCTIONS WITH(NOLOCK)
	   WHERE
			 USERID = @BARCODE AND  STATUSDELETE IS NULL AND DATEWEIGH = CONVERT(DATE,GETDATE()) AND FLAG = 0
	  ORDER BY CREATEDATE DESC
END

--FLAG = 0 AND
 -- select  * from   STB_VN_SCRAP_WEIGHSCALE_PRODUCTIONS   WHERE USERID =  '92005006'


 --select top(100)* from  STB_VN_SCRAP_WEIGHSCALE_PRODUCTIONS order by CREATEDATE DESC


--SELECT * FROM STB_VN_SCRAP_WEIGHSCALE_PRODUCTIONS WHERE USERID = '92005006'


--DELETE STB_VN_SCRAP_WEIGHSCALE_PRODUCTIONS WHERE USERID = '92005006'