CREATE PROC usp_VN_STAGEMACHINES_DETAIL
@CODEIDM NVARCHAR(50),
@Lang NVARCHAR(50)
AS
BEGIN
IF @Lang = 'en-US'
BEGIN
		SELECT
				CODEID,
				English AS Categories
		FROM 
				STB_VN_STAGEMACHINES_DETAIL WITH(NOLOCK)
		WHERE
				Actives = 1 AND CODEIDM = @CODEIDM
END
IF @Lang = 'vi-VN'
BEGIN
			SELECT
				CODEID,
				Categories AS Categories
		FROM 
				STB_VN_STAGEMACHINES_DETAIL WITH(NOLOCK)
		WHERE
				Actives = 1 AND CODEIDM = @CODEIDM
END
IF @Lang = 'ko-KR'
BEGIN
SELECT
				CODEID,
				Korean AS Categories
		FROM 
				STB_VN_STAGEMACHINES_DETAIL WITH(NOLOCK)
		WHERE
				Actives = 1 AND CODEIDM = @CODEIDM
END
END