CREATE PROC usp_View_Security  -- exec usp_View_Security 'bv_bg', 'VVT_F1'
@SECURITYAPPERVOER_BN NVARCHAR(50),
@FACTORY NVARCHAR(50)
AS
BEGIN

IF @FACTORY = 'VVT_F2'

		SELECT
				GROUPID,
				Barcode,
				RouteCode,
				RouteName,
				MaterialCode,
				MaterialName,
				LineCode,
				LineName,
				ProdQty,
				PERSONAPPROVER_BG AS 'SECURITY',

				CASE
						WHEN PERSONSTATUSAPPROVER_BG = 1 THEN N'Đã duyệt'

				ELSE ''

				END AS 'PERSONSTATUSAPPROVER'

		FROM

			STB_VN_STAGES_TRANSFER WITH(NOLOCK)

		WHERE
				PERSONSTATUSAPPROVER_BG = 1 AND SECURITYAPPERVOER_BG = @SECURITYAPPERVOER_BN AND GROUPID IS NOT NULL AND SECURITYSTATUS_BG IS NULL

ELSE IF @FACTORY = 'VVT_F1'

BEGIN
	
			SELECT
						GROUPID,
						Barcode,
						RouteCode,
						RouteName,
						MaterialCode,
						MaterialName,
						LineCode,
						LineName,
						ProdQty,
						PERSONAPPROVER_BN AS 'SECURITY',

						CASE
								WHEN PERSONSTATUSAPPROVER_BN = 1 THEN N'Đã duyệt'

						ELSE ''

						END AS 'PERSONSTATUSAPPROVER'

				FROM

					STB_VN_STAGES_TRANSFER WITH(NOLOCK)

				WHERE
						PERSONSTATUSAPPROVER_BN = 1 AND SECURITYAPPERVOER_BN = @SECURITYAPPERVOER_BN AND GROUPID IS NOT NULL AND SECURITYSTATUS_BN IS NULL

END

	ELSE
			PRINT 'Do not anything data'

END
