CREATE PROC [dbo].[usp_ViewWeighScale] -- EXEC usp_ViewWeighScale '2022-05-01','2022-05-30'

--	EXEC usp_ViewWeighScale'2024-04-05','2024-04-10','','VVT_F1'
--	EXEC usp_ViewWeighScale'2024-04-05','2024-04-10','','VVT_F2'
--	EXEC usp_ViewWeighScale'2024-04-05','2024-04-10','',''
@pFrom DATE = NULL,
@pTo DATE = NULL,
@pCompanyCode VARCHAR(20) = NULL,
@pWorkCenterCode VARCHAR(20) = NULL

AS
BEGIN

DECLARE @KG  FLOAT
DECLARE @CONVERTKG NVARCHAR(50)
SET @KG = 3.000

IF @pWorkCenterCode = 'VVT_F1'
	BEGIN 

		SELECT
	
				LINECODE,
				NAMELINE,
				'' + replace(WEIGHSCALE, 'U', '') + '' AS WEIGHSCALES, 
				QUANTITY,
				DATEWEIGH,
				USERID,
				TYPENAMES,CODENAME,NAMEPRODUCTION,UNITS,
				CASE
					WHEN FLAG = 0 AND STATUSDELETE IS NULL THEN N'Đang chờ in tem'
					WHEN FLAG = 1 AND STATUSDELETE IS NULL THEN N'Đã được in tem'
					WHEN FLAG = 0 AND STATUSDELETE IS NOT NULL THEN N'Dữ liệu đã được xóa'
				ELSE ''
				END AS 'STATUSPRINTER',
				CONVERTKG AS CONVERTKG,
				TYPESCRAP, 
				RIGHT(CREATEDATE,8) AS CREATEDATE,
				SHIFTS,
					NAMEERROR
 INTO #T1

		FROM
			STB_VN_SCRAP_WEIGHSCALE_PRODUCTIONS WITH(NOLOCK)
		WHERE  LINECODE not like '%BG%' and DATEWEIGH BETWEEN @pFrom AND @pTo 
				

				SELECT

				LINECODE,
				NAMELINE,
				'' + replace(WEIGHSCALES, 'Ta', '') + '' AS WEIGHSCALE, 
				QUANTITY,
				DATEWEIGH,
				USERID,
				TYPENAMES,CODENAME,NAMEPRODUCTION,UNITS,
				STATUSPRINTER,
				CONVERTKG,
				TYPESCRAP, 
				CREATEDATE,
				SHIFTS,
				NAMEERROR

				INTO #T2

				FROM 
						#T1

		SELECT

		
				LINECODE,
				NAMELINE,
				'' + replace(WEIGHSCALE, 'T', '') + '' AS WEIGHSCALE, 
				QUANTITY, 
				DATEWEIGH,
				USERID,
				TYPENAMES,CODENAME,NAMEPRODUCTION,UNITS,
				STATUSPRINTER,
				CONVERTKG,
				TYPESCRAP, 
				CREATEDATE,
				SHIFTS,
				NAMEERROR

			INTO #T3
		FROM
				#T2


SELECT

		
				LINECODE,
				NAMELINE,
				'' + replace(WEIGHSCALE, '/W', '') + '' AS WEIGHSCALE, 
				QUANTITY, 
				DATEWEIGH,
				USERID,
				TYPENAMES,CODENAME,NAMEPRODUCTION,UNITS,
				STATUSPRINTER,
				CONVERTKG,
				TYPESCRAP, 
				CREATEDATE,
				SHIFTS,
				NAMEERROR

			INTO #T4
		FROM
				#T3


				SELECT

		
				LINECODE,
				NAMELINE,
				'' + replace(WEIGHSCALE, 'E', '') + '' AS WEIGHSCALE, 
				QUANTITY, 
				DATEWEIGH,
				USERID,
				TYPENAMES,CODENAME,NAMEPRODUCTION,UNITS,
				STATUSPRINTER,
				CONVERTKG,
				TYPESCRAP, 
				CREATEDATE,
				SHIFTS,
				NAMEERROR
INTO #T5
		FROM
				#T4
			

			
				SELECT

		
				LINECODE,
				NAMELINE,
				'' + replace(WEIGHSCALE, '/', '') + '' AS WEIGHSCALE, 
				QUANTITY, 
				DATEWEIGH,
				USERID,
				TYPENAMES,CODENAME,NAMEPRODUCTION,UNITS,
				STATUSPRINTER,
				CONVERTKG,
				TYPESCRAP, 
				CREATEDATE,
				SHIFTS,
				NAMEERROR
INTO #T6
		FROM
				#T5

				SELECT

		
				LINECODE,
				NAMELINE,
				'' + replace(WEIGHSCALE, '-', '') + '' AS WEIGHSCALE, 
				QUANTITY, 
				DATEWEIGH,
				USERID,
				TYPENAMES,CODENAME,NAMEPRODUCTION,UNITS,
				STATUSPRINTER,
				CONVERTKG,
				TYPESCRAP, 
				CREATEDATE,
				SHIFTS,
				NAMEERROR
INTO #T7
		FROM
				#T6


								SELECT

		
				LINECODE,
				NAMELINE,
				'' + replace(WEIGHSCALE, 'r', '') + '' AS WEIGHSCALE, 
				QUANTITY, 
				DATEWEIGH,
				USERID,
				TYPENAMES,CODENAME,NAMEPRODUCTION,UNITS,
				STATUSPRINTER,
				CONVERTKG,
				TYPESCRAP, 
				CREATEDATE,
				SHIFTS,
				NAMEERROR

		FROM #T7
	END 
ELSE IF @pWorkCenterCode = 'VVT_F2'
	BEGIN
			SELECT
	
				LINECODE,
				NAMELINE,
				'' + replace(WEIGHSCALE, 'U', '') + '' AS WEIGHSCALES, 
				QUANTITY, 
				DATEWEIGH,
				USERID,
				TYPENAMES,CODENAME,NAMEPRODUCTION,UNITS,
				CASE
					WHEN FLAG = 0 AND STATUSDELETE IS NULL THEN N'Đang chờ in tem'
					WHEN FLAG = 1 AND STATUSDELETE IS NULL THEN N'Đã được in tem'
					WHEN FLAG = 0 AND STATUSDELETE IS NOT NULL THEN N'Dữ liệu đã được xóa'
				ELSE ''
				END AS 'STATUSPRINTER',
				CONVERTKG AS CONVERTKG,
				TYPESCRAP, 
				RIGHT(CREATEDATE,8) AS CREATEDATE,
				SHIFTS,
					NAMEERROR
 INTO #TBG1

		FROM
			STB_VN_SCRAP_WEIGHSCALE_PRODUCTIONS WITH(NOLOCK)
		WHERE
				LINECODE like '%BG%' and DATEWEIGH BETWEEN @pFrom AND @pTo 


				SELECT

				LINECODE,
				NAMELINE,
				'' + replace(WEIGHSCALES, 'Ta', '') + '' AS WEIGHSCALE, 
				QUANTITY, 
				DATEWEIGH,
				USERID,
				TYPENAMES,CODENAME,NAMEPRODUCTION,UNITS,
				STATUSPRINTER,
				CONVERTKG,
				TYPESCRAP, 
				CREATEDATE,
				SHIFTS,
				NAMEERROR

				INTO #TBG2

				FROM 
						#TBG1

		SELECT

		
				LINECODE,
				NAMELINE,
				'' + replace(WEIGHSCALE, 'T', '') + '' AS WEIGHSCALE, 
				QUANTITY, 
				DATEWEIGH,
				USERID,
				TYPENAMES,CODENAME,NAMEPRODUCTION,UNITS,
				STATUSPRINTER,
				CONVERTKG,
				TYPESCRAP, 
				CREATEDATE,
				SHIFTS,
				NAMEERROR

			INTO #TBG3
		FROM
				#TBG2


SELECT

		
				LINECODE,
				NAMELINE,
				'' + replace(WEIGHSCALE, '/W', '') + '' AS WEIGHSCALE, 
				QUANTITY, 
				DATEWEIGH,
				USERID,
				TYPENAMES,CODENAME,NAMEPRODUCTION,UNITS,
				STATUSPRINTER,
				CONVERTKG,
				TYPESCRAP, 
				CREATEDATE,
				SHIFTS,
				NAMEERROR

			INTO #TBG4
		FROM
				#TBG3


				SELECT

		
				LINECODE,
				NAMELINE,
				'' + replace(WEIGHSCALE, 'E', '') + '' AS WEIGHSCALE, 
				QUANTITY, 
				DATEWEIGH,
				USERID,
				TYPENAMES,CODENAME,NAMEPRODUCTION,UNITS,
				STATUSPRINTER,
				CONVERTKG,
				TYPESCRAP, 
				CREATEDATE,
				SHIFTS,
				NAMEERROR
INTO #TBG5
		FROM
				#TBG4
			

			
				SELECT

		
				LINECODE,
				NAMELINE,
				'' + replace(WEIGHSCALE, '/', '') + '' AS WEIGHSCALE, 
				QUANTITY, 
				DATEWEIGH,
				USERID,
				TYPENAMES,CODENAME,NAMEPRODUCTION,UNITS,
				STATUSPRINTER,
				CONVERTKG,
				TYPESCRAP, 
				CREATEDATE,
				SHIFTS,
				NAMEERROR
INTO #TBG6
		FROM
				#TBG5

				SELECT

		
				LINECODE,
				NAMELINE,
				'' + replace(WEIGHSCALE, '-', '') + '' AS WEIGHSCALE, 
				QUANTITY, 
				DATEWEIGH,
				USERID,
				TYPENAMES,CODENAME,NAMEPRODUCTION,UNITS,
				STATUSPRINTER,
				CONVERTKG,
				TYPESCRAP, 
				CREATEDATE,
				SHIFTS,
				NAMEERROR
INTO #TBG7
		FROM
				#TBG6


								SELECT

		
				LINECODE,
				NAMELINE,
				'' + replace(WEIGHSCALE, 'r', '') + '' AS WEIGHSCALE, 
				QUANTITY, 
				DATEWEIGH,
				USERID,
				TYPENAMES,CODENAME,NAMEPRODUCTION,UNITS,
				STATUSPRINTER,
				CONVERTKG,
				TYPESCRAP, 
				CREATEDATE,
				SHIFTS,
				NAMEERROR

		FROM #TBG7
	END
ELSE 
	BEGIN
			SELECT
	
				LINECODE,
				NAMELINE,
				'' + replace(WEIGHSCALE, 'U', '') + '' AS WEIGHSCALES, 
				QUANTITY, 
				DATEWEIGH,
				USERID,
				TYPENAMES,CODENAME,NAMEPRODUCTION,UNITS,
				CASE
					WHEN FLAG = 0 AND STATUSDELETE IS NULL THEN N'Đang chờ in tem'
					WHEN FLAG = 1 AND STATUSDELETE IS NULL THEN N'Đã được in tem'
					WHEN FLAG = 0 AND STATUSDELETE IS NOT NULL THEN N'Dữ liệu đã được xóa'
				ELSE ''
				END AS 'STATUSPRINTER',
				CONVERTKG AS CONVERTKG,
				TYPESCRAP, 
				RIGHT(CREATEDATE,8) AS CREATEDATE,
				SHIFTS,
					NAMEERROR
 INTO #TVN1

		FROM
			STB_VN_SCRAP_WEIGHSCALE_PRODUCTIONS WITH(NOLOCK)
		WHERE
				 DATEWEIGH BETWEEN @pFrom AND @pTo 


				SELECT

				LINECODE,
				NAMELINE,
				'' + replace(WEIGHSCALES, 'Ta', '') + '' AS WEIGHSCALE, 
				QUANTITY, 
				DATEWEIGH,
				USERID,
				TYPENAMES,CODENAME,NAMEPRODUCTION,UNITS,
				STATUSPRINTER,
				CONVERTKG,
				TYPESCRAP, 
				CREATEDATE,
				SHIFTS,
				NAMEERROR

				INTO #TVN2

				FROM 
						#TVN1

		SELECT

		
				LINECODE,
				NAMELINE,
				'' + replace(WEIGHSCALE, 'T', '') + '' AS WEIGHSCALE, 
				QUANTITY, 
				DATEWEIGH,
				USERID,
				TYPENAMES,CODENAME,NAMEPRODUCTION,UNITS,
				STATUSPRINTER,
				CONVERTKG,
				TYPESCRAP, 
				CREATEDATE,
				SHIFTS,
				NAMEERROR

			INTO #TVN3
		FROM
				#TVN2


SELECT

		
				LINECODE,
				NAMELINE,
				'' + replace(WEIGHSCALE, '/W', '') + '' AS WEIGHSCALE, 
				QUANTITY, 
				DATEWEIGH,
				USERID,
				TYPENAMES,CODENAME,NAMEPRODUCTION,UNITS,
				STATUSPRINTER,
				CONVERTKG,
				TYPESCRAP, 
				CREATEDATE,
				SHIFTS,
				NAMEERROR

			INTO #TVN4
		FROM
				#TVN3


				SELECT

		
				LINECODE,
				NAMELINE,
				'' + replace(WEIGHSCALE, 'E', '') + '' AS WEIGHSCALE, 
				QUANTITY, 
				DATEWEIGH,
				USERID,
				TYPENAMES,CODENAME,NAMEPRODUCTION,UNITS,
				STATUSPRINTER,
				CONVERTKG,
				TYPESCRAP, 
				CREATEDATE,
				SHIFTS,
				NAMEERROR
INTO #TVN5
		FROM
				#TVN4
			

			
				SELECT

		
				LINECODE,
				NAMELINE,
				'' + replace(WEIGHSCALE, '/', '') + '' AS WEIGHSCALE, 
				QUANTITY, 
				DATEWEIGH,
				USERID,
				TYPENAMES,CODENAME,NAMEPRODUCTION,UNITS,
				STATUSPRINTER,
				CONVERTKG,
				TYPESCRAP, 
				CREATEDATE,
				SHIFTS,
				NAMEERROR
INTO #TVN6
		FROM
				#TVN5

				SELECT

		
				LINECODE,
				NAMELINE,
				'' + replace(WEIGHSCALE, '-', '') + '' AS WEIGHSCALE, 
				QUANTITY, 
				DATEWEIGH,
				USERID,
				TYPENAMES,CODENAME,NAMEPRODUCTION,UNITS,
				STATUSPRINTER,
				CONVERTKG,
				TYPESCRAP, 
				CREATEDATE,
				SHIFTS,
				NAMEERROR
INTO #TVN7
		FROM
				#TVN6


								SELECT

		
				LINECODE,
				NAMELINE,
				'' + replace(WEIGHSCALE, 'r', '') + '' AS WEIGHSCALE, 
				QUANTITY, 
				DATEWEIGH,
				USERID,
				TYPENAMES,CODENAME,NAMEPRODUCTION,UNITS,
				STATUSPRINTER,
				CONVERTKG,
				TYPESCRAP, 
				CREATEDATE,
				SHIFTS,
				NAMEERROR

		FROM #TVN7
	END



END


--@pFrom DATE = NULL,
--@pTo DATE = NULL
--AS
--BEGIN

--DECLARE @KG  FLOAT
--DECLARE @CONVERTKG NVARCHAR(50)
--SET @KG = 3.000


--		SELECT
	
--				LINECODE,
--				NAMELINE,
--				'' + replace(WEIGHSCALE, 'U', '') + '' AS WEIGHSCALES, 
--				DATEWEIGH,
--				USERID,
--				TYPENAMES,CODENAME,NAMEPRODUCTION,UNITS,
--				CASE
--					WHEN FLAG = 0 AND STATUSDELETE IS NULL THEN N'Đang chờ in tem'
--					WHEN FLAG = 1 AND STATUSDELETE IS NULL THEN N'Đã được in tem'
--					WHEN FLAG = 0 AND STATUSDELETE IS NOT NULL THEN N'Dữ liệu đã được xóa'
--				ELSE ''
--				END AS 'STATUSPRINTER',
--				CONVERTKG AS CONVERTKG,
--				TYPESCRAP, 
--				RIGHT(CREATEDATE,8) AS CREATEDATE,
--				SHIFTS,
--					NAMEERROR
-- INTO #T1

--		FROM
--			STB_VN_SCRAP_WEIGHSCALE_PRODUCTIONS WITH(NOLOCK)
--		WHERE
--				DATEWEIGH BETWEEN @pFrom AND @pTo


--				SELECT

--				LINECODE,
--				NAMELINE,
--				'' + replace(WEIGHSCALES, 'Ta', '') + '' AS WEIGHSCALE, 
--				DATEWEIGH,
--				USERID,
--				TYPENAMES,CODENAME,NAMEPRODUCTION,UNITS,
--				STATUSPRINTER,
--				CONVERTKG,
--				TYPESCRAP, 
--				CREATEDATE,
--				SHIFTS,
--				NAMEERROR

--				INTO #T2

--				FROM 
--						#T1

--		SELECT

		
--				LINECODE,
--				NAMELINE,
--				'' + replace(WEIGHSCALE, 'T', '') + '' AS WEIGHSCALE, 
--				DATEWEIGH,
--				USERID,
--				TYPENAMES,CODENAME,NAMEPRODUCTION,UNITS,
--				STATUSPRINTER,
--				CONVERTKG,
--				TYPESCRAP, 
--				CREATEDATE,
--				SHIFTS,
--				NAMEERROR

--			INTO #T3
--		FROM
--				#T2


--SELECT

		
--				LINECODE,
--				NAMELINE,
--				'' + replace(WEIGHSCALE, '/W', '') + '' AS WEIGHSCALE, 
--				DATEWEIGH,
--				USERID,
--				TYPENAMES,CODENAME,NAMEPRODUCTION,UNITS,
--				STATUSPRINTER,
--				CONVERTKG,
--				TYPESCRAP, 
--				CREATEDATE,
--				SHIFTS,
--				NAMEERROR

--			INTO #T4
--		FROM
--				#T3


--				SELECT

		
--				LINECODE,
--				NAMELINE,
--				'' + replace(WEIGHSCALE, 'E', '') + '' AS WEIGHSCALE, 
--				DATEWEIGH,
--				USERID,
--				TYPENAMES,CODENAME,NAMEPRODUCTION,UNITS,
--				STATUSPRINTER,
--				CONVERTKG,
--				TYPESCRAP, 
--				CREATEDATE,
--				SHIFTS,
--				NAMEERROR
--INTO #T5
--		FROM
--				#T4
			

			
--				SELECT

		
--				LINECODE,
--				NAMELINE,
--				'' + replace(WEIGHSCALE, '/', '') + '' AS WEIGHSCALE, 
--				DATEWEIGH,
--				USERID,
--				TYPENAMES,CODENAME,NAMEPRODUCTION,UNITS,
--				STATUSPRINTER,
--				CONVERTKG,
--				TYPESCRAP, 
--				CREATEDATE,
--				SHIFTS,
--				NAMEERROR
--INTO #T6
--		FROM
--				#T5

--				SELECT

		
--				LINECODE,
--				NAMELINE,
--				'' + replace(WEIGHSCALE, '-', '') + '' AS WEIGHSCALE, 
--				DATEWEIGH,
--				USERID,
--				TYPENAMES,CODENAME,NAMEPRODUCTION,UNITS,
--				STATUSPRINTER,
--				CONVERTKG,
--				TYPESCRAP, 
--				CREATEDATE,
--				SHIFTS,
--				NAMEERROR
--INTO #T7
--		FROM
--				#T6


--								SELECT

		
--				LINECODE,
--				NAMELINE,
--				'' + replace(WEIGHSCALE, 'r', '') + '' AS WEIGHSCALE, 
--				DATEWEIGH,
--				USERID,
--				TYPENAMES,CODENAME,NAMEPRODUCTION,UNITS,
--				STATUSPRINTER,
--				CONVERTKG,
--				TYPESCRAP, 
--				CREATEDATE,
--				SHIFTS,
--				NAMEERROR

--		FROM #T7
--END



--alter table select * from  STB_VN_SCRAP_WEIGHSCALE_PRODUCTIONS
--add
--	SHIFTS NVARCHAR(50) NULL

--select * from delete STB_VN_SCRAP_WEIGHSCALE_PRODUCTIONS where USERID ='92011009'