CREATE proc [dbo].[usp_VN_EmployeeName]
AS
BEGIN
		CREATE TABLE #T
		(
			ID INT IDENTITY(1,1) NOT NULL PRIMARY KEY(ID),
			NAMEEMPLOYEES NVARCHAR(50) NULL,
		)

		INSERT INTO #T (NAMEEMPLOYEES) VALUES (N'Lò Thị Hằng')
		INSERT INTO #T (NAMEEMPLOYEES) VALUES (N'Hoàng Thị Hoài')
		INSERT INTO #T (NAMEEMPLOYEES) VALUES (N'Hoàng Thị Thu Trang')
		INSERT INTO #T (NAMEEMPLOYEES) VALUES (N'Lê Thị Thủy')
		INSERT INTO #T (NAMEEMPLOYEES) VALUES (N'Nguyễn Thị Hương')
		INSERT INTO #T (NAMEEMPLOYEES) VALUES (N'Bùi Thị Thủy')
		INSERT INTO #T (NAMEEMPLOYEES) VALUES (N'Nguyễn Thị Hường')
		INSERT INTO #T (NAMEEMPLOYEES) VALUES (N'Nguyễn Thị Hằng')
		INSERT INTO #T (NAMEEMPLOYEES) VALUES (N'Nguyễn Thị Nhung')
		INSERT INTO #T (NAMEEMPLOYEES) VALUES (N'Vi Thị Thành')
		INSERT INTO #T (NAMEEMPLOYEES) VALUES (N'Nguyễn Thị Xuyến')
		INSERT INTO #T (NAMEEMPLOYEES) VALUES (N'Nguyễn Thị Hay')
		INSERT INTO #T (NAMEEMPLOYEES) VALUES (N'Ngụy Thị Biên')
		INSERT INTO #T (NAMEEMPLOYEES) VALUES (N'Triệu Thị Mính')
		INSERT INTO #T (NAMEEMPLOYEES) VALUES (N'Trần Thị Hằng')
		INSERT INTO #T (NAMEEMPLOYEES) VALUES (N'Nguyễn Thị Minh')
		INSERT INTO #T (NAMEEMPLOYEES) VALUES (N'Hoàng Thị Hà Giang')
		INSERT INTO #T (NAMEEMPLOYEES) VALUES (N'Nguyễn Thị Huyền')
		INSERT INTO #T (NAMEEMPLOYEES) VALUES (N'Sầm Thị Ánh')
		INSERT INTO #T (NAMEEMPLOYEES) VALUES (N'Nguyễn Thị Xoan')
		INSERT INTO #T (NAMEEMPLOYEES) VALUES (N'Lê Thị Nội') 
		INSERT INTO #T (NAMEEMPLOYEES) VALUES (N'Nguyễn Thị Gấm') 
		SELECT
				NAMEEMPLOYEES
		FROM
				#T
END