CREATE PROC [dbo].[VN_DryMachines]
AS
BEGIN
		CREATE TABLE #Tbdry
		(
			DryName NVARCHAR(50) NOT NULL PRIMARY KEY(DryName),
			IsUse BIT NULL
		)

		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C1 OV1',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C1 OV2',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C1 OV3',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C2 OV1',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C2 OV2',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C2 OV3',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C3 OV1',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C3 OV2',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C3 OV3',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C3 OV4',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C4 OV1',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C4 OV2',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C4 OV3',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C4 OV4',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C5 OV1',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C5 OV2',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C5 OV3',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C5 OV4',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C6 OV1',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C6 OV2',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C6 OV3',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C6 OV4',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C7 OV1',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C7 OV2',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C7 OV3',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C7 OV4',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C8 OV1',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C8 OV2',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C8 OV3',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C8 OV4',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C9 OV1',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C9 OV2',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C9 OV3',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C9 OV4',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('DR1 OV1',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('DR1 OV2',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('DR1 OV3',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('DR1 OV4',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('DR1 OV5',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('DR1 OV6',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('DR1 OV7',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('DR1 OV8',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('DR1 OV9',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('DR1 OV10',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('DR2 OV1',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('DR2 OV2',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('DR2 OV3',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C10 OV1',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C10 OV2',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C10 OV3',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C10 OV4',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C11 OV1',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C11 OV2',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C11 OV3',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C11 OV4',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C12 OV1',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C12 OV2',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C12 OV3',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C12 OV4',1)

		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C12 OV#1',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C12 OV#2',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C12 OV#3',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C13 OV#1',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C13 OV#2',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C13 OV#3',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C14 OV#1',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C14 OV#2',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C14 OV#3',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C15 OV#1',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C15 OV#2',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C15 OV#3',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C15 OV#4',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C16 OV#1',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C16 OV#2',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C16 OV#3',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C17 OV#1',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C17 OV#2',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C17 OV#3',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C17 OV#4',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C18 OV#1',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C18 OV#2',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C18 OV#3',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C18 OV#4',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C19 OV#1',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C19 OV#2',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C19 OV#3',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C19 OV#4',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C19 OV#5',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C19 OV#6',1)

		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C20 OV#1',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C20 OV#2',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C20 OV#3',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C20 OV#4',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C20 OV#5',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C20 OV#6',1)

		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C21 OV#1',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C21 OV#2',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C21 OV#3',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C21 OV#4',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C21 OV#5',1)
		INSERT INTO #Tbdry (DryName,IsUse) VALUES ('C21 OV#6',1)

		SELECT
				DryName
		FROM
				#Tbdry
		WHERE
				IsUse = 1

		ORDER BY DryName DESC

		DROP TABLE #Tbdry
END