CREATE PROC [dbo].[VN_LOCATIONMACHINES]
AS
BEGIN
		SELECT 
				--CODELOCATIONMACHINES,
				NAMELOCATION AS NAMELOCATION
				
				
	    FROM
				STB_VN_LOCATIONMACHINES WITH(NOLOCK)

		--WHERE 
		--		IsUsed = 1

	   GROUP BY 
				--CODELOCATIONMACHINES,
				NAMELOCATION
		
	
	   
	   ORDER BY NAMELOCATION ASC

END

--SELECT CODEACC, COUNT(*)
--  FROM STB_VN_CODEGOODFINISED WITH (NOLOCK)
-- GROUP BY CODEACC
-- HAVING COUNT(*) > 1

-- SELECT * FROM STB_VN_LOCATIONMACHINES

