CREATE PROC VN_TYPE_INVENTORY
AS
BEGIN
		CREATE TABLE #T
		(
			  IDTYPE INT IDENTITY(1,1) NOT NULL PRIMARY KEY(IDTYPE),
			  NamType NVARCHAR(50) NULL
			 
		)

		INSERT INTO  #T (NamType) VALUES (N'WINDING')
		INSERT INTO  #T (NamType) VALUES (N'RUBBER')
		INSERT INTO  #T (NamType) VALUES (N'BEADING')
		INSERT INTO  #T (NamType) VALUES (N'CURLING')
		INSERT INTO  #T (NamType) VALUES (N'SLEEVE')
		INSERT INTO  #T (NamType) VALUES (N'PACKING')
		INSERT INTO  #T (NamType) VALUES (N'AGING')
		INSERT INTO  #T (NamType) VALUES (N'QC')
		INSERT INTO  #T (NamType) VALUES (N'NVL ON STAGE')
		INSERT INTO  #T (NamType) VALUES (N'NG (WAITING ANALYSIS)')
		INSERT INTO  #T (NamType) VALUES (N'Hàng chuyển phế(LOT)')
		INSERT INTO  #T (NamType) VALUES (N'Return')
		INSERT INTO  #T (NamType) VALUES (N'Waiting scrapped')
		
		SELECT IDTYPE,
			   NamType
		FROM 
				#T
END