CREATE PROC [dbo].[VN_TENMAYCONGDOAN]
	@pProcessLanguage VARCHAR(20),
	@pProcessUserID VARCHAR(20)
AS
BEGIN
		SET NOCOUNT ON;

		CREATE TABLE #T1
		(
			Line NVARCHAR(100) PRIMARY KEY(Line) NOT NULL,
			CodeLine NVARCHAR(100) NULL
		)

		INSERT INTO #T1 (Line,CodeLine)

		SELECT 
			   Line,
			   Line
		FROM STB_VN_LINE WITH(NOLOCK)
			WHERE IsUsed='1'


		SELECT Line,CodeLine
		FROM #T1

		--DROP TABLE #T1
END