CREATE proc vn_upfinshed  
@LOTNO NVARCHAR(50),
@QTY NVARCHAR(50),
@COUNTRY NVARCHAR(50),
@SOPHIEUXUATKHO NVARCHAR(50),
@SOINVOICE NVARCHAR(50),
@TOKHAIHAIQUAN NVARCHAR(50),
@KIEUXUAT NVARCHAR(50),
@DATE NVARCHAR(50),
@IDCODE NVARCHAR(50)
as
begin
		UPDATE STB_VN_FINISHGOODS
		SET
			SoPhieuXuatKho = @SOPHIEUXUATKHO,
			SoInVoice = @SOINVOICE,
			SoToKhaiHaiQuan = @TOKHAIHAIQUAN,
			Country = @COUNTRY,
			DateExport = @DATE
			
			WHERE IDCODE = @IDCODE AND LotNo = @LOTNO AND PackQty = @QTY

end
