-- Procedure: Automatic_UpdateTimesupport
--SELECT * FROM STB_VN_EMPLOYEESTRANSFER

CREATE PROC Automatic_UpdateTimesupport --exec Automatic_UpdateTimesupport
AS
BEGIN
		DECLARE @CNT INT
		DECLARE @END_DATES NVARCHAR(50)
		DECLARE @END_TIME NVARCHAR(50)
		DECLARE @CHANGEBY NVARCHAR(50)

		DECLARE Cusproduction CURSOR FOR
		
		SELECT 
				END_DATES,
				END_TIME,
				CHANGEBY
		
		FROM 
				STB_VN_EMPLOYEESTRANSFER WITH(NOLOCK)

		WHERE
				END_DATES IS NULL  


		OPEN Cusproduction

		FETCH NEXT FROM Cusproduction

		INTO @END_DATES,@END_TIME,@CHANGEBY

		WHILE @@FETCH_STATUS = 0

		BEGIN
		
			SELECT @CNT = COUNT(*) FROM STB_VN_EMPLOYEESTRANSFER WHERE  END_DATES IS NULL 

						IF @CNT > 0

							BEGIN

								UPDATE STB_VN_EMPLOYEESTRANSFER
								SET 
									END_DATES =  DATEADD(dd, -2, DATEDIFF(dd, -2, GETDATE())), END_TIME =   DATEADD(HH, -2, GETDATE()),
									CHANGEBY = 'System', DATECHAGE = DATEADD(HH, -2, GETDATE()),
									TOTALHOUR ='0.00',
									TOTALMINUTES = '0.00'
								
								WHERE
										END_DATES IS NULL
							END
					FETCH NEXT FROM Cusproduction
					INTO  @END_DATES,@END_TIME,@CHANGEBY		
		
		END
		CLOSE Cusproduction              
		DEALLOCATE Cusproduction   

END

--SELECT * FROM STB_VN_EMPLOYEESTRANSFER
GO

