-- Procedure: ups_employeestransferline

CREATE PROC ups_employeestransferline
	@EMPLOYEESID NVARCHAR(50),
	@EMPLOYEESNAME NVARCHAR(50),
	@DEPARTMENTNAME NVARCHAR(50),
	@CODEDEPARTMENT NVARCHAR(50),
	@CODELINE NVARCHAR(50),
	@NAMELINE NVARCHAR(50),
	@CODELINEMOVE NVARCHAR(50),
	@NAMELINEMOVE NVARCHAR(50),
	@POSISTION NVARCHAR(50),
	@EFFECTIVEDATE NVARCHAR(50),
	@SHIFTCONTRACT NVARCHAR(50),
	@CREATEDATETIME NVARCHAR(50),
	@CREATEUSERID NVARCHAR(50)
AS
BEGIN
INSERT INTO STB_VN_EMPLOYEESTRANSFERLINE
(
	EMPLOYEESID,
	EMPLOYEESNAME,
	DEPARTMENTNAME,
	CODEDEPARTMENT,
	CODELINE,
	NAMELINE,
	CODELINEMOVE,
	NAMELINEMOVE,
	POSISTION,
	EFFECTIVEDATE,
	SHIFTCONTRACT,
	CREATEDATETIME,
	CREATEUSERID
)
VALUES
(
	@EMPLOYEESID,
	@EMPLOYEESNAME,
	@DEPARTMENTNAME,
	@CODEDEPARTMENT,
	@CODELINE,
	@NAMELINE,
	@CODELINEMOVE,
	@NAMELINEMOVE,
	@POSISTION,
	@EFFECTIVEDATE,
	@SHIFTCONTRACT,
	@CREATEDATETIME,
	@CREATEUSERID
)
END
GO

