-- Procedure: usp_Add_Loading_LOCATIONMACHINES
CREATE PROC usp_Add_Loading_LOCATIONMACHINES
AS
BEGIN
		SELECT 
				CODELOCATIONMACHINES,
				NAMELOCATION
				
	    FROM
				STB_VN_LOCATIONMACHINES WITH(NOLOCK)

		WHERE 
				IsUsed = 1
END
GO

