-- Procedure: usp_Appro_VN_Security
CREATE PROC usp_Appro_VN_Security
@CODE NVARCHAR(50),
@SUSERID NVARCHAR(50),
@GRID NVARCHAR(50)
AS
BEGIN
		IF @CODE = 'VVT_F1'
			
			BEGIN
					UPDATE STB_VN_STAGES_TRANSFER

					SET	
							SECURITYSTATUS_BN = 'TRUE',
							SECURITYAPPERVOER_BN = @SUSERID,
							SECURITYAPPROVERDATE_BN = GETDATE()

					WHERE
							GROUPID = @GRID AND SECURITYAPPERVOER_BN = @SUSERID
			END

		ELSE

			BEGIN
							UPDATE STB_VN_STAGES_TRANSFER

							SET
									SECURITYSTATUS_BG = 'True',
									SECURITYAPPERVOER_BG = @SUSERID,
									SECURITYAPPROVERDATE_BG = GETDATE()
			END
END

--SELECT * FROM STB_VN_STAGES_TRANSFER
GO

