-- ============================================================================
-- Neo cho function parse ngày từ Vendor Lot (F330 / F721 / B597).
--
-- Body thường KHÔNG lưu trong Git (quá dài, thay đổi theo DB). Luồng làm việc:
--   1) SSMS → SmartFactoryV2
--   2) SELECT OBJECT_DEFINITION(OBJECT_ID('dbo.fn_VVT_getdatebyVendorLot')) AS FnBody;
--   3) Lưu kết quả vào file riêng hoặc paste vào đây nếu cần review offline.
--
-- File test regression: test_GBSN00_002.sql
-- Tài liệu: MES_MASTER_KNOWLEDGE_BASE\KB_02_KHO_WMS.md (mục F330 đặc tính 10),
--           MES_MASTER_KNOWLEDGE_BASE\Vinatech_MES_Complete_DataFlow.md
-- ============================================================================
