-- ============================================================
-- VINATECH MES SAMPLE FACTORY DATA (FOR EDUCATIONAL TOUR)
-- Model: GCMDPT-621
-- Generated: 2026-05-05 21:14:02
-- ============================================================

USE [SmartFactoryV2];
GO

-- 1. MATERIAL MASTER
INSERT INTO [dbo].[STB_MaterialMaster] ([MaterialCode], [MaterialName], [MaterialNameL], [AltMaterialCode], [MaterialTypeCode], [ProductGroupCode], [MaterialUnit], [BasicGrQty], [MaterialSpec], [MaterialSpecL], [MaterialSource], [MaterialThickness], [AvgGrDay], [IsDelegate], [IsInternalProd], [IsProdPlan], [IsPurchase], [IsOrder], [IsUseFlush], [IsUseBackFlush], [IsClosed], [IsRequireOqc], [BeforeMaterialCode], [RequestGrDay], [BasicCostPrice], [BasicPackingQty], [DelegateMaterialCode], [MaterialPurchaseType], [MaxProdPlanQty], [BasicRoutingCode], [MMExtText01], [MMExtText02], [MMExtText03], [MMExtText04], [MMExtText05], [MMExtText06], [MMExtText07], [MMExtText08], [MMExtText09], [MMExtText10], [MMExtInt01], [MMExtInt02], [MMExtInt03], [MMExtInt04], [MMExtInt05], [MMExtReal01], [MMExtReal02], [MMExtReal03], [MMExtReal04], [MMExtReal05], [MMExtLongText01], [MMExtLongText02], [MMExtLongText03], [MMExtLongText04], [MMExtLongText05], [MMExtImage01], [MMExtImage02], [MMExtImage03], [MMExtImage04], [MMExtImage05], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID], [MMExtBit01], [VNcode], [BasicCostPriceVVT], [PlusMinus], [MaterialWidth], [DangerMaterialYn], [DangerClassification], [DangerClassificationDetail], [Purpose], [Appearance], [StorageMethod], [ChemicalName], [CasNo], [Concentration], [DesignQty], [BefModelCode]) VALUES (N'GCMDPT-621', N'Sleeve_VEL10403R8257G_1040 VPC_High CAP', NULL, NULL, N'ROH', N'SLEEVE', N'M', NULL, N'Sleeve_VEL10403R8257G_1040 VPC_High CAP', N'Sleeve_VEL10403R8257G_1040 VPC_High CAP', NULL, NULL, NULL, NULL, NULL, 1, 0, 0, NULL, NULL, 0, NULL, N'', NULL, NULL, NULL, NULL, NULL, NULL, N'MainRouting', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, 5, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, '2026-05-05 18:14:51', NULL, '2026-05-05 19:00:01', NULL, NULL, NULL, NULL, NULL, NULL, N'N', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL);

-- 2. ROUTING
INSERT INTO [dbo].[STB_BasicRoutingInfo] ([BasicRoutingCode], [CompanyCode], [WorkCenterCode], [BasicRoutingName], [BasicRoutingDesc], [IsUsed], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID]) VALUES (N'MainRouting', N'VNT', N'VNT_F1', N'제품 기본 라우팅', NULL, 1, '2018-07-30 18:13:53', N'khjeon', '2018-08-21 17:21:27', N'khjeon');
INSERT INTO [dbo].[STB_BasicRoutingDetail] ([BasicRoutingDetailNo], [BasicRoutingCode], [RouteCode], [RouteIndex], [IsInputRoute], [IsOutputRoute], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID], [CompanyCode], [WorkCenterCode]) VALUES (N'2019030700009', N'MainRouting', N'E-22', 1, 1, 0, '2019-03-07 10:19:55', N'yjyu', '2019-10-04 14:39:52', N'yjyu', N'VNT', N'VNT_F1');
INSERT INTO [dbo].[STB_BasicRoutingDetail] ([BasicRoutingDetailNo], [BasicRoutingCode], [RouteCode], [RouteIndex], [IsInputRoute], [IsOutputRoute], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID], [CompanyCode], [WorkCenterCode]) VALUES (N'2019030700010', N'MainRouting', N'E-24', 2, 0, 0, '2019-03-07 10:19:55', N'yjyu', NULL, NULL, N'VNT', N'VNT_F1');
INSERT INTO [dbo].[STB_BasicRoutingDetail] ([BasicRoutingDetailNo], [BasicRoutingCode], [RouteCode], [RouteIndex], [IsInputRoute], [IsOutputRoute], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID], [CompanyCode], [WorkCenterCode]) VALUES (N'2019030700011', N'MainRouting', N'E-25', 3, 0, 0, '2019-03-07 10:19:55', N'yjyu', NULL, NULL, N'VNT', N'VNT_F1');
INSERT INTO [dbo].[STB_BasicRoutingDetail] ([BasicRoutingDetailNo], [BasicRoutingCode], [RouteCode], [RouteIndex], [IsInputRoute], [IsOutputRoute], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID], [CompanyCode], [WorkCenterCode]) VALUES (N'2019030700012', N'MainRouting', N'E-26', 4, 0, 0, '2019-03-07 10:19:55', N'yjyu', NULL, NULL, N'VNT', N'VNT_F1');
INSERT INTO [dbo].[STB_BasicRoutingDetail] ([BasicRoutingDetailNo], [BasicRoutingCode], [RouteCode], [RouteIndex], [IsInputRoute], [IsOutputRoute], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID], [CompanyCode], [WorkCenterCode]) VALUES (N'2019030700013', N'MainRouting', N'E-27', 5, 0, 0, '2019-03-07 10:19:55', N'yjyu', NULL, NULL, N'VNT', N'VNT_F1');
INSERT INTO [dbo].[STB_BasicRoutingDetail] ([BasicRoutingDetailNo], [BasicRoutingCode], [RouteCode], [RouteIndex], [IsInputRoute], [IsOutputRoute], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID], [CompanyCode], [WorkCenterCode]) VALUES (N'2019030700014', N'MainRouting', N'E-28', 6, 0, 1, '2019-03-07 10:19:55', N'yjyu', NULL, NULL, N'VNT', N'VNT_F1');
INSERT INTO [dbo].[STB_BasicRoutingDetail] ([BasicRoutingDetailNo], [BasicRoutingCode], [RouteCode], [RouteIndex], [IsInputRoute], [IsOutputRoute], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID], [CompanyCode], [WorkCenterCode]) VALUES (N'2019092700001', N'MainRouting', N'V-22', 1, 1, 0, '2019-09-27 16:54:13', N'yjyu', NULL, NULL, N'VVT', N'VVT_F1');
INSERT INTO [dbo].[STB_BasicRoutingDetail] ([BasicRoutingDetailNo], [BasicRoutingCode], [RouteCode], [RouteIndex], [IsInputRoute], [IsOutputRoute], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID], [CompanyCode], [WorkCenterCode]) VALUES (N'2019092700002', N'MainRouting', N'V-24', 2, 0, 0, '2019-09-27 16:54:13', N'yjyu', NULL, NULL, N'VVT', N'VVT_F1');
INSERT INTO [dbo].[STB_BasicRoutingDetail] ([BasicRoutingDetailNo], [BasicRoutingCode], [RouteCode], [RouteIndex], [IsInputRoute], [IsOutputRoute], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID], [CompanyCode], [WorkCenterCode]) VALUES (N'2019092700003', N'MainRouting', N'V-25', 3, 0, 0, '2019-09-27 16:54:13', N'yjyu', NULL, NULL, N'VVT', N'VVT_F1');
INSERT INTO [dbo].[STB_BasicRoutingDetail] ([BasicRoutingDetailNo], [BasicRoutingCode], [RouteCode], [RouteIndex], [IsInputRoute], [IsOutputRoute], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID], [CompanyCode], [WorkCenterCode]) VALUES (N'2019092700004', N'MainRouting', N'V-27', 4, 0, 0, '2019-09-27 16:54:13', N'yjyu', NULL, NULL, N'VVT', N'VVT_F1');
INSERT INTO [dbo].[STB_BasicRoutingDetail] ([BasicRoutingDetailNo], [BasicRoutingCode], [RouteCode], [RouteIndex], [IsInputRoute], [IsOutputRoute], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID], [CompanyCode], [WorkCenterCode]) VALUES (N'2019092700005', N'MainRouting', N'V-28', 5, 0, 1, '2019-09-27 16:54:13', N'yjyu', NULL, NULL, N'VVT', N'VVT_F1');
INSERT INTO [dbo].[STB_BasicRoutingDetail] ([BasicRoutingDetailNo], [BasicRoutingCode], [RouteCode], [RouteIndex], [IsInputRoute], [IsOutputRoute], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID], [CompanyCode], [WorkCenterCode]) VALUES (N'2024011100004', N'MainRouting', N'V-22_BG', 1, 1, 0, '2024-01-11 11:10:17', N'nguyennha', NULL, NULL, N'VVT', N'VVT_F2');
INSERT INTO [dbo].[STB_BasicRoutingDetail] ([BasicRoutingDetailNo], [BasicRoutingCode], [RouteCode], [RouteIndex], [IsInputRoute], [IsOutputRoute], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID], [CompanyCode], [WorkCenterCode]) VALUES (N'2024011100005', N'MainRouting', N'V-24_BG', 2, 0, 0, '2024-01-11 11:10:17', N'nguyennha', NULL, NULL, N'VVT', N'VVT_F2');
INSERT INTO [dbo].[STB_BasicRoutingDetail] ([BasicRoutingDetailNo], [BasicRoutingCode], [RouteCode], [RouteIndex], [IsInputRoute], [IsOutputRoute], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID], [CompanyCode], [WorkCenterCode]) VALUES (N'2024011100006', N'MainRouting', N'V-25_BG', 3, 0, 0, '2024-01-11 11:10:17', N'nguyennha', NULL, NULL, N'VVT', N'VVT_F2');
INSERT INTO [dbo].[STB_BasicRoutingDetail] ([BasicRoutingDetailNo], [BasicRoutingCode], [RouteCode], [RouteIndex], [IsInputRoute], [IsOutputRoute], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID], [CompanyCode], [WorkCenterCode]) VALUES (N'2024011100007', N'MainRouting', N'V-27_BG', 4, 0, 0, '2024-01-11 11:10:17', N'nguyennha', NULL, NULL, N'VVT', N'VVT_F2');
INSERT INTO [dbo].[STB_BasicRoutingDetail] ([BasicRoutingDetailNo], [BasicRoutingCode], [RouteCode], [RouteIndex], [IsInputRoute], [IsOutputRoute], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID], [CompanyCode], [WorkCenterCode]) VALUES (N'2024011100008', N'MainRouting', N'V-28_BG', 5, 0, 1, '2024-01-11 11:10:17', N'nguyennha', NULL, NULL, N'VVT', N'VVT_F2');
INSERT INTO [dbo].[STB_BasicRoutingDetail] ([BasicRoutingDetailNo], [BasicRoutingCode], [RouteCode], [RouteIndex], [IsInputRoute], [IsOutputRoute], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID], [CompanyCode], [WorkCenterCode]) VALUES (N'2024102900001', N'MainRouting', N'VE01', 1, 0, 0, '2024-10-29 14:50:56', N'anhduy157', '2024-11-23 12:23:04', N'nguyennha', N'VVT', N'VVT_F3');
INSERT INTO [dbo].[STB_BasicRoutingDetail] ([BasicRoutingDetailNo], [BasicRoutingCode], [RouteCode], [RouteIndex], [IsInputRoute], [IsOutputRoute], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID], [CompanyCode], [WorkCenterCode]) VALUES (N'2024102900002', N'MainRouting', N'VE02', 2, 1, 0, '2024-10-29 14:50:56', N'anhduy157', '2024-11-23 12:23:04', N'nguyennha', N'VVT', N'VVT_F3');
INSERT INTO [dbo].[STB_BasicRoutingDetail] ([BasicRoutingDetailNo], [BasicRoutingCode], [RouteCode], [RouteIndex], [IsInputRoute], [IsOutputRoute], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID], [CompanyCode], [WorkCenterCode]) VALUES (N'2024102900003', N'MainRouting', N'VE03', 3, 0, 0, '2024-10-29 16:50:56', N'anhduy157', NULL, NULL, N'VVT', N'VVT_F3');
INSERT INTO [dbo].[STB_BasicRoutingDetail] ([BasicRoutingDetailNo], [BasicRoutingCode], [RouteCode], [RouteIndex], [IsInputRoute], [IsOutputRoute], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID], [CompanyCode], [WorkCenterCode]) VALUES (N'2024102900004', N'MainRouting', N'VE04', 4, 0, 0, '2024-10-29 16:50:56', N'anhduy157', NULL, NULL, N'VVT', N'VVT_F3');
INSERT INTO [dbo].[STB_BasicRoutingDetail] ([BasicRoutingDetailNo], [BasicRoutingCode], [RouteCode], [RouteIndex], [IsInputRoute], [IsOutputRoute], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID], [CompanyCode], [WorkCenterCode]) VALUES (N'2024102900005', N'MainRouting', N'VE05', 5, 0, 0, '2024-10-29 16:50:56', N'anhduy157', NULL, NULL, N'VVT', N'VVT_F3');
INSERT INTO [dbo].[STB_BasicRoutingDetail] ([BasicRoutingDetailNo], [BasicRoutingCode], [RouteCode], [RouteIndex], [IsInputRoute], [IsOutputRoute], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID], [CompanyCode], [WorkCenterCode]) VALUES (N'2024102900006', N'MainRouting', N'VE06', 6, 0, 0, '2024-10-29 16:50:56', N'anhduy157', NULL, NULL, N'VVT', N'VVT_F3');
INSERT INTO [dbo].[STB_BasicRoutingDetail] ([BasicRoutingDetailNo], [BasicRoutingCode], [RouteCode], [RouteIndex], [IsInputRoute], [IsOutputRoute], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID], [CompanyCode], [WorkCenterCode]) VALUES (N'2024102900007', N'MainRouting', N'VE07', 7, 0, 0, '2024-10-29 16:50:56', N'anhduy157', NULL, NULL, N'VVT', N'VVT_F3');
INSERT INTO [dbo].[STB_BasicRoutingDetail] ([BasicRoutingDetailNo], [BasicRoutingCode], [RouteCode], [RouteIndex], [IsInputRoute], [IsOutputRoute], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID], [CompanyCode], [WorkCenterCode]) VALUES (N'2024102900008', N'MainRouting', N'VE08', 8, 0, 0, '2024-10-29 16:50:56', N'anhduy157', NULL, NULL, N'VVT', N'VVT_F3');
INSERT INTO [dbo].[STB_BasicRoutingDetail] ([BasicRoutingDetailNo], [BasicRoutingCode], [RouteCode], [RouteIndex], [IsInputRoute], [IsOutputRoute], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID], [CompanyCode], [WorkCenterCode]) VALUES (N'2024102900009', N'MainRouting', N'VE09', 9, 0, 0, '2024-10-29 16:50:56', N'anhduy157', NULL, NULL, N'VVT', N'VVT_F3');
INSERT INTO [dbo].[STB_BasicRoutingDetail] ([BasicRoutingDetailNo], [BasicRoutingCode], [RouteCode], [RouteIndex], [IsInputRoute], [IsOutputRoute], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID], [CompanyCode], [WorkCenterCode]) VALUES (N'2024102900010', N'MainRouting', N'VE10', 10, 0, 0, '2024-10-29 16:50:56', N'anhduy157', NULL, NULL, N'VVT', N'VVT_F3');
INSERT INTO [dbo].[STB_BasicRoutingDetail] ([BasicRoutingDetailNo], [BasicRoutingCode], [RouteCode], [RouteIndex], [IsInputRoute], [IsOutputRoute], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID], [CompanyCode], [WorkCenterCode]) VALUES (N'2026022000001', N'MainRouting', N'VP03', 1, 1, 0, '2026-02-20 16:55:07', N'DinhManh', NULL, NULL, N'VVT', N'VVT_F4');
INSERT INTO [dbo].[STB_BasicRoutingDetail] ([BasicRoutingDetailNo], [BasicRoutingCode], [RouteCode], [RouteIndex], [IsInputRoute], [IsOutputRoute], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID], [CompanyCode], [WorkCenterCode]) VALUES (N'2026022000002', N'MainRouting', N'VP04', 2, 0, 0, '2026-02-20 16:55:07', N'DinhManh', NULL, NULL, N'VVT', N'VVT_F4');
INSERT INTO [dbo].[STB_BasicRoutingDetail] ([BasicRoutingDetailNo], [BasicRoutingCode], [RouteCode], [RouteIndex], [IsInputRoute], [IsOutputRoute], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID], [CompanyCode], [WorkCenterCode]) VALUES (N'2026022000003', N'MainRouting', N'VP05', 3, 0, 0, '2026-02-20 16:55:07', N'DinhManh', NULL, NULL, N'VVT', N'VVT_F4');
INSERT INTO [dbo].[STB_BasicRoutingDetail] ([BasicRoutingDetailNo], [BasicRoutingCode], [RouteCode], [RouteIndex], [IsInputRoute], [IsOutputRoute], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID], [CompanyCode], [WorkCenterCode]) VALUES (N'2026022000004', N'MainRouting', N'VP06', 4, 0, 0, '2026-02-20 16:55:07', N'DinhManh', NULL, NULL, N'VVT', N'VVT_F4');
INSERT INTO [dbo].[STB_BasicRoutingDetail] ([BasicRoutingDetailNo], [BasicRoutingCode], [RouteCode], [RouteIndex], [IsInputRoute], [IsOutputRoute], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID], [CompanyCode], [WorkCenterCode]) VALUES (N'2026022000005', N'MainRouting', N'VP07', 5, 0, 0, '2026-02-20 16:55:07', N'DinhManh', NULL, NULL, N'VVT', N'VVT_F4');
INSERT INTO [dbo].[STB_BasicRoutingDetail] ([BasicRoutingDetailNo], [BasicRoutingCode], [RouteCode], [RouteIndex], [IsInputRoute], [IsOutputRoute], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID], [CompanyCode], [WorkCenterCode]) VALUES (N'2026022000006', N'MainRouting', N'VP08', 6, 0, 0, '2026-02-20 16:55:07', N'DinhManh', NULL, NULL, N'VVT', N'VVT_F4');
INSERT INTO [dbo].[STB_BasicRoutingDetail] ([BasicRoutingDetailNo], [BasicRoutingCode], [RouteCode], [RouteIndex], [IsInputRoute], [IsOutputRoute], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID], [CompanyCode], [WorkCenterCode]) VALUES (N'2026022000007', N'MainRouting', N'VP09', 7, 0, 0, '2026-02-20 16:55:07', N'DinhManh', NULL, NULL, N'VVT', N'VVT_F4');
INSERT INTO [dbo].[STB_BasicRoutingDetail] ([BasicRoutingDetailNo], [BasicRoutingCode], [RouteCode], [RouteIndex], [IsInputRoute], [IsOutputRoute], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID], [CompanyCode], [WorkCenterCode]) VALUES (N'2026022000008', N'MainRouting', N'VP10', 8, 0, 1, '2026-02-20 14:55:07', N'DinhManh', '2026-02-20 16:56:44', N'DinhManh', N'VVT', N'VVT_F4');

-- 3. BOM
-- No data for STB_BomHeader

-- No data for STB_BomDetail


-- 4. LINES & PROCESSES
INSERT INTO [dbo].[STB_LineInfo] ([LineCode], [CompanyCode], [WorkCenterCode], [LineName], [LineDesc], [LineType], [ErpCode], [MonitoringGroup], [MonitoringName], [IsUsed], [TotalLossTime], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID], [IsCheckScheduleMonitoring], [MaterialWarehouseCode], [ChildLines], [checkFuelCellWorkCenter]) VALUES (N'ACN', N'VVT', N'VVT_F1', N'Aging co nho', N'Aging co nho', NULL, NULL, NULL, NULL, 1, NULL, '2022-01-21 16:25:34', N'nguyennha', NULL, NULL, 1, NULL, NULL, NULL);
INSERT INTO [dbo].[STB_LineInfo] ([LineCode], [CompanyCode], [WorkCenterCode], [LineName], [LineDesc], [LineType], [ErpCode], [MonitoringGroup], [MonitoringName], [IsUsed], [TotalLossTime], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID], [IsCheckScheduleMonitoring], [MaterialWarehouseCode], [ChildLines], [checkFuelCellWorkCenter]) VALUES (N'ACT', N'VVT', N'VVT_F1', N'Aging co trung', N'Aging co trung', NULL, NULL, NULL, NULL, 1, NULL, '2022-01-21 16:25:34', N'nguyennha', NULL, NULL, 1, NULL, NULL, NULL);
INSERT INTO [dbo].[STB_LineInfo] ([LineCode], [CompanyCode], [WorkCenterCode], [LineName], [LineDesc], [LineType], [ErpCode], [MonitoringGroup], [MonitoringName], [IsUsed], [TotalLossTime], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID], [IsCheckScheduleMonitoring], [MaterialWarehouseCode], [ChildLines], [checkFuelCellWorkCenter]) VALUES (N'ASSYLINE-01', N'VNT', N'VNT_F1', N'셀 1라인', N'셀 1라인', N'Auto', NULL, NULL, N'셀 #1', 1, NULL, '2019-03-07 08:52:24', N'yjyu', '2024-04-24 14:43:09', N'mhkim', 1, NULL, NULL, NULL);
INSERT INTO [dbo].[STB_LineInfo] ([LineCode], [CompanyCode], [WorkCenterCode], [LineName], [LineDesc], [LineType], [ErpCode], [MonitoringGroup], [MonitoringName], [IsUsed], [TotalLossTime], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID], [IsCheckScheduleMonitoring], [MaterialWarehouseCode], [ChildLines], [checkFuelCellWorkCenter]) VALUES (N'AssyLine-01D', N'VNT', N'VNT_F4', N'도약 1라인(1625)', N'도약 (1625)', N'Auto', NULL, NULL, N'도약 1라인(1625)', 1, NULL, '2024-09-03 17:27:18', N'mhkim', '2024-12-09 08:39:37', N'hjjo', 1, NULL, NULL, NULL);
INSERT INTO [dbo].[STB_LineInfo] ([LineCode], [CompanyCode], [WorkCenterCode], [LineName], [LineDesc], [LineType], [ErpCode], [MonitoringGroup], [MonitoringName], [IsUsed], [TotalLossTime], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID], [IsCheckScheduleMonitoring], [MaterialWarehouseCode], [ChildLines], [checkFuelCellWorkCenter]) VALUES (N'ASSYLINE-02', N'VNT', N'VNT_F1', N'셀 2라인', N'셀 2라인', N'Auto', NULL, NULL, N'셀 #2', 1, NULL, '2019-03-07 08:52:24', N'yjyu', '2024-04-24 16:57:14', N'mhkim', 1, NULL, NULL, NULL);
INSERT INTO [dbo].[STB_LineInfo] ([LineCode], [CompanyCode], [WorkCenterCode], [LineName], [LineDesc], [LineType], [ErpCode], [MonitoringGroup], [MonitoringName], [IsUsed], [TotalLossTime], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID], [IsCheckScheduleMonitoring], [MaterialWarehouseCode], [ChildLines], [checkFuelCellWorkCenter]) VALUES (N'ASSYLINE-09', N'VNT', N'VNT_F1', N'셀 6라인', N'셀 6라인', N'Auto', NULL, N'Y', N'셀 #6', 1, NULL, '2019-03-07 08:52:24', N'yjyu', '2024-06-18 12:54:28', N'yjyu', 1, NULL, NULL, NULL);
INSERT INTO [dbo].[STB_LineInfo] ([LineCode], [CompanyCode], [WorkCenterCode], [LineName], [LineDesc], [LineType], [ErpCode], [MonitoringGroup], [MonitoringName], [IsUsed], [TotalLossTime], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID], [IsCheckScheduleMonitoring], [MaterialWarehouseCode], [ChildLines], [checkFuelCellWorkCenter]) VALUES (N'ASSYLINE-VPC', N'VNT', N'VNT_F1', N'VPC수동조립라인', N'VPC수동조립라인', N'Manual', NULL, NULL, NULL, 1, NULL, '2020-05-27 09:43:27', N'yjyu', '2023-01-30 14:58:32', N'hjjo', 1, NULL, NULL, NULL);
INSERT INTO [dbo].[STB_LineInfo] ([LineCode], [CompanyCode], [WorkCenterCode], [LineName], [LineDesc], [LineType], [ErpCode], [MonitoringGroup], [MonitoringName], [IsUsed], [TotalLossTime], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID], [IsCheckScheduleMonitoring], [MaterialWarehouseCode], [ChildLines], [checkFuelCellWorkCenter]) VALUES (N'BCT', N'VVT', N'VVT_F1', N'Bending,Cutting,Taping', N'Bending,Cutting,Taping', NULL, NULL, NULL, NULL, 1, NULL, '2022-01-21 16:25:34', N'nguyennha', NULL, NULL, 1, NULL, NULL, NULL);
INSERT INTO [dbo].[STB_LineInfo] ([LineCode], [CompanyCode], [WorkCenterCode], [LineName], [LineDesc], [LineType], [ErpCode], [MonitoringGroup], [MonitoringName], [IsUsed], [TotalLossTime], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID], [IsCheckScheduleMonitoring], [MaterialWarehouseCode], [ChildLines], [checkFuelCellWorkCenter]) VALUES (N'BG', N'VVT', N'VVT_F1', N'Bắc Giang', N'Xuất NVL sang Bắc Giang', NULL, NULL, NULL, NULL, 1, NULL, '2023-11-21 15:45:32', N'nguyennha', '2025-01-10 17:56:09', N'anhduy157', 1, N'ROH_BG_WH', NULL, NULL);
INSERT INTO [dbo].[STB_LineInfo] ([LineCode], [CompanyCode], [WorkCenterCode], [LineName], [LineDesc], [LineType], [ErpCode], [MonitoringGroup], [MonitoringName], [IsUsed], [TotalLossTime], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID], [IsCheckScheduleMonitoring], [MaterialWarehouseCode], [ChildLines], [checkFuelCellWorkCenter]) VALUES (N'BG-SLITTING03', N'VVT', N'VVT_F2', N'Máy cắt điện cực #3', N'Máy cắt điện cực #3', NULL, NULL, NULL, NULL, 1, NULL, '2025-05-26 16:17:20', N'DinhManh', '2025-05-26 16:46:33', N'DinhManh', 1, N'ROUTE_BG_WH', NULL, NULL);
INSERT INTO [dbo].[STB_MaterialType] ([MaterialTypeCode], [BasicMaterialType], [MaterialTypeName], [MaterialTypeNameL], [IsUsed], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID]) VALUES (N'CHIP_HN', N'CHIP_HN', N'Hàng Chip của Hà Nam', N'Chips from Ha Nam', 0, '2025-01-03 12:05:24', N'anhduy157', NULL, NULL);
INSERT INTO [dbo].[STB_MaterialType] ([MaterialTypeCode], [BasicMaterialType], [MaterialTypeName], [MaterialTypeNameL], [IsUsed], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID]) VALUES (N'EROH', N'EROH', N'전극원자재', NULL, 1, '2019-01-14 15:46:27', N'yjyu', NULL, NULL);
INSERT INTO [dbo].[STB_MaterialType] ([MaterialTypeCode], [BasicMaterialType], [MaterialTypeName], [MaterialTypeNameL], [IsUsed], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID]) VALUES (N'FERT', N'FERT', N'제품', NULL, 1, '2018-07-24 14:38:27', N'jspark', NULL, NULL);
INSERT INTO [dbo].[STB_MaterialType] ([MaterialTypeCode], [BasicMaterialType], [MaterialTypeName], [MaterialTypeNameL], [IsUsed], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID]) VALUES (N'HALB', N'HALB', N'반제품', NULL, 1, '2018-07-26 14:49:24', N'jspark', NULL, NULL);
INSERT INTO [dbo].[STB_MaterialType] ([MaterialTypeCode], [BasicMaterialType], [MaterialTypeName], [MaterialTypeNameL], [IsUsed], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID]) VALUES (N'HAWA', N'HAWA', N'상품', NULL, 1, '2018-07-24 14:38:27', N'jspark', NULL, NULL);
INSERT INTO [dbo].[STB_MaterialType] ([MaterialTypeCode], [BasicMaterialType], [MaterialTypeName], [MaterialTypeNameL], [IsUsed], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID]) VALUES (N'HIBE', N'HIBE', N'소모자재', NULL, 1, '2018-07-26 14:50:55', N'jspark', NULL, NULL);
INSERT INTO [dbo].[STB_MaterialType] ([MaterialTypeCode], [BasicMaterialType], [MaterialTypeName], [MaterialTypeNameL], [IsUsed], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID]) VALUES (N'MDL', N'MODULE', N'모듈', NULL, 1, '2018-09-19 18:36:26', N'yjyu', NULL, NULL);
INSERT INTO [dbo].[STB_MaterialType] ([MaterialTypeCode], [BasicMaterialType], [MaterialTypeName], [MaterialTypeNameL], [IsUsed], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID]) VALUES (N'NORMAL_HN', N'NORMAL_HN', N'Hàng NORMAL của Hà Nam', N'NORMAL from Ha Nam', 0, '2025-01-03 12:06:40', N'anhduy157', NULL, NULL);
INSERT INTO [dbo].[STB_MaterialType] ([MaterialTypeCode], [BasicMaterialType], [MaterialTypeName], [MaterialTypeNameL], [IsUsed], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID]) VALUES (N'ROH', N'ROH', N'원자재', NULL, 1, '2018-07-26 14:49:24', N'jspark', NULL, NULL);
INSERT INTO [dbo].[STB_MaterialType] ([MaterialTypeCode], [BasicMaterialType], [MaterialTypeName], [MaterialTypeNameL], [IsUsed], [CreateDateTime], [CreateUserID], [ChangeDateTime], [ChangeUserID]) VALUES (N'SUB', N'SUB', N'부자재', N'Subsidiary Materials', 1, '2025-09-29 17:43:07', N'yjyu', NULL, NULL);

GO
