BEGIN TRANSACTION;
BEGIN TRY

    UPDATE PRH
    SET PRH.ProdQty = 1179.00041
    FROM dbo.STB_ProdRouteHist PRH WITH (UPDLOCK)
    INNER JOIN dbo.STB_SetInfo SI WITH (NOLOCK) ON PRH.ControlNo = SI.ControlNo
    WHERE SI.Barcode = 'VVQQ053R072725' AND PRH.RouteCode LIKE 'V-26%' AND PRH.WorkCenterCode = 'VVT_F5';
    UPDATE PRH
    SET PRH.ProdQty = 500.001499999998
    FROM dbo.STB_ProdRouteHist PRH WITH (UPDLOCK)
    INNER JOIN dbo.STB_SetInfo SI WITH (NOLOCK) ON PRH.ControlNo = SI.ControlNo
    WHERE SI.Barcode = 'VVQQ173R060612' AND PRH.RouteCode LIKE 'V-26%' AND PRH.WorkCenterCode = 'VVT_F5';
    UPDATE PRH
    SET PRH.ProdQty = 1070
    FROM dbo.STB_ProdRouteHist PRH WITH (UPDLOCK)
    INNER JOIN dbo.STB_SetInfo SI WITH (NOLOCK) ON PRH.ControlNo = SI.ControlNo
    WHERE SI.Barcode = 'VVQQ123R072708' AND PRH.RouteCode LIKE 'V-26%' AND PRH.WorkCenterCode = 'VVT_F5';
    UPDATE PRH
    SET PRH.ProdQty = 500
    FROM dbo.STB_ProdRouteHist PRH WITH (UPDLOCK)
    INNER JOIN dbo.STB_SetInfo SI WITH (NOLOCK) ON PRH.ControlNo = SI.ControlNo
    WHERE SI.Barcode = 'VVQQ123R060624' AND PRH.RouteCode LIKE 'V-26%' AND PRH.WorkCenterCode = 'VVT_F5';
    UPDATE PRH
    SET PRH.ProdQty = 1065.00011
    FROM dbo.STB_ProdRouteHist PRH WITH (UPDLOCK)
    INNER JOIN dbo.STB_SetInfo SI WITH (NOLOCK) ON PRH.ControlNo = SI.ControlNo
    WHERE SI.Barcode = 'VVQQ143R072704' AND PRH.RouteCode LIKE 'V-26%' AND PRH.WorkCenterCode = 'VVT_F5';
    UPDATE PRH
    SET PRH.ProdQty = 1073.00029
    FROM dbo.STB_ProdRouteHist PRH WITH (UPDLOCK)
    INNER JOIN dbo.STB_SetInfo SI WITH (NOLOCK) ON PRH.ControlNo = SI.ControlNo
    WHERE SI.Barcode = 'VVQP223R072704' AND PRH.RouteCode LIKE 'V-26%' AND PRH.WorkCenterCode = 'VVT_F5';
    UPDATE PRH
    SET PRH.ProdQty = 500
    FROM dbo.STB_ProdRouteHist PRH WITH (UPDLOCK)
    INNER JOIN dbo.STB_SetInfo SI WITH (NOLOCK) ON PRH.ControlNo = SI.ControlNo
    WHERE SI.Barcode = 'VVQQ183R060607' AND PRH.RouteCode LIKE 'V-26%' AND PRH.WorkCenterCode = 'VVT_F5';

    COMMIT TRANSACTION;
    PRINT 'DA DIEU CHINH THUA CHINH XAC 150 HANG CHO TOAN BO 7 NGAY!';
END TRY
BEGIN CATCH
    ROLLBACK TRANSACTION;
    DECLARE @ErrMsg NVARCHAR(4000) = ERROR_MESSAGE();
    RAISERROR('LOI: %s', 16, 1, @ErrMsg);
END CATCH;
