-- Function: GET_REGEX_REPLACE

CREATE FUNCTION GET_REGEX_REPLACE (
  @TARGET_TEXT NVARCHAR(MAX),
  @EXPRESSION NVARCHAR(80),
  @REPLACE_VAL NVARCHAR(80)
)
RETURNS NVARCHAR(MAX)
AS
BEGIN
  DECLARE @RETURN_VAL NVARCHAR(MAX) = @TARGET_TEXT;
  
  IF ISNULL(@RETURN_VAL, '') = ''
    RETURN @RETURN_VAL;
  WHILE 1=1
    BEGIN
      IF PATINDEX('%'+@EXPRESSION+'%', @RETURN_VAL) = 0
        BREAK;
      SET @RETURN_VAL = STUFF(@RETURN_VAL, PATINDEX('%'+@EXPRESSION+'%', @RETURN_VAL),1,@REPLACE_VAL)
    END
  RETURN @RETURN_VAL
END  


GO

