-- =============================================
-- Author:	    Park Jong Seob(jspark@awoo.co.kr)
-- Create date: 2016-07-10
-- Browsable : true
-- Group : 공통
-- Description:	모델정보 IUD
-- Modified:
-- =============================================
CREATE PROCEDURE [dbo].[usp_ModelBasicInfo_iud]
	@pProcessUserID VARCHAR(20),
	@pProcessLanguage VARCHAR(20),
    @pProcessViewName VARCHAR(50),
	@pXml NVARCHAR(MAX) = null
AS
BEGIN
	SET NOCOUNT ON;

    DECLARE @ProcessUserID VARCHAR(20) = @pProcessUserID
	DECLARE @ProcessLanguage VARCHAR(20) = @pProcessLanguage
    DECLARE @ProcessViewName VARCHAR(50) = @pProcessViewName
    DECLARE @InsertTableName VARCHAR(100) = '/DataSet/' + @ProcessViewName + '_INSERT'
    DECLARE @UpdateTableName VARCHAR(100) = '/DataSet/' + @ProcessViewName + '_UPDATE'
    DECLARE @DeleteTableName VARCHAR(100) = '/DataSet/' + @ProcessViewName + '_DELETE'
	DECLARE @ERROR_MSG NVARCHAR(MAX)
    DECLARE @IUD_FLAG VARCHAR(10)
	DECLARE @IsAutoKey BIT
	DECLARE @IsLoopIUD BIT
	DECLARE @PrefixString VARCHAR(20)
	DECLARE @SerialLen INT
    DECLARE @MaxKeyField VARCHAR(20)

    -- Declare Columns Variable
  DECLARE @OldModelCode VARCHAR(50)
  DECLARE @ModelCode VARCHAR(50)
  DECLARE @ModelName NVARCHAR(100)
  DECLARE @ModelNameL NVARCHAR(100)
  DECLARE @MaterialTypeCode VARCHAR(20)
  DECLARE @ProductGroupCode VARCHAR(20)
  DECLARE @ModelPrintName NVARCHAR(100)
  DECLARE @BasicModel NVARCHAR(100)
  DECLARE @OemModelBarcode VARCHAR(20)
  DECLARE @DEFlag VARCHAR(1)
  DECLARE @EanCode VARCHAR(20)
  DECLARE @UpcCode VARCHAR(20)
  DECLARE @ModelColor NVARCHAR(30)
  DECLARE @MBIWeight NUMERIC(20,4)
  DECLARE @MBISizeD NUMERIC(20,4)
  DECLARE @MBISizeH NUMERIC(20,4)
  DECLARE @MBISizeW NUMERIC(20,4)
  DECLARE @IsClosed BIT
  DECLARE @OqcType VARCHAR(20)
  DECLARE @OqcCreateRuleNo VARCHAR(20)
  DECLARE @OqcInspectionRuleType VARCHAR(20)
  DECLARE @InspectionType VARCHAR(20)
  DECLARE @InspectionLevel VARCHAR(20)
  DECLARE @AQL NUMERIC(10,3)
  DECLARE @MBIExtText01 NVARCHAR(200)
  DECLARE @MBIExtText02 NVARCHAR(200)
  DECLARE @MBIExtText03 NVARCHAR(200)
  DECLARE @MBIExtText04 NVARCHAR(200)
  DECLARE @MBIExtText05 NVARCHAR(200)
  DECLARE @MBIExtText06 NVARCHAR(200)
  DECLARE @MBIExtText07 NVARCHAR(200)
  DECLARE @MBIExtText08 NVARCHAR(200)
  DECLARE @MBIExtText09 NVARCHAR(200)
  DECLARE @MBIExtText10 NVARCHAR(200)
  DECLARE @MBIExtInt01 BIGINT
  DECLARE @MBIExtInt02 BIGINT
  DECLARE @MBIExtInt03 BIGINT
  DECLARE @MBIExtInt04 BIGINT
  DECLARE @MBIExtInt05 BIGINT
  DECLARE @MBIExtReal01 NUMERIC(20,4)
  DECLARE @MBIExtReal02 NUMERIC(20,4)
  DECLARE @MBIExtReal03 NUMERIC(20,4)
  DECLARE @MBIExtReal04 NUMERIC(20,4)
  DECLARE @MBIExtReal05 NUMERIC(20,4)
  DECLARE @MBIExtLongText01 NVARCHAR(MAX)
  DECLARE @MBIExtLongText02 NVARCHAR(MAX)
  DECLARE @MBIExtLongText03 NVARCHAR(MAX)
  DECLARE @MBIExtLongText04 NVARCHAR(MAX)
  DECLARE @MBIExtLongText05 NVARCHAR(MAX)
  DECLARE @MBIExtImage01 VARBINARY(MAX)
  DECLARE @MBIExtImage02 VARBINARY(MAX)
  DECLARE @MBIExtImage03 VARBINARY(MAX)
  DECLARE @MBIExtImage04 VARBINARY(MAX)
  DECLARE @MBIExtImage05 VARBINARY(MAX)
  DECLARE @CreateDateTime DATETIME
  DECLARE @CreateUserID VARCHAR(20)
  DECLARE @ChangeDateTime DATETIME
  DECLARE @ChangeUserID VARCHAR(20)
  DECLARE @MBIExtBit01 BIT

  -- 신뢰성 시험의뢰 관리항목 추가 2024.07.08 by Jackaroe
  Declare @AcEsr NUMERIC(20, 5)
  Declare @DcEsr NUMERIC(20, 5)
  Declare @MaximumCurrent NUMERIC(20, 5)
  Declare @LeakageCurrent NUMERIC(20, 5)


	DECLARE @iDoc INT

    EXEC SmartFramework.dbo.usp_GetSerialRule 
			@pTableName = 'STB_ModelBasicInfo',
			@pIsAutoKey = @IsAutoKey OUTPUT,
			@pIsLoopIUD = @IsLoopIUD OUTPUT,
			@pPrefixData = @PrefixString OUTPUT,
			@pSerialLen = @SerialLen OUTPUT
    
    IF @IsAutoKey = 0 AND @IsLoopIUD = 0 BEGIN
   
	    EXEC sp_xml_preparedocument @iDoc OUTPUT, @pXml
	
	    BEGIN TRY
			-- Process Insert Table
            MERGE STB_ModelBasicInfo AS TargetTable
			USING
				(
					SELECT
							CASE
							    WHEN OldModelCode IS NULL THEN ModelCode
							    ELSE OldModelCode
							END AS OldModelCode,
							ModelCode,
							ModelName,
							ModelNameL,
							MaterialTypeCode,
							ProductGroupCode,
							ModelPrintName,
							BasicModel,
							OemModelBarcode,
							DEFlag,
							EanCode,
							UpcCode,
							ModelColor,
							MBIWeight,
							MBISizeD,
							MBISizeH,
							MBISizeW,
							IsClosed,
							OqcType,
							OqcCreateRuleNo,
							OqcInspectionRuleType,
							InspectionType,
							InspectionLevel,
							AQL,
							MBIExtText01,
							MBIExtText02,
							MBIExtText03,
							MBIExtText04,
							MBIExtText05,
							MBIExtText06,
							MBIExtText07,
							MBIExtText08,
							MBIExtText09,
							MBIExtText10,
							MBIExtInt01,
							MBIExtInt02,
							MBIExtInt03,
							MBIExtInt04,
							MBIExtInt05,
							MBIExtReal01,
							MBIExtReal02,
							MBIExtReal03,
							MBIExtReal04,
							MBIExtReal05,
							MBIExtLongText01,
							MBIExtLongText02,
							MBIExtLongText03,
							MBIExtLongText04,
							MBIExtLongText05,
							dbo.fnBase64ToBinary(MBIExtImage01) as MBIExtImage01,
							dbo.fnBase64ToBinary(MBIExtImage02) as MBIExtImage02,
							dbo.fnBase64ToBinary(MBIExtImage03) as MBIExtImage03,
							dbo.fnBase64ToBinary(MBIExtImage04) as MBIExtImage04,
							dbo.fnBase64ToBinary(MBIExtImage05) as MBIExtImage05,
							GETDATE() AS CreateDateTime,
							@pProcessUserID AS CreateUserID,
							GETDATE() AS ChangeDateTime,
							@pProcessUserID AS ChangeUserID,
							MBIExtBit01,
							AcEsr,
							DcEsr,
							MaximumCurrent,
							LeakageCurrent
					FROM
							OPENXML(@idoc , @InsertTableName , 2)
							WITH  (
										OldModelCode VARCHAR(50),
										ModelCode VARCHAR(50),
										ModelName NVARCHAR(100),
										ModelNameL NVARCHAR(100),
										MaterialTypeCode VARCHAR(20),
										ProductGroupCode VARCHAR(20),
										ModelPrintName NVARCHAR(100),
										BasicModel NVARCHAR(100),
										OemModelBarcode VARCHAR(20),
										DEFlag VARCHAR(1),
										EanCode VARCHAR(20),
										UpcCode VARCHAR(20),
										ModelColor NVARCHAR(30),
										MBIWeight NUMERIC(20,4),
										MBISizeD NUMERIC(20,4),
										MBISizeH NUMERIC(20,4),
										MBISizeW NUMERIC(20,4),
										IsClosed BIT,
										OqcType VARCHAR(20),
										OqcCreateRuleNo VARCHAR(20),
										OqcInspectionRuleType VARCHAR(20),
										InspectionType VARCHAR(20),
										InspectionLevel VARCHAR(20),
										AQL NUMERIC(10,3),
										MBIExtText01 NVARCHAR(200),
										MBIExtText02 NVARCHAR(200),
										MBIExtText03 NVARCHAR(200),
										MBIExtText04 NVARCHAR(200),
										MBIExtText05 NVARCHAR(200),
										MBIExtText06 NVARCHAR(200),
										MBIExtText07 NVARCHAR(200),
										MBIExtText08 NVARCHAR(200),
										MBIExtText09 NVARCHAR(200),
										MBIExtText10 NVARCHAR(200),
										MBIExtInt01 BIGINT,
										MBIExtInt02 BIGINT,
										MBIExtInt03 BIGINT,
										MBIExtInt04 BIGINT,
										MBIExtInt05 BIGINT,
										MBIExtReal01 NUMERIC(20,4),
										MBIExtReal02 NUMERIC(20,4),
										MBIExtReal03 NUMERIC(20,4),
										MBIExtReal04 NUMERIC(20,4),
										MBIExtReal05 NUMERIC(20,4),
										MBIExtLongText01 NVARCHAR(MAX),
										MBIExtLongText02 NVARCHAR(MAX),
										MBIExtLongText03 NVARCHAR(MAX),
										MBIExtLongText04 NVARCHAR(MAX),
										MBIExtLongText05 NVARCHAR(MAX),
										MBIExtImage01 NVARCHAR(MAX),
										MBIExtImage02 NVARCHAR(MAX),
										MBIExtImage03 NVARCHAR(MAX),
										MBIExtImage04 NVARCHAR(MAX),
										MBIExtImage05 NVARCHAR(MAX),
										CreateDateTime DATETIMEOFFSET,
										CreateUserID VARCHAR(20),
										ChangeDateTime DATETIMEOFFSET,
										ChangeUserID VARCHAR(20),
										MBIExtBit01 BIT,
										AcEsr NUMERIC(20, 5),
										DcEsr NUMERIC(20, 5),
										MaximumCurrent NUMERIC(20, 5),
										LeakageCurrent NUMERIC(20, 5)
									) 
				) AS SourceTable
			ON
				(
					TargetTable.ModelCode = SourceTable.OldModelCode
				)

			WHEN MATCHED THEN
				UPDATE SET
					ModelCode = ISNULL(SourceTable.ModelCode,TargetTable.ModelCode),
					ModelName = ISNULL(SourceTable.ModelName,TargetTable.ModelName),
					ModelNameL = ISNULL(SourceTable.ModelNameL,TargetTable.ModelNameL),
					MaterialTypeCode = ISNULL(SourceTable.MaterialTypeCode,TargetTable.MaterialTypeCode),
					ProductGroupCode = ISNULL(SourceTable.ProductGroupCode,TargetTable.ProductGroupCode),
					ModelPrintName = ISNULL(SourceTable.ModelPrintName,TargetTable.ModelPrintName),
					BasicModel = ISNULL(SourceTable.BasicModel,TargetTable.BasicModel),
					OemModelBarcode = ISNULL(SourceTable.OemModelBarcode,TargetTable.OemModelBarcode),
					DEFlag = ISNULL(SourceTable.DEFlag,TargetTable.DEFlag),
					EanCode = ISNULL(SourceTable.EanCode,TargetTable.EanCode),
					UpcCode = ISNULL(SourceTable.UpcCode,TargetTable.UpcCode),
					ModelColor = ISNULL(SourceTable.ModelColor,TargetTable.ModelColor),
					MBIWeight = ISNULL(SourceTable.MBIWeight,TargetTable.MBIWeight),
					MBISizeD = ISNULL(SourceTable.MBISizeD,TargetTable.MBISizeD),
					MBISizeH = ISNULL(SourceTable.MBISizeH,TargetTable.MBISizeH),
					MBISizeW = ISNULL(SourceTable.MBISizeW,TargetTable.MBISizeW),
					IsClosed = ISNULL(SourceTable.IsClosed,TargetTable.IsClosed),
					OqcType = ISNULL(SourceTable.OqcType,TargetTable.OqcType),
					OqcCreateRuleNo = ISNULL(SourceTable.OqcCreateRuleNo,TargetTable.OqcCreateRuleNo),
					OqcInspectionRuleType = ISNULL(SourceTable.OqcInspectionRuleType,TargetTable.OqcInspectionRuleType),
					InspectionType = ISNULL(SourceTable.InspectionType,TargetTable.InspectionType),
					InspectionLevel = ISNULL(SourceTable.InspectionLevel,TargetTable.InspectionLevel),
					AQL = ISNULL(SourceTable.AQL,TargetTable.AQL),
					MBIExtText01 = ISNULL(SourceTable.MBIExtText01,TargetTable.MBIExtText01),
					MBIExtText02 = ISNULL(SourceTable.MBIExtText02,TargetTable.MBIExtText02),
					MBIExtText03 = ISNULL(SourceTable.MBIExtText03,TargetTable.MBIExtText03),
					MBIExtText04 = ISNULL(SourceTable.MBIExtText04,TargetTable.MBIExtText04),
					MBIExtText05 = ISNULL(SourceTable.MBIExtText05,TargetTable.MBIExtText05),
					MBIExtText06 = ISNULL(SourceTable.MBIExtText06,TargetTable.MBIExtText06),
					MBIExtText07 = ISNULL(SourceTable.MBIExtText07,TargetTable.MBIExtText07),
					MBIExtText08 = ISNULL(SourceTable.MBIExtText08,TargetTable.MBIExtText08),
					MBIExtText09 = ISNULL(SourceTable.MBIExtText09,TargetTable.MBIExtText09),
					MBIExtText10 = ISNULL(SourceTable.MBIExtText10,TargetTable.MBIExtText10),
					MBIExtInt01 = ISNULL(SourceTable.MBIExtInt01,TargetTable.MBIExtInt01),
					MBIExtInt02 = ISNULL(SourceTable.MBIExtInt02,TargetTable.MBIExtInt02),
					MBIExtInt03 = ISNULL(SourceTable.MBIExtInt03,TargetTable.MBIExtInt03),
					MBIExtInt04 = ISNULL(SourceTable.MBIExtInt04,TargetTable.MBIExtInt04),
					MBIExtInt05 = ISNULL(SourceTable.MBIExtInt05,TargetTable.MBIExtInt05),
					MBIExtReal01 = ISNULL(SourceTable.MBIExtReal01,TargetTable.MBIExtReal01),
					MBIExtReal02 = ISNULL(SourceTable.MBIExtReal02,TargetTable.MBIExtReal02),
					MBIExtReal03 = ISNULL(SourceTable.MBIExtReal03,TargetTable.MBIExtReal03),
					MBIExtReal04 = ISNULL(SourceTable.MBIExtReal04,TargetTable.MBIExtReal04),
					MBIExtReal05 = ISNULL(SourceTable.MBIExtReal05,TargetTable.MBIExtReal05),
					MBIExtLongText01 = ISNULL(SourceTable.MBIExtLongText01,TargetTable.MBIExtLongText01),
					MBIExtLongText02 = ISNULL(SourceTable.MBIExtLongText02,TargetTable.MBIExtLongText02),
					MBIExtLongText03 = ISNULL(SourceTable.MBIExtLongText03,TargetTable.MBIExtLongText03),
					MBIExtLongText04 = ISNULL(SourceTable.MBIExtLongText04,TargetTable.MBIExtLongText04),
					MBIExtLongText05 = ISNULL(SourceTable.MBIExtLongText05,TargetTable.MBIExtLongText05),
					MBIExtImage01 = ISNULL(SourceTable.MBIExtImage01,TargetTable.MBIExtImage01),
					MBIExtImage02 = ISNULL(SourceTable.MBIExtImage02,TargetTable.MBIExtImage02),
					MBIExtImage03 = ISNULL(SourceTable.MBIExtImage03,TargetTable.MBIExtImage03),
					MBIExtImage04 = ISNULL(SourceTable.MBIExtImage04,TargetTable.MBIExtImage04),
					MBIExtImage05 = ISNULL(SourceTable.MBIExtImage05,TargetTable.MBIExtImage05),
					ChangeDateTime = ISNULL(SourceTable.ChangeDateTime,TargetTable.ChangeDateTime),
					ChangeUserID = ISNULL(SourceTable.ChangeUserID,TargetTable.ChangeUserID),
					MBIExtBit01 = ISNULL(SourceTable.MBIExtBit01,TargetTable.MBIExtBit01),
					AcEsr = ISNULL(SourceTable.AcEsr,TargetTable.AcEsr),
					DcEsr = ISNULL(SourceTable.DcEsr,TargetTable.DcEsr),
					MaximumCurrent = ISNULL(SourceTable.MaximumCurrent,TargetTable.MaximumCurrent),
					LeakageCurrent = ISNULL(SourceTable.LeakageCurrent,TargetTable.LeakageCurrent)
			WHEN NOT MATCHED THEN
				INSERT
					(
						ModelCode,
						ModelName,
						ModelNameL,
						MaterialTypeCode,
						ProductGroupCode,
						ModelPrintName,
						BasicModel,
						OemModelBarcode,
						DEFlag,
						EanCode,
						UpcCode,
						ModelColor,
						MBIWeight,
						MBISizeD,
						MBISizeH,
						MBISizeW,
						IsClosed,
						OqcType,
						OqcCreateRuleNo,
						OqcInspectionRuleType,
						InspectionType,
						InspectionLevel,
						AQL,
						MBIExtText01,
						MBIExtText02,
						MBIExtText03,
						MBIExtText04,
						MBIExtText05,
						MBIExtText06,
						MBIExtText07,
						MBIExtText08,
						MBIExtText09,
						MBIExtText10,
						MBIExtInt01,
						MBIExtInt02,
						MBIExtInt03,
						MBIExtInt04,
						MBIExtInt05,
						MBIExtReal01,
						MBIExtReal02,
						MBIExtReal03,
						MBIExtReal04,
						MBIExtReal05,
						MBIExtLongText01,
						MBIExtLongText02,
						MBIExtLongText03,
						MBIExtLongText04,
						MBIExtLongText05,
						MBIExtImage01,
						MBIExtImage02,
						MBIExtImage03,
						MBIExtImage04,
						MBIExtImage05,
						CreateDateTime,
						CreateUserID,
						MBIExtBit01,
						AcEsr,
						DcEsr,
						MaximumCurrent,
						LeakageCurrent
					)
				VALUES
					(
							SourceTable.ModelCode,
							SourceTable.ModelName,
							SourceTable.ModelNameL,
							SourceTable.MaterialTypeCode,
							SourceTable.ProductGroupCode,
							SourceTable.ModelPrintName,
							SourceTable.BasicModel,
							SourceTable.OemModelBarcode,
							SourceTable.DEFlag,
							SourceTable.EanCode,
							SourceTable.UpcCode,
							SourceTable.ModelColor,
							SourceTable.MBIWeight,
							SourceTable.MBISizeD,
							SourceTable.MBISizeH,
							SourceTable.MBISizeW,
							SourceTable.IsClosed,
							SourceTable.OqcType,
							SourceTable.OqcCreateRuleNo,
							SourceTable.OqcInspectionRuleType,
							SourceTable.InspectionType,
							SourceTable.InspectionLevel,
							SourceTable.AQL,
							SourceTable.MBIExtText01,
							SourceTable.MBIExtText02,
							SourceTable.MBIExtText03,
							SourceTable.MBIExtText04,
							SourceTable.MBIExtText05,
							SourceTable.MBIExtText06,
							SourceTable.MBIExtText07,
							SourceTable.MBIExtText08,
							SourceTable.MBIExtText09,
							SourceTable.MBIExtText10,
							SourceTable.MBIExtInt01,
							SourceTable.MBIExtInt02,
							SourceTable.MBIExtInt03,
							SourceTable.MBIExtInt04,
							SourceTable.MBIExtInt05,
							SourceTable.MBIExtReal01,
							SourceTable.MBIExtReal02,
							SourceTable.MBIExtReal03,
							SourceTable.MBIExtReal04,
							SourceTable.MBIExtReal05,
							SourceTable.MBIExtLongText01,
							SourceTable.MBIExtLongText02,
							SourceTable.MBIExtLongText03,
							SourceTable.MBIExtLongText04,
							SourceTable.MBIExtLongText05,
							SourceTable.MBIExtImage01,
							SourceTable.MBIExtImage02,
							SourceTable.MBIExtImage03,
							SourceTable.MBIExtImage04,
							SourceTable.MBIExtImage05,
							SourceTable.CreateDateTime,
							SourceTable.CreateUserID,
							SourceTable.MBIExtBit01,
							SourceTable.AcEsr,
							SourceTable.DcEsr,
							SourceTable.MaximumCurrent,
							SourceTable.LeakageCurrent
					);


			-- Process Update Table
            MERGE STB_ModelBasicInfo AS TargetTable
			USING
				(
					SELECT
							CASE
							    WHEN OldModelCode IS NULL THEN ModelCode
							    ELSE OldModelCode
							END AS OldModelCode,
							ModelCode,
							ModelName,
							ModelNameL,
							MaterialTypeCode,
							ProductGroupCode,
							ModelPrintName,
							BasicModel,
							OemModelBarcode,
							DEFlag,
							EanCode,
							UpcCode,
							ModelColor,
							MBIWeight,
							MBISizeD,
							MBISizeH,
							MBISizeW,
							IsClosed,
							OqcType,
							OqcCreateRuleNo,
							OqcInspectionRuleType,
							InspectionType,
							InspectionLevel,
							AQL,
							MBIExtText01,
							MBIExtText02,
							MBIExtText03,
							MBIExtText04,
							MBIExtText05,
							MBIExtText06,
							MBIExtText07,
							MBIExtText08,
							MBIExtText09,
							MBIExtText10,
							MBIExtInt01,
							MBIExtInt02,
							MBIExtInt03,
							MBIExtInt04,
							MBIExtInt05,
							MBIExtReal01,
							MBIExtReal02,
							MBIExtReal03,
							MBIExtReal04,
							MBIExtReal05,
							MBIExtLongText01,
							MBIExtLongText02,
							MBIExtLongText03,
							MBIExtLongText04,
							MBIExtLongText05,
							dbo.fnBase64ToBinary(MBIExtImage01) as MBIExtImage01,
							dbo.fnBase64ToBinary(MBIExtImage02) as MBIExtImage02,
							dbo.fnBase64ToBinary(MBIExtImage03) as MBIExtImage03,
							dbo.fnBase64ToBinary(MBIExtImage04) as MBIExtImage04,
							dbo.fnBase64ToBinary(MBIExtImage05) as MBIExtImage05,
							GETDATE() AS CreateDateTime,
							@pProcessUserID AS CreateUserID,
							GETDATE() AS ChangeDateTime,
							@pProcessUserID AS ChangeUserID,
							MBIExtBit01,
							AcEsr,
							DcEsr,
							MaximumCurrent,
							LeakageCurrent
					FROM
							OPENXML(@idoc , @UpdateTableName , 2)
							WITH  (
										OldModelCode VARCHAR(50),
										ModelCode VARCHAR(50),
										ModelName NVARCHAR(100),
										ModelNameL NVARCHAR(100),
										MaterialTypeCode VARCHAR(20),
										ProductGroupCode VARCHAR(20),
										ModelPrintName NVARCHAR(100),
										BasicModel NVARCHAR(100),
										OemModelBarcode VARCHAR(20),
										DEFlag VARCHAR(1),
										EanCode VARCHAR(20),
										UpcCode VARCHAR(20),
										ModelColor NVARCHAR(30),
										MBIWeight NUMERIC(20,4),
										MBISizeD NUMERIC(20,4),
										MBISizeH NUMERIC(20,4),
										MBISizeW NUMERIC(20,4),
										IsClosed BIT,
										OqcType VARCHAR(20),
										OqcCreateRuleNo VARCHAR(20),
										OqcInspectionRuleType VARCHAR(20),
										InspectionType VARCHAR(20),
										InspectionLevel VARCHAR(20),
										AQL NUMERIC(10,3),
										MBIExtText01 NVARCHAR(200),
										MBIExtText02 NVARCHAR(200),
										MBIExtText03 NVARCHAR(200),
										MBIExtText04 NVARCHAR(200),
										MBIExtText05 NVARCHAR(200),
										MBIExtText06 NVARCHAR(200),
										MBIExtText07 NVARCHAR(200),
										MBIExtText08 NVARCHAR(200),
										MBIExtText09 NVARCHAR(200),
										MBIExtText10 NVARCHAR(200),
										MBIExtInt01 BIGINT,
										MBIExtInt02 BIGINT,
										MBIExtInt03 BIGINT,
										MBIExtInt04 BIGINT,
										MBIExtInt05 BIGINT,
										MBIExtReal01 NUMERIC(20,4),
										MBIExtReal02 NUMERIC(20,4),
										MBIExtReal03 NUMERIC(20,4),
										MBIExtReal04 NUMERIC(20,4),
										MBIExtReal05 NUMERIC(20,4),
										MBIExtLongText01 NVARCHAR(MAX),
										MBIExtLongText02 NVARCHAR(MAX),
										MBIExtLongText03 NVARCHAR(MAX),
										MBIExtLongText04 NVARCHAR(MAX),
										MBIExtLongText05 NVARCHAR(MAX),
										MBIExtImage01 NVARCHAR(MAX),
										MBIExtImage02 NVARCHAR(MAX),
										MBIExtImage03 NVARCHAR(MAX),
										MBIExtImage04 NVARCHAR(MAX),
										MBIExtImage05 NVARCHAR(MAX),
										CreateDateTime DATETIMEOFFSET,
										CreateUserID VARCHAR(20),
										ChangeDateTime DATETIMEOFFSET,
										ChangeUserID VARCHAR(20),
										MBIExtBit01 BIT,
										AcEsr NUMERIC(20, 5),
										DcEsr NUMERIC(20, 5),
										MaximumCurrent NUMERIC(20, 5),
										LeakageCurrent NUMERIC(20, 5)
									) 
				) AS SourceTable
			ON
				(
					TargetTable.ModelCode = SourceTable.OldModelCode
				)

			WHEN MATCHED THEN
				UPDATE SET
					ModelCode = ISNULL(SourceTable.ModelCode,TargetTable.ModelCode),
					ModelName = ISNULL(SourceTable.ModelName,TargetTable.ModelName),
					ModelNameL = ISNULL(SourceTable.ModelNameL,TargetTable.ModelNameL),
					MaterialTypeCode = ISNULL(SourceTable.MaterialTypeCode,TargetTable.MaterialTypeCode),
					ProductGroupCode = ISNULL(SourceTable.ProductGroupCode,TargetTable.ProductGroupCode),
					ModelPrintName = ISNULL(SourceTable.ModelPrintName,TargetTable.ModelPrintName),
					BasicModel = ISNULL(SourceTable.BasicModel,TargetTable.BasicModel),
					OemModelBarcode = ISNULL(SourceTable.OemModelBarcode,TargetTable.OemModelBarcode),
					DEFlag = ISNULL(SourceTable.DEFlag,TargetTable.DEFlag),
					EanCode = ISNULL(SourceTable.EanCode,TargetTable.EanCode),
					UpcCode = ISNULL(SourceTable.UpcCode,TargetTable.UpcCode),
					ModelColor = ISNULL(SourceTable.ModelColor,TargetTable.ModelColor),
					MBIWeight = ISNULL(SourceTable.MBIWeight,TargetTable.MBIWeight),
					MBISizeD = ISNULL(SourceTable.MBISizeD,TargetTable.MBISizeD),
					MBISizeH = ISNULL(SourceTable.MBISizeH,TargetTable.MBISizeH),
					MBISizeW = ISNULL(SourceTable.MBISizeW,TargetTable.MBISizeW),
					IsClosed = ISNULL(SourceTable.IsClosed,TargetTable.IsClosed),
					OqcType = ISNULL(SourceTable.OqcType,TargetTable.OqcType),
					OqcCreateRuleNo = ISNULL(SourceTable.OqcCreateRuleNo,TargetTable.OqcCreateRuleNo),
					OqcInspectionRuleType = ISNULL(SourceTable.OqcInspectionRuleType,TargetTable.OqcInspectionRuleType),
					InspectionType = ISNULL(SourceTable.InspectionType,TargetTable.InspectionType),
					InspectionLevel = ISNULL(SourceTable.InspectionLevel,TargetTable.InspectionLevel),
					AQL = ISNULL(SourceTable.AQL,TargetTable.AQL),
					MBIExtText01 = ISNULL(SourceTable.MBIExtText01,TargetTable.MBIExtText01),
					MBIExtText02 = ISNULL(SourceTable.MBIExtText02,TargetTable.MBIExtText02),
					MBIExtText03 = ISNULL(SourceTable.MBIExtText03,TargetTable.MBIExtText03),
					MBIExtText04 = ISNULL(SourceTable.MBIExtText04,TargetTable.MBIExtText04),
					MBIExtText05 = ISNULL(SourceTable.MBIExtText05,TargetTable.MBIExtText05),
					MBIExtText06 = ISNULL(SourceTable.MBIExtText06,TargetTable.MBIExtText06),
					MBIExtText07 = ISNULL(SourceTable.MBIExtText07,TargetTable.MBIExtText07),
					MBIExtText08 = ISNULL(SourceTable.MBIExtText08,TargetTable.MBIExtText08),
					MBIExtText09 = ISNULL(SourceTable.MBIExtText09,TargetTable.MBIExtText09),
					MBIExtText10 = ISNULL(SourceTable.MBIExtText10,TargetTable.MBIExtText10),
					MBIExtInt01 = ISNULL(SourceTable.MBIExtInt01,TargetTable.MBIExtInt01),
					MBIExtInt02 = ISNULL(SourceTable.MBIExtInt02,TargetTable.MBIExtInt02),
					MBIExtInt03 = ISNULL(SourceTable.MBIExtInt03,TargetTable.MBIExtInt03),
					MBIExtInt04 = ISNULL(SourceTable.MBIExtInt04,TargetTable.MBIExtInt04),
					MBIExtInt05 = ISNULL(SourceTable.MBIExtInt05,TargetTable.MBIExtInt05),
					MBIExtReal01 = ISNULL(SourceTable.MBIExtReal01,TargetTable.MBIExtReal01),
					MBIExtReal02 = ISNULL(SourceTable.MBIExtReal02,TargetTable.MBIExtReal02),
					MBIExtReal03 = ISNULL(SourceTable.MBIExtReal03,TargetTable.MBIExtReal03),
					MBIExtReal04 = ISNULL(SourceTable.MBIExtReal04,TargetTable.MBIExtReal04),
					MBIExtReal05 = ISNULL(SourceTable.MBIExtReal05,TargetTable.MBIExtReal05),
					MBIExtLongText01 = ISNULL(SourceTable.MBIExtLongText01,TargetTable.MBIExtLongText01),
					MBIExtLongText02 = ISNULL(SourceTable.MBIExtLongText02,TargetTable.MBIExtLongText02),
					MBIExtLongText03 = ISNULL(SourceTable.MBIExtLongText03,TargetTable.MBIExtLongText03),
					MBIExtLongText04 = ISNULL(SourceTable.MBIExtLongText04,TargetTable.MBIExtLongText04),
					MBIExtLongText05 = ISNULL(SourceTable.MBIExtLongText05,TargetTable.MBIExtLongText05),
					MBIExtImage01 = ISNULL(SourceTable.MBIExtImage01,TargetTable.MBIExtImage01),
					MBIExtImage02 = ISNULL(SourceTable.MBIExtImage02,TargetTable.MBIExtImage02),
					MBIExtImage03 = ISNULL(SourceTable.MBIExtImage03,TargetTable.MBIExtImage03),
					MBIExtImage04 = ISNULL(SourceTable.MBIExtImage04,TargetTable.MBIExtImage04),
					MBIExtImage05 = ISNULL(SourceTable.MBIExtImage05,TargetTable.MBIExtImage05),
					ChangeDateTime = ISNULL(SourceTable.ChangeDateTime,TargetTable.ChangeDateTime),
					ChangeUserID = ISNULL(SourceTable.ChangeUserID,TargetTable.ChangeUserID),
					MBIExtBit01 = ISNULL(SourceTable.MBIExtBit01,TargetTable.MBIExtBit01),
					AcEsr = ISNULL(SourceTable.AcEsr,TargetTable.AcEsr),
					DcEsr = ISNULL(SourceTable.DcEsr,TargetTable.DcEsr),
					MaximumCurrent = ISNULL(SourceTable.MaximumCurrent,TargetTable.MaximumCurrent),
					LeakageCurrent = ISNULL(SourceTable.LeakageCurrent,TargetTable.LeakageCurrent)
			WHEN NOT MATCHED THEN
				INSERT
					(
						ModelCode,
						ModelName,
						ModelNameL,
						MaterialTypeCode,
						ProductGroupCode,
						ModelPrintName,
						BasicModel,
						OemModelBarcode,
						DEFlag,
						EanCode,
						UpcCode,
						ModelColor,
						MBIWeight,
						MBISizeD,
						MBISizeH,
						MBISizeW,
						IsClosed,
						OqcType,
						OqcCreateRuleNo,
						OqcInspectionRuleType,
						InspectionType,
						InspectionLevel,
						AQL,
						MBIExtText01,
						MBIExtText02,
						MBIExtText03,
						MBIExtText04,
						MBIExtText05,
						MBIExtText06,
						MBIExtText07,
						MBIExtText08,
						MBIExtText09,
						MBIExtText10,
						MBIExtInt01,
						MBIExtInt02,
						MBIExtInt03,
						MBIExtInt04,
						MBIExtInt05,
						MBIExtReal01,
						MBIExtReal02,
						MBIExtReal03,
						MBIExtReal04,
						MBIExtReal05,
						MBIExtLongText01,
						MBIExtLongText02,
						MBIExtLongText03,
						MBIExtLongText04,
						MBIExtLongText05,
						MBIExtImage01,
						MBIExtImage02,
						MBIExtImage03,
						MBIExtImage04,
						MBIExtImage05,
						CreateDateTime,
						CreateUserID,
						MBIExtBit01,
						AcEsr,
						DcEsr,
						MaximumCurrent,
						LeakageCurrent
					)
				VALUES
					(
							SourceTable.ModelCode,
							SourceTable.ModelName,
							SourceTable.ModelNameL,
							SourceTable.MaterialTypeCode,
							SourceTable.ProductGroupCode,
							SourceTable.ModelPrintName,
							SourceTable.BasicModel,
							SourceTable.OemModelBarcode,
							SourceTable.DEFlag,
							SourceTable.EanCode,
							SourceTable.UpcCode,
							SourceTable.ModelColor,
							SourceTable.MBIWeight,
							SourceTable.MBISizeD,
							SourceTable.MBISizeH,
							SourceTable.MBISizeW,
							SourceTable.IsClosed,
							SourceTable.OqcType,
							SourceTable.OqcCreateRuleNo,
							SourceTable.OqcInspectionRuleType,
							ISNULL(SourceTable.InspectionType,'NONE'),
							SourceTable.InspectionLevel,
							SourceTable.AQL,
							SourceTable.MBIExtText01,
							SourceTable.MBIExtText02,
							SourceTable.MBIExtText03,
							SourceTable.MBIExtText04,
							SourceTable.MBIExtText05,
							SourceTable.MBIExtText06,
							SourceTable.MBIExtText07,
							SourceTable.MBIExtText08,
							SourceTable.MBIExtText09,
							SourceTable.MBIExtText10,
							SourceTable.MBIExtInt01,
							SourceTable.MBIExtInt02,
							SourceTable.MBIExtInt03,
							SourceTable.MBIExtInt04,
							SourceTable.MBIExtInt05,
							SourceTable.MBIExtReal01,
							SourceTable.MBIExtReal02,
							SourceTable.MBIExtReal03,
							SourceTable.MBIExtReal04,
							SourceTable.MBIExtReal05,
							SourceTable.MBIExtLongText01,
							SourceTable.MBIExtLongText02,
							SourceTable.MBIExtLongText03,
							SourceTable.MBIExtLongText04,
							SourceTable.MBIExtLongText05,
							SourceTable.MBIExtImage01,
							SourceTable.MBIExtImage02,
							SourceTable.MBIExtImage03,
							SourceTable.MBIExtImage04,
							SourceTable.MBIExtImage05,
							SourceTable.CreateDateTime,
							SourceTable.CreateUserID,
							SourceTable.MBIExtBit01,
							SourceTable.AcEsr,
							SourceTable.DcEsr,
							SourceTable.MaximumCurrent,
							SourceTable.LeakageCurrent
					);


			--UPDATE	STB_MaterialMaster
			--SET
			--		IsRequireOqc = 1
			--FROM
			--		STB_MaterialMaster MM
			--		INNER JOIN STB_ModelBasicInfo MBI
			--			ON MBI.ModelCode = MM.MaterialCode
			--WHERE
			--		MBI.InspectionType IN ('SAMPLE','ALL')
			-- Process Delete Table
            MERGE STB_ModelBasicInfo AS TargetTable
			USING
				(
					SELECT
							CASE
							    WHEN OldModelCode IS NULL THEN ModelCode
							    ELSE OldModelCode
							END AS OldModelCode,
							ModelCode,
							ModelName,
							ModelNameL,
							MaterialTypeCode,
							ProductGroupCode,
							ModelPrintName,
							BasicModel,
							OemModelBarcode,
							DEFlag,
							EanCode,
							UpcCode,
							ModelColor,
							MBIWeight,
							MBISizeD,
							MBISizeH,
							MBISizeW,
							IsClosed,
							MBIExtText01,
							MBIExtText02,
							MBIExtText03,
							MBIExtText04,
							MBIExtText05,
							MBIExtText06,
							MBIExtText07,
							MBIExtText08,
							MBIExtText09,
							MBIExtText10,
							MBIExtInt01,
							MBIExtInt02,
							MBIExtInt03,
							MBIExtInt04,
							MBIExtInt05,
							MBIExtReal01,
							MBIExtReal02,
							MBIExtReal03,
							MBIExtReal04,
							MBIExtReal05,
							MBIExtLongText01,
							MBIExtLongText02,
							MBIExtLongText03,
							MBIExtLongText04,
							MBIExtLongText05,
							dbo.fnBase64ToBinary(MBIExtImage01) as MBIExtImage01,
							dbo.fnBase64ToBinary(MBIExtImage02) as MBIExtImage02,
							dbo.fnBase64ToBinary(MBIExtImage03) as MBIExtImage03,
							dbo.fnBase64ToBinary(MBIExtImage04) as MBIExtImage04,
							dbo.fnBase64ToBinary(MBIExtImage05) as MBIExtImage05,
							GETDATE() AS CreateDateTime,
							@pProcessUserID AS CreateUserID,
							GETDATE() AS ChangeDateTime,
							@pProcessUserID AS ChangeUserID,
							MBIExtBit01,
							AcEsr,
							DcEsr,
							MaximumCurrent,
							LeakageCurrent
					FROM
							OPENXML(@idoc , @DeleteTableName , 2)
							WITH  (
										OldModelCode VARCHAR(50),
										ModelCode VARCHAR(50),
										ModelName NVARCHAR(100),
										ModelNameL NVARCHAR(100),
										MaterialTypeCode VARCHAR(20),
										ProductGroupCode VARCHAR(20),
										ModelPrintName NVARCHAR(100),
										BasicModel NVARCHAR(100),
										OemModelBarcode VARCHAR(20),
										DEFlag VARCHAR(1),
										EanCode VARCHAR(20),
										UpcCode VARCHAR(20),
										ModelColor NVARCHAR(30),
										MBIWeight NUMERIC(20,4),
										MBISizeD NUMERIC(20,4),
										MBISizeH NUMERIC(20,4),
										MBISizeW NUMERIC(20,4),
										IsClosed BIT,
										MBIExtText01 NVARCHAR(200),
										MBIExtText02 NVARCHAR(200),
										MBIExtText03 NVARCHAR(200),
										MBIExtText04 NVARCHAR(200),
										MBIExtText05 NVARCHAR(200),
										MBIExtText06 NVARCHAR(200),
										MBIExtText07 NVARCHAR(200),
										MBIExtText08 NVARCHAR(200),
										MBIExtText09 NVARCHAR(200),
										MBIExtText10 NVARCHAR(200),
										MBIExtInt01 BIGINT,
										MBIExtInt02 BIGINT,
										MBIExtInt03 BIGINT,
										MBIExtInt04 BIGINT,
										MBIExtInt05 BIGINT,
										MBIExtReal01 NUMERIC(20,4),
										MBIExtReal02 NUMERIC(20,4),
										MBIExtReal03 NUMERIC(20,4),
										MBIExtReal04 NUMERIC(20,4),
										MBIExtReal05 NUMERIC(20,4),
										MBIExtLongText01 NVARCHAR(MAX),
										MBIExtLongText02 NVARCHAR(MAX),
										MBIExtLongText03 NVARCHAR(MAX),
										MBIExtLongText04 NVARCHAR(MAX),
										MBIExtLongText05 NVARCHAR(MAX),
										MBIExtImage01 NVARCHAR(MAX),
										MBIExtImage02 NVARCHAR(MAX),
										MBIExtImage03 NVARCHAR(MAX),
										MBIExtImage04 NVARCHAR(MAX),
										MBIExtImage05 NVARCHAR(MAX),
										CreateDateTime DATETIMEOFFSET,
										CreateUserID VARCHAR(20),
										ChangeDateTime DATETIMEOFFSET,
										ChangeUserID VARCHAR(20),
										MBIExtBit01 BIT,
										AcEsr NUMERIC(20, 5),
										DcEsr NUMERIC(20, 5),
										MaximumCurrent NUMERIC(20, 5),
										LeakageCurrent NUMERIC(20, 5)
									) 
				) AS SourceTable
			ON
				(
					TargetTable.ModelCode = SourceTable.OldModelCode 
				)

			WHEN MATCHED THEN
				DELETE;

        END TRY
	    BEGIN CATCH
            SET @ERROR_MSG = ERROR_MESSAGE()
			RAISERROR( @ERROR_MSG ,16, 1)
	    END CATCH
		
	    EXEC sp_xml_removedocument @idoc

    END ELSE BEGIN
        EXEC sp_xml_preparedocument @iDoc OUTPUT, @pXml
        BEGIN TRY
		    DECLARE SourceData CURSOR FOR
                SELECT
                        'INSERT' AS IUD_FLAG,
									OldModelCode,
									ModelCode,
									ModelName,
									ModelNameL,
									MaterialTypeCode,
									ProductGroupCode,
									ModelPrintName,
									BasicModel,
									OemModelBarcode,
									DEFlag,
									EanCode,
									UpcCode,
									ModelColor,
									MBIWeight,
									MBISizeD,
									MBISizeH,
									MBISizeW,
									IsClosed,
									MBIExtText01,
									MBIExtText02,
									MBIExtText03,
									MBIExtText04,
									MBIExtText05,
									MBIExtText06,
									MBIExtText07,
									MBIExtText08,
									MBIExtText09,
									MBIExtText10,
									MBIExtInt01,
									MBIExtInt02,
									MBIExtInt03,
									MBIExtInt04,
									MBIExtInt05,
									MBIExtReal01,
									MBIExtReal02,
									MBIExtReal03,
									MBIExtReal04,
									MBIExtReal05,
									MBIExtLongText01,
									MBIExtLongText02,
									MBIExtLongText03,
									MBIExtLongText04,
									MBIExtLongText05,
									dbo.fnBase64ToBinary(MBIExtImage01) as MBIExtImage01,
									dbo.fnBase64ToBinary(MBIExtImage02) as MBIExtImage02,
									dbo.fnBase64ToBinary(MBIExtImage03) as MBIExtImage03,
									dbo.fnBase64ToBinary(MBIExtImage04) as MBIExtImage04,
									dbo.fnBase64ToBinary(MBIExtImage05) as MBIExtImage05,
									CreateDateTime,
									CreateUserID,
									ChangeDateTime,
									ChangeUserID,
									MBIExtBit01,
									AcEsr,
									DcEsr,
									MaximumCurrent,
									LeakageCurrent
							FROM
									OPENXML(@idoc , @InsertTableName , 2)
							        WITH  (
											 OldModelCode VARCHAR(50),
											 ModelCode VARCHAR(50),
											 ModelName NVARCHAR(100),
											 ModelNameL NVARCHAR(100),
											 MaterialTypeCode VARCHAR(20),
											 ProductGroupCode VARCHAR(20),
											 ModelPrintName NVARCHAR(100),
											 BasicModel NVARCHAR(100),
											 OemModelBarcode VARCHAR(20),
											 DEFlag VARCHAR(1),
											 EanCode VARCHAR(20),
											 UpcCode VARCHAR(20),
											 ModelColor NVARCHAR(30),
											 MBIWeight NUMERIC(20,4),
											 MBISizeD NUMERIC(20,4),
											 MBISizeH NUMERIC(20,4),
											 MBISizeW NUMERIC(20,4),
											 IsClosed BIT,
											 OqcType VARCHAR(20),
											 OqcCreateRuleNo VARCHAR(20),
											 OqcInspectionRuleType VARCHAR(20),
											 InspectionType VARCHAR(20),
											 InspectionLevel VARCHAR(20),
											 AQL NUMERIC(10,3),
											 MBIExtText01 NVARCHAR(200),
											 MBIExtText02 NVARCHAR(200),
											 MBIExtText03 NVARCHAR(200),
											 MBIExtText04 NVARCHAR(200),
											 MBIExtText05 NVARCHAR(200),
											 MBIExtText06 NVARCHAR(200),
											 MBIExtText07 NVARCHAR(200),
											 MBIExtText08 NVARCHAR(200),
											 MBIExtText09 NVARCHAR(200),
											 MBIExtText10 NVARCHAR(200),
											 MBIExtInt01 BIGINT,
											 MBIExtInt02 BIGINT,
											 MBIExtInt03 BIGINT,
											 MBIExtInt04 BIGINT,
											 MBIExtInt05 BIGINT,
											 MBIExtReal01 NUMERIC(20,4),
											 MBIExtReal02 NUMERIC(20,4),
											 MBIExtReal03 NUMERIC(20,4),
											 MBIExtReal04 NUMERIC(20,4),
											 MBIExtReal05 NUMERIC(20,4),
											 MBIExtLongText01 NVARCHAR(MAX),
											 MBIExtLongText02 NVARCHAR(MAX),
											 MBIExtLongText03 NVARCHAR(MAX),
											 MBIExtLongText04 NVARCHAR(MAX),
											 MBIExtLongText05 NVARCHAR(MAX),
											 MBIExtImage01 NVARCHAR(MAX),
											 MBIExtImage02 NVARCHAR(MAX),
											 MBIExtImage03 NVARCHAR(MAX),
											 MBIExtImage04 NVARCHAR(MAX),
											 MBIExtImage05 NVARCHAR(MAX),
											 CreateDateTime DATETIMEOFFSET,
											 CreateUserID VARCHAR(20),
											 ChangeDateTime DATETIMEOFFSET,
											 ChangeUserID VARCHAR(20),
											 MBIExtBit01 BIT,
											AcEsr NUMERIC(20, 5),
											DcEsr NUMERIC(20, 5),
											MaximumCurrent NUMERIC(20, 5),
											LeakageCurrent NUMERIC(20, 5)
											)
							UNION ALL
							SELECT
									'UPDATE' AS IUD_FLAG,
									CASE 
										WHEN OldModelCode IS NULL THEN ModelCode
										ELSE OldModelCode
									END AS OldModelCode,
									ModelCode,
									ModelName,
									ModelNameL,
									MaterialTypeCode,
									ProductGroupCode,
									ModelPrintName,
									BasicModel,
									OemModelBarcode,
									DEFlag,
									EanCode,
									UpcCode,
									ModelColor,
									MBIWeight,
									MBISizeD,
									MBISizeH,
									MBISizeW,
									IsClosed,
									MBIExtText01,
									MBIExtText02,
									MBIExtText03,
									MBIExtText04,
									MBIExtText05,
									MBIExtText06,
									MBIExtText07,
									MBIExtText08,
									MBIExtText09,
									MBIExtText10,
									MBIExtInt01,
									MBIExtInt02,
									MBIExtInt03,
									MBIExtInt04,
									MBIExtInt05,
									MBIExtReal01,
									MBIExtReal02,
									MBIExtReal03,
									MBIExtReal04,
									MBIExtReal05,
									MBIExtLongText01,
									MBIExtLongText02,
									MBIExtLongText03,
									MBIExtLongText04,
									MBIExtLongText05,
									dbo.fnBase64ToBinary(MBIExtImage01) as MBIExtImage01,
									dbo.fnBase64ToBinary(MBIExtImage02) as MBIExtImage02,
									dbo.fnBase64ToBinary(MBIExtImage03) as MBIExtImage03,
									dbo.fnBase64ToBinary(MBIExtImage04) as MBIExtImage04,
									dbo.fnBase64ToBinary(MBIExtImage05) as MBIExtImage05,
									CreateDateTime,
									CreateUserID,
									ChangeDateTime,
									ChangeUserID,
									MBIExtBit01,
									AcEsr,
									DcEsr,
									MaximumCurrent,
									LeakageCurrent
							FROM
									OPENXML(@idoc , @UpdateTableName , 2)
							        WITH  (
											 OldModelCode VARCHAR(50),
											 ModelCode VARCHAR(50),
											 ModelName NVARCHAR(100),
											 ModelNameL NVARCHAR(100),
											 MaterialTypeCode VARCHAR(20),
											 ProductGroupCode VARCHAR(20),
											 ModelPrintName NVARCHAR(100),
											 BasicModel NVARCHAR(100),
											 OemModelBarcode VARCHAR(20),
											 DEFlag VARCHAR(1),
											 EanCode VARCHAR(20),
											 UpcCode VARCHAR(20),
											 ModelColor NVARCHAR(30),
											 MBIWeight NUMERIC(20,4),
											 MBISizeD NUMERIC(20,4),
											 MBISizeH NUMERIC(20,4),
											 MBISizeW NUMERIC(20,4),
											 IsClosed BIT,
											 OqcType VARCHAR(20),
											 OqcCreateRuleNo VARCHAR(20),
											 OqcInspectionRuleType VARCHAR(20),
											 InspectionType VARCHAR(20),
											 InspectionLevel VARCHAR(20),
											 AQL NUMERIC(10,3),
											 MBIExtText01 NVARCHAR(200),
											 MBIExtText02 NVARCHAR(200),
											 MBIExtText03 NVARCHAR(200),
											 MBIExtText04 NVARCHAR(200),
											 MBIExtText05 NVARCHAR(200),
											 MBIExtText06 NVARCHAR(200),
											 MBIExtText07 NVARCHAR(200),
											 MBIExtText08 NVARCHAR(200),
											 MBIExtText09 NVARCHAR(200),
											 MBIExtText10 NVARCHAR(200),
											 MBIExtInt01 BIGINT,
											 MBIExtInt02 BIGINT,
											 MBIExtInt03 BIGINT,
											 MBIExtInt04 BIGINT,
											 MBIExtInt05 BIGINT,
											 MBIExtReal01 NUMERIC(20,4),
											 MBIExtReal02 NUMERIC(20,4),
											 MBIExtReal03 NUMERIC(20,4),
											 MBIExtReal04 NUMERIC(20,4),
											 MBIExtReal05 NUMERIC(20,4),
											 MBIExtLongText01 NVARCHAR(MAX),
											 MBIExtLongText02 NVARCHAR(MAX),
											 MBIExtLongText03 NVARCHAR(MAX),
											 MBIExtLongText04 NVARCHAR(MAX),
											 MBIExtLongText05 NVARCHAR(MAX),
											 MBIExtImage01 NVARCHAR(MAX),
											 MBIExtImage02 NVARCHAR(MAX),
											 MBIExtImage03 NVARCHAR(MAX),
											 MBIExtImage04 NVARCHAR(MAX),
											 MBIExtImage05 NVARCHAR(MAX),
											 CreateDateTime DATETIMEOFFSET,
											 CreateUserID VARCHAR(20),
											 ChangeDateTime DATETIMEOFFSET,
											 ChangeUserID VARCHAR(20),
											 MBIExtBit01 BIT,
											AcEsr NUMERIC(20, 5),
											DcEsr NUMERIC(20, 5),
											MaximumCurrent NUMERIC(20, 5),
											LeakageCurrent NUMERIC(20, 5)
											)
							UNION ALL
							SELECT
									'DELETE' AS IUD_FLAG,
									CASE 
										WHEN OldModelCode IS NULL THEN ModelCode
										ELSE OldModelCode
									END AS OldModelCode,
									ModelCode,
									ModelName,
									ModelNameL,
									MaterialTypeCode,
									ProductGroupCode,
									ModelPrintName,
									BasicModel,
									OemModelBarcode,
									DEFlag,
									EanCode,
									UpcCode,
									ModelColor,
									MBIWeight,
									MBISizeD,
									MBISizeH,
									MBISizeW,
									IsClosed,
									MBIExtText01,
									MBIExtText02,
									MBIExtText03,
									MBIExtText04,
									MBIExtText05,
									MBIExtText06,
									MBIExtText07,
									MBIExtText08,
									MBIExtText09,
									MBIExtText10,
									MBIExtInt01,
									MBIExtInt02,
									MBIExtInt03,
									MBIExtInt04,
									MBIExtInt05,
									MBIExtReal01,
									MBIExtReal02,
									MBIExtReal03,
									MBIExtReal04,
									MBIExtReal05,
									MBIExtLongText01,
									MBIExtLongText02,
									MBIExtLongText03,
									MBIExtLongText04,
									MBIExtLongText05,
									dbo.fnBase64ToBinary(MBIExtImage01) as MBIExtImage01,
									dbo.fnBase64ToBinary(MBIExtImage02) as MBIExtImage02,
									dbo.fnBase64ToBinary(MBIExtImage03) as MBIExtImage03,
									dbo.fnBase64ToBinary(MBIExtImage04) as MBIExtImage04,
									dbo.fnBase64ToBinary(MBIExtImage05) as MBIExtImage05,
									CreateDateTime,
									CreateUserID,
									ChangeDateTime,
									ChangeUserID,
									MBIExtBit01,
									AcEsr,
									DcEsr,
									MaximumCurrent,
									LeakageCurrent
							FROM
									OPENXML(@idoc , @DeleteTableName , 2)
							        WITH  (
											 OldModelCode VARCHAR(50),
											 ModelCode VARCHAR(50),
											 ModelName NVARCHAR(100),
											 ModelNameL NVARCHAR(100),
											 MaterialTypeCode VARCHAR(20),
											 ProductGroupCode VARCHAR(20),
											 ModelPrintName NVARCHAR(100),
											 BasicModel NVARCHAR(100),
											 OemModelBarcode VARCHAR(20),
											 DEFlag VARCHAR(1),
											 EanCode VARCHAR(20),
											 UpcCode VARCHAR(20),
											 ModelColor NVARCHAR(30),
											 MBIWeight NUMERIC(20,4),
											 MBISizeD NUMERIC(20,4),
											 MBISizeH NUMERIC(20,4),
											 MBISizeW NUMERIC(20,4),
											 IsClosed BIT,
											 OqcType VARCHAR(20),
											 OqcCreateRuleNo VARCHAR(20),
											 OqcInspectionRuleType VARCHAR(20),
											 InspectionType VARCHAR(20),
											 InspectionLevel VARCHAR(20),
											 AQL NUMERIC(10,3),
											 MBIExtText01 NVARCHAR(200),
											 MBIExtText02 NVARCHAR(200),
											 MBIExtText03 NVARCHAR(200),
											 MBIExtText04 NVARCHAR(200),
											 MBIExtText05 NVARCHAR(200),
											 MBIExtText06 NVARCHAR(200),
											 MBIExtText07 NVARCHAR(200),
											 MBIExtText08 NVARCHAR(200),
											 MBIExtText09 NVARCHAR(200),
											 MBIExtText10 NVARCHAR(200),
											 MBIExtInt01 BIGINT,
											 MBIExtInt02 BIGINT,
											 MBIExtInt03 BIGINT,
											 MBIExtInt04 BIGINT,
											 MBIExtInt05 BIGINT,
											 MBIExtReal01 NUMERIC(20,4),
											 MBIExtReal02 NUMERIC(20,4),
											 MBIExtReal03 NUMERIC(20,4),
											 MBIExtReal04 NUMERIC(20,4),
											 MBIExtReal05 NUMERIC(20,4),
											 MBIExtLongText01 NVARCHAR(MAX),
											 MBIExtLongText02 NVARCHAR(MAX),
											 MBIExtLongText03 NVARCHAR(MAX),
											 MBIExtLongText04 NVARCHAR(MAX),
											 MBIExtLongText05 NVARCHAR(MAX),
											 MBIExtImage01 NVARCHAR(MAX),
											 MBIExtImage02 NVARCHAR(MAX),
											 MBIExtImage03 NVARCHAR(MAX),
											 MBIExtImage04 NVARCHAR(MAX),
											 MBIExtImage05 NVARCHAR(MAX),
											 CreateDateTime DATETIMEOFFSET,
											 CreateUserID VARCHAR(20),
											 ChangeDateTime DATETIMEOFFSET,
											 ChangeUserID VARCHAR(20),
											 MBIExtBit01 BIT,
											AcEsr NUMERIC(20, 5),
											DcEsr NUMERIC(20, 5),
											MaximumCurrent NUMERIC(20, 5),
											LeakageCurrent NUMERIC(20, 5)
											) 


            OPEN SourceData

            WHILE 1 = 1 BEGIN
                FETCH NEXT FROM SourceData INTO
								 @IUD_FLAG,
								 @OldModelCode,
								 @ModelCode,
								 @ModelName,
								 @ModelNameL,
								 @MaterialTypeCode,
								 @ProductGroupCode,
								 @ModelPrintName,
								 @BasicModel,
								 @OemModelBarcode,
								 @DEFlag,
								 @EanCode,
								 @UpcCode,
								 @ModelColor,
								 @MBIWeight,
								 @MBISizeD,
								 @MBISizeH,
								 @MBISizeW,
								 @IsClosed,
								 @MBIExtText01,
								 @MBIExtText02,
								 @MBIExtText03,
								 @MBIExtText04,
								 @MBIExtText05,
								 @MBIExtText06,
								 @MBIExtText07,
								 @MBIExtText08,
								 @MBIExtText09,
								 @MBIExtText10,
								 @MBIExtInt01,
								 @MBIExtInt02,
								 @MBIExtInt03,
								 @MBIExtInt04,
								 @MBIExtInt05,
								 @MBIExtReal01,
								 @MBIExtReal02,
								 @MBIExtReal03,
								 @MBIExtReal04,
								 @MBIExtReal05,
								 @MBIExtLongText01,
								 @MBIExtLongText02,
								 @MBIExtLongText03,
								 @MBIExtLongText04,
								 @MBIExtLongText05,
								 @MBIExtImage01,
								 @MBIExtImage02,
								 @MBIExtImage03,
								 @MBIExtImage04,
								 @MBIExtImage05,
								 @CreateDateTime,
								 @CreateUserID,
								 @ChangeDateTime,
								 @ChangeUserID,
								 @MBIExtBit01,
								 @AcEsr,
								 @DcEsr,
								 @MaximumCurrent,
								 @LeakageCurrent


                IF @@FETCH_STATUS <> 0 BEGIN
					BREAK
				END
                IF @IUD_FLAG = 'INSERT' BEGIN

                    IF EXISTS (SELECT 1 FROM STB_ModelBasicInfo WHERE ModelCode = @ModelCode) BEGIN
						RAISERROR('Duplicate Data : KeyField = %s', 16, 1, @ModelCode)
					END

                    IF @IsAutoKey = 1 BEGIN
						EXEC SmartFramework.dbo.usp_DoCreateSerial 'STB_ModelBasicInfo', @ModelCode OUTPUT
                    END

                    INSERT INTO STB_ModelBasicInfo
						(
						    ModelCode,
						    ModelName,
						    ModelNameL,
						    MaterialTypeCode,
						    ProductGroupCode,
						    ModelPrintName,
						    BasicModel,
						    OemModelBarcode,
						    DEFlag,
						    EanCode,
						    UpcCode,
						    ModelColor,
						    MBIWeight,
						    MBISizeD,
						    MBISizeH,
						    MBISizeW,
						    IsClosed,
						    MBIExtText01,
						    MBIExtText02,
						    MBIExtText03,
						    MBIExtText04,
						    MBIExtText05,
						    MBIExtText06,
						    MBIExtText07,
						    MBIExtText08,
						    MBIExtText09,
						    MBIExtText10,
						    MBIExtInt01,
						    MBIExtInt02,
						    MBIExtInt03,
						    MBIExtInt04,
						    MBIExtInt05,
						    MBIExtReal01,
						    MBIExtReal02,
						    MBIExtReal03,
						    MBIExtReal04,
						    MBIExtReal05,
						    MBIExtLongText01,
						    MBIExtLongText02,
						    MBIExtLongText03,
						    MBIExtLongText04,
						    MBIExtLongText05,
						    MBIExtImage01,
						    MBIExtImage02,
						    MBIExtImage03,
						    MBIExtImage04,
						    MBIExtImage05,
						    CreateDateTime,
						    CreateUserID,
						    ChangeDateTime,
						    ChangeUserID,
							MBIExtBit01,
							AcEsr,
							DcEsr,
							MaximumCurrent,
							LeakageCurrent
						)
						VALUES
						(
						    @ModelCode,
						    @ModelName,
						    @ModelNameL,
						    @MaterialTypeCode,
						    @ProductGroupCode,
						    @ModelPrintName,
						    @BasicModel,
						    @OemModelBarcode,
						    @DEFlag,
						    @EanCode,
						    @UpcCode,
						    @ModelColor,
						    @MBIWeight,
						    @MBISizeD,
						    @MBISizeH,
						    @MBISizeW,
						    @IsClosed,
						    @MBIExtText01,
						    @MBIExtText02,
						    @MBIExtText03,
						    @MBIExtText04,
						    @MBIExtText05,
						    @MBIExtText06,
						    @MBIExtText07,
						    @MBIExtText08,
						    @MBIExtText09,
						    @MBIExtText10,
						    @MBIExtInt01,
						    @MBIExtInt02,
						    @MBIExtInt03,
						    @MBIExtInt04,
						    @MBIExtInt05,
						    @MBIExtReal01,
						    @MBIExtReal02,
						    @MBIExtReal03,
						    @MBIExtReal04,
						    @MBIExtReal05,
						    @MBIExtLongText01,
						    @MBIExtLongText02,
						    @MBIExtLongText03,
						    @MBIExtLongText04,
						    @MBIExtLongText05,
						    @MBIExtImage01,
						    @MBIExtImage02,
						    @MBIExtImage03,
						    @MBIExtImage04,
						    @MBIExtImage05,
						    GETDATE(),
						    @pProcessUserID,
						    @ChangeDateTime,
						    @ChangeUserID,
							@MBIExtBit01,
							@AcEsr,
							@DcEsr,
							@MaximumCurrent,
							@LeakageCurrent
						)

				END ELSE IF @IUD_FLAG = 'UPDATE' BEGIN
                    UPDATE STB_ModelBasicInfo
						SET
						    ModelCode =   ISNULL(@ModelCode,ModelCode),
						    ModelName =   ISNULL(@ModelName,ModelName),
						    ModelNameL =   ISNULL(@ModelNameL,ModelNameL),
						    MaterialTypeCode =   ISNULL(@MaterialTypeCode,MaterialTypeCode),
						    ProductGroupCode =   ISNULL(@ProductGroupCode,ProductGroupCode),
						    ModelPrintName =   ISNULL(@ModelPrintName,ModelPrintName),
						    BasicModel =   ISNULL(@BasicModel,BasicModel),
						    OemModelBarcode =   ISNULL(@OemModelBarcode,OemModelBarcode),
						    DEFlag =   ISNULL(@DEFlag,DEFlag),
						    EanCode =   ISNULL(@EanCode,EanCode),
						    UpcCode =   ISNULL(@UpcCode,UpcCode),
						    ModelColor =   ISNULL(@ModelColor,ModelColor),
						    MBIWeight =   ISNULL(@MBIWeight,MBIWeight),
						    MBISizeD =   ISNULL(@MBISizeD,MBISizeD),
						    MBISizeH =   ISNULL(@MBISizeH,MBISizeH),
						    MBISizeW =   ISNULL(@MBISizeW,MBISizeW),
						    IsClosed =   ISNULL(@IsClosed,IsClosed),
						    MBIExtText01 =   ISNULL(@MBIExtText01,MBIExtText01),
						    MBIExtText02 =   ISNULL(@MBIExtText02,MBIExtText02),
						    MBIExtText03 =   ISNULL(@MBIExtText03,MBIExtText03),
						    MBIExtText04 =   ISNULL(@MBIExtText04,MBIExtText04),
						    MBIExtText05 =   ISNULL(@MBIExtText05,MBIExtText05),
						    MBIExtText06 =   ISNULL(@MBIExtText06,MBIExtText06),
						    MBIExtText07 =   ISNULL(@MBIExtText07,MBIExtText07),
						    MBIExtText08 =   ISNULL(@MBIExtText08,MBIExtText08),
						    MBIExtText09 =   ISNULL(@MBIExtText09,MBIExtText09),
						    MBIExtText10 =   ISNULL(@MBIExtText10,MBIExtText10),
						    MBIExtInt01 =   ISNULL(@MBIExtInt01,MBIExtInt01),
						    MBIExtInt02 =   ISNULL(@MBIExtInt02,MBIExtInt02),
						    MBIExtInt03 =   ISNULL(@MBIExtInt03,MBIExtInt03),
						    MBIExtInt04 =   ISNULL(@MBIExtInt04,MBIExtInt04),
						    MBIExtInt05 =   ISNULL(@MBIExtInt05,MBIExtInt05),
						    MBIExtReal01 =   ISNULL(@MBIExtReal01,MBIExtReal01),
						    MBIExtReal02 =   ISNULL(@MBIExtReal02,MBIExtReal02),
						    MBIExtReal03 =   ISNULL(@MBIExtReal03,MBIExtReal03),
						    MBIExtReal04 =   ISNULL(@MBIExtReal04,MBIExtReal04),
						    MBIExtReal05 =   ISNULL(@MBIExtReal05,MBIExtReal05),
						    MBIExtLongText01 =   ISNULL(@MBIExtLongText01,MBIExtLongText01),
						    MBIExtLongText02 =   ISNULL(@MBIExtLongText02,MBIExtLongText02),
						    MBIExtLongText03 =   ISNULL(@MBIExtLongText03,MBIExtLongText03),
						    MBIExtLongText04 =   ISNULL(@MBIExtLongText04,MBIExtLongText04),
						    MBIExtLongText05 =   ISNULL(@MBIExtLongText05,MBIExtLongText05),
						    MBIExtImage01 =   ISNULL(@MBIExtImage01,MBIExtImage01),
						    MBIExtImage02 =   ISNULL(@MBIExtImage02,MBIExtImage02),
						    MBIExtImage03 =   ISNULL(@MBIExtImage03,MBIExtImage03),
						    MBIExtImage04 =   ISNULL(@MBIExtImage04,MBIExtImage04),
						    MBIExtImage05 =   ISNULL(@MBIExtImage05,MBIExtImage05),
						    CreateDateTime =   ISNULL(@CreateDateTime,CreateDateTime),
						    CreateUserID =   ISNULL(@CreateUserID,CreateUserID),
						    ChangeDateTime = GETDATE(),
						    ChangeUserID = @pProcessUserID,
							MBIExtBit01 =   ISNULL(@MBIExtBit01,MBIExtBit01),
							AcEsr =   ISNULL(@AcEsr,AcEsr),
							DcEsr =   ISNULL(@DcEsr,DcEsr),
							MaximumCurrent =   ISNULL(@MaximumCurrent,MaximumCurrent),
							LeakageCurrent =   ISNULL(@LeakageCurrent,LeakageCurrent)
						WHERE
						    ModelCode = @OldModelCode
                END ELSE IF @IUD_FLAG = 'DELETE' BEGIN
                    DELETE FROM STB_ModelBasicInfo
						WHERE
						    ModelCode = @ModelCode
                END
            END
        END TRY
		BEGIN CATCH
			SET @ERROR_MSG = ERROR_MESSAGE()
			RAISERROR( @ERROR_MSG ,16, 1)
		END CATCH
			
		CLOSE SourceData;
		DEALLOCATE SourceData;
			
		EXEC sp_xml_removedocument @idoc	
    END
END