CREATE TABLE [dbo].[CURLING_PLAN] (
    [기준년월] VARCHAR(12) NOT NULL DEFAULT ,
    [라인코드] VARCHAR(14) NOT NULL DEFAULT ,
    [라인명] VARCHAR(20) NULL DEFAULT ,
    [사이즈] VARCHAR(20) NULL DEFAULT ,
    [규격] VARCHAR(30) NULL DEFAULT ,
    [월간계획] INT NULL DEFAULT ,
    [라인별칭] VARCHAR(20) NULL DEFAULT ,
    [특이사항] VARCHAR(200) NULL DEFAULT ,
    [RouteCode] VARCHAR(20) NULL DEFAULT ,
    [CompanyCode] VARCHAR(20) NULL DEFAULT ,
    [MaterialCode] VARCHAR(20) NULL DEFAULT ,
    [Idx] BIGINT IDENTITY(1,1) NOT NULL DEFAULT 
);
GO

