CREATE TABLE [dbo].[EquipmentAuditLogs] (
    [Id] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [EquipmentId] INT NOT NULL DEFAULT ,
    [EntityName] NVARCHAR(MAX) NOT NULL DEFAULT ,
    [PropertyName] NVARCHAR(MAX) NOT NULL DEFAULT ,
    [OldValue] NVARCHAR(MAX) NULL DEFAULT ,
    [NewValue] NVARCHAR(MAX) NULL DEFAULT ,
    [UpdatedBy] NVARCHAR(MAX) NULL DEFAULT ,
    [UpdatedAt] DATETIME2 NOT NULL DEFAULT ,
    [Action] NVARCHAR(MAX) NOT NULL DEFAULT 
);
GO

