CREATE TABLE [dbo].[ESM_ProdRouteLotHist] (
    [DayPlanNo] VARCHAR(20) NOT NULL DEFAULT ,
    [OrgDayPlanNo] VARCHAR(20) NOT NULL DEFAULT ,
    [PONo] VARCHAR(20) NOT NULL DEFAULT ,
    [ControlNo] VARCHAR(20) NOT NULL DEFAULT ,
    [ProdRouteHistNo] VARCHAR(20) NOT NULL DEFAULT ,
    [Barcode] VARCHAR(20) NOT NULL DEFAULT ,
    [RowHash] VARBINARY(150) NOT NULL DEFAULT ,
    [LineCode] VARCHAR(20) NOT NULL DEFAULT ,
    [RouteCode] VARCHAR(20) NOT NULL DEFAULT ,
    [MaterialCode] VARCHAR(50) NOT NULL DEFAULT ,
    [WorkCenterCode] VARCHAR(20) NOT NULL DEFAULT ,
    [CompanyCode] VARCHAR(20) NOT NULL DEFAULT ,
    [CdCompany] VARCHAR(20) NOT NULL DEFAULT ,
    [ORDERS] INT NOT NULL DEFAULT ,
    [WorkCenterName] NVARCHAR(100) NULL DEFAULT ,
    [BomVersion] VARCHAR(20) NULL DEFAULT ,
    [MaterialName] VARCHAR(200) NULL DEFAULT ,
    [PlanDate] DATE NULL DEFAULT ,
    [JobDate] DATE NULL DEFAULT ,
    [PlanQty] NUMERIC(20,4) NULL DEFAULT ,
    [ProdQty] NUMERIC(20,4) NULL DEFAULT ,
    [DefectQty] NUMERIC(20,4) NULL DEFAULT ,
    [ParentMaterialCode] VARCHAR(20) NULL DEFAULT ,
    [ParentBarcode] VARCHAR(20) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    CONSTRAINT [PK_ESM_ProdRouteLotHist] PRIMARY KEY CLUSTERED ([DayPlanNo], [OrgDayPlanNo], [PONo], [ControlNo], [ProdRouteHistNo], [Barcode], [RowHash])
);
GO

