CREATE TABLE [dbo].[ESM_ProdRouteHist] (
    [DayPlanNo] VARCHAR(20) NOT NULL DEFAULT ,
    [OrgDayPlanNo] VARCHAR(20) NOT NULL DEFAULT ,
    [RouteCode] VARCHAR(20) NOT NULL DEFAULT ,
    [MaterialCode] VARCHAR(50) NOT NULL DEFAULT ,
    [WorkCenterCode] VARCHAR(20) NOT NULL DEFAULT ,
    [CdCompany] VARCHAR(20) NOT NULL DEFAULT ,
    [LineCode] VARCHAR(20) NOT NULL DEFAULT ,
    [PlanQty] NUMERIC(20,4) NULL DEFAULT ,
    [ProdQty] NUMERIC(20,4) NULL DEFAULT ,
    [DefectQty] NUMERIC(20,4) NULL DEFAULT ,
    [LastRoute] NCHAR(1) NULL DEFAULT ,
    [RouteName] NVARCHAR(300) NULL DEFAULT ,
    [JobDate] DATETIME NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [Barcode] VARCHAR(100) NULL DEFAULT ,
    [ErpUpdate] CHAR(1) NULL DEFAULT ('N'),
    [ErpUpdateDateTime] DATETIME NULL DEFAULT ,
    [NotEnd15DayYn] CHAR(1) NULL DEFAULT ('N')
);
GO

