CREATE TABLE [dbo].[InvoiceFinishGoodStockOutBG] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [Customer] NVARCHAR(255) NULL DEFAULT ,
    [PN] VARCHAR(100) NULL DEFAULT ,
    [Qty] INT NULL DEFAULT ,
    [BoxQty] INT NULL DEFAULT ,
    [Note] NVARCHAR(MAX) NULL DEFAULT ,
    [NoiXuat] NVARCHAR(100) NULL DEFAULT ,
    [InvoiceNo] NVARCHAR(100) NULL DEFAULT ,
    [PO] NVARCHAR(100) NULL DEFAULT ,
    [HH_PN] NVARCHAR(100) NULL DEFAULT ,
    [NgayXuat] DATETIME NULL DEFAULT 
);
GO

