CREATE TABLE [dbo].[MA_GRANT_AUTOREMOVE_LOG] (
    [IDX] BIGINT IDENTITY(1,1) NOT NULL DEFAULT ,
    [CD_GROUP] NVARCHAR(7) NOT NULL DEFAULT ,
    [CD_COMPANY] NVARCHAR(7) NOT NULL DEFAULT ,
    [ID_USER] NVARCHAR(15) NOT NULL DEFAULT ,
    [USR_GBN] NVARCHAR(3) NOT NULL DEFAULT ,
    [NM_USER] NVARCHAR(40) NULL DEFAULT ,
    [NO_EMP] NVARCHAR(10) NULL DEFAULT ,
    [ID_INSERT] NVARCHAR(15) NULL DEFAULT ,
    [ID_UPDATE] NVARCHAR(15) NULL DEFAULT ,
    [DTS_UPDATE] NVARCHAR(14) NULL DEFAULT ,
    [DTS_INSERT] NVARCHAR(14) NULL DEFAULT ,
    [YN_USERMENU] CHAR(1) NULL DEFAULT ,
    [NM_USER_L1] NVARCHAR(20) NULL DEFAULT ,
    [NM_USER_L2] NVARCHAR(20) NULL DEFAULT ,
    [NM_USER_L3] NVARCHAR(20) NULL DEFAULT ,
    [NM_USER_L4] NVARCHAR(20) NULL DEFAULT ,
    [NM_USER_L5] NVARCHAR(20) NULL DEFAULT ,
    [DTS_LOG] DATETIME NOT NULL DEFAULT (getdate())
);
GO

