CREATE TABLE [dbo].[MaintenanceTasks] (
    [TaskID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [StepID] INT NULL DEFAULT ,
    [TaskDescription] NVARCHAR(MAX) NULL DEFAULT ,
    [AsIs] NVARCHAR(MAX) NULL DEFAULT ,
    [ToBe] NVARCHAR(MAX) NULL DEFAULT ,
    [Cause] NVARCHAR(MAX) NULL DEFAULT ,
    [PerformedBy] NVARCHAR(100) NULL DEFAULT ,
    [CreatedAt] DATETIME NULL DEFAULT (getdate()),
    [CellLineID] INT NULL DEFAULT 
);
GO

