CREATE TABLE [dbo].[OUT_ASN] (
    [OUT_ORD_NO] VARCHAR(20) NOT NULL DEFAULT ,
    [PACK_ID] VARCHAR(20) NOT NULL DEFAULT ,
    [OUT_TYPE] VARCHAR(2) NOT NULL DEFAULT ,
    [ITM_CD] VARCHAR(20) NOT NULL DEFAULT ,
    [ITM_NM] VARCHAR(100) NOT NULL DEFAULT ,
    [ITM_QTY] NUMERIC(20,5) NULL DEFAULT ,
    [STATUS] VARCHAR(2) NOT NULL DEFAULT ,
    [CRT_DT] DATETIME NOT NULL DEFAULT (getdate()),
    CONSTRAINT [PK_OUT_ASN] PRIMARY KEY CLUSTERED ([OUT_ORD_NO], [PACK_ID])
);
GO

