CREATE TABLE [dbo].[OUT_RSLT] (
    [OUT_ORD_NO] VARCHAR(20) NOT NULL DEFAULT ,
    [PACK_ID] VARCHAR(20) NOT NULL DEFAULT ,
    [OUT_CODE] VARCHAR(1) NOT NULL DEFAULT ,
    [OUT_TYPE] VARCHAR(2) NOT NULL DEFAULT ,
    [LOC_CD] VARCHAR(20) NOT NULL DEFAULT ,
    [ITM_CD] VARCHAR(20) NOT NULL DEFAULT ,
    [ITM_QTY] NUMERIC(6,0) NOT NULL DEFAULT ,
    [STATUS] VARCHAR(2) NOT NULL DEFAULT ((0)),
    [CRT_DT] DATETIME NOT NULL DEFAULT (getdate()),
    [AUTO_OUT_STATUS] INT NOT NULL DEFAULT ((0)),
    [IDX] BIGINT IDENTITY(1,1) NOT NULL DEFAULT 
);
GO

