CREATE TABLE [dbo].[PopToDryProcess] (
    [Id] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [Barcode] VARCHAR(20) NOT NULL DEFAULT ,
    [MachineCode] VARCHAR(20) NULL DEFAULT ,
    [StartTime] DATETIME NULL DEFAULT ,
    [EndTime] DATETIME NULL DEFAULT ,
    [CreateUserId] VARCHAR(20) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [ModifyUserId] VARCHAR(20) NULL DEFAULT ,
    [ModifyDateTime] DATETIME NULL DEFAULT 
);
GO

