CREATE TABLE [dbo].[RCV_ASN] (
    [RCV_ORD_NO] VARCHAR(20) NOT NULL DEFAULT ,
    [PACK_ID] VARCHAR(20) NOT NULL DEFAULT ,
    [RCV_TYPE] VARCHAR(1) NOT NULL DEFAULT ,
    [ITM_CD] VARCHAR(20) NOT NULL DEFAULT ,
    [ITM_NM] VARCHAR(100) NOT NULL DEFAULT ,
    [ITM_QTY] NUMERIC(20,5) NULL DEFAULT ,
    [STATUS] VARCHAR(2) NOT NULL DEFAULT ,
    [CRT_DT] DATETIME NOT NULL DEFAULT (getdate()),
    CONSTRAINT [PK_RCV_ASN] PRIMARY KEY CLUSTERED ([RCV_ORD_NO], [PACK_ID])
);
GO

