CREATE TABLE [dbo].[RefreshTokens] (
    [Id] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [UserId] NVARCHAR(450) NOT NULL DEFAULT ,
    [Token] NVARCHAR(MAX) NOT NULL DEFAULT ,
    [JwtId] NVARCHAR(MAX) NOT NULL DEFAULT ,
    [IsUsed] BIT NOT NULL DEFAULT ,
    [IsRevoked] BIT NOT NULL DEFAULT ,
    [AddedDate] DATETIME2 NOT NULL DEFAULT ,
    [ExpiryDate] DATETIME2 NOT NULL DEFAULT 
);
GO

