CREATE TABLE [dbo].[RoleClaims] (
    [Id] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [RoleId] UNIQUEIDENTIFIER NOT NULL DEFAULT ,
    [ClaimType] NVARCHAR(MAX) NULL DEFAULT ,
    [ClaimValue] NVARCHAR(MAX) NULL DEFAULT 
);
GO

