CREATE TABLE [dbo].[SIZE_UNIT] (
    [SIZE] VARCHAR(20) NOT NULL DEFAULT ,
    [FARAD] FLOAT NOT NULL DEFAULT ,
    [WIDTH] FLOAT NOT NULL DEFAULT ,
    [KIND] VARCHAR(20) NOT NULL DEFAULT ,
    [PLUS] INT NULL DEFAULT ,
    [MINUS] INT NULL DEFAULT ,
    [비고] VARCHAR(200) NULL DEFAULT ,
    [VNT_PLAN_QTY] INT NULL DEFAULT ,
    [VVT_PLAN_QTY] INT NULL DEFAULT ,
    CONSTRAINT [PK_SIZE_UNIT] PRIMARY KEY CLUSTERED ([SIZE], [FARAD], [WIDTH], [KIND])
);
GO

