CREATE TABLE [dbo].[SpecialSparePartINFO] (
    [PartID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [MachineID] VARCHAR(50) NULL DEFAULT ,
    [SparePartName] NVARCHAR(100) NULL DEFAULT ,
    [QtyUsing] INT NULL DEFAULT ,
    [QtyPerLot] INT NULL DEFAULT ,
    [NumberLot] NVARCHAR(100) NULL DEFAULT ,
    [CycleReplace] NVARCHAR(50) NULL DEFAULT 
);
GO

