CREATE TABLE [dbo].[STB_TEST01] (
    [CodeLine] VARCHAR(50) NULL DEFAULT ,
    [NameLine] VARCHAR(50) NULL DEFAULT ,
    [LineDesc] VARCHAR(100) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT 
);
GO

