CREATE TABLE [dbo].[STB_ESD_REQUIREMENT_SETTING] (
    [EsdRequirementSettingCode] VARCHAR(50) NOT NULL DEFAULT ,
    [Requirement] NVARCHAR(50) NOT NULL DEFAULT ,
    [ESD_Limit] NVARCHAR(50) NULL DEFAULT ,
    [Frequency] NVARCHAR(50) NULL DEFAULT ,
    [TestMethod] NVARCHAR(50) NULL DEFAULT ,
    [CreateUserId] VARCHAR(20) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT 
);
GO

