CREATE TABLE [dbo].[STB_SCRAPHISTORY] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [LOTNO] VARCHAR(50) NULL DEFAULT ,
    [BASICDATE] DATE NULL DEFAULT ,
    [STATUSSCRAP] VARCHAR(50) NULL DEFAULT ,
    [QUANTITY] NUMERIC(18,0) NULL DEFAULT ,
    [REASON] VARCHAR(200) NULL DEFAULT ,
    [DESCRIPTION] VARCHAR(200) NULL DEFAULT ,
    [CREATEDATETIME] DATETIME NULL DEFAULT ,
    [CREATEUSERID] VARCHAR(50) NULL DEFAULT ,
    [CHANGEDATETIME] DATETIME NULL DEFAULT ,
    [CHANGEUSERID] VARCHAR(50) NULL DEFAULT ,
    [LINECODE] VARCHAR(50) NULL DEFAULT 
);
GO

