CREATE TABLE [dbo].[STB_ElectrodeCommon] (
    [ProdCode] VARCHAR(20) NOT NULL DEFAULT ,
    [LivingSubstance] VARCHAR(50) NULL DEFAULT ,
    [MixRatio] NUMERIC(20,5) NULL DEFAULT ,
    [TankVolume] NUMERIC(20,5) NULL DEFAULT ,
    [ElectrodeType] VARCHAR(20) NULL DEFAULT ,
    [MeasureViscosity] NUMERIC(20,5) NULL DEFAULT ,
    [Remark] VARCHAR(1000) NULL DEFAULT ,
    [OneSide] NUMERIC(20,5) NULL DEFAULT ,
    [BothSide] NUMERIC(20,5) NULL DEFAULT ,
    [RollingDensityMin] NUMERIC(20,5) NULL DEFAULT ,
    [RollingDensityMax] NUMERIC(20,5) NULL DEFAULT ,
    [ViscosityMin] NUMERIC(20,5) NULL DEFAULT ,
    [ViscosityMax] NUMERIC(20,5) NULL DEFAULT ,
    [UnwndngStdMin] NUMERIC(20,5) NULL DEFAULT ,
    [UnwndngStdMax] NUMERIC(20,5) NULL DEFAULT ,
    [UnwndngMeasureValue] NUMERIC(20,5) NULL DEFAULT ,
    [RwndngStdMin] NUMERIC(20,5) NULL DEFAULT ,
    [RwndngStdMax] NUMERIC(20,5) NULL DEFAULT ,
    [RwndngMeasureValue] NUMERIC(20,5) NULL DEFAULT ,
    [ProdConLinePressure] NUMERIC(20,5) NULL DEFAULT ,
    [ProdConTemp] NUMERIC(20,5) NULL DEFAULT ,
    [ProdConSpeed] NUMERIC(20,5) NULL DEFAULT ,
    [ProdConThickStdMin] NUMERIC(20,5) NULL DEFAULT ,
    [ProdConThickStdMax] NUMERIC(20,5) NULL DEFAULT ,
    [CoolingWaterStdMin] NUMERIC(20,5) NULL DEFAULT ,
    [CoolingWaterStdMax] NUMERIC(20,5) NULL DEFAULT ,
    [LeftHeadGap] VARCHAR(20) NULL DEFAULT ,
    [RightHeadGap] VARCHAR(20) NULL DEFAULT ,
    [AlFoilWidth] NUMERIC(20,5) NULL DEFAULT ,
    [CoatingWidth] NUMERIC(20,5) NULL DEFAULT ,
    [OneSideSpeed] NUMERIC(20,5) NULL DEFAULT ,
    [BothSideSpeed] NUMERIC(20,5) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT (getdate()),
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT ,
    [OneSideUpperTolerance] NUMERIC(20,5) NULL DEFAULT ,
    [OneSideLowerTolerance] NUMERIC(20,5) NULL DEFAULT ,
    [BothSideUpperTolerance] NUMERIC(20,5) NULL DEFAULT ,
    [BothSideLowerTolerance] NUMERIC(20,5) NULL DEFAULT ,
    [ProdConTempUpperTolerance] NUMERIC(20,5) NULL DEFAULT ,
    [ProdConTempLowerTolerance] NUMERIC(20,5) NULL DEFAULT ,
    [ProdConSpeedUpperTolerance] NUMERIC(20,5) NULL DEFAULT ,
    [ProdConSpeedLowerTolerance] NUMERIC(20,5) NULL DEFAULT ,
    [Batches] INT NULL DEFAULT 
);
GO

