CREATE TABLE [dbo].[STB_MachineBasicInfo] (
    [MachineCode] VARCHAR(20) NOT NULL DEFAULT ,
    [MachineManagementNo] VARCHAR(30) NULL DEFAULT ,
    [OriginalMachineName] NVARCHAR(100) NULL DEFAULT ,
    [MakerName] NVARCHAR(100) NULL DEFAULT ,
    [ProductionDate] DATE NULL DEFAULT ,
    [MachineSerialNo] VARCHAR(30) NULL DEFAULT ,
    [BuyVendorName] NVARCHAR(100) NULL DEFAULT ,
    [InstallDate] DATE NULL DEFAULT ,
    [BuyPrice] NVARCHAR(50) NULL DEFAULT ,
    [ASVendorName] NVARCHAR(100) NULL DEFAULT ,
    [ASVendorPhone] NVARCHAR(100) NULL DEFAULT ,
    [ASPersonName] NVARCHAR(100) NULL DEFAULT ,
    [ASPersonPhone] NVARCHAR(100) NULL DEFAULT ,
    [MachineImage] BIGINT NULL DEFAULT ,
    [MachineExtText01] NVARCHAR(MAX) NULL DEFAULT ,
    [MachineExtText02] NVARCHAR(MAX) NULL DEFAULT ,
    [MachineExtText03] NVARCHAR(MAX) NULL DEFAULT ,
    [MachineExtText04] NVARCHAR(MAX) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT ,
    [IsIdle] BIT NULL DEFAULT ,
    [IdleDate] DATE NULL DEFAULT ,
    [IsDisposal] BIT NULL DEFAULT ,
    [DisposalDate] DATE NULL DEFAULT ,
    [IsVietnamShipment] BIT NULL DEFAULT ,
    [VietnamShipmentDate] DATE NULL DEFAULT ,
    [ModelSpec] NVARCHAR(MAX) NULL DEFAULT ,
    [MachinetSize] NVARCHAR(MAX) NULL DEFAULT ,
    [MachineWeight] NVARCHAR(100) NULL DEFAULT ,
    [MachinePower] NVARCHAR(100) NULL DEFAULT ,
    [VendorContact] VARCHAR(50) NULL DEFAULT ,
    [Remark] NVARCHAR(MAX) NULL DEFAULT ,
    [MachineStatusCode] VARCHAR(20) NULL DEFAULT ,
    [MachineStatusChangeDate] DATE NULL DEFAULT 
);
GO

