CREATE TABLE [dbo].[STB_TypeWaste] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [NameTypeWaste] NVARCHAR(50) NULL DEFAULT ,
    [IsUse] BIT NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(50) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(50) NULL DEFAULT 
);
GO

