CREATE TABLE [dbo].[STB_VN_FINISHGOODS_HN_Export] (
    [CodeExport] VARCHAR(50) NOT NULL DEFAULT ,
    [LotNo] VARCHAR(50) NULL DEFAULT ,
    [PackingID] VARCHAR(50) NULL DEFAULT ,
    [PackingID_Divide] VARCHAR(50) NULL DEFAULT ,
    [Qty] NUMERIC(20,5) NULL DEFAULT ,
    [Country] NVARCHAR(50) NULL DEFAULT ,
    [SoPhieuXuatKho] VARCHAR(50) NULL DEFAULT ,
    [SoInVoice] VARCHAR(50) NULL DEFAULT ,
    [SoToKhaiHaiQuan] VARCHAR(50) NULL DEFAULT ,
    [TypeExport] VARCHAR(50) NULL DEFAULT ,
    [TRANSPORT] VARCHAR(50) NULL DEFAULT ,
    [CustomerName] NVARCHAR(50) NULL DEFAULT ,
    [LevelOut] VARCHAR(10) NULL DEFAULT ,
    [DateRequestExport] DATETIME NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(50) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(50) NULL DEFAULT ,
    [StatusExport] NVARCHAR(50) NULL DEFAULT ,
    [Evaluation] INT NULL DEFAULT ((0))
);
GO

