CREATE TABLE [dbo].[STB_VN_SCRAPLOT] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [CODESCRAPLOT] NVARCHAR(100) NULL DEFAULT ,
    [LOTNO] NVARCHAR(50) NULL DEFAULT ,
    [NVLTPBTP] NVARCHAR(50) NULL DEFAULT ,
    [MODEL] NVARCHAR(50) NULL DEFAULT ,
    [PRODUCTIONNAME] NVARCHAR(100) NULL DEFAULT ,
    [UNIT] NVARCHAR(20) NULL DEFAULT ,
    [QtyActual] INT NULL DEFAULT ,
    [QtyMove] INT NULL DEFAULT ,
    [StausWait] NVARCHAR(50) NULL DEFAULT ,
    [StatusCancel] NVARCHAR(50) NULL DEFAULT ,
    [ReasonCancel] NVARCHAR(500) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] NVARCHAR(50) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] NVARCHAR(50) NULL DEFAULT 
);
GO

