CREATE TABLE [dbo].[STB_XRFInspectionInfo] (
    [InspectionNo] BIGINT IDENTITY(1,1) NOT NULL DEFAULT ,
    [MachineID] VARCHAR(20) NULL DEFAULT ,
    [LotNo] VARCHAR(20) NULL DEFAULT ,
    [Barcode] VARCHAR(50) NULL DEFAULT ,
    [Idx] NUMERIC(20,5) NULL DEFAULT ,
    [RunTime] NUMERIC(20,5) NULL DEFAULT ,
    [Detector] VARCHAR(20) NULL DEFAULT ,
    [Result1] NUMERIC(20,5) NULL DEFAULT ,
    [Result2] NUMERIC(20,5) NULL DEFAULT ,
    [Result3] NUMERIC(20,5) NULL DEFAULT ,
    [LogDateTime] DATETIME NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT (getdate())
);
GO

