CREATE TABLE [dbo].[STB_MrpMaster] (
    [MrpNo] VARCHAR(20) NOT NULL DEFAULT ,
    [CompanyCode] VARCHAR(20) NULL DEFAULT ,
    [WorkCenterCode] VARCHAR(20) NULL DEFAULT ,
    [BasicDate] DATE NULL DEFAULT ,
    [MrpDesc] NVARCHAR(200) NULL DEFAULT ,
    [IsUseMrpProdDate] BIT NULL DEFAULT ,
    [MrpProdDate] DATE NULL DEFAULT ,
    [IsRunMrp] BIT NULL DEFAULT ,
    [MrpRunDateTime] DATETIME NULL DEFAULT ,
    [MrpRunUserID] VARCHAR(20) NULL DEFAULT ,
    [IsFixedMRP] BIT NULL DEFAULT ,
    [IsCancel] BIT NULL DEFAULT ,
    [MrpFixDateTime] DATETIME NULL DEFAULT ,
    [MrpFixUserID] VARCHAR(20) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT 
);
GO

