CREATE TABLE [dbo].[STB_WorkTimeInfo] (
    [YM] NVARCHAR(6) NOT NULL DEFAULT ,
    [CD_BIZAREA] NVARCHAR(7) NOT NULL DEFAULT ,
    [CD_DEPT] NVARCHAR(12) NOT NULL DEFAULT ,
    [NO_EMP] NVARCHAR(10) NOT NULL DEFAULT ,
    [TM_01] NUMERIC(20,5) NULL DEFAULT ,
    [TM_02] NUMERIC(20,5) NULL DEFAULT ,
    [TM_03] NUMERIC(20,5) NULL DEFAULT ,
    [TM_04] NUMERIC(20,5) NULL DEFAULT ,
    [TM_05] NUMERIC(20,5) NULL DEFAULT 
);
GO

