CREATE TABLE [dbo].[STB_MaterialBarcodeHist] (
    [MaterialBarcodeNo] VARCHAR(20) NOT NULL DEFAULT ,
    [MaterialDocDetailNo] VARCHAR(20) NOT NULL DEFAULT ,
    [BarcodeText] VARCHAR(100) NULL DEFAULT ,
    [LotNo] VARCHAR(20) NULL DEFAULT ,
    [LotQty] NUMERIC(20,5) NULL DEFAULT ,
    [LotAttr01] NVARCHAR(100) NULL DEFAULT ,
    [LotAttr02] NVARCHAR(100) NULL DEFAULT ,
    [LotAttr03] NVARCHAR(100) NULL DEFAULT ,
    [LotAttr04] NVARCHAR(100) NULL DEFAULT ,
    [LotAttr05] NVARCHAR(100) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT (getdate()),
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT 
);
GO

