CREATE TABLE [dbo].[STB_VVT_SortingErrorData] (
    [SortingID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [SortingDate] DATE NOT NULL DEFAULT ,
    [Shift] VARCHAR(5) NULL DEFAULT ,
    [PersonName] NVARCHAR(100) NULL DEFAULT ,
    [VendorCode] VARCHAR(50) NULL DEFAULT ,
    [FactoryName] NVARCHAR(100) NULL DEFAULT ,
    [MaterialCode] VARCHAR(50) NULL DEFAULT ,
    [LotNo] VARCHAR(100) NULL DEFAULT ,
    [MaterialType] VARCHAR(20) NOT NULL DEFAULT ,
    [QtyCheck] INT NULL DEFAULT ((0)),
    [QtyOK] INT NULL DEFAULT ((0)),
    [Remark] NVARCHAR(200) NULL DEFAULT ,
    [ALBuiDust] INT NULL DEFAULT ,
    [ALMoDent] INT NULL DEFAULT ,
    [ALMepDeform] INT NULL DEFAULT ,
    [ALXuocScratch] INT NULL DEFAULT ,
    [ALBongNBPlating] INT NULL DEFAULT ,
    [ALSanRoughFace] INT NULL DEFAULT ,
    [ALBanDirty] INT NULL DEFAULT ,
    [ALBanBoDentGroup] INT NULL DEFAULT ,
    [ALBienSacDiscolor] INT NULL DEFAULT ,
    [ALLoiKhacOther] INT NULL DEFAULT ,
    [PLBuuNhom] INT NULL DEFAULT ,
    [PLBuuNhua] INT NULL DEFAULT ,
    [PLBuuRandom] INT NULL DEFAULT ,
    [PLBongTamNhieu] INT NULL DEFAULT ,
    [PLXuocScratch] INT NULL DEFAULT ,
    [PLBienDangDeform] INT NULL DEFAULT ,
    [PLMoDongExposed] INT NULL DEFAULT ,
    [PLBienDangCamSu] INT NULL DEFAULT ,
    [PLNutGoCrackWood] INT NULL DEFAULT ,
    [PLBienSacDiscolor] INT NULL DEFAULT ,
    [PLOther] INT NULL DEFAULT ,
    [CreateDateTime] DATETIME NOT NULL DEFAULT (getdate()),
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT 
);
GO

