CREATE TABLE [dbo].[STB_NOBOOK] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [MothDate] NVARCHAR(50) NULL DEFAULT ,
    [Stage] NVARCHAR(50) NULL DEFAULT ,
    [Code] NVARCHAR(50) NULL DEFAULT ,
    [ProductionName] NVARCHAR(100) NULL DEFAULT ,
    [Unit] NVARCHAR(10) NULL DEFAULT ,
    [Qty] INT NULL DEFAULT ,
    [QtyOut] INT NULL DEFAULT ,
    [StatusIn] NVARCHAR(50) NULL DEFAULT ('1'),
    [StatusOut] NVARCHAR(50) NULL DEFAULT ,
    [TotalInventory] INT NULL DEFAULT ,
    [DATEOUT] DATETIME NULL DEFAULT ,
    [Remark] NVARCHAR(500) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] NVARCHAR(50) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] NVARCHAR(50) NULL DEFAULT 
);
GO

