CREATE TABLE [dbo].[STB_VN_InventoryFirst_History] (
    [IFH] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [IDIF] INT NULL DEFAULT ,
    [CLASSIFY] NVARCHAR(50) NULL DEFAULT ,
    [STAGE] NVARCHAR(50) NULL DEFAULT ,
    [STAGENAME] NVARCHAR(50) NULL DEFAULT ,
    [MODEL] NVARCHAR(50) NULL DEFAULT ,
    [PRODUCTIONNAME] NVARCHAR(50) NULL DEFAULT ,
    [UNIT] NVARCHAR(20) NULL DEFAULT ,
    [STATUSS] NVARCHAR(50) NULL DEFAULT ,
    [LOCATIONS] NVARCHAR(50) NULL DEFAULT ,
    [QTYONPAGER] FLOAT NULL DEFAULT ,
    [ACTUALLYQTY] FLOAT NULL DEFAULT ,
    [DESCRIPTIONS] NVARCHAR(500) NULL DEFAULT ,
    [DateInput] DATETIME NULL DEFAULT ,
    [NamType] NVARCHAR(20) NULL DEFAULT ,
    [TYPEACTIONS] NVARCHAR(20) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] NVARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] NVARCHAR(20) NULL DEFAULT ,
    [CreateDateActions] DATETIME NULL DEFAULT 
);
GO

