CREATE TABLE [dbo].[STB_VN_USER_FINISHGOOD] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [USERID] NVARCHAR(50) NULL DEFAULT ,
    [PASSWORDS] NVARCHAR(100) NULL DEFAULT ,
    [FULLNAME] NVARCHAR(100) NULL DEFAULT ,
    [IsUse] BIT NULL DEFAULT ,
    [IDPermission] INT NULL DEFAULT ,
    [CODECOMPANY] NVARCHAR(50) NULL DEFAULT 
);
GO

