CREATE TABLE [dbo].[stb_DetailAgaingHN] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [LOTNO] NVARCHAR(30) NULL DEFAULT ,
    [NOITEMS] NVARCHAR(30) NULL DEFAULT ,
    [RESULT] NVARCHAR(30) NULL DEFAULT ,
    [CAPUF] NVARCHAR(30) NULL DEFAULT ,
    [LCUA] NVARCHAR(30) NULL DEFAULT ,
    [DFPHANTRAM] NVARCHAR(30) NULL DEFAULT ,
    [ESRM] NVARCHAR(30) NULL DEFAULT ,
    [TIMEC] NVARCHAR(50) NULL DEFAULT ,
    [LINES] NVARCHAR(30) NULL DEFAULT ,
    [COMPUTER] NVARCHAR(50) NULL DEFAULT ,
    [CREATEDATE] DATETIME NULL DEFAULT 
);
GO

