CREATE TABLE [dbo].[STB_VN_QC_LOTNO_MODULE_DETAIL] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [LOTNO] NVARCHAR(50) NULL DEFAULT ,
    [NAMETYPE] NVARCHAR(10) NULL DEFAULT ,
    [NUMBERTYPE] INT NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] NVARCHAR(50) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] NVARCHAR(50) NULL DEFAULT ,
    [STATUSPSS] NVARCHAR(20) NULL DEFAULT 
);
GO

