CREATE TABLE [dbo].[STB_SanminaIndiaLabelPrintHist] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [SupplierName] VARCHAR(50) NULL DEFAULT ,
    [SanminaPartNumber] VARCHAR(50) NULL DEFAULT ,
    [PartDesc] NVARCHAR(100) NULL DEFAULT ,
    [MFR] VARCHAR(50) NULL DEFAULT ,
    [MPN] VARCHAR(50) NULL DEFAULT ,
    [Quantity] VARCHAR(10) NULL DEFAULT ,
    [PONumber] VARCHAR(50) NULL DEFAULT ,
    [LotNo] VARCHAR(50) NULL DEFAULT ,
    [LotCode] VARCHAR(6) NULL DEFAULT ,
    [PackingDate] VARCHAR(6) NULL DEFAULT ,
    [InspEmpID] VARCHAR(10) NULL DEFAULT ,
    [InspEmpName] NVARCHAR(100) NULL DEFAULT ,
    [CartonBoxNo] VARCHAR(10) NULL DEFAULT ,
    [PrintTime] DATETIME NULL DEFAULT ,
    [PrintUserID] VARCHAR(30) NULL DEFAULT 
);
GO

