CREATE TABLE [dbo].[STB_VN_SHIPCUSTOMER] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [PUBLICCODE] NVARCHAR(50) NULL DEFAULT ,
    [PARTNO] NVARCHAR(50) NULL DEFAULT ,
    [SIZE] NVARCHAR(50) NULL DEFAULT ,
    [QUANITY] INT NULL DEFAULT ,
    [CUSTOMER] NVARCHAR(100) NULL DEFAULT ,
    [QTYACTUALLSHIP] INT NULL DEFAULT ,
    [SHIPDATE] DATETIME NULL DEFAULT ,
    [PRODUCTIONSCHEDULE] DATETIME NULL DEFAULT ,
    [OUTINSPECTIONSTATUS] NVARCHAR(50) NULL DEFAULT ,
    [STATUSSHIP] NVARCHAR(50) NULL DEFAULT ,
    [REMARK] NVARCHAR(500) NULL DEFAULT ,
    [CREATEDATETIME] DATETIME NULL DEFAULT ,
    [CREATEUSERID] NVARCHAR(50) NULL DEFAULT ,
    [CHANGEUSERID] NVARCHAR(50) NULL DEFAULT 
);
GO

