CREATE TABLE [dbo].[STB_TYPE_COMPUTER] (
    [IDTC] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [NameTypes] NVARCHAR(50) NULL DEFAULT ,
    [CreateBy] NVARCHAR(50) NULL DEFAULT ,
    [CreateDate] DATETIME NULL DEFAULT ,
    [Descptions] NVARCHAR(500) NULL DEFAULT 
);
GO

