CREATE TABLE [dbo].[STB_PLAN_VN] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [DATEPLAN] DATETIME NULL DEFAULT ,
    [MONTHPLAN] NVARCHAR(50) NULL DEFAULT ,
    [MODEL] NVARCHAR(50) NULL DEFAULT ,
    [GROUPSIZE] NVARCHAR(50) NULL DEFAULT ,
    [DAILYTARGET] NVARCHAR(50) NULL DEFAULT ,
    [REMARK] NVARCHAR(MAX) NULL DEFAULT ,
    [TYPEDATA] NVARCHAR(50) NULL DEFAULT ,
    [ISUSED] BIT NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] NVARCHAR(50) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] NVARCHAR(50) NULL DEFAULT ,
    [CompanyCode] NVARCHAR(50) NULL DEFAULT ,
    [WorkCenterCode] NVARCHAR(50) NULL DEFAULT ,
    [DATEPLANS] DATETIME NULL DEFAULT 
);
GO

