CREATE TABLE [dbo].[STB_VN_SparePartLineUsage] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [SparePartCode] VARCHAR(30) NOT NULL DEFAULT ,
    [SparePartLotID] VARCHAR(50) NOT NULL DEFAULT ,
    [LineCode] VARCHAR(20) NULL DEFAULT ,
    [MachineCode] VARCHAR(20) NULL DEFAULT ,
    [StartDate] DATETIME NOT NULL DEFAULT ,
    [EndDate] DATETIME NULL DEFAULT ,
    [IsUsing] BIT NOT NULL DEFAULT ((1)),
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT (getdate()),
    [WorkCenterCode] VARCHAR(50) NULL DEFAULT 
);
GO

