CREATE TABLE [dbo].[STB_VN_STASTUS_PROCDUCTION_ERROR] (
    [IDSPE] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [CodeStatus] NVARCHAR(50) NULL DEFAULT ,
    [NameStatus] NVARCHAR(20) NULL DEFAULT ,
    [IsUsed] BIT NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] NVARCHAR(20) NULL DEFAULT 
);
GO

