CREATE TABLE [dbo].[STB_VN_STOREMACHINES] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [CODESTOREMACHINES] NVARCHAR(100) NULL DEFAULT ,
    [NAMESTORE] NVARCHAR(50) NULL DEFAULT ,
    [Locations] NVARCHAR(50) NULL DEFAULT ,
    [Descptions] NVARCHAR(50) NULL DEFAULT ,
    [IsUsed] BIT NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] NVARCHAR(50) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] NVARCHAR(50) NULL DEFAULT 
);
GO

