CREATE TABLE [dbo].[STB_QcDefectReportDeleteLog] (
    [DefectReportNo] VARCHAR(20) NOT NULL DEFAULT ,
    [DefectDivisionCode] VARCHAR(3) NULL DEFAULT ,
    [PublishDeptCode] VARCHAR(20) NULL DEFAULT ,
    [PublishEmpID] VARCHAR(20) NULL DEFAULT ,
    [ReceiveDeptCode] VARCHAR(20) NULL DEFAULT ,
    [OccurProcessCode] VARCHAR(3) NULL DEFAULT ,
    [MachineCode] VARCHAR(20) NULL DEFAULT ,
    [ProdWorkerCode] VARCHAR(20) NULL DEFAULT ,
    [JobDate] DATETIME NULL DEFAULT ,
    [LotNo] VARCHAR(20) NULL DEFAULT ,
    [MaterialCode] VARCHAR(20) NULL DEFAULT ,
    [MaterialName] VARCHAR(100) NULL DEFAULT ,
    [MaterialSpec] VARCHAR(20) NULL DEFAULT ,
    [LotNo2] VARCHAR(20) NULL DEFAULT ,
    [LotNo3] VARCHAR(20) NULL DEFAULT ,
    [LotNo4] VARCHAR(20) NULL DEFAULT ,
    [LotNo5] VARCHAR(20) NULL DEFAULT ,
    [DefectCode] VARCHAR(20) NULL DEFAULT ,
    [DefectImage] VARBINARY(MAX) NULL DEFAULT ,
    [DefectLotSize] INT NULL DEFAULT ,
    [DefectErrorCnt] INT NULL DEFAULT ,
    [DefectSampleCnt] INT NULL DEFAULT ,
    [LotLimitCnt] INT NULL DEFAULT ,
    [ActionContent] NVARCHAR(2000) NULL DEFAULT ,
    [ActionWorkerCode] VARCHAR(20) NULL DEFAULT ,
    [QcOpinionContent] NVARCHAR(2000) NULL DEFAULT ,
    [IsCustomerSendRequired] BIT NULL DEFAULT ,
    [ProdCauseContent] NVARCHAR(2000) NULL DEFAULT ,
    [ProdCauseImage] VARBINARY(MAX) NULL DEFAULT ,
    [ProdMeasuresContent] NVARCHAR(2000) NULL DEFAULT ,
    [ProdProcessContent] NVARCHAR(2000) NULL DEFAULT ,
    [ProdProcessResultCode] VARCHAR(3) NULL DEFAULT ,
    [LossCost] DECIMAL(10,2) NULL DEFAULT ,
    [ProdProcessContentAuthorUserName] NVARCHAR(100) NULL DEFAULT ,
    [ProdProcessContentCheckUserName] NVARCHAR(100) NULL DEFAULT ,
    [QcMeasuresContent] NVARCHAR(2000) NULL DEFAULT ,
    [QcFlwupCheckContent] NVARCHAR(2000) NULL DEFAULT ,
    [IsQcAsSatisfaction] BIT NULL DEFAULT ,
    [IsProdHeadConfirm] BIT NULL DEFAULT ,
    [ProdHeadComment] NVARCHAR(4000) NULL DEFAULT ,
    [IsQcHeadConfirm] BIT NULL DEFAULT ,
    [QcHeadComment] NVARCHAR(4000) NULL DEFAULT ,
    [CreateDateTime] DATETIME NOT NULL DEFAULT ,
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT ,
    [ProdProcessResultFile] BIGINT NULL DEFAULT ,
    [ApprovalStepID] INT NULL DEFAULT 
);
GO

