CREATE TABLE [dbo].[STB_Vvt_SdProds_new] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [LotNo] VARCHAR(50) NULL DEFAULT ,
    [FileName] VARCHAR(50) NULL DEFAULT ,
    [CH] VARCHAR(20) NULL DEFAULT ,
    [OCV] FLOAT NULL DEFAULT ,
    [OCV등급] FLOAT NULL DEFAULT ,
    [충전V] FLOAT NULL DEFAULT ,
    [충전I] FLOAT NULL DEFAULT ,
    [방전V] FLOAT NULL DEFAULT ,
    [방전I] FLOAT NULL DEFAULT ,
    [방전용량] FLOAT NULL DEFAULT ,
    [방전용량등급] FLOAT NULL DEFAULT ,
    [DCR] FLOAT NULL DEFAULT ,
    [DCR등급] FLOAT NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT 
);
GO

