CREATE TABLE [dbo].[STB_VN_SpecialSparePartIOHist] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [SparePartLotID] VARCHAR(30) NULL DEFAULT ,
    [SparePartCode] VARCHAR(30) NULL DEFAULT ,
    [IOType] VARCHAR(10) NULL DEFAULT ,
    [IOQty] INT NULL DEFAULT ,
    [WorkCenterCode] VARCHAR(20) NULL DEFAULT ,
    [SPWarehouseCode] VARCHAR(20) NULL DEFAULT ,
    [LineCode] VARCHAR(20) NULL DEFAULT ,
    [MachineCode] VARCHAR(20) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(30) NULL DEFAULT 
);
GO

