CREATE TABLE [dbo].[STB_SystemSms] (
    [SystemSmsNo] BIGINT IDENTITY(1,1) NOT NULL DEFAULT ,
    [MobileNoList] VARCHAR(MAX) NOT NULL DEFAULT ,
    [MsgType] VARCHAR(10) NULL DEFAULT ,
    [Msg] NVARCHAR(MAX) NULL DEFAULT ,
    [SmsSendUrl] VARCHAR(500) NULL DEFAULT ,
    [TransferDateTime] DATETIME NULL DEFAULT ,
    [CreateDateTime] DATETIME NOT NULL DEFAULT (getdate()),
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT ,
    [IsSend] BIT NULL DEFAULT (CONVERT([bit],(0),0))
);
GO

