CREATE TABLE [dbo].[STB_ESRDataBackup6Line] (
    [ID] BIGINT NOT NULL DEFAULT ,
    [LINE_NUM] INT NOT NULL DEFAULT ,
    [INSPECTION_DATE] DATETIME NOT NULL DEFAULT ,
    [ESR_VALUE] VARCHAR(100) NULL DEFAULT ,
    [LSL] NUMERIC(20,5) NULL DEFAULT ,
    [USL] NUMERIC(20,5) NULL DEFAULT ,
    [MaterialCode] VARCHAR(20) NULL DEFAULT 
);
GO

