CREATE TABLE [dbo].[STB_RawMaterialInputHist] (
    [RawMaterialInputHistNo] VARCHAR(20) NOT NULL DEFAULT ,
    [Barcode] VARCHAR(20) NOT NULL DEFAULT ,
    [ProductGroupCode] VARCHAR(100) NULL DEFAULT ,
    [RawMaterialBarcode] VARCHAR(200) NULL DEFAULT ,
    [CreateDateTime] DATETIME NOT NULL DEFAULT (getdate()),
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT ,
    [LotMaterialCode] VARCHAR(200) NULL DEFAULT ,
    [ActualRate] NUMERIC(20,10) NULL DEFAULT ,
    [MaterialCode] VARCHAR(50) NULL DEFAULT ,
    [Qty] DECIMAL(18,4) NULL DEFAULT ,
    [MaterialLotNo] VARCHAR(50) NULL DEFAULT ,
    [MaterialWarehouseInOutHistNo] VARCHAR(20) NULL DEFAULT ,
    [RouteCode] VARCHAR(20) NULL DEFAULT ,
    [MachineCode] VARCHAR(20) NULL DEFAULT ,
    [Unit] VARCHAR(20) NULL DEFAULT ,
    [Status] VARCHAR(10) NOT NULL DEFAULT ('ACTIVE'),
    [IsBomItem] VARCHAR(1) NOT NULL DEFAULT ('Y'),
    [InputGroupId] VARCHAR(36) NULL DEFAULT ,
    [InputType] VARCHAR(10) NULL DEFAULT ('MES'),
    [WarehouseCode] VARCHAR(20) NULL DEFAULT ,
    [InputReasonCode] VARCHAR(50) NULL DEFAULT ,
    [Source] VARCHAR(10) NOT NULL DEFAULT ('MES'),
    [Remark] NVARCHAR(MAX) NULL DEFAULT ,
    [MEADefectDivCode] VARCHAR(20) NULL DEFAULT ,
    [WorkerCode] VARCHAR(20) NULL DEFAULT 
);
GO

