CREATE TABLE [dbo].[STB_VN_STAMP_MODULE] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [MaterialCode] NVARCHAR(50) NULL DEFAULT ,
    [MaterialName] NVARCHAR(50) NULL DEFAULT ,
    [Barcode] NVARCHAR(100) NULL DEFAULT ,
    [LabelQty] INT NULL DEFAULT ,
    [LotQty] NVARCHAR(50) NULL DEFAULT ,
    [Voltage] NVARCHAR(20) NULL DEFAULT ,
    [Farad] NVARCHAR(20) NULL DEFAULT ,
    [Rating] NVARCHAR(50) NULL DEFAULT ,
    [PartNo] NVARCHAR(100) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] NVARCHAR(50) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] NVARCHAR(50) NULL DEFAULT 
);
GO

