CREATE TABLE [dbo].[STB_VN_KPIMACHINES] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [CODEKPIM] NVARCHAR(50) NULL DEFAULT ,
    [MACHINESNAME] NVARCHAR(50) NULL DEFAULT ,
    [LINENAME] NVARCHAR(50) NULL DEFAULT ,
    [DATEACTION] DATETIME NULL DEFAULT ,
    [OPERATIONTIME] INT NULL DEFAULT ,
    [TACKTIME] INT NULL DEFAULT ,
    [QUANTITYTAGET] FLOAT NULL DEFAULT ,
    [QUANTITYACTUAL] FLOAT NULL DEFAULT ,
    [PRODUCTIONOK] INT NULL DEFAULT ,
    [PRODUCTIONNG] INT NULL DEFAULT ,
    [TYLEDITHANG] FLOAT NULL DEFAULT ,
    [RUNDOWN] FLOAT NULL DEFAULT ,
    [DOWNTIME] FLOAT NULL DEFAULT ,
    [RUNTIME] FLOAT NULL DEFAULT ,
    [LOSSTIME] FLOAT NULL DEFAULT ,
    [TYLEVANHANHTHIETBI] FLOAT NULL DEFAULT ,
    [HIEUSUATTINHNANG] FLOAT NULL DEFAULT ,
    [TYLEDATDUOCMUCTIEU] FLOAT NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] NVARCHAR(50) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] NVARCHAR(50) NULL DEFAULT 
);
GO

