CREATE TABLE [dbo].[STB_WipInfo] (
    [LotID] VARCHAR(20) NOT NULL DEFAULT ,
    [E22] INT NULL DEFAULT ,
    [E23] INT NULL DEFAULT ,
    [E24] INT NULL DEFAULT ,
    [E25] INT NULL DEFAULT ,
    [E26] INT NULL DEFAULT ,
    [E27] INT NULL DEFAULT ,
    [E99] INT NULL DEFAULT ,
    [E28] INT NULL DEFAULT ,
    [CreateDateTime] DATETIME NOT NULL DEFAULT ,
    [CreateUserID] VARCHAR(20) NOT NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT ,
    CONSTRAINT [PK_STB_WipInfo] PRIMARY KEY CLUSTERED ([LotID], [CreateDateTime], [CreateUserID])
);
GO

