CREATE TABLE [dbo].[STB_MaterialRouteMoveInfo] (
    [MaterialRouteMoveNo] VARCHAR(20) NOT NULL DEFAULT ,
    [CompanyCode] VARCHAR(20) NULL DEFAULT ,
    [WorkCenterCode] VARCHAR(20) NULL DEFAULT ,
    [MaterialWarehouseCode] VARCHAR(20) NULL DEFAULT ,
    [FacilityRouteCode] VARCHAR(20) NULL DEFAULT ,
    [RouteWarehouseCode] VARCHAR(20) NULL DEFAULT ,
    [MRMIMoveType] VARCHAR(20) NULL DEFAULT ,
    [RequestDateTime] DATETIME NULL DEFAULT ,
    [RequestUserID] VARCHAR(20) NULL DEFAULT ,
    [RequestGIDate] DATE NULL DEFAULT ,
    [RequestDesc] NVARCHAR(200) NULL DEFAULT ,
    [RequestFixDateTime] DATETIME NULL DEFAULT ,
    [RequestFixUserID] VARCHAR(20) NULL DEFAULT ,
    [IsRequestFix] BIT NULL DEFAULT ,
    [RequestApprovalDateTime] DATETIME NULL DEFAULT ,
    [RequestApprovalUserID] VARCHAR(20) NULL DEFAULT ,
    [IsRequestApproval] BIT NULL DEFAULT ,
    [IsAssingPicking] BIT NULL DEFAULT ,
    [PickingStartDateTime] DATETIME NULL DEFAULT ,
    [PickingEndDateTime] DATETIME NULL DEFAULT ,
    [PickingUserID] VARCHAR(20) NULL DEFAULT ,
    [IsPickingFix] BIT NULL DEFAULT ,
    [GIBasicDate] DATE NULL DEFAULT ,
    [GIProcessDateTime] DATETIME NULL DEFAULT ,
    [GIProcessUserID] VARCHAR(20) NULL DEFAULT ,
    [IsFinishGI] BIT NULL DEFAULT ,
    [ReceiptUserID] VARCHAR(20) NULL DEFAULT ,
    [ReceiptDateTime] DATETIME NULL DEFAULT ,
    [MRMIExtText01] NVARCHAR(MAX) NULL DEFAULT ,
    [MRMIExtText02] NVARCHAR(MAX) NULL DEFAULT ,
    [MRMIExtText03] NVARCHAR(MAX) NULL DEFAULT ,
    [MRMIExtText04] NVARCHAR(MAX) NULL DEFAULT ,
    [MRMIExtText05] NVARCHAR(MAX) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT 
);
GO

