CREATE TABLE [dbo].[STB_MoldMoveType] (
    [MoldMoveTypeCode] VARCHAR(20) NOT NULL DEFAULT ,
    [MoldMoveTypeName] NVARCHAR(100) NULL DEFAULT ,
    [IsGR] VARCHAR(1) NULL DEFAULT ,
    [IsCheckWhenGR] VARCHAR(1) NULL DEFAULT ,
    [IsGI] VARCHAR(1) NULL DEFAULT ,
    [IsMove] VARCHAR(1) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT 
);
GO

