CREATE TABLE [dbo].[STB_BRAND_DEVICE] (
    [IDBD] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [NameBrand] NVARCHAR(50) NULL DEFAULT ,
    [CreateBy] NVARCHAR(50) NULL DEFAULT ,
    [CreateDate] DATETIME NULL DEFAULT ,
    [Descptions] NVARCHAR(500) NULL DEFAULT 
);
GO

