CREATE TABLE [dbo].[STB_LotChangeMaterialHistory] (
    [CPHNo] BIGINT IDENTITY(1,1) NOT NULL DEFAULT ,
    [ControlNo] VARCHAR(20) NULL DEFAULT ,
    [BefMaterialCode] VARCHAR(50) NULL DEFAULT ,
    [BefPONo] VARCHAR(20) NULL DEFAULT ,
    [BefDayPlanNo] VARCHAR(20) NULL DEFAULT ,
    [AftMaterialCode] VARCHAR(50) NULL DEFAULT ,
    [AftPONo] VARCHAR(20) NULL DEFAULT ,
    [AftDayPlanNo] VARCHAR(20) NULL DEFAULT ,
    [JobDate] DATE NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [OldBarcode] VARCHAR(20) NULL DEFAULT ,
    [NewBarcode] VARCHAR(20) NULL DEFAULT 
);
GO

