CREATE TABLE [dbo].[STB_ReliabilityTestManagementInfo] (
    [RTSampleNo] VARCHAR(20) NOT NULL DEFAULT ,
    [RTReceptionNo] VARCHAR(20) NULL DEFAULT ,
    [RTStatusCode] VARCHAR(10) NULL DEFAULT ('01'),
    [RTStatusDetail] VARCHAR(100) NULL DEFAULT ,
    [RTReceptionDate] DATETIME NULL DEFAULT ,
    [RTFinishDate] DATE NULL DEFAULT ,
    [TestName] VARCHAR(200) NULL DEFAULT ,
    [RTSampleInfo] VARCHAR(MAX) NULL DEFAULT ,
    [RTReportFile] VARBINARY(MAX) NULL DEFAULT ,
    [RTRemark] VARCHAR(MAX) NULL DEFAULT ,
    [RTFeedbackReport] VARCHAR(MAX) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT 
);
GO

