CREATE TABLE [dbo].[STB_VN_Employees] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [CODEDEPARTMENT] NVARCHAR(30) NULL DEFAULT ,
    [DEPARTMENTNAME] NVARCHAR(100) NULL DEFAULT ,
    [EMPLOYEESID] NVARCHAR(100) NULL DEFAULT ,
    [EMPLOYEESNAME] NVARCHAR(100) NULL DEFAULT ,
    [POSITTION] NVARCHAR(100) NULL DEFAULT ,
    [STATUSS] BIT NULL DEFAULT ,
    [SORT] INT NULL DEFAULT ,
    [CREATEDATE] DATETIME NULL DEFAULT ,
    [USERID] NVARCHAR(50) NULL DEFAULT ,
    [STATUSEMPLOYESS] BIT NULL DEFAULT ,
    [IDENTITYCARD] NVARCHAR(50) NULL DEFAULT ,
    [TELEPHONE] NVARCHAR(50) NULL DEFAULT ,
    [CODELINE] NVARCHAR(50) NULL DEFAULT ,
    [NAMELINE] NVARCHAR(50) NULL DEFAULT 
);
GO

