CREATE TABLE [dbo].[STB_MarkingLabelPrintHist] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [MenuCode] VARCHAR(10) NULL DEFAULT ,
    [LotNo1] VARCHAR(50) NULL DEFAULT ,
    [LotNo2] VARCHAR(50) NULL DEFAULT ,
    [LotNo3] VARCHAR(50) NULL DEFAULT ,
    [MarkingLetter] NVARCHAR(50) NULL DEFAULT ,
    [LabelQty] VARCHAR(5) NULL DEFAULT ,
    [PrintTime] DATETIME NULL DEFAULT ,
    [PrintUserID] VARCHAR(30) NULL DEFAULT ,
    [TypePrint] VARCHAR(30) NULL DEFAULT 
);
GO

