CREATE TABLE [dbo].[STB_VVT_ESR_MONITOR] (
    [CompanyCode] VARCHAR(10) NULL DEFAULT ,
    [COMPort] VARCHAR(10) NULL DEFAULT ,
    [machinecode] VARCHAR(30) NOT NULL DEFAULT ,
    [ip] VARCHAR(50) NULL DEFAULT ,
    [CellLine] VARCHAR(30) NULL DEFAULT ,
    [CreateDateTime] DATETIME NOT NULL DEFAULT 
);
GO

