CREATE TABLE [dbo].[STB_CommInspMeasureHist_audit] (
    [사업장] VARCHAR(255) NULL DEFAULT ,
    [LotNo] VARCHAR(50) NULL DEFAULT ,
    [품목코드] VARCHAR(50) NULL DEFAULT ,
    [품목명] VARCHAR(255) NULL DEFAULT ,
    [사이즈] VARCHAR(50) NULL DEFAULT ,
    [라인코드] VARCHAR(50) NULL DEFAULT ,
    [라인명] VARCHAR(255) NULL DEFAULT ,
    [점검항목명] VARCHAR(255) NULL DEFAULT ,
    [측정순번] INT NULL DEFAULT ,
    [LSL] FLOAT NULL DEFAULT ,
    [USL] FLOAT NULL DEFAULT ,
    [측정결과] FLOAT NULL DEFAULT ,
    [측정일시] DATETIME NULL DEFAULT ,
    [id] INT IDENTITY(1,1) NOT NULL DEFAULT 
);
GO

