CREATE TABLE [dbo].[STB_MasterAgaingDetails] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [IDCODE] NVARCHAR(50) NULL DEFAULT ,
    [DATAGAING] DATETIME NULL DEFAULT ,
    [MODEL] NVARCHAR(20) NULL DEFAULT ,
    [NAMEERROR] NVARCHAR(50) NULL DEFAULT ,
    [STANDAGAING] NVARCHAR(50) NULL DEFAULT ,
    [QTYINPUT] INT NULL DEFAULT ,
    [QTYOK] INT NULL DEFAULT ,
    [NGESR] INT NULL DEFAULT ,
    [NGLC] INT NULL DEFAULT ,
    [NGOTHER] INT NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] NVARCHAR(50) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] NVARCHAR(50) NULL DEFAULT ,
    [LOTNO] NVARCHAR(50) NULL DEFAULT 
);
GO

