CREATE TABLE [dbo].[STB_PACLabelPrintHistV1] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [LabelQty] VARCHAR(2) NULL DEFAULT ,
    [PO] VARCHAR(50) NULL DEFAULT ,
    [CustomerPN] VARCHAR(50) NULL DEFAULT ,
    [SupplierPN] VARCHAR(50) NULL DEFAULT ,
    [UnitQty] VARCHAR(50) NULL DEFAULT ,
    [DC] VARCHAR(50) NULL DEFAULT ,
    [LotNo] VARCHAR(50) NULL DEFAULT ,
    [CREATEUSERID] NVARCHAR(30) NULL DEFAULT ,
    [CREATEDATE] DATETIME NULL DEFAULT 
);
GO

