CREATE TABLE [dbo].[STB_hodl_situationVVT] (
    [id] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [type] VARCHAR(20) NOT NULL DEFAULT ,
    [decisiondate] DATETIME NOT NULL DEFAULT ,
    [modelcode] VARCHAR(30) NULL DEFAULT ,
    [modelname] VARCHAR(200) NULL DEFAULT ,
    [lotno] VARCHAR(30) NOT NULL DEFAULT ,
    [pic] VARCHAR(50) NULL DEFAULT ,
    [reason] NVARCHAR(MAX) NULL DEFAULT ,
    [location] VARCHAR(30) NULL DEFAULT ,
    [wip] NVARCHAR(MAX) NULL DEFAULT ,
    [packingid] VARCHAR(20) NULL DEFAULT ,
    [createdatetime] DATETIME NULL DEFAULT (getdate()),
    [createuserid] VARCHAR(20) NULL DEFAULT ,
    [line] VARCHAR(30) NULL DEFAULT ,
    [technical] VARCHAR(30) NULL DEFAULT ,
    [quantity] INT NULL DEFAULT ,
    [DeptIC] VARCHAR(30) NULL DEFAULT ,
    [Expecteddate] DATETIME NULL DEFAULT ,
    [Realdate] DATETIME NULL DEFAULT ,
    [DeptProcess] VARCHAR(30) NULL DEFAULT ,
    [Procedures] NVARCHAR(MAX) NULL DEFAULT ,
    [OkQty] INT NULL DEFAULT ,
    [NgQty] INT NULL DEFAULT ,
    [Other] NVARCHAR(MAX) NULL DEFAULT ,
    [Status] VARCHAR(30) NULL DEFAULT ,
    [HoldFileID] INT NULL DEFAULT 
);
GO

