CREATE TABLE [dbo].[STB_VN_NEW_PRINTER] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [Barcode] NVARCHAR(50) NULL DEFAULT ,
    [MaterialName] NVARCHAR(50) NULL DEFAULT ,
    [MaterialCode] NVARCHAR(30) NULL DEFAULT ,
    [LotQty] NVARCHAR(50) NULL DEFAULT ,
    [LabelQty] INT NULL DEFAULT ,
    [Voltage] NVARCHAR(30) NULL DEFAULT ,
    [Farad] NVARCHAR(30) NULL DEFAULT ,
    [Rating] NVARCHAR(30) NULL DEFAULT ,
    [PartNo] NVARCHAR(50) NULL DEFAULT ,
    [StatusPrinter] BIT NULL DEFAULT ,
    [Descptions] NVARCHAR(500) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT ,
    [PackingID] NVARCHAR(50) NULL DEFAULT ,
    [Line] NVARCHAR(50) NULL DEFAULT 
);
GO

