CREATE TABLE [dbo].[STB_UnitConversion] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [MaterialCode] VARCHAR(50) NULL DEFAULT ,
    [ConvertRate] NUMERIC(38,19) NULL DEFAULT ,
    [TargetUnit] VARCHAR(20) NULL DEFAULT ,
    [BaseUnit] VARCHAR(20) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(50) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(50) NULL DEFAULT 
);
GO

