CREATE TABLE [dbo].[STB_VN_InventoryFirst] (
    [IDIF] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [CLASSIFY] NVARCHAR(50) NULL DEFAULT ,
    [STAGE] NVARCHAR(50) NULL DEFAULT ,
    [STAGENAME] NVARCHAR(50) NULL DEFAULT ,
    [MODEL] NVARCHAR(50) NULL DEFAULT ,
    [PRODUCTIONNAME] NVARCHAR(50) NULL DEFAULT ,
    [UNIT] NVARCHAR(20) NULL DEFAULT ,
    [STATUSS] NVARCHAR(50) NULL DEFAULT ,
    [LOCATIONS] NVARCHAR(50) NULL DEFAULT ,
    [QTYONPAGER] FLOAT NULL DEFAULT ,
    [ACTUALLYQTY] FLOAT NULL DEFAULT ,
    [DateInput] DATE NULL DEFAULT ,
    [NAMETYPE] NVARCHAR(20) NULL DEFAULT ,
    [DESCRIPTIONS] NVARCHAR(500) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] NVARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] NVARCHAR(20) NULL DEFAULT 
);
GO

