CREATE TABLE [dbo].[STB_RawMaterialLineInputHist] (
    [MaterialWarehouseInOutHistNo] VARCHAR(20) NOT NULL DEFAULT ,
    [LotID] VARCHAR(500) NOT NULL DEFAULT ,
    [LineCode] VARCHAR(20) NOT NULL DEFAULT ,
    [InOutCode] VARCHAR(1) NOT NULL DEFAULT ,
    [Qty] NUMERIC(20,5) NULL DEFAULT ,
    [ModelCode] VARCHAR(20) NULL DEFAULT ,
    [CompanyCode] VARCHAR(20) NULL DEFAULT ,
    [WorkCenterCode] VARCHAR(20) NULL DEFAULT ,
    [WorkerCode] VARCHAR(20) NULL DEFAULT ,
    [CreateDateTime] DATETIME NOT NULL DEFAULT ,
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT 
);
GO

