CREATE TABLE [dbo].[STB_SlippingElectrode] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [CaLamViec] NVARCHAR(20) NULL DEFAULT ,
    [Model] NVARCHAR(50) NULL DEFAULT ,
    [LoaiDienCuc] NVARCHAR(50) NULL DEFAULT ,
    [Cell_Line] NVARCHAR(50) NULL DEFAULT ,
    [MayMai] NVARCHAR(50) NULL DEFAULT ,
    [LotNo] NVARCHAR(100) NULL DEFAULT ,
    [DienCuc] NVARCHAR(50) NULL DEFAULT ,
    [TieuChuanChieuDai] NVARCHAR(50) NULL DEFAULT ,
    [CaiDatChieuDai] NVARCHAR(50) NULL DEFAULT ,
    [CongNhan] NVARCHAR(100) NULL DEFAULT ,
    [QcPart] NVARCHAR(50) NULL DEFAULT ,
    [Khac] NVARCHAR(255) NULL DEFAULT ,
    [CreatedDate] DATETIME NULL DEFAULT (getdate())
);
GO

