CREATE TABLE [dbo].[STB_CustomerComplaintsRequestInfo] (
    [CustomerComplaintsRequestNo] VARCHAR(20) NOT NULL DEFAULT ,
    [ReceiptDate] DATE NULL DEFAULT ,
    [SubmissionDate] DATE NULL DEFAULT ,
    [AgencyCode] VARCHAR(20) NULL DEFAULT ,
    [CustomerName] NVARCHAR(100) NULL DEFAULT ,
    [SalesManagerID] VARCHAR(20) NULL DEFAULT ,
    [MaterialCode] VARCHAR(20) NULL DEFAULT ,
    [DeliveryDate] DATE NULL DEFAULT ,
    [DeliveryQty] NUMERIC(20,2) NULL DEFAULT ,
    [ComplaintContent] NVARCHAR(MAX) NULL DEFAULT ,
    [ComplaintImage] VARBINARY(MAX) NULL DEFAULT ,
    [UseConditionContent] NVARCHAR(MAX) NULL DEFAULT ,
    [MassSampleClassCode] VARCHAR(20) NULL DEFAULT ,
    [LotNo] VARCHAR(20) NULL DEFAULT ,
    [MarkingLetter] VARCHAR(20) NULL DEFAULT ,
    [ApplicationName] NVARCHAR(100) NULL DEFAULT ,
    [InputQty] NUMERIC(20,2) NULL DEFAULT ,
    [DefectQty] NUMERIC(20,2) NULL DEFAULT ,
    [IsCustomerComplaintsReport] BIT NULL DEFAULT ,
    [ProcessingRequestDate] DATE NULL DEFAULT ,
    [CustomerRequestContent] NVARCHAR(MAX) NULL DEFAULT ,
    [CustomerRequestImage] VARBINARY(MAX) NULL DEFAULT ,
    [SalesRequestContent] NVARCHAR(MAX) NULL DEFAULT ,
    [SalesRequestImage] VARBINARY(MAX) NULL DEFAULT ,
    [CreateDateTime] DATETIME NOT NULL DEFAULT (getdate()),
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT 
);
GO

