CREATE TABLE [dbo].[STB_BAD_LIST2] (
    [standardDate] VARCHAR(10) NOT NULL DEFAULT ,
    [BAD_KIND] VARCHAR(20) NOT NULL DEFAULT ,
    [Qty] INT NOT NULL DEFAULT ,
    [CreateDateTime] DATETIME NOT NULL DEFAULT ,
    CONSTRAINT [PK_STB_BAD_LIST2] PRIMARY KEY CLUSTERED ([standardDate], [BAD_KIND], [Qty])
);
GO

