CREATE TABLE [dbo].[STB_VN_BENDING_TAPPING_WORKCENTER] (
    [Id] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [MaterialCode] VARCHAR(255) NOT NULL DEFAULT ,
    [PartNo] VARCHAR(255) NULL DEFAULT ,
    [Model] VARCHAR(255) NULL DEFAULT ,
    [WorkCenterCode] VARCHAR(255) NULL DEFAULT ,
    [IsUsed] BIT NULL DEFAULT ,
    [CreatedBy] VARCHAR(50) NULL DEFAULT ,
    [CreateDate] DATETIME NULL DEFAULT ,
    [ModifiedBy] VARCHAR(50) NULL DEFAULT ,
    [ModifieDate] DATETIME NULL DEFAULT 
);
GO

