CREATE TABLE [dbo].[STB_VN_LOGINBNBG] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [USERID] NVARCHAR(50) NULL DEFAULT ,
    [PASSWORDS] NVARCHAR(50) NULL DEFAULT ,
    [GROUPID] NVARCHAR(50) NULL DEFAULT ,
    [FACTORYCODE] NVARCHAR(50) NULL DEFAULT ,
    [USERACTVIES] BIT NULL DEFAULT 
);
GO

