CREATE TABLE [dbo].[stb_SDParam] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [ModelNo] NVARCHAR(100) NULL DEFAULT ,
    [LotNo] NVARCHAR(100) NULL DEFAULT ,
    [Date] DATE NULL DEFAULT ,
    [Employee] NVARCHAR(100) NULL DEFAULT ,
    [ChargingVoltage] NVARCHAR(10) NULL DEFAULT ,
    [ChargingCurrent] NVARCHAR(10) NULL DEFAULT ,
    [ChargingTime] NVARCHAR(10) NULL DEFAULT ,
    [LeavingTime] NVARCHAR(10) NULL DEFAULT ,
    [V1Time] NVARCHAR(10) NULL DEFAULT ,
    [V2Time] NVARCHAR(10) NULL DEFAULT ,
    [V1LMT] NVARCHAR(10) NULL DEFAULT ,
    [DV_DT] NVARCHAR(10) NULL DEFAULT ,
    [CreateDate] DATETIME NULL DEFAULT ,
    [Attribute1] NVARCHAR(50) NULL DEFAULT ,
    [Attribute2] NVARCHAR(50) NULL DEFAULT ,
    [Attribute3] NVARCHAR(50) NULL DEFAULT ,
    [CodeParam] NVARCHAR(20) NULL DEFAULT 
);
GO

