CREATE TABLE [dbo].[STB_PackingQtyPrintB523_VVT] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [MaterialCode] VARCHAR(50) NOT NULL DEFAULT ,
    [PackingQty] VARCHAR(10) NOT NULL DEFAULT ,
    [IsUsed] BIT NULL DEFAULT ,
    [Notes] NVARCHAR(MAX) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(30) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(30) NULL DEFAULT 
);
GO

