CREATE TABLE [dbo].[STB_LICENSE_INFO] (
    [LIC_NO] VARCHAR(30) NOT NULL DEFAULT ,
    [EMPID] VARCHAR(30) NOT NULL DEFAULT ,
    [LCODE] VARCHAR(10) NOT NULL DEFAULT ,
    [DCODE] VARCHAR(10) NOT NULL DEFAULT ,
    [LIC_NM] VARCHAR(100) NULL DEFAULT ,
    [LIC_START_DATE] DATE NOT NULL DEFAULT ,
    [LIC_END_DATE] DATE NULL DEFAULT ,
    [REMARK] VARCHAR(1000) NULL DEFAULT ,
    [REG_DATE] DATE NOT NULL DEFAULT (getdate()),
    [REG_YMS] DATETIME NOT NULL DEFAULT (getdate()),
    [UDT_DATE] DATE NOT NULL DEFAULT (getdate()),
    [UDT_YMS] DATETIME NOT NULL DEFAULT (getdate())
);
GO

