CREATE TABLE [dbo].[STB_MaterialRevision] (
    [MaterialCode] VARCHAR(50) NOT NULL DEFAULT ,
    [Revision] VARCHAR(20) NOT NULL DEFAULT ,
    [SubClass] VARCHAR(200) NULL DEFAULT ,
    [LifecyclePhase] VARCHAR(50) NULL DEFAULT ,
    [RevIncorpDate] DATETIME NULL DEFAULT ,
    [RevReleaseDate] DATETIME NULL DEFAULT ,
    [EffectivityDate] DATETIME NULL DEFAULT ,
    [ItemThumbnail] VARCHAR(500) NULL DEFAULT ,
    [Sites] VARCHAR(100) NULL DEFAULT ,
    [BomThumbnail] VARCHAR(500) NULL DEFAULT ,
    [BomItemRev] VARCHAR(100) NULL DEFAULT ,
    [BomItemLifecycle] VARCHAR(50) NULL DEFAULT ,
    [OracleTemplate] VARCHAR(50) NULL DEFAULT ,
    [ComponentType] VARCHAR(50) NULL DEFAULT ,
    [SubstitutionPriority] VARCHAR(10) NULL DEFAULT ,
    [ProductLine] VARCHAR(100) NULL DEFAULT ,
    [ModuleName] VARCHAR(100) NULL DEFAULT ,
    [SubSystem] VARCHAR(100) NULL DEFAULT ,
    [CommodityCode] VARCHAR(100) NULL DEFAULT ,
    [BomSubclass] VARCHAR(200) NULL DEFAULT ,
    [PartType] VARCHAR(50) NULL DEFAULT ,
    [UlReqd] VARCHAR(10) NULL DEFAULT ,
    [UlCritical] VARCHAR(10) NULL DEFAULT ,
    [RohsCompliant] VARCHAR(10) NULL DEFAULT ,
    [BomNotes] NVARCHAR(2000) NULL DEFAULT ,
    [MsdsReqd] VARCHAR(10) NULL DEFAULT ,
    [BomEffectiveDate] DATETIME NULL DEFAULT ,
    [DrawingNumber] VARCHAR(100) NULL DEFAULT ,
    [MaterialSpec] VARCHAR(100) NULL DEFAULT ,
    [DocumentSaveCode] VARCHAR(50) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT (getdate()),
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT ,
    [MfrPartHasRedline] VARCHAR(10) NULL DEFAULT ,
    CONSTRAINT [PK_STB_MaterialRevision] PRIMARY KEY CLUSTERED ([MaterialCode], [Revision])
);
GO

