CREATE TABLE [dbo].[STB_VN_IssueReceipt] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [GROUPID] NVARCHAR(50) NULL DEFAULT ,
    [PUBLICCODE] NVARCHAR(50) NULL DEFAULT ,
    [PARTNO] NVARCHAR(50) NULL DEFAULT ,
    [PACKQTY] INT NULL DEFAULT ,
    [DATEEXPORT_IMPORT] DATETIME NULL DEFAULT ,
    [STATUSISSUERECEIPT] NVARCHAR(20) NULL DEFAULT ,
    [UNIT] NVARCHAR(5) NULL DEFAULT ,
    [FROMDATE] DATETIME NULL DEFAULT ,
    [TODATE] DATETIME NULL DEFAULT ,
    [CREATEDATE] TIME NULL DEFAULT ,
    [CREATEUSERID] NVARCHAR(50) NULL DEFAULT ,
    [USERCRATE] NVARCHAR(50) NULL DEFAULT ,
    [DATEEXPORT] DATETIME NULL DEFAULT ,
    [TYPEREPORT] NVARCHAR(50) NULL DEFAULT 
);
GO

