CREATE TABLE [dbo].[STB_VN_BOM_LOGITIC] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [PRODUCTIONNAME] NVARCHAR(50) NULL DEFAULT ,
    [ONCELLSIZE] NVARCHAR(50) NULL DEFAULT ,
    [PRODUCTIONCODE] NVARCHAR(50) NULL DEFAULT ,
    [PART] NVARCHAR(50) NULL DEFAULT ,
    [MATERIALNAME] NVARCHAR(50) NULL DEFAULT ,
    [MATERIALCODE] NVARCHAR(50) NULL DEFAULT ,
    [USAGE] NVARCHAR(50) NULL DEFAULT ,
    [UNIT] NVARCHAR(50) NULL DEFAULT ,
    [TYPEBOM] NVARCHAR(50) NULL DEFAULT ,
    [NOTES] NVARCHAR(500) NULL DEFAULT ,
    [IsUsed] BIT NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] NVARCHAR(50) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] NVARCHAR(50) NULL DEFAULT 
);
GO

