CREATE TABLE [dbo].[stb_Vietnam_MapCode] (
    [Size] VARCHAR(20) NULL DEFAULT ,
    [Modelname] NVARCHAR(200) NULL DEFAULT ,
    [Modelcode] VARCHAR(20) NOT NULL DEFAULT ,
    [V-22] VARCHAR(20) NULL DEFAULT ,
    [V-23] VARCHAR(20) NULL DEFAULT ,
    [V-24] VARCHAR(20) NULL DEFAULT ,
    [V-25] VARCHAR(20) NULL DEFAULT ,
    [V-26] VARCHAR(20) NULL DEFAULT ,
    [V-27] VARCHAR(20) NULL DEFAULT ,
    [V-28] VARCHAR(20) NULL DEFAULT ,
    [V-29] VARCHAR(20) NULL DEFAULT ,
    [V-30] VARCHAR(20) NULL DEFAULT ,
    [V-33] VARCHAR(20) NULL DEFAULT ,
    [V-34] VARCHAR(20) NULL DEFAULT ,
    [MV-01] VARCHAR(20) NULL DEFAULT ,
    [MV-03] VARCHAR(20) NULL DEFAULT ,
    [MV-04] VARCHAR(20) NULL DEFAULT ,
    [MV-05] VARCHAR(20) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT (getdate())
);
GO

