CREATE TABLE [dbo].[STB_SavePackingQtyByLevel_VVT] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [IDSPT] VARCHAR(10) NULL DEFAULT ,
    [LotNo] VARCHAR(50) NULL DEFAULT ,
    [SClass] NUMERIC(15,0) NULL DEFAULT ,
    [AClass] NUMERIC(15,0) NULL DEFAULT ,
    [BClass] NUMERIC(15,0) NULL DEFAULT ,
    [CClass] NUMERIC(15,0) NULL DEFAULT ,
    [DClass] NUMERIC(15,0) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(30) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(30) NULL DEFAULT 
);
GO

