CREATE TABLE [dbo].[STB_VN_THAILANSTAMP] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [PNCELESTICA] NVARCHAR(50) NULL DEFAULT ,
    [PNSUPPLIERS] NVARCHAR(50) NULL DEFAULT ,
    [CODEVENDOR] NVARCHAR(50) NULL DEFAULT ,
    [LOTNO] NVARCHAR(50) NULL DEFAULT ,
    [DATEPRODUCTION] NVARCHAR(50) NULL DEFAULT ,
    [QTY] NVARCHAR(50) NULL DEFAULT ,
    [MADESBY] NVARCHAR(20) NULL DEFAULT ,
    [STATUSPRINTER] BIT NULL DEFAULT ('0'),
    [LABLELQTY] INT NULL DEFAULT ('1'),
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] NVARCHAR(50) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] NVARCHAR(50) NULL DEFAULT 
);
GO

