CREATE TABLE [dbo].[STB_ChangePartNoAndLotNo] (
    [ID] BIGINT IDENTITY(1,1) NOT NULL DEFAULT ,
    [oldLotID] VARCHAR(50) NULL DEFAULT ,
    [NewLotID] VARCHAR(50) NULL DEFAULT ,
    [isLotID] BIT NULL DEFAULT ((1)),
    [oldPartNo] VARCHAR(50) NULL DEFAULT ,
    [NewPartNo] VARCHAR(50) NULL DEFAULT ,
    [isPartNo] BIT NULL DEFAULT ((1)),
    [CreateDateTime] DATETIME NULL DEFAULT (getdate()),
    [CreateUserID] VARCHAR(50) NULL DEFAULT 
);
GO

