CREATE TABLE [dbo].[STB_AgingSortingData] (
    [Id] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [EquipmentNumber] NVARCHAR(100) NULL DEFAULT ,
    [SorterNum] NVARCHAR(100) NULL DEFAULT ,
    [StartTime] VARCHAR(100) NULL DEFAULT ,
    [WorkflowCode] NVARCHAR(100) NULL DEFAULT ,
    [Barcode] NVARCHAR(100) NULL DEFAULT ,
    [Slot] NVARCHAR(50) NULL DEFAULT ,
    [Position] NVARCHAR(50) NULL DEFAULT ,
    [Channel] NVARCHAR(50) NULL DEFAULT ,
    [Capacity] NVARCHAR(50) NULL DEFAULT ,
    [Capacitance] NVARCHAR(50) NULL DEFAULT ,
    [BeginVoltageSD] NVARCHAR(50) NULL DEFAULT ,
    [ChargeEndCurrent] NVARCHAR(50) NULL DEFAULT ,
    [EndVoltage] NVARCHAR(50) NULL DEFAULT ,
    [EndCurrent] NVARCHAR(50) NULL DEFAULT ,
    [DischargeVoltage1] NVARCHAR(50) NULL DEFAULT ,
    [DischargeVoltage1_Time] NVARCHAR(50) NULL DEFAULT ,
    [DischargeVoltage2] NVARCHAR(50) NULL DEFAULT ,
    [DischargeVoltage2_Time] NVARCHAR(50) NULL DEFAULT ,
    [DischargeBeginVoltage] NVARCHAR(50) NULL DEFAULT ,
    [DischargeBeginCurrent] NVARCHAR(50) NULL DEFAULT ,
    [NGInfo] NVARCHAR(200) NULL DEFAULT ,
    [EndTime] VARCHAR(100) NULL DEFAULT ,
    [LineCode] NVARCHAR(100) NULL DEFAULT ,
    [MachineName] NVARCHAR(100) NULL DEFAULT ,
    [CreatedDateTime] DATETIME NULL DEFAULT (getdate()),
    [WorkCenterCode] NVARCHAR(50) NULL DEFAULT 
);
GO

