CREATE TABLE [dbo].[STB_FourMChangHist] (
    [TimeCode] VARCHAR(2) NULL DEFAULT ,
    [ProdUserID] VARCHAR(20) NULL DEFAULT ,
    [Approver] VARCHAR(20) NULL DEFAULT ,
    [LotNo] VARCHAR(18) NOT NULL DEFAULT ,
    [MaterialCode] VARCHAR(50) NOT NULL DEFAULT ,
    [MachineCode] VARCHAR(20) NOT NULL DEFAULT ,
    [ChangesReasons] VARCHAR(1000) NULL DEFAULT ,
    [DetailContent] VARCHAR(1000) NULL DEFAULT ,
    [ItemCode] VARCHAR(1) NULL DEFAULT ,
    [Inspector] VARCHAR(20) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT ,
    [LotNo2] VARCHAR(18) NULL DEFAULT ,
    [LotNo3] VARCHAR(18) NULL DEFAULT ,
    [Unusual] VARCHAR(1000) NULL DEFAULT ,
    CONSTRAINT [PK_STB_FourMChangHist] PRIMARY KEY CLUSTERED ([LotNo], [MaterialCode], [MachineCode])
);
GO

