CREATE TABLE [dbo].[STB_VN_QCModule] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [DateInput] DATETIME NULL DEFAULT ,
    [LotNo] NVARCHAR(100) NULL DEFAULT ,
    [Species] NVARCHAR(100) NULL DEFAULT ,
    [ValuesESR] NVARCHAR(10) NULL DEFAULT ,
    [TypeSpecies] NVARCHAR(10) NULL DEFAULT ,
    [Descriptions] NVARCHAR(500) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] NVARCHAR(50) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] NVARCHAR(50) NULL DEFAULT 
);
GO

