CREATE TABLE [dbo].[STB_VN_BENDING_TAPPING] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [CODEPRODUCTION] NVARCHAR(50) NULL DEFAULT ,
    [FWAL] NVARCHAR(50) NULL DEFAULT ,
    [Vol] NVARCHAR(50) NULL DEFAULT ,
    [CODEERROR] NVARCHAR(50) NULL DEFAULT ,
    [NAMEERROR] NVARCHAR(50) NULL DEFAULT ,
    [QTYERROR] INT NULL DEFAULT ,
    [LOTNO] NVARCHAR(50) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] NVARCHAR(50) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] NVARCHAR(50) NULL DEFAULT ,
    [TYPESS] NVARCHAR(50) NULL DEFAULT ,
    [QTYLOTNO] INT NULL DEFAULT ,
    [MachineName] VARCHAR(50) NULL DEFAULT ,
    [ModelCode] VARCHAR(50) NULL DEFAULT ,
    [MarkingLetters] VARCHAR(50) NULL DEFAULT 
);
GO

