CREATE TABLE [dbo].[STB_MaterialQcInfo_audit] (
    [등록일자] DATE NULL DEFAULT ,
    [품목코드] NVARCHAR(50) NULL DEFAULT ,
    [품목명] NVARCHAR(100) NULL DEFAULT ,
    [PartNo] NVARCHAR(50) NULL DEFAULT ,
    [사이즈] NVARCHAR(50) NULL DEFAULT ,
    [제품검사번호] NVARCHAR(50) NULL DEFAULT ,
    [Lot번호_변경후] NVARCHAR(50) NULL DEFAULT ,
    [품목코드_변경후] NVARCHAR(50) NULL DEFAULT ,
    [KoreaLabel] NVARCHAR(50) NULL DEFAULT ,
    [판정결과] NVARCHAR(50) NULL DEFAULT ,
    [비고정보] NVARCHAR(MAX) NULL DEFAULT ,
    [검사자코드] NVARCHAR(50) NULL DEFAULT ,
    [검사자명] NVARCHAR(100) NULL DEFAULT ,
    [검사항목명] NVARCHAR(100) NULL DEFAULT ,
    [시료번호] NVARCHAR(50) NULL DEFAULT ,
    [측정값] NVARCHAR(50) NULL DEFAULT ,
    [라인코드] NVARCHAR(50) NULL DEFAULT ,
    [라인명] NVARCHAR(100) NULL DEFAULT ,
    [CLASSIFY] NVARCHAR(50) NULL DEFAULT ,
    [LotID_list] NVARCHAR(MAX) NULL DEFAULT ,
    [Holding_Hist] NVARCHAR(MAX) NULL DEFAULT ,
    [Id] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [LSL] DECIMAL(10,2) NULL DEFAULT ,
    [USL] DECIMAL(10,2) NULL DEFAULT 
);
GO

