CREATE TABLE [dbo].[STB_VietnamSemiInventory] (
    [MaterialCode] VARCHAR(50) NULL DEFAULT ,
    [MaterialName] NVARCHAR(100) NULL DEFAULT ,
    [InputLineCode] VARCHAR(20) NULL DEFAULT ,
    [LineName] VARCHAR(50) NULL DEFAULT ,
    [Barcode] VARCHAR(50) NULL DEFAULT ,
    [IsProdFinish] BIT NULL DEFAULT ,
    [IsLoss] BIT NULL DEFAULT ,
    [Remark] NVARCHAR(MAX) NULL DEFAULT ,
    [Route-22] NUMERIC(20,5) NULL DEFAULT ,
    [Route-23] NUMERIC(20,5) NULL DEFAULT ,
    [Route-24] NUMERIC(20,5) NULL DEFAULT ,
    [Route-25] NUMERIC(20,5) NULL DEFAULT ,
    [Route-26] NUMERIC(20,5) NULL DEFAULT ,
    [Route-27] NUMERIC(20,5) NULL DEFAULT ,
    [Route-99] NUMERIC(20,5) NULL DEFAULT ,
    [Route-28] NUMERIC(20,5) NULL DEFAULT ,
    [DateCapture] DATETIME NULL DEFAULT (getdate()),
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT 
);
GO

