CREATE TABLE [dbo].[STB_VN_HR_EQUIPMENT_MANAGEMENT] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [IDCODEEQ] NVARCHAR(50) NULL DEFAULT ,
    [LOCATIONS] NVARCHAR(50) NULL DEFAULT ,
    [DEPARTMENT] NVARCHAR(50) NULL DEFAULT ,
    [INSTALLATION] NVARCHAR(50) NULL DEFAULT ,
    [USERUSSING] NVARCHAR(50) NULL DEFAULT ,
    [DEVICECODE] NVARCHAR(50) NULL DEFAULT ,
    [DEVICENAME] NVARCHAR(50) NULL DEFAULT ,
    [UNIT] NVARCHAR(50) NULL DEFAULT ,
    [LAPTOP] NVARCHAR(50) NULL DEFAULT ,
    [CODE] NVARCHAR(50) NULL DEFAULT ,
    [VENDORCOMPANY] NVARCHAR(50) NULL DEFAULT ,
    [PURCHASEDATE] NVARCHAR(50) NULL DEFAULT ,
    [STATUSUSSING] NVARCHAR(50) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] NVARCHAR(50) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] NVARCHAR(50) NULL DEFAULT 
);
GO

