CREATE TABLE [dbo].[STB_VN_B598] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [LOAIHANG] NVARCHAR(50) NULL DEFAULT ,
    [CODENVL] NVARCHAR(50) NULL DEFAULT ,
    [NAMESNVL] NVARCHAR(50) NULL DEFAULT ,
    [UNIT] NVARCHAR(10) NULL DEFAULT ,
    [PRICES] FLOAT NULL DEFAULT ,
    [NORM] FLOAT NULL DEFAULT ,
    [DESCPRTIONS] NVARCHAR(50) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] NVARCHAR(50) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] NVARCHAR(50) NULL DEFAULT ,
    [TypeWasteID] INT NULL DEFAULT ,
    [IsDeleted] BIT NOT NULL DEFAULT ((0))
);
GO

