CREATE TABLE [dbo].[STB_VN_FINISHGOOD_OUT_TEMPORARY] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [GROUPID] NVARCHAR(50) NULL DEFAULT ,
    [IDFG] NVARCHAR(50) NULL DEFAULT ,
    [PACKINGID] NVARCHAR(30) NULL DEFAULT ,
    [LOTNO] NVARCHAR(30) NULL DEFAULT ,
    [MATERIALCODE] NVARCHAR(20) NULL DEFAULT ,
    [MATERIALNAME] NVARCHAR(40) NULL DEFAULT ,
    [PACKQTY] NVARCHAR(10) NULL DEFAULT ,
    [PARTNO] NVARCHAR(30) NULL DEFAULT ,
    [PUBLICCODE] NVARCHAR(30) NULL DEFAULT ,
    [TYPEPRODUCTION] NVARCHAR(30) NULL DEFAULT ,
    [PRODUCTIONSIZE] NVARCHAR(30) NULL DEFAULT ,
    [CREATEUSERID] NVARCHAR(20) NULL DEFAULT ,
    [CREATEDATEIN] DATETIME NULL DEFAULT ,
    [CREATEDATEOUT] DATETIME NULL DEFAULT ,
    [STATUSPRINTER] BIT NULL DEFAULT ,
    [STATUSIN] BIT NULL DEFAULT ,
    [STATUSOUT] BIT NULL DEFAULT ,
    [CREATEDATEGROUPID] DATETIME NULL DEFAULT ,
    [CUSTOMERS] NVARCHAR(50) NULL DEFAULT ,
    [SOINVOICES] NVARCHAR(50) NULL DEFAULT 
);
GO

