CREATE TABLE [dbo].[STB_VN_LABLEWAHOUSEEXPORT] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [FIRSTLABLE] NVARCHAR(50) NULL DEFAULT ('Outer BOX PACKING STICKER'),
    [FIRSTSECOND] NVARCHAR(50) NULL DEFAULT ('GENUS POWER INFRASTUCTURES LIMITED'),
    [FIRSTTHREE] NVARCHAR(100) NULL DEFAULT ,
    [FRISTFOURS] NVARCHAR(50) NULL DEFAULT ('VINATECH CO.,LTD'),
    [INVOICENO] NVARCHAR(50) NULL DEFAULT ,
    [DATES] NVARCHAR(20) NULL DEFAULT ,
    [DESCRIPTIONS] NVARCHAR(50) NULL DEFAULT ('Make: Vinatech'),
    [MODEL] NVARCHAR(50) NULL DEFAULT ,
    [DRNOWITHREV] NVARCHAR(50) NULL DEFAULT ,
    [SAPCODE] NVARCHAR(50) NULL DEFAULT ,
    [PKTQTY] INT NULL DEFAULT ,
    [LOTQTY] INT NULL DEFAULT ,
    [NUMBERPINTERED] INT NULL DEFAULT ,
    [NOTES] NVARCHAR(150) NULL DEFAULT ('Note: All information is Availablein Lastest Gennus PO &N Drawing'),
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] NVARCHAR(50) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] NVARCHAR(50) NULL DEFAULT 
);
GO

