CREATE TABLE [dbo].[STB_TYPESPAREPART] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [TYPECODE] NVARCHAR(50) NULL DEFAULT ,
    [TYPENAME] NVARCHAR(200) NULL DEFAULT ,
    [DESCRIPTION] NVARCHAR(200) NULL DEFAULT ,
    [ATTRIBUTE] NVARCHAR(200) NULL DEFAULT ,
    [ATTRIBUTE1] NVARCHAR(200) NULL DEFAULT ,
    [ATTRIBUTE2] NVARCHAR(200) NULL DEFAULT ,
    [ATTRIBUTE3] NVARCHAR(200) NULL DEFAULT ,
    [ATTRIBUTE4] NVARCHAR(200) NULL DEFAULT ,
    [ATTRIBUTE5] NVARCHAR(200) NULL DEFAULT ,
    [CREATEDATETIME] DATETIME NULL DEFAULT ,
    [CREATEUSERID] NVARCHAR(50) NULL DEFAULT ,
    [CHANGEDATETIME] DATETIME NULL DEFAULT ,
    [CHANGEUSERID] NVARCHAR(50) NULL DEFAULT ,
    [ISUSED] BIT NULL DEFAULT 
);
GO

