CREATE TABLE [dbo].[STB_MoldProductMachine] (
    [MachineCode] VARCHAR(20) NOT NULL DEFAULT ,
    [WorkCenterCode] VARCHAR(20) NULL DEFAULT ,
    [LineCode] VARCHAR(20) NULL DEFAULT ,
    [RouteCode] VARCHAR(20) NULL DEFAULT ,
    [MachineName] VARCHAR(50) NULL DEFAULT ,
    [DisplayIndex] INT NULL DEFAULT ,
    [InjectType] VARCHAR(20) NULL DEFAULT ,
    [Capa] VARCHAR(20) NULL DEFAULT ,
    [MonitoringGroup] VARCHAR(20) NULL DEFAULT ,
    [ErpMachineCode] VARCHAR(20) NULL DEFAULT ,
    [IsTemperatureControl] BIT NULL DEFAULT ,
    [IsCommunication] BIT NULL DEFAULT ,
    [MachineDesc1] VARCHAR(200) NULL DEFAULT ,
    [MachineDesc2] VARCHAR(200) NULL DEFAULT ,
    [MachineDesc3] VARCHAR(200) NULL DEFAULT ,
    [MachineDesc4] VARCHAR(200) NULL DEFAULT ,
    [MachineDesc5] VARCHAR(200) NULL DEFAULT ,
    [MoldProdNo] VARCHAR(50) NULL DEFAULT ,
    [RunMode] VARCHAR(1) NULL DEFAULT ,
    [IsMachineAlarm] BIT NULL DEFAULT ,
    [IsMoldTempControl] BIT NULL DEFAULT ,
    [MoldTemp1] NUMERIC(10,2) NULL DEFAULT ,
    [MoldTemp2] NUMERIC(10,2) NULL DEFAULT ,
    [MoldTemp3] NUMERIC(10,2) NULL DEFAULT ,
    [MoldTemp4] NUMERIC(10,2) NULL DEFAULT ,
    [MoldTemp5] NUMERIC(10,2) NULL DEFAULT ,
    [MoldTemp6] NUMERIC(10,2) NULL DEFAULT ,
    [IsMoldTempAlarm1] BIT NULL DEFAULT ,
    [IsMoldTempAlarm2] BIT NULL DEFAULT ,
    [IsMoldTempAlarm3] BIT NULL DEFAULT ,
    [IsMoldTempAlarm4] BIT NULL DEFAULT ,
    [IsMoldTempAlarm5] BIT NULL DEFAULT ,
    [IsMoldTempAlarm6] BIT NULL DEFAULT ,
    [MoldTemperatureSet1] NUMERIC(10,2) NULL DEFAULT ,
    [MoldTemperatureSet2] NUMERIC(10,2) NULL DEFAULT ,
    [MoldTemperatureSet3] NUMERIC(10,2) NULL DEFAULT ,
    [MoldTemperatureSet4] NUMERIC(10,2) NULL DEFAULT ,
    [MoldTemperatureSet5] NUMERIC(10,2) NULL DEFAULT ,
    [MoldTemperatureSet6] NUMERIC(10,2) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT 
);
GO

