CREATE TABLE [dbo].[STB_MontylyProdPlan_ITF] (
    [CompanyCode] NVARCHAR(7) NOT NULL DEFAULT ,
    [LineSeq] NUMERIC(17,0) NOT NULL DEFAULT ,
    [FactoryCode] NVARCHAR(7) NOT NULL DEFAULT ,
    [PlanMonth] NCHAR(6) NOT NULL DEFAULT ,
    [EmpCode] NVARCHAR(10) NOT NULL DEFAULT ,
    [PlanDateCode] NVARCHAR(3) NOT NULL DEFAULT ,
    [ProdPlanOrderNo] NUMERIC(4,0) NOT NULL DEFAULT ,
    [MaterialCode] NVARCHAR(20) NOT NULL DEFAULT ,
    [StockVNTQty] NUMERIC(17,4) NULL DEFAULT ,
    [StockVVTQty] NUMERIC(17,4) NULL DEFAULT ,
    [SalesNonDeliveryCellQty] NUMERIC(17,4) NULL DEFAULT ,
    [SalesNonDeliveryMdlQty] NUMERIC(17,4) NULL DEFAULT ,
    [PackingVNTQty] NUMERIC(17,4) NULL DEFAULT ,
    [PackingVVTQty] NUMERIC(17,4) NULL DEFAULT ,
    [AddProdVNTQty] NUMERIC(17,4) NULL DEFAULT ,
    [AddProdVVTQty] NUMERIC(17,4) NULL DEFAULT ,
    [SalesPlanFixCellQty] NUMERIC(17,4) NULL DEFAULT ,
    [SalesPlanFixMdlQty] NUMERIC(17,4) NULL DEFAULT ,
    [SalesPlanAddCellQty] NUMERIC(17,4) NULL DEFAULT ,
    [SalesPlanAddMdlQty] NUMERIC(17,4) NULL DEFAULT ,
    [ProdPlanPreProdQty] NUMERIC(17,4) NULL DEFAULT ,
    [ProdPlanChangeReqQty] NUMERIC(17,4) NULL DEFAULT ,
    [ProdPlanVNTQty] NUMERIC(17,4) NULL DEFAULT ,
    [ProdPlanVVTQty] NUMERIC(17,4) NULL DEFAULT ,
    [CreateDateTime] NVARCHAR(14) NULL DEFAULT ,
    [CreateUserID] NVARCHAR(15) NULL DEFAULT ,
    [ChangeDateTime] NVARCHAR(14) NULL DEFAULT ,
    [ChangeUserID] NVARCHAR(15) NULL DEFAULT ,
    [IUD_FLAG] VARCHAR(10) NULL DEFAULT ,
    [PONo] VARCHAR(20) NULL DEFAULT ,
    CONSTRAINT [PK_STB_MontylyProdPlan_ITF] PRIMARY KEY CLUSTERED ([CompanyCode], [LineSeq], [FactoryCode], [PlanMonth], [EmpCode], [PlanDateCode], [ProdPlanOrderNo], [MaterialCode])
);
GO

