CREATE TABLE [dbo].[STB_DataMediumSorting] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [FilenameL] NVARCHAR(100) NULL DEFAULT ,
    [Step] VARCHAR(30) NULL DEFAULT ,
    [Time] VARCHAR(30) NULL DEFAULT ,
    [V] VARCHAR(30) NULL DEFAULT ,
    [I] VARCHAR(30) NULL DEFAULT ,
    [Ah] VARCHAR(30) NULL DEFAULT ,
    [Wh] VARCHAR(30) NULL DEFAULT ,
    [Grade_1] VARCHAR(30) NULL DEFAULT ,
    [OCV] VARCHAR(30) NULL DEFAULT ,
    [Grade_2] VARCHAR(30) NULL DEFAULT ,
    [DCR] VARCHAR(30) NULL DEFAULT ,
    [Grade_3] VARCHAR(30) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT (getdate()),
    [CreateUserID] VARCHAR(30) NULL DEFAULT 
);
GO

