CREATE TABLE [dbo].[STB_Vietnam_Module_InpectionHist] (
    [Id] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [LotNo] VARCHAR(50) NOT NULL DEFAULT ,
    [S_JARVIS] DATETIME NULL DEFAULT ,
    [S_Quality_Outsourcing_] DATETIME NULL DEFAULT ,
    [E_JARVIS] DATETIME NULL DEFAULT ,
    [E_Quality_Outsourcing_] DATETIME NULL DEFAULT ,
    [E_Quality_VN_] NVARCHAR(MAX) NULL DEFAULT ,
    [SD_Quality_VN_] DATETIME NULL DEFAULT ,
    [SD_QTY] VARCHAR(20) NULL DEFAULT ,
    [고객사] VARCHAR(MAX) NULL DEFAULT ,
    [Result] VARCHAR(20) NULL DEFAULT ,
    [partno] VARCHAR(50) NULL DEFAULT ,
    [size] VARCHAR(20) NULL DEFAULT ,
    [lotqty] INT NULL DEFAULT ,
    [Module_Prod_Date] DATETIME NULL DEFAULT ,
    [S_EMP] VARCHAR(50) NULL DEFAULT ,
    [S_NG_QTY] VARCHAR(20) NULL DEFAULT ,
    [E_EMP] VARCHAR(50) NULL DEFAULT ,
    [E_NG_QTY] VARCHAR(20) NULL DEFAULT ,
    [SD_EMP] VARCHAR(50) NULL DEFAULT ,
    [SD_NG_QTY] VARCHAR(20) NULL DEFAULT 
);
GO

