CREATE TABLE [dbo].[STB_MoistureMeasureHist_audit] (
    [측정일자] DATE NULL DEFAULT ,
    [주야구분코드] NVARCHAR(50) NULL DEFAULT ,
    [주야구분명] NVARCHAR(255) NULL DEFAULT ,
    [검사자코드] NVARCHAR(50) NULL DEFAULT ,
    [검사자명] NVARCHAR(255) NULL DEFAULT ,
    [사업장코드] NVARCHAR(50) NULL DEFAULT ,
    [사업장명] NVARCHAR(255) NULL DEFAULT ,
    [작업장코드] NVARCHAR(50) NULL DEFAULT ,
    [작업장명] NVARCHAR(255) NULL DEFAULT ,
    [라인코드] NVARCHAR(50) NULL DEFAULT ,
    [라인명] NVARCHAR(255) NULL DEFAULT ,
    [설비코드] NVARCHAR(50) NULL DEFAULT ,
    [설비명] NVARCHAR(255) NULL DEFAULT ,
    [유의사항] NVARCHAR(MAX) NULL DEFAULT ,
    [제품사이즈] NVARCHAR(255) NULL DEFAULT ,
    [품목코드] NVARCHAR(50) NULL DEFAULT ,
    [품목명] NVARCHAR(255) NULL DEFAULT ,
    [온도] DECIMAL(18,2) NULL DEFAULT ,
    [노점온도] DECIMAL(18,2) NULL DEFAULT ,
    [시료무게] DECIMAL(18,2) NULL DEFAULT ,
    [전해액수분측정값] DECIMAL(18,2) NULL DEFAULT ,
    [원자재] NVARCHAR(255) NULL DEFAULT ,
    [합격여부] NVARCHAR(10) NULL DEFAULT ,
    [비고] NVARCHAR(MAX) NULL DEFAULT ,
    [Id] INT IDENTITY(1,1) NOT NULL DEFAULT 
);
GO

