CREATE TABLE [dbo].[STB_VN_MODEL] (
    [IDMDE] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [CodeModel] NVARCHAR(10) NULL DEFAULT ,
    [NameModel] NVARCHAR(50) NULL DEFAULT ,
    [Desc] NVARCHAR(100) NULL DEFAULT ,
    [IsUsed] BIT NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] NVARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] NVARCHAR(20) NULL DEFAULT 
);
GO

