CREATE TABLE [dbo].[stb_MasterAgaingHN] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [MACHINES] NVARCHAR(30) NULL DEFAULT ,
    [LOTNO] NVARCHAR(30) NULL DEFAULT ,
    [SPEC] NVARCHAR(30) NULL DEFAULT ,
    [DATES] NVARCHAR(100) NULL DEFAULT ,
    [COMPUTER] NVARCHAR(50) NULL DEFAULT ,
    [CREATEDATE] DATETIME NULL DEFAULT 
);
GO

