CREATE TABLE [dbo].[STB_VN_CAPTURE_FINSHEDGOOD] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [PUBLICCODE] NVARCHAR(50) NULL DEFAULT ,
    [PARTNO] NVARCHAR(50) NULL DEFAULT ,
    [UNIT] NVARCHAR(20) NULL DEFAULT ,
    [QTYINPUT] INT NULL DEFAULT ,
    [QTYOUT] INT NULL DEFAULT ,
    [QTYLOCATION] INT NULL DEFAULT ,
    [TOTALSALE] INT NULL DEFAULT ,
    [TOTALCURRENTLY] INT NULL DEFAULT ,
    [STATUSSALE] NVARCHAR(100) NULL DEFAULT ,
    [CAPUTER_DATE] DATETIME NULL DEFAULT 
);
GO

