CREATE TABLE [dbo].[STB_VN_CLASSIFY] (
    [IDS] NVARCHAR(50) NOT NULL DEFAULT ,
    [NameCLASSIFY] NVARCHAR(50) NULL DEFAULT ,
    [DESCRIPTIONS] NVARCHAR(500) NULL DEFAULT ,
    [IsUsed] BIT NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] NVARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] NVARCHAR(20) NULL DEFAULT 
);
GO

