CREATE TABLE [dbo].[STB_NamesAndSizeForB717] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [NAMES] NVARCHAR(50) NULL DEFAULT ,
    [SIZE] NVARCHAR(50) NULL DEFAULT ,
    [IsUsed] BIT NULL DEFAULT ,
    [WorkCenterCode] VARCHAR(20) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT 
);
GO

