CREATE TABLE [dbo].[STB_QCExportInfoRecord] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [Model] VARCHAR(50) NULL DEFAULT ,
    [Size] VARCHAR(10) NULL DEFAULT ,
    [LotNo] VARCHAR(30) NULL DEFAULT ,
    [Qty] INT NULL DEFAULT ,
    [DateShip] DATE NULL DEFAULT ,
    [Customer] NVARCHAR(200) NULL DEFAULT ,
    [Korea] NVARCHAR(200) NULL DEFAULT ,
    [Note] NVARCHAR(1000) NULL DEFAULT ,
    [Grade] VARCHAR(5) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT 
);
GO

