CREATE TABLE [dbo].[STB_RTInfo] (
    [RTNo] VARCHAR(20) NOT NULL DEFAULT ,
    [Seq] INT NOT NULL DEFAULT ,
    [TestClassCode] VARCHAR(20) NULL DEFAULT ,
    [TestItemCode] VARCHAR(20) NULL DEFAULT ,
    [TestName] NVARCHAR(500) NULL DEFAULT ,
    [ModelSpec] NVARCHAR(100) NULL DEFAULT ,
    [AppliedVoltage] NUMERIC(20,5) NULL DEFAULT ,
    [Temperature] NUMERIC(20,5) NULL DEFAULT ,
    [Humidity] NUMERIC(20,5) NULL DEFAULT ,
    [RequestDeptCode] VARCHAR(20) NULL DEFAULT ,
    [RequestWorkerCode] VARCHAR(20) NULL DEFAULT ,
    [RequestDate] DATE NULL DEFAULT ,
    [TestStartDate] DATE NULL DEFAULT ,
    [MeasureDate] DATE NULL DEFAULT ,
    [TestRestartDate] DATE NULL DEFAULT ,
    [MeasureCycle] INT NULL DEFAULT ,
    [CumulativeTime] INT NULL DEFAULT ,
    [TestEndTime] INT NULL DEFAULT ,
    [ChamberCode] VARCHAR(20) NULL DEFAULT ,
    [CDMachineChannel] VARCHAR(50) NULL DEFAULT ,
    [JigNo] VARCHAR(50) NULL DEFAULT ,
    [SampleQty] INT NULL DEFAULT ,
    [RTStatusCode] VARCHAR(20) NULL DEFAULT ,
    [CreateDateTime] DATETIME NOT NULL DEFAULT (getdate()),
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT ,
    [ModelCode] VARCHAR(20) NULL DEFAULT ,
    [Farad] NUMERIC(7,2) NULL DEFAULT ,
    [ProdSize] VARCHAR(20) NULL DEFAULT ,
    [ModelType] VARCHAR(20) NULL DEFAULT ,
    [Remark] VARCHAR(20) NULL DEFAULT ,
    [Volt] NUMERIC(7,2) NULL DEFAULT ,
    [ModelName] NVARCHAR(500) NULL DEFAULT ,
    CONSTRAINT [PK_STB_RTInfo] PRIMARY KEY CLUSTERED ([RTNo], [Seq])
);
GO

