CREATE TABLE [dbo].[STB_StocktakingPlanResult] (
    [StocktakingDocNo] VARCHAR(20) NOT NULL DEFAULT ,
    [SDNSeqNo] INT NOT NULL DEFAULT ,
    [MaterialLocationCode] VARCHAR(20) NULL DEFAULT ,
    [MaterialLotNo] VARCHAR(20) NULL DEFAULT ,
    [LotID] VARCHAR(50) NULL DEFAULT ,
    [MaterialCode] VARCHAR(50) NULL DEFAULT ,
    [MaterialStockAttribute] VARCHAR(20) NULL DEFAULT ,
    [StockAttrib1] VARCHAR(20) NULL DEFAULT ,
    [StockAttrib2] VARCHAR(20) NULL DEFAULT ,
    [StockAttrib3] VARCHAR(20) NULL DEFAULT ,
    [PackingID] VARCHAR(50) NULL DEFAULT ,
    [BasicQty] NUMERIC(20,5) NULL DEFAULT ,
    [LotAttr01] NVARCHAR(200) NULL DEFAULT ,
    [LotAttr02] NVARCHAR(200) NULL DEFAULT ,
    [LotAttr03] NVARCHAR(200) NULL DEFAULT ,
    [LotAttr04] NVARCHAR(200) NULL DEFAULT ,
    [LotAttr05] NVARCHAR(200) NULL DEFAULT ,
    [LotAttr06] NVARCHAR(200) NULL DEFAULT ,
    [LotAttr07] NVARCHAR(200) NULL DEFAULT ,
    [LotAttr08] NVARCHAR(200) NULL DEFAULT ,
    [LotAttr09] NVARCHAR(200) NULL DEFAULT ,
    [LotAttr10] NVARCHAR(200) NULL DEFAULT ,
    [IsStocktaking] BIT NULL DEFAULT ,
    [StocktakingQty] NUMERIC(20,5) NULL DEFAULT ,
    [StocktakingMaterialLocationCode] VARCHAR(20) NULL DEFAULT ,
    [StocktakingUserID] VARCHAR(20) NULL DEFAULT ,
    [StocktakingDateTime] DATETIME NULL DEFAULT ,
    [IsApplied] BIT NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT ,
    CONSTRAINT [PK_STB_StocktakingPlanResult] PRIMARY KEY CLUSTERED ([StocktakingDocNo], [SDNSeqNo])
);
GO

