CREATE TABLE [dbo].[STB_PackingHN710_HN] (
    [LotNo] NVARCHAR(50) NOT NULL DEFAULT ,
    [Qty] INT NULL DEFAULT ,
    [Marking] NVARCHAR(50) NULL DEFAULT ,
    [MaterialCode] NVARCHAR(50) NULL DEFAULT ,
    [CombiPackkingAndMarking] VARCHAR(MAX) NULL DEFAULT ,
    [CreateUserId] VARCHAR(50) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [PackingId] VARCHAR(255) NULL DEFAULT 
);
GO

