CREATE TABLE [dbo].[STB_INVERTORY_COMPUTER] (
    [IDIC] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [UserDevice] NVARCHAR(50) NULL DEFAULT ,
    [CodeDevice] NVARCHAR(50) NULL DEFAULT ,
    [Departmets] NVARCHAR(50) NULL DEFAULT ,
    [TypeComputer] NVARCHAR(20) NULL DEFAULT ,
    [NameBrand] NVARCHAR(20) NULL DEFAULT ,
    [NameStatus] NVARCHAR(20) NULL DEFAULT ,
    [RAM] NVARCHAR(10) NULL DEFAULT ,
    [HHDCAPACITY] NVARCHAR(20) NULL DEFAULT ,
    [WINDOWKEY] NVARCHAR(30) NULL DEFAULT ,
    [OFFICEKEY] NVARCHAR(30) NULL DEFAULT ,
    [SEVICETAGE] NVARCHAR(30) NULL DEFAULT ,
    [LOCATIONS] NVARCHAR(30) NULL DEFAULT ,
    [DESCPTIONS] NVARCHAR(500) NULL DEFAULT ,
    [CreateBy] NVARCHAR(50) NULL DEFAULT ,
    [CreateDate] DATETIME NULL DEFAULT 
);
GO

