CREATE TABLE [dbo].[STB_VN_EMPLOYEESTRANSFER] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [EMPLOYEESID] NVARCHAR(50) NULL DEFAULT ,
    [EMPLOYEESNAME] NVARCHAR(50) NULL DEFAULT ,
    [CODELINECURRENTLY] NVARCHAR(20) NULL DEFAULT ,
    [LINECURRENTLY] NVARCHAR(100) NULL DEFAULT ,
    [CODELINETRANSFER] NVARCHAR(50) NULL DEFAULT ,
    [LINETRANSFER] NVARCHAR(100) NULL DEFAULT ,
    [START_DATES] DATETIME NULL DEFAULT ,
    [END_DATES] DATETIME NULL DEFAULT ,
    [START_TIME] DATETIME NULL DEFAULT ,
    [END_TIME] DATETIME NULL DEFAULT ,
    [TOTALMINUTES] NVARCHAR(50) NULL DEFAULT ,
    [TOTALHOUR] DECIMAL(5,2) NULL DEFAULT ,
    [CREATEBY] NVARCHAR(50) NULL DEFAULT ,
    [CREATEDATE] DATETIME NULL DEFAULT ,
    [CHANGEBY] NVARCHAR(50) NULL DEFAULT ,
    [DATECHAGE] DATETIME NULL DEFAULT ,
    [Shifts] NVARCHAR(50) NULL DEFAULT 
);
GO

