CREATE TABLE [dbo].[Stb_EmployeeDepartment] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [CODEEMP] NVARCHAR(50) NULL DEFAULT ,
    [NAME] NVARCHAR(200) NULL DEFAULT ,
    [DEPARTMENT] NVARCHAR(200) NULL DEFAULT ,
    [SEX] NVARCHAR(200) NULL DEFAULT ,
    [BIRTHDAY] DATE NULL DEFAULT ,
    [ADDRESS] NVARCHAR(200) NULL DEFAULT ,
    [PHONENUMBER] NVARCHAR(200) NULL DEFAULT ,
    [DESCRIPTION] NVARCHAR(200) NULL DEFAULT ,
    [ATTRIBUTE] NVARCHAR(200) NULL DEFAULT ,
    [ATTRIBUTE1] NVARCHAR(200) NULL DEFAULT ,
    [ATTRIBUTE2] NVARCHAR(200) NULL DEFAULT ,
    [ATTRIBUTE3] NVARCHAR(200) NULL DEFAULT ,
    [ATTRIBUTE4] NVARCHAR(200) NULL DEFAULT ,
    [ATTRIBUTE5] NVARCHAR(200) NULL DEFAULT ,
    [IsUsed] BIT NULL DEFAULT ,
    [CREATEDATETIME] DATETIME NULL DEFAULT ,
    [CREATEUSERID] NVARCHAR(50) NULL DEFAULT ,
    [CHANGEDATETIME] DATETIME NULL DEFAULT ,
    [CHANGEUSERID] NVARCHAR(50) NULL DEFAULT ,
    [PartName] NVARCHAR(100) NULL DEFAULT ,
    [COMPANYCODE] NVARCHAR(50) NULL DEFAULT ,
    [WORKCENTERCODE] NVARCHAR(50) NULL DEFAULT 
);
GO

