CREATE TABLE [dbo].[STB_VN_LABLE_CUSTOMER] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [NAMEBARCODE1] NVARCHAR(50) NULL DEFAULT ,
    [NAMEBARCODE2] NVARCHAR(20) NULL DEFAULT ,
    [EXTENSIONs] NVARCHAR(20) NULL DEFAULT ,
    [LableQtys] INT NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] NVARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] NVARCHAR(20) NULL DEFAULT 
);
GO

