CREATE TABLE [dbo].[Stb_ShortingInfor] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [LotNo] NVARCHAR(50) NULL DEFAULT ,
    [Value1] NVARCHAR(50) NULL DEFAULT ,
    [Value2] NVARCHAR(50) NULL DEFAULT ,
    [Description] NVARCHAR(200) NULL DEFAULT ,
    [Note] NVARCHAR(100) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateBy] NVARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeBy] NVARCHAR(20) NULL DEFAULT ,
    [value3] NVARCHAR(50) NULL DEFAULT ,
    [value4] NVARCHAR(50) NULL DEFAULT ,
    [value5] NVARCHAR(50) NULL DEFAULT ,
    [value6] NVARCHAR(50) NULL DEFAULT ,
    [value7] NVARCHAR(50) NULL DEFAULT ,
    [value8] NVARCHAR(50) NULL DEFAULT ,
    [value9] NVARCHAR(50) NULL DEFAULT ,
    [value10] NVARCHAR(50) NULL DEFAULT ,
    [value11] NVARCHAR(50) NULL DEFAULT 
);
GO

