CREATE TABLE [dbo].[STB_TYPEINOUT] (
    [DOCTYPE] VARCHAR(50) NULL DEFAULT ,
    [NAME] VARCHAR(100) NULL DEFAULT ,
    [DESCRIPTION] VARCHAR(200) NULL DEFAULT ,
    [CREATEDATETIME] DATETIME NULL DEFAULT ,
    [CREATEUSERID] VARCHAR(50) NULL DEFAULT ,
    [CHANGEDATETIME] DATETIME NULL DEFAULT ,
    [CHANGEUSERID] VARCHAR(50) NULL DEFAULT ,
    [ATTRIBUTE1] VARCHAR(200) NULL DEFAULT ,
    [ATTRIBUTE2] VARCHAR(200) NULL DEFAULT ,
    [ATTRIBUTE3] VARCHAR(200) NULL DEFAULT ,
    [ATTRIBUTE4] VARCHAR(200) NULL DEFAULT ,
    [ATTRIBUTE5] VARCHAR(200) NULL DEFAULT ,
    [ISACTIVE] BIT NULL DEFAULT ,
    [TYPEINOUT] VARCHAR(20) NULL DEFAULT 
);
GO

