CREATE TABLE [dbo].[STB_QC4MChangeDataRecord] (
    [QC4MNo] VARCHAR(20) NOT NULL DEFAULT ,
    [ApprovalType] NVARCHAR(100) NULL DEFAULT ,
    [IssuingDepartment] VARCHAR(10) NULL DEFAULT ,
    [ChangeType4M] VARCHAR(50) NULL DEFAULT ,
    [Level] NVARCHAR(50) NULL DEFAULT ,
    [Factory] VARCHAR(10) NULL DEFAULT ,
    [Model] VARCHAR(30) NULL DEFAULT ,
    [LineCode] VARCHAR(20) NULL DEFAULT ,
    [RouteCode] VARCHAR(20) NULL DEFAULT ,
    [LotNo1] VARCHAR(30) NULL DEFAULT ,
    [LotNo2] VARCHAR(30) NULL DEFAULT ,
    [LotNo3] VARCHAR(30) NULL DEFAULT ,
    [DetailedChangeCategories] NVARCHAR(MAX) NULL DEFAULT ,
    [ReasonForChange] NVARCHAR(MAX) NULL DEFAULT ,
    [ConditionsBefChange] NVARCHAR(MAX) NULL DEFAULT ,
    [ConditionsAftChange] NVARCHAR(MAX) NULL DEFAULT ,
    [QualityAssuranceContent] NVARCHAR(MAX) NULL DEFAULT ,
    [ApprovalDate] DATE NULL DEFAULT ,
    [EffectiveDate] DATE NULL DEFAULT ,
    [Conclusion] NVARCHAR(MAX) NULL DEFAULT ,
    [Inspector] NVARCHAR(50) NULL DEFAULT ,
    [Change4MImage] VARBINARY(MAX) NULL DEFAULT ,
    [Change4MImageUrl] VARCHAR(500) NULL DEFAULT ,
    [ProdProcessResultFile] BIGINT NULL DEFAULT ,
    [Status] NVARCHAR(50) NULL DEFAULT ,
    [Note] NVARCHAR(MAX) NULL DEFAULT ,
    [ConnectString] VARCHAR(40) NULL DEFAULT ,
    [ShowData] BIT NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT 
);
GO

