CREATE TABLE [dbo].[STB_VN_BloomBoxLabelPrintHist] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [LotID] VARCHAR(50) NULL DEFAULT ,
    [MaterialCode] VARCHAR(50) NULL DEFAULT ,
    [MaterialName] NVARCHAR(100) NULL DEFAULT ,
    [PackingID] VARCHAR(50) NULL DEFAULT ,
    [LabelQty] INT NULL DEFAULT ,
    [LotQty] INT NULL DEFAULT ,
    [CurrentQty] NUMERIC(20,10) NULL DEFAULT ,
    [LotNo] VARCHAR(50) NULL DEFAULT ,
    [PartNo] VARCHAR(50) NULL DEFAULT ,
    [MarkingLetter] VARCHAR(50) NULL DEFAULT ,
    [SN] VARCHAR(10) NULL DEFAULT ,
    [DC] VARCHAR(10) NULL DEFAULT ,
    [SalesPONo] VARCHAR(50) NULL DEFAULT ,
    [StockAttrib1] NVARCHAR(100) NULL DEFAULT ,
    [PrintTime] DATETIME NULL DEFAULT ,
    [PrintUserID] VARCHAR(20) NULL DEFAULT 
);
GO

