CREATE TABLE [dbo].[STB_VN_SCRAP_WEIGHSCALE_PRODUCTIONS] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [GROUPID] NVARCHAR(500) NULL DEFAULT ,
    [BARCODE] NVARCHAR(500) NULL DEFAULT ,
    [LINECODE] NVARCHAR(50) NULL DEFAULT ,
    [NAMELINE] NVARCHAR(50) NULL DEFAULT ,
    [WEIGHSCALE] NVARCHAR(100) NULL DEFAULT ,
    [CREATEDATE] DATETIME NULL DEFAULT ,
    [DATEWEIGH] NVARCHAR(50) NULL DEFAULT ,
    [USERID] NVARCHAR(50) NULL DEFAULT ,
    [FLAG] BIT NULL DEFAULT ,
    [STATUSDELETE] NVARCHAR(200) NULL DEFAULT ,
    [CONVERTKG] NVARCHAR(50) NULL DEFAULT ,
    [IMAGEBARCODE] IMAGE NULL DEFAULT ,
    [TYPESCRAP] NVARCHAR(50) NULL DEFAULT ,
    [SHIFTS] NVARCHAR(50) NULL DEFAULT ,
    [TYPES] NVARCHAR(50) NULL DEFAULT ,
    [TYPENAMES] NVARCHAR(50) NULL DEFAULT ,
    [CODENAME] NVARCHAR(50) NULL DEFAULT ,
    [NAMEPRODUCTION] NVARCHAR(50) NULL DEFAULT ,
    [UNITS] NVARCHAR(20) NULL DEFAULT ,
    [NAMEERROR] NVARCHAR(100) NULL DEFAULT ,
    [QUANTITY] INT NULL DEFAULT 
);
GO

