CREATE TABLE [dbo].[STB_MEAClassInfo] (
    [MEAClassCode] VARCHAR(20) NOT NULL DEFAULT ,
    [MEAClassName] NVARCHAR(100) NOT NULL DEFAULT ,
    [CreateDateTime] DATETIME NOT NULL DEFAULT (getdate()),
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT 
);
GO

