CREATE TABLE [dbo].[STB_TYPE_PRODUCTION_ERROR] (
    [IDTPE] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [NameTypeError] NVARCHAR(50) NULL DEFAULT ,
    [CreateBy] NVARCHAR(50) NULL DEFAULT ,
    [CreateDate] DATETIME NULL DEFAULT ,
    [Actives] BIT NULL DEFAULT 
);
GO

