CREATE TABLE [dbo].[STB_LICENSE_CODE_DETAIL] (
    [LCODE] VARCHAR(10) NOT NULL DEFAULT ,
    [DCODE] VARCHAR(10) NOT NULL DEFAULT ,
    [DNAME] VARCHAR(30) NOT NULL DEFAULT ,
    [REG_DATE] DATE NOT NULL DEFAULT (getdate()),
    [REG_YMS] DATETIME NOT NULL DEFAULT (getdate()),
    [UDT_DATE] DATE NOT NULL DEFAULT (getdate()),
    [UDT_YMS] DATETIME NOT NULL DEFAULT (getdate()),
    CONSTRAINT [PK_STB_LICENSE_CODE_DETAIL] PRIMARY KEY CLUSTERED ([LCODE], [DCODE])
);
GO

