CREATE TABLE [dbo].[STB_VN_DRYOVER] (
    [IDDO] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [MaterialCode] NVARCHAR(50) NULL DEFAULT ,
    [MaterialName] NVARCHAR(100) NULL DEFAULT ,
    [BarCode] NVARCHAR(100) NULL DEFAULT ,
    [DryMachines] NVARCHAR(100) NULL DEFAULT ,
    [QTY] FLOAT NULL DEFAULT ,
    [StatusIn] NVARCHAR(30) NULL DEFAULT ,
    [StatusOut] NVARCHAR(30) NULL DEFAULT ,
    [OvenInputDate] DATETIME NULL DEFAULT ,
    [OvenOutDate] DATETIME NULL DEFAULT ,
    [TotalMinutes] INT NULL DEFAULT ,
    [TotalHouse] INT NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] NVARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] NVARCHAR(20) NULL DEFAULT ,
    [Pressure] FLOAT NULL DEFAULT ,
    [DryTemperature] FLOAT NULL DEFAULT ,
    [OutTemperature] FLOAT NULL DEFAULT ,
    [Unit] VARCHAR(20) NULL DEFAULT 
);
GO

