CREATE TABLE [dbo].[STB_MaterialWarehouseUsageHist] (
    [UsageHistId] BIGINT IDENTITY(1,1) NOT NULL DEFAULT ,
    [MaterialLotNo] VARCHAR(50) NULL DEFAULT ,
    [MaterialWarehouseInOutHistNo] VARCHAR(20) NULL DEFAULT ,
    [DayPlanNo] VARCHAR(20) NOT NULL DEFAULT ,
    [MaterialLotId] VARCHAR(20) NOT NULL DEFAULT ,
    [MaterialCode] VARCHAR(50) NOT NULL DEFAULT ,
    [RouteCode] VARCHAR(20) NULL DEFAULT ,
    [MachineCode] VARCHAR(20) NULL DEFAULT ,
    [QtyUsed] NUMERIC(18,4) NOT NULL DEFAULT ,
    [Unit] VARCHAR(20) NOT NULL DEFAULT ,
    [NoEmp] VARCHAR(10) NOT NULL DEFAULT ,
    [OutDate] DATETIME NOT NULL DEFAULT ,
    [Status] VARCHAR(10) NOT NULL DEFAULT ('ACTIVE'),
    [IsBomItem] VARCHAR(1) NOT NULL DEFAULT ('Y'),
    [InputGroupId] VARCHAR(36) NULL DEFAULT ,
    [InputType] VARCHAR(10) NULL DEFAULT ('MANUAL'),
    [WarehouseCode] VARCHAR(20) NULL DEFAULT ,
    [LotNo] VARCHAR(500) NULL DEFAULT ,
    [CompanyCode] VARCHAR(20) NULL DEFAULT ,
    [LotID] NVARCHAR(50) NULL DEFAULT ,
    [InputReasonCode] VARCHAR(50) NULL DEFAULT 
);
GO

