CREATE TABLE [dbo].[STB_VN_STAMP_FOXCONN] (
    [CPN] VARCHAR(50) NULL DEFAULT ,
    [Qty] NUMERIC(20,5) NULL DEFAULT ,
    [MaterialCode] VARCHAR(50) NULL DEFAULT ,
    [GRDate] VARCHAR(50) NULL DEFAULT ,
    [LotNo] VARCHAR(50) NULL DEFAULT ,
    [PackingID] VARCHAR(50) NULL DEFAULT ,
    [COO] VARCHAR(50) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(50) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(50) NULL DEFAULT ,
    [id] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [ParentPackingID] VARCHAR(50) NULL DEFAULT ,
    [TypeBox] INT NULL DEFAULT 
);
GO

