CREATE TABLE [dbo].[STB_SFGWarehouse_VVTF3] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [OldControlNo] VARCHAR(20) NULL DEFAULT ,
    [NewBarcode] VARCHAR(50) NULL DEFAULT ,
    [ProdQty] INT NULL DEFAULT ,
    [WHStatus] VARCHAR(10) NULL DEFAULT ,
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [ExportUserID] VARCHAR(20) NULL DEFAULT ,
    [ExportDateTime] DATETIME NULL DEFAULT 
);
GO

