CREATE TABLE [dbo].[stb_SDValueTest] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [IDParam] VARCHAR(20) NULL DEFAULT ,
    [V1] NVARCHAR(10) NULL DEFAULT ,
    [V2] NVARCHAR(10) NULL DEFAULT ,
    [DV] NVARCHAR(10) NULL DEFAULT ,
    [Result] NVARCHAR(10) NULL DEFAULT ,
    [CreateDate] DATETIME NULL DEFAULT ,
    [Attribute1] NVARCHAR(50) NULL DEFAULT ,
    [Attribute2] NVARCHAR(50) NULL DEFAULT ,
    [Attribute3] NVARCHAR(50) NULL DEFAULT 
);
GO

