CREATE TABLE [dbo].[STB_MachineByRoute_HN] (
    [RouteCode] VARCHAR(20) NOT NULL DEFAULT ,
    [MachineName] VARCHAR(50) NOT NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT ,
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [IsUsed] BIT NULL DEFAULT 
);
GO

