CREATE TABLE [dbo].[STB_DigiKeySingleLevelPackagePrintHist] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [PackListNumber] NVARCHAR(50) NULL DEFAULT ,
    [PackageCount] VARCHAR(10) NULL DEFAULT ,
    [SUMPackage] VARCHAR(5) NULL DEFAULT ,
    [Weight] VARCHAR(5) NULL DEFAULT ,
    [CREATEUSERID] NVARCHAR(30) NULL DEFAULT ,
    [CREATEDATE] DATETIME NULL DEFAULT 
);
GO

