CREATE TABLE [dbo].[STB_VN_CATEGORIES] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [TYPEINPUT] NVARCHAR(100) NULL DEFAULT ,
    [INPUT] NVARCHAR(100) NULL DEFAULT ,
    [UNIT] NVARCHAR(20) NULL DEFAULT ,
    [REMARK] NVARCHAR(500) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] NVARCHAR(50) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] NVARCHAR(50) NULL DEFAULT ,
    [IsUse] BIT NULL DEFAULT 
);
GO

