CREATE TABLE [dbo].[STB_QC_LOTNO_MODULE] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [LOTNO] NVARCHAR(50) NULL DEFAULT ,
    [DATEBASIC] DATETIME NULL DEFAULT ,
    [METERIALNAME] NVARCHAR(100) NULL DEFAULT ,
    [NAMEMODEL] NVARCHAR(100) NULL DEFAULT ,
    [PARTNO] NVARCHAR(50) NULL DEFAULT ,
    [Descriptions] NVARCHAR(500) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] NVARCHAR(50) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] NVARCHAR(50) NULL DEFAULT ,
    [Size] NVARCHAR(20) NULL DEFAULT ,
    [Voltage] NVARCHAR(20) NULL DEFAULT ,
    [Farad] NVARCHAR(20) NULL DEFAULT ,
    [Rating] NVARCHAR(20) NULL DEFAULT ,
    [Person] NVARCHAR(50) NULL DEFAULT ,
    [CreateDateTimePackge] DATETIME NULL DEFAULT ,
    [LotQty] INT NULL DEFAULT ,
    [STATUSPSS] NVARCHAR(20) NULL DEFAULT ,
    [PersonCheck] NVARCHAR(50) NULL DEFAULT ,
    [MATERIALCODE] NVARCHAR(50) NULL DEFAULT 
);
GO

