CREATE TABLE [dbo].[STB_MaterialQcInfo_240903] (
    [MaterialQcNo] VARCHAR(20) NOT NULL DEFAULT ,
    [CompanyCode] VARCHAR(20) NULL DEFAULT ,
    [WorkCenterCode] VARCHAR(20) NULL DEFAULT ,
    [InspectionDocType] VARCHAR(10) NULL DEFAULT ,
    [MaterialCode] VARCHAR(50) NULL DEFAULT ,
    [QcQty] NUMERIC(20,5) NULL DEFAULT ,
    [InspectionType] VARCHAR(10) NULL DEFAULT ,
    [BasicDate] DATE NULL DEFAULT ,
    [TargetSampleQty] INT NULL DEFAULT ,
    [ActualSampleQty] INT NULL DEFAULT ,
    [DestoryInspectionQty] INT NULL DEFAULT ,
    [ProcessQty] NUMERIC(20,5) NULL DEFAULT ,
    [MaxAcceptDefectQty] INT NULL DEFAULT ,
    [PassedSampleQty] INT NULL DEFAULT ,
    [DefectSampleQty] INT NULL DEFAULT ,
    [DecisionResult] VARCHAR(10) NULL DEFAULT ,
    [DecisionDateTime] DATETIME NULL DEFAULT ,
    [DecisionUserID] VARCHAR(20) NULL DEFAULT ,
    [SpecialAcceptDesc] NVARCHAR(100) NULL DEFAULT ,
    [DescText] NVARCHAR(MAX) NULL DEFAULT ,
    [VendorQcReport] BIGINT NULL DEFAULT ,
    [VendorLotNo] VARCHAR(100) NULL DEFAULT ,
    [MIIExtText01] NVARCHAR(MAX) NULL DEFAULT ,
    [MIIExtText02] NVARCHAR(MAX) NULL DEFAULT ,
    [MIIExtText03] NVARCHAR(MAX) NULL DEFAULT ,
    [MIIExtText04] NVARCHAR(MAX) NULL DEFAULT ,
    [MIIExtText05] NVARCHAR(MAX) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT ,
    [IQCSampleLotList] NVARCHAR(MAX) NULL DEFAULT 
);
GO

