CREATE TABLE [dbo].[STB_IQcDefectReport] (
    [DefectReportNo] VARCHAR(20) NOT NULL DEFAULT ,
    [DefectDivisionCode] VARCHAR(3) NULL DEFAULT ,
    [PublishDeptCode] VARCHAR(20) NULL DEFAULT ,
    [PublishEmpID] VARCHAR(20) NULL DEFAULT ,
    [OccurProcessCode] VARCHAR(3) NULL DEFAULT ,
    [LotNo] VARCHAR(80) NULL DEFAULT ,
    [ProdProcessResultCode] VARCHAR(2) NULL DEFAULT ,
    [CorrectiveActionCode] VARCHAR(2) NULL DEFAULT ,
    [CorrectiveActionName] VARCHAR(50) NULL DEFAULT ,
    [DefectImage] VARBINARY(MAX) NULL DEFAULT ,
    [DefectLotSize] INT NULL DEFAULT ,
    [IsActionCode] BIT NULL DEFAULT ,
    [Nonconformity] NVARCHAR(4000) NULL DEFAULT ,
    [ImmediateAction] NVARCHAR(4000) NULL DEFAULT ,
    [CauseInvestigation] NVARCHAR(4000) NULL DEFAULT ,
    [PreventionRecurrence] NVARCHAR(4000) NULL DEFAULT ,
    [DetectionCounterMeasures] NVARCHAR(4000) NULL DEFAULT ,
    [CheckingCorrectiveAction] NVARCHAR(4000) NULL DEFAULT ,
    [Validation] NVARCHAR(4000) NULL DEFAULT ,
    [JobDate] DATETIME NULL DEFAULT ,
    [CreateDateTime] DATETIME NOT NULL DEFAULT (getdate()),
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT ,
    [ProdProcessResultFile] BIGINT NULL DEFAULT ,
    [ApprovalStepID] INT NULL DEFAULT ,
    [DefectImage2] VARBINARY(MAX) NULL DEFAULT ,
    [QcOpinionContent] NVARCHAR(400) NULL DEFAULT ,
    [IsQcHeadConfirm] BIT NULL DEFAULT ,
    [InspectionQty] INT NULL DEFAULT ,
    [DefectiveRate] NUMERIC(5,2) NULL DEFAULT ,
    [NonconformityRate] NUMERIC(5,2) NULL DEFAULT ,
    [DefectImageUrl] VARCHAR(500) NULL DEFAULT ,
    [ActionContent] NVARCHAR(4000) NULL DEFAULT 
);
GO

