CREATE TABLE [dbo].[STB_PACBoxLabalPrintHist] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [LotNo] VARCHAR(30) NULL DEFAULT ,
    [LabelQty] VARCHAR(2) NULL DEFAULT ,
    [LabelType] NVARCHAR(20) NULL DEFAULT ,
    [PN] VARCHAR(50) NULL DEFAULT ,
    [DC] VARCHAR(10) NULL DEFAULT ,
    [Qty] VARCHAR(5) NULL DEFAULT ,
    [Reel] VARCHAR(30) NULL DEFAULT ,
    [MPN] VARCHAR(20) NULL DEFAULT ,
    [VN] VARCHAR(100) NULL DEFAULT ,
    [CREATEUSERID] NVARCHAR(30) NULL DEFAULT ,
    [CREATEDATE] DATETIME NULL DEFAULT 
);
GO

