CREATE TABLE [dbo].[STB_ProductionOrderSalesInfo] (
    [PoSalesNo] BIGINT IDENTITY(1,1) NOT NULL DEFAULT ,
    [PONo] VARCHAR(20) NULL DEFAULT ,
    [SOISequence] BIGINT NULL DEFAULT ,
    [PlanQty] NUMERIC(20,5) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT 
);
GO

