CREATE TABLE [dbo].[STB_LICENSE_CODE] (
    [LCODE] VARCHAR(10) NOT NULL DEFAULT ,
    [LNAME] VARCHAR(30) NOT NULL DEFAULT ,
    [REG_DATE] DATE NOT NULL DEFAULT (getdate()),
    [REG_YMS] DATETIME NOT NULL DEFAULT (getdate()),
    [UDT_DATE] DATE NOT NULL DEFAULT (getdate()),
    [UDT_YMS] DATETIME NOT NULL DEFAULT (getdate())
);
GO

