CREATE TABLE [dbo].[STB_VN_STAMP_HONGKONG] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [PARTNO] NVARCHAR(50) NULL DEFAULT ,
    [LOTNO] NVARCHAR(50) NULL DEFAULT ,
    [PARTNAME] NVARCHAR(50) NULL DEFAULT ,
    [QTY] INT NULL DEFAULT ,
    [VENDOR] NVARCHAR(50) NULL DEFAULT ,
    [PRODUCTIONDATE] NVARCHAR(50) NULL DEFAULT ,
    [GROSSWEIGHT] NVARCHAR(50) NULL DEFAULT ,
    [PONOLINE] NVARCHAR(50) NULL DEFAULT ,
    [CREATEDATETIME] DATETIME NULL DEFAULT ,
    [CREATEUSERID] NVARCHAR(50) NULL DEFAULT ,
    [CHANGEDATETIME] NVARCHAR(50) NULL DEFAULT ,
    [CHANGEUSERID] NVARCHAR(50) NULL DEFAULT ,
    [ISCHECK] BIT NULL DEFAULT 
);
GO

