CREATE TABLE [dbo].[STB_VN_FINISHGOODS_ConfigPosition] (
    [Id] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [LotNo] NVARCHAR(50) NOT NULL DEFAULT ,
    [Qty] INT NOT NULL DEFAULT ,
    [Position] NVARCHAR(50) NULL DEFAULT ,
    [CreatedBy] NVARCHAR(50) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT 
);
GO

