CREATE TABLE [dbo].[STB_SalesMonthlyPlan] (
    [SalesIndex] BIGINT IDENTITY(1,1) NOT NULL DEFAULT ,
    [Region] VARCHAR(30) NULL DEFAULT ,
    [SizeW] INT NULL DEFAULT ,
    [SizeH] INT NULL DEFAULT ,
    [Volt] NUMERIC(3,1) NULL DEFAULT ,
    [Farad] NUMERIC(20,1) NULL DEFAULT ,
    [BaseMonth] VARCHAR(7) NULL DEFAULT ,
    [PlanQty] INT NULL DEFAULT 
);
GO

