CREATE TABLE [dbo].[STB_LineSituation_VVT] (
    [id] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [linecode] VARCHAR(20) NOT NULL DEFAULT ,
    [linename] VARCHAR(50) NULL DEFAULT ,
    [errorcode] NVARCHAR(1000) NULL DEFAULT ,
    [errorname] NVARCHAR(1000) NULL DEFAULT ,
    [routecode] VARCHAR(20) NULL DEFAULT ,
    [routename] NVARCHAR(50) NULL DEFAULT ,
    [status] BIT NULL DEFAULT ,
    [statusApp] INT NULL DEFAULT ,
    [statusEmail] INT NULL DEFAULT ,
    [createdatetime] DATETIME NULL DEFAULT (getdate()),
    [createuserid] VARCHAR(50) NULL DEFAULT ,
    [UserName] NVARCHAR(MAX) NULL DEFAULT ,
    [CategoryErrorRouteID] INT NULL DEFAULT ,
    [ChildCategoryErrorRouteID] INT NULL DEFAULT ,
    [DescriptionInputError] NVARCHAR(MAX) NULL DEFAULT ,
    [DiscovererInputError] NVARCHAR(MAX) NULL DEFAULT ,
    [WorkerInputError] NVARCHAR(MAX) NULL DEFAULT ,
    [ReasonChangeError] NVARCHAR(MAX) NULL DEFAULT ,
    [StrategyChangeError] NVARCHAR(MAX) NULL DEFAULT ,
    [RepairerChangeError] NVARCHAR(MAX) NULL DEFAULT ,
    [BeginChangeErrorStatus] BIT NULL DEFAULT ,
    [BeginChangeErrorCreateTime] DATETIME2 NULL DEFAULT ,
    [TotalFinishCreateTime] NVARCHAR(MAX) NULL DEFAULT ,
    [TotalFailureTime] NVARCHAR(MAX) NULL DEFAULT ,
    [FinishChangeErrorStatus] BIT NULL DEFAULT ,
    [FinishCreateTime] DATETIME2 NULL DEFAULT ,
    [CreateTime] DATETIME2 NULL DEFAULT ,
    [DetailErrorDifferent] NVARCHAR(MAX) NULL DEFAULT 
);
GO

