CREATE TABLE [dbo].[STB_CommInspItem] (
    [CommInspItemCode] VARCHAR(50) NOT NULL DEFAULT ,
    [CommInspTypeCode] VARCHAR(50) NOT NULL DEFAULT ,
    [CompanyCode] VARCHAR(20) NULL DEFAULT ,
    [WorkCenterCode] VARCHAR(20) NULL DEFAULT ,
    [RouteCode] VARCHAR(20) NULL DEFAULT ,
    [MachineCode] VARCHAR(20) NULL DEFAULT ,
    [MoldNumber] VARCHAR(50) NULL DEFAULT ,
    [MaterialCode] VARCHAR(50) NULL DEFAULT ,
    [CategoryName] NVARCHAR(50) NULL DEFAULT ,
    [DisplayIndex] INT NULL DEFAULT ,
    [CommInspItemGroup1] NVARCHAR(100) NULL DEFAULT ,
    [CommInspItemGroup2] NVARCHAR(100) NULL DEFAULT ,
    [CommInspItemGroup3] NVARCHAR(100) NULL DEFAULT ,
    [CommInspItemName] NVARCHAR(150) NULL DEFAULT ,
    [CommInspUnit] VARCHAR(20) NULL DEFAULT ,
    [CommInspItemDesc] NVARCHAR(250) NULL DEFAULT ,
    [CommInspInputType] VARCHAR(1) NULL DEFAULT ,
    [CommInspSelectGroupCode] VARCHAR(20) NULL DEFAULT ,
    [CommInspItemSpec] VARCHAR(50) NULL DEFAULT ,
    [CommInspUpper] VARCHAR(50) NULL DEFAULT ,
    [CommInspLower] VARCHAR(50) NULL DEFAULT ,
    [ItemImageFileID] BIGINT NULL DEFAULT ,
    [ItemTargetQty] INT NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT ,
    [IsIndividualSpec] BIT NULL DEFAULT ,
    [FacilityRouteCode] VARCHAR(20) NULL DEFAULT ,
    [ProductGroupCode] VARCHAR(20) NULL DEFAULT ,
    [LineCode] VARCHAR(20) NULL DEFAULT 
);
GO

