CREATE TABLE [dbo].[STB_VNSparePartInfo] (
    [SparePartCode] VARCHAR(20) NOT NULL DEFAULT ,
    [SparePartName] NVARCHAR(100) NULL DEFAULT ,
    [SparePartSpec01] NVARCHAR(100) NULL DEFAULT ,
    [SparePartSpec02] NVARCHAR(100) NULL DEFAULT ,
    [SparePartSpec03] NVARCHAR(100) NULL DEFAULT ,
    [SparePartSpec04] NVARCHAR(100) NULL DEFAULT ,
    [SparePartSpec05] NVARCHAR(100) NULL DEFAULT ,
    [SparePartImage] BIGINT NULL DEFAULT ,
    [BasicUnitPrice] NUMERIC(15,2) NULL DEFAULT ,
    [BasicDeliveryDay] INT NULL DEFAULT ,
    [BasicUnit] VARCHAR(20) NULL DEFAULT ,
    [SafeQty] NUMERIC(20,5) NULL DEFAULT ,
    [LastDeliveryVendor] VARCHAR(20) NULL DEFAULT ,
    [CompatibilityGroup] NVARCHAR(50) NULL DEFAULT ,
    [IsUsed] BIT NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT ,
    [MaxSafeQty] NUMERIC(20,5) NULL DEFAULT ,
    [TypeCode] NVARCHAR(50) NULL DEFAULT ,
    [Attribute] NVARCHAR(200) NULL DEFAULT ,
    [Attribute1] NVARCHAR(200) NULL DEFAULT ,
    [Attribute2] NVARCHAR(200) NULL DEFAULT ,
    [Attribute3] NVARCHAR(200) NULL DEFAULT ,
    [Attribute4] NVARCHAR(200) NULL DEFAULT ,
    [Attribute5] NVARCHAR(200) NULL DEFAULT ,
    [Position] NVARCHAR(200) NULL DEFAULT ,
    [IsSpecial] BIT NULL DEFAULT ,
    [CompanyCode] VARCHAR(20) NULL DEFAULT ('VVT'),
    [WorkCenterCode] VARCHAR(20) NULL DEFAULT ,
    [NameWorkCenterCode] NVARCHAR(50) NULL DEFAULT ,
    [PositionBG] NVARCHAR(200) NULL DEFAULT ,
    [CurrentStock] NUMERIC(18,0) NULL DEFAULT 
);
GO

