CREATE TABLE [dbo].[STB_MaterialOrder] (
    [MaterialOrderNo] VARCHAR(20) NOT NULL DEFAULT ,
    [CompanyCode] VARCHAR(20) NULL DEFAULT ,
    [WorkCenterCode] VARCHAR(20) NULL DEFAULT ,
    [MOCreateType] VARCHAR(10) NULL DEFAULT ,
    [MaterialOrderType] VARCHAR(20) NULL DEFAULT ,
    [CustomerCode] VARCHAR(20) NULL DEFAULT ,
    [OrderFromUserID] VARCHAR(20) NULL DEFAULT ,
    [OrderToName] NVARCHAR(50) NULL DEFAULT ,
    [MaterialWarehouseCode] VARCHAR(20) NULL DEFAULT ,
    [OrderDate] DATE NULL DEFAULT ,
    [DeliveryPlanDate] DATE NULL DEFAULT ,
    [TotalItemQty] INT NULL DEFAULT ,
    [TotalOrderPrice] NUMERIC(20,5) NULL DEFAULT ,
    [OrderStatus] VARCHAR(10) NULL DEFAULT ,
    [IsAllCancel] BIT NULL DEFAULT ,
    [AllCencelUserID] VARCHAR(20) NULL DEFAULT ,
    [IsFinished] BIT NULL DEFAULT ,
    [FinishedUserID] VARCHAR(20) NULL DEFAULT ,
    [MOExtText01] NVARCHAR(MAX) NULL DEFAULT ,
    [MOExtText02] NVARCHAR(MAX) NULL DEFAULT ,
    [MOExtText03] NVARCHAR(MAX) NULL DEFAULT ,
    [MOExtText04] NVARCHAR(MAX) NULL DEFAULT ,
    [MOExtText05] NVARCHAR(MAX) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT 
);
GO

