CREATE TABLE [dbo].[STB_PackingQtyWarehouse] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [ModelCode] VARCHAR(50) NULL DEFAULT ,
    [ModelName] VARCHAR(100) NULL DEFAULT ,
    [Qty] NVARCHAR(20) NULL DEFAULT ,
    [Kind] NVARCHAR(100) NULL DEFAULT ,
    [IsUsed] BIT NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT 
);
GO

