CREATE TABLE [dbo].[STB_QC_LOTNO_MODULE_VALUES] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [LOTNO] NVARCHAR(50) NULL DEFAULT ,
    [NAMETYPE] NVARCHAR(50) NULL DEFAULT ,
    [NUMBERID] INT NULL DEFAULT ,
    [VALUESCHECK] FLOAT NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] NVARCHAR(50) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] NVARCHAR(50) NULL DEFAULT 
);
GO

