CREATE TABLE [dbo].[STB_VN_PRODUCTION_ERROR_HISTORY] (
    [IDPE] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [Line] NVARCHAR(30) NOT NULL DEFAULT ,
    [Model] NVARCHAR(50) NULL DEFAULT ,
    [Item] NVARCHAR(120) NULL DEFAULT ,
    [NG] NVARCHAR(50) NULL DEFAULT ,
    [NameError] NVARCHAR(50) NULL DEFAULT ,
    [Weights] FLOAT NULL DEFAULT ,
    [InputDate] DATETIME NULL DEFAULT ,
    [StatusError] NVARCHAR(50) NULL DEFAULT ,
    [NameShift] NVARCHAR(50) NULL DEFAULT ,
    [Flag] BIT NULL DEFAULT ,
    [Decs] NVARCHAR(20) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT ,
    [UNIT] NVARCHAR(20) NULL DEFAULT ,
    [PersonAction] NVARCHAR(50) NULL DEFAULT ,
    [DateAction] DATETIME NULL DEFAULT ,
    [TypeAction] NVARCHAR(20) NULL DEFAULT 
);
GO

