CREATE TABLE [dbo].[STB_VN_MODEL_INVENTORY] (
    [IDM] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [CODEMODEL] NVARCHAR(100) NULL DEFAULT ,
    [NAMES] NVARCHAR(150) NULL DEFAULT ,
    [IsUsed] BIT NULL DEFAULT ,
    [DECRISPTION] NVARCHAR(500) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] NVARCHAR(50) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] NVARCHAR(50) NULL DEFAULT 
);
GO

