CREATE TABLE [dbo].[STB_CompanyInfo] (
    [CompanyCode] VARCHAR(20) NOT NULL DEFAULT ,
    [CompanyName] NVARCHAR(50) NULL DEFAULT ,
    [CompanyNameL] NVARCHAR(50) NULL DEFAULT ,
    [CompanyDesc] NVARCHAR(200) NULL DEFAULT ,
    [CompanyDescL] NVARCHAR(200) NULL DEFAULT ,
    [IsUsed] BIT NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT ,
    [CD_COMPANY] VARCHAR(10) NULL DEFAULT 
);
GO

