CREATE TABLE [dbo].[STB_EMPLOYEES] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [EMPID] NVARCHAR(50) NOT NULL DEFAULT ,
    [FULLNAME] NVARCHAR(50) NULL DEFAULT ,
    [BIRTHDAY] NVARCHAR(50) NULL DEFAULT ,
    [GENDER] NVARCHAR(10) NULL DEFAULT ,
    [STARTWORK] NVARCHAR(50) NULL DEFAULT ,
    [DEPARTMENT] NVARCHAR(50) NULL DEFAULT ,
    [PART] NVARCHAR(50) NULL DEFAULT ,
    [POSITION] NVARCHAR(50) NULL DEFAULT ,
    [ISUED] BIT NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT 
);
GO

