CREATE TABLE [dbo].[STB_VN_CUSTOMER_LABLE] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [RLCS] NVARCHAR(30) NULL DEFAULT ('RLC'),
    [FIXCODE] NVARCHAR(30) NULL DEFAULT ('287016'),
    [YMD] NVARCHAR(50) NULL DEFAULT (CONVERT([varchar],getdate(),(112))),
    [SERIALNO] NVARCHAR(50) NULL DEFAULT ,
    [WNCPNVSID] NVARCHAR(100) NULL DEFAULT ('12.53010.006-287016'),
    [PARTNUMBER] NVARCHAR(200) NULL DEFAULT ('SUPER CAP,DIP,10F,Y(-10/+30),3V,10A,5MM,10X30MM,-40℃~,65℃,AECQ-N,WEC3R0106QG-B080R'),
    [DCBRAND] NVARCHAR(30) NULL DEFAULT ,
    [LOTNO] NVARCHAR(50) NULL DEFAULT ,
    [VINATECHPARTNUMBER] NVARCHAR(50) NULL DEFAULT ('HY-CAP WEC3R0106QG-B080R'),
    [MARKING] NVARCHAR(100) NULL DEFAULT ('WEC3R0106QG-B080R'),
    [QTY] NVARCHAR(10) NULL DEFAULT ,
    [D2QRCODE] NVARCHAR(100) NULL DEFAULT ,
    [CODERLCS] NVARCHAR(150) NULL DEFAULT ,
    [LabelQty] INT NULL DEFAULT ,
    [STATUSPRINTER] BIT NULL DEFAULT ('0'),
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] NVARCHAR(30) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] NVARCHAR(50) NULL DEFAULT 
);
GO

