CREATE TABLE [dbo].[STB_Vietnam_SettingPackLabel] (
    [LotNo] VARCHAR(50) NOT NULL DEFAULT ,
    [OriginalPartno] VARCHAR(50) NOT NULL DEFAULT ,
    [VVorVJ] VARCHAR(50) NOT NULL DEFAULT ,
    [newLotNo] VARCHAR(50) NULL DEFAULT ,
    [newPartNo] VARCHAR(50) NULL DEFAULT ,
    [PrintTime] VARCHAR(50) NULL DEFAULT ,
    [id] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [Vol] VARCHAR(50) NULL DEFAULT 
);
GO

