CREATE TABLE [dbo].[STB_VN_DETAILMODULES] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [GROUPID] NVARCHAR(100) NULL DEFAULT ,
    [LOTNO] NVARCHAR(50) NULL DEFAULT ,
    [QTYACT] INT NULL DEFAULT ,
    [MaterialCode] NVARCHAR(50) NULL DEFAULT ,
    [MaterialName] NVARCHAR(100) NULL DEFAULT ,
    [LineCode] NVARCHAR(20) NULL DEFAULT ,
    [RouteCode] NVARCHAR(20) NULL DEFAULT ,
    [RouteName] NVARCHAR(30) NULL DEFAULT ,
    [InputProdQty] NVARCHAR(30) NULL DEFAULT ,
    [DefectQty] NVARCHAR(30) NULL DEFAULT ,
    [ProdQty] NVARCHAR(30) NULL DEFAULT ,
    [CREATEDATEPACKED] DATETIME NULL DEFAULT ,
    [CREATEDATETIME] DATETIME NULL DEFAULT ,
    [CREATEUSSERID] NVARCHAR(50) NULL DEFAULT ,
    [CHANGEDATETIME] DATETIME NULL DEFAULT ,
    [CHANGEUSERID] NVARCHAR(50) NULL DEFAULT ,
    [STATUSAGAING] NVARCHAR(50) NULL DEFAULT 
);
GO

