CREATE TABLE [dbo].[STB_VN_FINISHGOOD] (
    [IDFG] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [LotID] NVARCHAR(70) NULL DEFAULT ,
    [LotNo] NVARCHAR(70) NULL DEFAULT ,
    [MaterialQcNo] NVARCHAR(70) NULL DEFAULT ,
    [MaterialCode] NVARCHAR(70) NULL DEFAULT ,
    [DecisionResult] NVARCHAR(20) NULL DEFAULT ,
    [CurrentQty] INT NULL DEFAULT ,
    [INPUT] NVARCHAR(30) NULL DEFAULT (N'Nhập'),
    [OUTPUTS] NVARCHAR(30) NULL DEFAULT ,
    [DateIn] DATETIME NULL DEFAULT ,
    [DateOut] DATETIME NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT 
);
GO

