CREATE TABLE [dbo].[STB_VN_EMPLOYEESTRANSFERLINE] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [EMPLOYEESID] NVARCHAR(50) NULL DEFAULT ,
    [EMPLOYEESNAME] NVARCHAR(50) NULL DEFAULT ,
    [DEPARTMENTNAME] NVARCHAR(50) NULL DEFAULT ,
    [CODEDEPARTMENT] NVARCHAR(50) NULL DEFAULT ,
    [CODELINE] NVARCHAR(50) NULL DEFAULT ,
    [NAMELINE] NVARCHAR(50) NULL DEFAULT ,
    [CODELINEMOVE] NVARCHAR(50) NULL DEFAULT ,
    [NAMELINEMOVE] NVARCHAR(50) NULL DEFAULT ,
    [POSISTION] NVARCHAR(50) NULL DEFAULT ,
    [EFFECTIVEDATE] DATETIME NULL DEFAULT ,
    [SHIFTCONTRACT] NVARCHAR(50) NULL DEFAULT ,
    [CREATEDATETIME] DATETIME NULL DEFAULT ,
    [CREATEUSERID] NVARCHAR(50) NULL DEFAULT ,
    [CHANGEDATETIME] DATETIME NULL DEFAULT 
);
GO

