CREATE TABLE [dbo].[STB_MoldRepairHistory] (
    [RepairHistNo] VARCHAR(20) NOT NULL DEFAULT ,
    [MoldNumber] VARCHAR(20) NULL DEFAULT ,
    [WorkCenterCode] VARCHAR(20) NULL DEFAULT ,
    [RepairType] VARCHAR(1) NULL DEFAULT ,
    [ApprovalDate1] DATETIME NULL DEFAULT ,
    [ApprovalUser1] VARCHAR(20) NULL DEFAULT ,
    [ApprovalDate2] DATETIME NULL DEFAULT ,
    [ApprovalUser2] VARCHAR(20) NULL DEFAULT ,
    [ApprovalDate3] DATETIME NULL DEFAULT ,
    [ApprovalUser3] VARCHAR(20) NULL DEFAULT ,
    [ApprovalDate4] DATETIME NULL DEFAULT ,
    [ApprovalUser4] VARCHAR(20) NULL DEFAULT ,
    [MaterialType] VARCHAR(50) NULL DEFAULT ,
    [ProductionWorkCenter] VARCHAR(20) NULL DEFAULT ,
    [RequestWorkCenter] VARCHAR(20) NULL DEFAULT ,
    [RequestUser] VARCHAR(50) NULL DEFAULT ,
    [RequestDate] DATE NULL DEFAULT ,
    [DemandDate] DATE NULL DEFAULT ,
    [TotalProdQty] INT NULL DEFAULT ,
    [DeliveryQty] INT NULL DEFAULT ,
    [CauseImageID] BIGINT NULL DEFAULT ,
    [CauseText] VARCHAR(MAX) NULL DEFAULT ,
    [MeasureText] VARCHAR(MAX) NULL DEFAULT ,
    [DevUser] VARCHAR(50) NULL DEFAULT ,
    [GIDate] DATE NULL DEFAULT ,
    [RepairTerm] NUMERIC(5,2) NULL DEFAULT ,
    [GRDate] DATE NULL DEFAULT ,
    [TestDate] DATE NULL DEFAULT ,
    [RepairVendor] VARCHAR(20) NULL DEFAULT ,
    [CompleteDate] DATE NULL DEFAULT ,
    [CompleteCheckUser] VARCHAR(20) NULL DEFAULT ,
    [StockProdQtyPerDay] INT NULL DEFAULT ,
    [StockProdWorkCenter] VARCHAR(20) NULL DEFAULT ,
    [StockWipQty] INT NULL DEFAULT ,
    [StockTotalQty] INT NULL DEFAULT ,
    [StockCompleteDate] DATE NULL DEFAULT ,
    [ProblemText] VARCHAR(MAX) NULL DEFAULT ,
    [EONO] VARCHAR(50) NULL DEFAULT ,
    [EONOFileID] BIGINT NULL DEFAULT ,
    [RepairText] VARCHAR(MAX) NULL DEFAULT ,
    [Relations] VARCHAR(MAX) NULL DEFAULT ,
    [IsComplete] BIT NULL DEFAULT ,
    [EtcText] VARCHAR(MAX) NULL DEFAULT ,
    [DocFileID] BIGINT NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT 
);
GO

