CREATE TABLE [dbo].[STB_VN_Shift] (
    [IDS] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [CodeShift] NVARCHAR(10) NULL DEFAULT ,
    [NameShift] NVARCHAR(50) NULL DEFAULT ,
    [FromTime] DATETIME NULL DEFAULT ,
    [ToTime] DATETIME NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] NVARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] NVARCHAR(20) NULL DEFAULT ,
    [IsUsed] BIT NULL DEFAULT 
);
GO

