CREATE TABLE [dbo].[STB_ManufacturingCostExtend] (
    [ApplyDate] DATE NOT NULL DEFAULT ,
    [CompanyCode] VARCHAR(20) NOT NULL DEFAULT ,
    [WorkCenterCode] VARCHAR(20) NOT NULL DEFAULT ,
    [MaterialCode] VARCHAR(20) NOT NULL DEFAULT ,
    [IsManual] BIT NOT NULL DEFAULT ,
    [ActivatedCarbonCostPrice] NUMERIC(20,10) NULL DEFAULT ,
    [ActiveMaterialCostPrice] NUMERIC(20,10) NULL DEFAULT ,
    [ConductiveMaterialCostPrice] NUMERIC(20,10) NULL DEFAULT ,
    [BinderCostPrice] NUMERIC(20,10) NULL DEFAULT ,
    [SurfactantCostPrice] NUMERIC(20,10) NULL DEFAULT ,
    [MenstruumCostPrice] NUMERIC(20,10) NULL DEFAULT ,
    [CurrentCollectorCostPrice] NUMERIC(20,10) NULL DEFAULT ,
    [TerminalCostPrice] NUMERIC(20,10) NULL DEFAULT ,
    [ATLTerminalCostPrice] NUMERIC(20,10) NULL DEFAULT ,
    [SeparatorCostPrice] NUMERIC(20,10) NULL DEFAULT ,
    [PiTapeCostPrice] NUMERIC(20,10) NULL DEFAULT ,
    [RubberStopperCostPrice] NUMERIC(20,10) NULL DEFAULT ,
    [TerminalBoardCostPrice] NUMERIC(20,10) NULL DEFAULT ,
    [WasherCostPrice] NUMERIC(20,10) NULL DEFAULT ,
    [ElectrolyteCostPrice] NUMERIC(20,10) NULL DEFAULT ,
    [CaseCostPrice] NUMERIC(20,10) NULL DEFAULT ,
    [SleeveCostPrice] NUMERIC(20,10) NULL DEFAULT ,
    [BottomPlateCostPrice] NUMERIC(20,10) NULL DEFAULT ,
    [PackagingMaterialCostPrice] NUMERIC(20,10) NULL DEFAULT ,
    [PCBForModuleCostPrice] NUMERIC(20,10) NULL DEFAULT ,
    [WireForModuleCostPrice] NUMERIC(20,10) NULL DEFAULT ,
    [MaterialCostPrice] NUMERIC(20,10) NULL DEFAULT ,
    [LaborCostPrice] NUMERIC(20,10) NULL DEFAULT ,
    [OverheadCostPrice] NUMERIC(20,10) NULL DEFAULT ,
    [CreateDateTime] DATETIME NOT NULL DEFAULT (getdate()),
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT ,
    CONSTRAINT [PK_STB_ManufacturingCostExtend] PRIMARY KEY CLUSTERED ([ApplyDate], [CompanyCode], [WorkCenterCode], [MaterialCode])
);
GO

