CREATE TABLE [dbo].[STB_ProdRouteHistNotes] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [ControlNo] VARCHAR(50) NULL DEFAULT ,
    [RouteCode] VARCHAR(50) NULL DEFAULT ,
    [Notes] NVARCHAR(MAX) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT 
);
GO

