CREATE TABLE [dbo].[STB_VN_STAGEMACHINES_MATERS] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [CODEIDM] NVARCHAR(30) NULL DEFAULT ,
    [Stagename] NVARCHAR(50) NULL DEFAULT ,
    [Actives] BIT NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] NVARCHAR(50) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] NVARCHAR(50) NULL DEFAULT ,
    [Vietnamese] NVARCHAR(50) NULL DEFAULT ,
    [Korean] NVARCHAR(50) NULL DEFAULT 
);
GO

