CREATE TABLE [dbo].[Stb_LogWeight] (
    [Id] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [LineCode] NVARCHAR(50) NULL DEFAULT ,
    [Value] REAL NOT NULL DEFAULT ,
    [CreatedAt] DATETIME NULL DEFAULT (getdate()),
    [Ip] VARCHAR(50) NOT NULL DEFAULT ,
    [LineNum] NVARCHAR(50) NULL DEFAULT ,
    [Barcode] NVARCHAR(100) NULL DEFAULT 
);
GO

