CREATE TABLE [dbo].[STB_VN_ITEM_CHECK] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [CODELINE] NVARCHAR(20) NULL DEFAULT ,
    [NAMELINE] NVARCHAR(50) NULL DEFAULT ,
    [CATEGORIESCHECK] NVARCHAR(50) NULL DEFAULT ,
    [QTY] FLOAT NULL DEFAULT ,
    [TYPEINPUT] NVARCHAR(200) NULL DEFAULT ,
    [INPUT] NVARCHAR(50) NULL DEFAULT ,
    [UNIT] NVARCHAR(20) NULL DEFAULT ,
    [REMARK] NVARCHAR(4000) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] NVARCHAR(50) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] NVARCHAR(50) NULL DEFAULT ,
    [DEPARTMENT] NVARCHAR(50) NULL DEFAULT ,
    [TYPES] NVARCHAR(50) NULL DEFAULT ,
    [CODENAME] NVARCHAR(50) NULL DEFAULT ,
    [IDS] INT NULL DEFAULT 
);
GO

