CREATE TABLE [dbo].[Stb_Vvt_InvoiceEcus] (
    [SoInvoice] NVARCHAR(50) NOT NULL DEFAULT ,
    [NgayInvoice] DATETIME NULL DEFAULT ,
    [NgayDangKy] DATETIME NULL DEFAULT ,
    [NgayVanDon] DATETIME NULL DEFAULT ,
    [MaGiaoHang] NVARCHAR(50) NULL DEFAULT ,
    [NgayApDung] DATETIME NULL DEFAULT 
);
GO

