CREATE TABLE [dbo].[STB_VN_Form_Request_Machines] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [CODEFORMREQUESTMACHINES] NVARCHAR(100) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] NVARCHAR(50) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] NVARCHAR(50) NULL DEFAULT 
);
GO

