CREATE TABLE [dbo].[STB_CheckScheduleInfo] (
    [CheckScheduleNo] VARCHAR(20) NOT NULL DEFAULT ,
    [CheckStandardNo] VARCHAR(20) NULL DEFAULT ,
    [CheckDate] DATE NULL DEFAULT ,
    [CheckTime] DATETIME NULL DEFAULT ,
    [CheckYn] BIT NULL DEFAULT ,
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT ,
    [IsUsed] BIT NULL DEFAULT ,
    [OccasionalCheckItemName] VARCHAR(100) NULL DEFAULT ,
    [CreateDateTime] DATETIME NOT NULL DEFAULT (getdate()),
    [CSIExtReal01] NUMERIC(10,5) NULL DEFAULT ,
    [CSIExtReal02] NUMERIC(10,5) NULL DEFAULT ,
    [CSIExtReal03] NUMERIC(10,5) NULL DEFAULT ,
    [CSIExtReal04] NUMERIC(10,5) NULL DEFAULT ,
    [CSIExtReal05] NUMERIC(10,5) NULL DEFAULT 
);
GO

