CREATE TABLE [dbo].[STB_MasterAgaing] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [IDCODE] NVARCHAR(50) NOT NULL DEFAULT ,
    [PRODROUTEHISTNO] NVARCHAR(50) NULL DEFAULT ,
    [PONO] NVARCHAR(50) NULL DEFAULT ,
    [DAYPLANNO] NVARCHAR(50) NULL DEFAULT ,
    [CONTROLNO] NVARCHAR(50) NULL DEFAULT ,
    [MATERIALCODE] NVARCHAR(50) NULL DEFAULT ,
    [PRODQTY] INT NULL DEFAULT ,
    [LINECODE] NVARCHAR(20) NULL DEFAULT ,
    [ROUTECODE] NVARCHAR(20) NULL DEFAULT ,
    [MACHINECODE] NVARCHAR(20) NULL DEFAULT ,
    [USERID] NVARCHAR(30) NULL DEFAULT ,
    [DATECREATE] DATETIME NULL DEFAULT ,
    [LOTNO] NVARCHAR(50) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] NVARCHAR(50) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] NVARCHAR(50) NULL DEFAULT 
);
GO

