CREATE TABLE [dbo].[STB_IoTDeviceInfo] (
    [DeviceID] VARCHAR(20) NOT NULL DEFAULT ,
    [DeviceClassCode] VARCHAR(20) NOT NULL DEFAULT ,
    [DeviceLocationCode] NVARCHAR(MAX) NULL DEFAULT ,
    [DeviceCredential] VARCHAR(100) NULL DEFAULT ,
    [CreateDateTime] DATETIME NOT NULL DEFAULT (getdate()),
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT ,
    [IsUsed] BIT NOT NULL DEFAULT (CONVERT([bit],(1),0)),
    [TempLSL] NUMERIC(10,2) NULL DEFAULT ,
    [TempUSL] NUMERIC(10,2) NULL DEFAULT ,
    [HumiLSL] NUMERIC(10,2) NULL DEFAULT ,
    [HumiUSL] NUMERIC(10,2) NULL DEFAULT 
);
GO

