CREATE TABLE [dbo].[STB_VN_ORDER_MATERIALS] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [MaterialCode] NVARCHAR(50) NULL DEFAULT ,
    [MaterialName] NVARCHAR(50) NULL DEFAULT ,
    [QTYACTUALLY] NUMERIC(18,0) NULL DEFAULT ,
    [QTYREQUEST] NUMERIC(18,0) NULL DEFAULT ,
    [EXPECTED_DATE_NEEDED] DATETIME NULL DEFAULT ,
    [APPROVEREDBY] NVARCHAR(50) NULL DEFAULT ,
    [CREATEDATE_APPROVERBY] DATETIME NULL DEFAULT ,
    [LineCode] NVARCHAR(30) NULL DEFAULT ,
    [LineName] NVARCHAR(50) NULL DEFAULT ,
    [STATUS_MATERIALS] NVARCHAR(50) NULL DEFAULT (N'Chờ duyệt'),
    [WorkCenterCode] NVARCHAR(20) NULL DEFAULT ,
    [WorkCenterName] NVARCHAR(50) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] NVARCHAR(50) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] NVARCHAR(50) NULL DEFAULT 
);
GO

