CREATE TABLE [dbo].[STB_ERPLoginHist] (
    [IDX] BIGINT IDENTITY(1,1) NOT NULL DEFAULT ,
    [BaseDate] DATE NULL DEFAULT ,
    [BaseTime] TIME NULL DEFAULT ,
    [ModuleName] NVARCHAR(100) NULL DEFAULT ,
    [MenuID] VARCHAR(50) NULL DEFAULT ,
    [MenuName] NVARCHAR(100) NULL DEFAULT 
);
GO

