CREATE TABLE [dbo].[stb_ExpectedShip] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [Size] NVARCHAR(50) NULL DEFAULT ,
    [Quality] NVARCHAR(20) NULL DEFAULT ,
    [Customer] NVARCHAR(100) NULL DEFAULT ,
    [ShippingDate] DATE NULL DEFAULT ,
    [ProdSchedule] DATE NULL DEFAULT ,
    [QC_SD] NVARCHAR(20) NULL DEFAULT ,
    [QC_ESR] NVARCHAR(20) NULL DEFAULT ,
    [QC_CAPA] NVARCHAR(20) NULL DEFAULT ,
    [Atribute1] NVARCHAR(200) NULL DEFAULT ,
    [Attribute2] NVARCHAR(200) NULL DEFAULT ,
    [Attribute3] NVARCHAR(200) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT ,
    [Status] NVARCHAR(20) NULL DEFAULT ,
    [QC_ETC] NVARCHAR(20) NULL DEFAULT 
);
GO

