CREATE TABLE [dbo].[STB_ProductionPlan] (
    [PlanID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [Month] INT NULL DEFAULT ,
    [DatePlan] DATE NULL DEFAULT ,
    [DayOfWeek] NVARCHAR(10) NULL DEFAULT ,
    [InputESR] NUMERIC(18,2) NULL DEFAULT ,
    [NGESR] NUMERIC(18,2) NULL DEFAULT ,
    [InputSD] NUMERIC(18,2) NULL DEFAULT ,
    [NGSD] NUMERIC(18,2) NULL DEFAULT ,
    [NoteModelNGESR] NVARCHAR(255) NULL DEFAULT ,
    [NoteModelNGSD] NVARCHAR(255) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT (getdate()),
    [CreateUserID] VARCHAR(50) NULL DEFAULT 
);
GO

