CREATE TABLE [dbo].[STB_HelaBarcode] (
    [PackageID] VARCHAR(20) NOT NULL DEFAULT ,
    [PartNo] VARCHAR(20) NOT NULL DEFAULT ('792.282-01'),
    [Quantity] INT NOT NULL DEFAULT ((32)),
    [ManPartNo] VARCHAR(20) NOT NULL DEFAULT ('VEC2R7506QG'),
    [SupplierID] VARCHAR(20) NOT NULL DEFAULT ('100004440'),
    [BatchID] VARCHAR(20) NULL DEFAULT ,
    [PrintYn] BIT NULL DEFAULT ((0)),
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT ,
    [BatchIDQuantityForMAT] VARCHAR(41) NULL DEFAULT ,
    [PartNoSuplierIDForMAT] VARCHAR(52) NOT NULL DEFAULT ,
    [ExpiryDate] VARCHAR(8) NULL DEFAULT ,
    [QrCode] VARCHAR(128) NULL DEFAULT ,
    [ManDate] VARCHAR(20) NULL DEFAULT ,
    [MATCode] VARCHAR(260) NULL DEFAULT 
);
GO

