CREATE TABLE [dbo].[STB_VN_ITEM] (
    [IDI] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [CodeItem] NVARCHAR(100) NULL DEFAULT ,
    [Item] NVARCHAR(100) NULL DEFAULT ,
    [Desc] NVARCHAR(100) NULL DEFAULT ,
    [IsUsed] BIT NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] NVARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] NVARCHAR(20) NULL DEFAULT 
);
GO

