CREATE TABLE [dbo].[STB_RndRawMaterial_HN] (
    [Id] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [Class] NVARCHAR(10) NULL DEFAULT ,
    [MaterialCode] NVARCHAR(50) NULL DEFAULT ,
    [GroupCode] NVARCHAR(50) NULL DEFAULT ,
    [Description] NVARCHAR(MAX) NULL DEFAULT ,
    [Unit] NVARCHAR(5) NULL DEFAULT ,
    [Value] FLOAT NULL DEFAULT ,
    [CreateDate] DATETIME NULL DEFAULT 
);
GO

