CREATE TABLE [dbo].[STB_VN_STAGEMACHINES_DETAIL] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [CODEID] NVARCHAR(30) NULL DEFAULT ,
    [CODEIDM] NVARCHAR(30) NULL DEFAULT ,
    [Categories] NVARCHAR(100) NULL DEFAULT ,
    [Standar] NVARCHAR(100) NULL DEFAULT ,
    [Actives] BIT NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] NVARCHAR(50) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] NVARCHAR(50) NULL DEFAULT ,
    [Korean] NVARCHAR(100) NULL DEFAULT ,
    [English] NVARCHAR(100) NULL DEFAULT 
);
GO

