CREATE TABLE [dbo].[STB_VN_LOCATION] (
    [IDSL] NVARCHAR(50) NOT NULL DEFAULT ,
    [NameLocations] NVARCHAR(50) NULL DEFAULT ,
    [DESCRIPTIONS] NVARCHAR(500) NULL DEFAULT ,
    [Actives] BIT NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] NVARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] NVARCHAR(20) NULL DEFAULT 
);
GO

