CREATE TABLE [dbo].[STB_BasicStatisticsConst] (
    [SampleSize] INT NOT NULL DEFAULT ,
    [A2] NUMERIC(10,4) NULL DEFAULT ,
    [A3] NUMERIC(10,4) NULL DEFAULT ,
    [D2] NUMERIC(10,4) NULL DEFAULT ,
    [D3] NUMERIC(10,4) NULL DEFAULT ,
    [D4] NUMERIC(10,4) NULL DEFAULT ,
    [B3] NUMERIC(10,4) NULL DEFAULT ,
    [B4] NUMERIC(10,4) NULL DEFAULT 
);
GO

