CREATE TABLE [dbo].[STB_ProdWorkerInfo_test] (
    [CompanyCode] VARCHAR(20) NOT NULL DEFAULT ,
    [WorkCenterCode] VARCHAR(20) NOT NULL DEFAULT ,
    [WorkerCode] VARCHAR(20) NOT NULL DEFAULT ,
    [WorkerName] NVARCHAR(50) NULL DEFAULT ,
    [LanguageCode] VARCHAR(20) NULL DEFAULT ,
    [OrgWorkerName] NVARCHAR(50) NULL DEFAULT ,
    [Nationality] NVARCHAR(50) NULL DEFAULT ,
    [EmpNo] VARCHAR(20) NULL DEFAULT ,
    [WorkerImage] VARBINARY(MAX) NULL DEFAULT ,
    [IsUsed] BIT NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT ,
    [IsProdWorker] BIT NULL DEFAULT ,
    [WorkerGroupCode] VARCHAR(20) NULL DEFAULT ,
    [DATEJOIN] DATETIME NULL DEFAULT ,
    [LineCode] VARCHAR(50) NULL DEFAULT 
);
GO

