CREATE TABLE [dbo].[STB_VNSparePartIOHistory] (
    [SparePartIOHistoryNo] VARCHAR(20) NOT NULL DEFAULT ,
    [CompanyCode] VARCHAR(20) NULL DEFAULT ,
    [WorkCenterCode] VARCHAR(20) NULL DEFAULT ,
    [SPWarehouseCode] VARCHAR(20) NULL DEFAULT ,
    [SPLocationCode] VARCHAR(20) NULL DEFAULT ,
    [SparePartIOTypeCode] VARCHAR(20) NULL DEFAULT ,
    [SparePartCode] VARCHAR(20) NULL DEFAULT ,
    [VendorCode] VARCHAR(20) NULL DEFAULT ,
    [UnitPrice] NUMERIC(20,5) NULL DEFAULT ,
    [ProcessQty] NUMERIC(20,5) NULL DEFAULT ,
    [HistoryText] NVARCHAR(100) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT ,
    [CurlingGomaUniqueNo] VARCHAR(20) NULL DEFAULT ,
    [LineCode] VARCHAR(20) NULL DEFAULT ,
    [EmployeeDepartment] NVARCHAR(50) NULL DEFAULT ,
    [Attribute1] NVARCHAR(200) NULL DEFAULT ,
    [Attribute2] NVARCHAR(200) NULL DEFAULT ,
    [Attribute3] NVARCHAR(200) NULL DEFAULT ,
    [Attribute4] NVARCHAR(200) NULL DEFAULT ,
    [Attribute5] NVARCHAR(200) NULL DEFAULT ,
    [BasicDate] DATE NULL DEFAULT ,
    [CodeEmp] NVARCHAR(100) NULL DEFAULT ,
    [InvoiceNo] NVARCHAR(200) NULL DEFAULT 
);
GO

