CREATE TABLE [dbo].[stb_MidlleAgaingHN] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [IDPARAM] INT NULL DEFAULT ,
    [LOTNO] NVARCHAR(30) NULL DEFAULT ,
    [ITEM] NVARCHAR(30) NULL DEFAULT ,
    [UPPERS] NVARCHAR(30) NULL DEFAULT ,
    [LOWERS] NVARCHAR(30) NULL DEFAULT ,
    [MAXS] NVARCHAR(30) NULL DEFAULT ,
    [MINS] NVARCHAR(30) NULL DEFAULT ,
    [AVGS] NVARCHAR(20) NULL DEFAULT ,
    [OO] NVARCHAR(30) NULL DEFAULT ,
    [CPK] NVARCHAR(30) NULL DEFAULT ,
    [COMPUTER] NVARCHAR(50) NULL DEFAULT ,
    [CREATEDATE] DATETIME NULL DEFAULT 
);
GO

