CREATE TABLE [dbo].[Stb_VVT_DopingJIG] (
    [JigID] VARCHAR(30) NOT NULL DEFAULT ,
    [LotInUsed] VARCHAR(30) NULL DEFAULT ,
    [Status] VARCHAR(30) NULL DEFAULT ,
    [LastJig] VARCHAR(30) NULL DEFAULT ,
    [BeginDateTime] DATETIME NULL DEFAULT ,
    [EndDateTime] DATETIME NULL DEFAULT ,
    [Comment1] NVARCHAR(1000) NULL DEFAULT ,
    [Comment2] NVARCHAR(1000) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT 
);
GO

