CREATE TABLE [dbo].[STB_VPCLinePlan] (
    [LineCode] VARCHAR(20) NOT NULL DEFAULT ,
    [PlanQty] NUMERIC(20,4) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT ,
    [LineName] VARCHAR(30) NULL DEFAULT ,
    [RouteCode] VARCHAR(12) NULL DEFAULT ,
    [RouteName] VARCHAR(20) NULL DEFAULT 
);
GO

