CREATE TABLE [dbo].[STB_TypeExport_HN] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [TypeCode] VARCHAR(50) NULL DEFAULT ,
    [TypeName] NVARCHAR(50) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(50) NULL DEFAULT 
);
GO

