CREATE TABLE [dbo].[STB_VN_Module] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [CMDL] NVARCHAR(50) NULL DEFAULT ,
    [CODESM] NVARCHAR(50) NULL DEFAULT ,
    [NameForms] NVARCHAR(50) NULL DEFAULT ,
    [NameModules] NVARCHAR(50) NULL DEFAULT ,
    [PathForms] NVARCHAR(50) NULL DEFAULT ,
    [MainTableNames] NVARCHAR(50) NULL DEFAULT ,
    [DetailTableNames] NVARCHAR(50) NULL DEFAULT ,
    [Descptions] NVARCHAR(500) NULL DEFAULT ,
    [IsUed] BIT NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] NVARCHAR(50) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] NVARCHAR(50) NULL DEFAULT 
);
GO

