CREATE TABLE [dbo].[STB_ElectrodeRouteInspHist] (
    [ElectrodeRouteInspHistNo] VARCHAR(20) NOT NULL DEFAULT ,
    [MeasureDate] DATE NULL DEFAULT ,
    [MaterialName] NVARCHAR(200) NULL DEFAULT ,
    [Barcode] VARCHAR(20) NULL DEFAULT ,
    [REQ_A011] NUMERIC(20,5) NULL DEFAULT ,
    [REQ_A021] NUMERIC(20,5) NULL DEFAULT ,
    [REQ_A031] NUMERIC(20,5) NULL DEFAULT ,
    [REQ_A012] NUMERIC(20,5) NULL DEFAULT ,
    [REQ_A022] NUMERIC(20,5) NULL DEFAULT ,
    [REQ_A032] NUMERIC(20,5) NULL DEFAULT ,
    [REQ_A013] NUMERIC(20,5) NULL DEFAULT ,
    [REQ_A023] NUMERIC(20,5) NULL DEFAULT ,
    [REQ_A033] NUMERIC(20,5) NULL DEFAULT ,
    [REQ_W01] NUMERIC(20,5) NULL DEFAULT ,
    [REQ_W02] NUMERIC(20,5) NULL DEFAULT ,
    [REQ_W03] NUMERIC(20,5) NULL DEFAULT ,
    [REQ_E01] BIT NULL DEFAULT ,
    [REQ_E02] BIT NULL DEFAULT ,
    [REQ_E03] BIT NULL DEFAULT ,
    [Remark] NVARCHAR(1000) NULL DEFAULT ,
    [InspWorkerName] NVARCHAR(50) NULL DEFAULT ,
    [CreateDateTime] DATETIME NOT NULL DEFAULT (getdate()),
    [ProcessDateTime] DATETIME NULL DEFAULT ,
    [MaterialCode] VARCHAR(20) NULL DEFAULT ,
    [InspWorkerCode] NVARCHAR(50) NULL DEFAULT 
);
GO

