CREATE TABLE [dbo].[Stb_ESRValueMonitor] (
    [Date] DATE NULL DEFAULT ,
    [Lotno] NVARCHAR(50) NULL DEFAULT ,
    [Employee] NVARCHAR(50) NULL DEFAULT ,
    [Value] NVARCHAR(50) NULL DEFAULT ,
    [Note] NVARCHAR(200) NULL DEFAULT ,
    [UploadToMes] VARCHAR(10) NULL DEFAULT ,
    [Attribute1] NVARCHAR(200) NULL DEFAULT ,
    [Attribute2] NVARCHAR(200) NULL DEFAULT ,
    [Attribute3] NVARCHAR(200) NULL DEFAULT ,
    [Attribute4] NVARCHAR(200) NULL DEFAULT ,
    [Attribute5] NVARCHAR(200) NULL DEFAULT ,
    [CreateDate] DATETIME NULL DEFAULT ,
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [ValueOCV] NVARCHAR(50) NULL DEFAULT ,
    [UploadOCVToMess] NVARCHAR(10) NULL DEFAULT 
);
GO

