CREATE TABLE [dbo].[Stb_SlittingStock_VVT_20220929] (
    [id] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [PartNo] VARCHAR(60) NULL DEFAULT ,
    [CoatingCode] VARCHAR(60) NULL DEFAULT ,
    [SlittingCode] VARCHAR(60) NULL DEFAULT ,
    [SlittingSize] VARCHAR(60) NULL DEFAULT ,
    [Farad] FLOAT NULL DEFAULT ,
    [Width] FLOAT NULL DEFAULT ,
    [RollQty] INT NULL DEFAULT ,
    [Location] VARCHAR(60) NULL DEFAULT ,
    [MaterialCode] VARCHAR(60) NULL DEFAULT ,
    [MaterialName] VARCHAR(200) NULL DEFAULT ,
    [MaterialSource] VARCHAR(60) NULL DEFAULT ,
    [MaterialThickness] VARCHAR(60) NULL DEFAULT ,
    [ElectrodeLotNumber] VARCHAR(60) NULL DEFAULT ,
    [Barcode] VARCHAR(60) NOT NULL DEFAULT ,
    [Seq] INT NULL DEFAULT ,
    [ElectrodeThick] FLOAT NULL DEFAULT ,
    [SlittingWidth] FLOAT NULL DEFAULT ,
    [GoodQtyLength] FLOAT NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT (getdate()),
    [CreateUserID] VARCHAR(60) NULL DEFAULT ,
    [LotUniqueNumber] VARCHAR(60) NULL DEFAULT ,
    [WarehouseCode] VARCHAR(60) NULL DEFAULT ,
    [WarehouseDesc] VARCHAR(200) NULL DEFAULT ,
    [ListUsed] VARCHAR(1000) NULL DEFAULT ,
    [ListDate] VARCHAR(1000) NULL DEFAULT ,
    [LotCount] INT NULL DEFAULT 
);
GO

