CREATE TABLE [dbo].[STB_VN_LINES] (
    [IDLINE] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [LINENAME] NVARCHAR(50) NULL DEFAULT ,
    [IsUsed] BIT NULL DEFAULT ,
    [CreateUserID] NVARCHAR(50) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT 
);
GO

