CREATE TABLE [dbo].[STB_SDINFORBYLOT] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [LOTNO] NVARCHAR(50) NULL DEFAULT ,
    [SD] NVARCHAR(50) NULL DEFAULT ,
    [CREATEDATE] DATETIME NULL DEFAULT ,
    [ATTRIBUTE1] NVARCHAR(50) NULL DEFAULT ,
    [ATTRIBUTE2] NVARCHAR(50) NULL DEFAULT ,
    [ATTRIBUTE3] NVARCHAR(50) NULL DEFAULT ,
    [Pattern] NVARCHAR(200) NULL DEFAULT ,
    [Capacity] NVARCHAR(100) NULL DEFAULT 
);
GO

