CREATE TABLE [dbo].[stb_FingerPrint] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [UserFullCode] NVARCHAR(50) NULL DEFAULT ,
    [UserEnrollNumber] NVARCHAR(50) NULL DEFAULT ,
    [TimeDate] DATETIME NULL DEFAULT ,
    [TimeStr] DATETIME NULL DEFAULT ,
    [TimeType] NVARCHAR(20) NULL DEFAULT ,
    [TimeSource] NVARCHAR(20) NULL DEFAULT ,
    [MachineNo] NVARCHAR(50) NULL DEFAULT ,
    [CardNo] INT NULL DEFAULT ,
    [CreateDate] DATETIME NULL DEFAULT ,
    [Attribute1] NVARCHAR(100) NULL DEFAULT ,
    [Attribute2] NVARCHAR(100) NULL DEFAULT ,
    [Attribute3] NVARCHAR(100) NULL DEFAULT 
);
GO

