CREATE TABLE [dbo].[Stb_FingerPosition] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [IDP] INT NULL DEFAULT ,
    [IDZ] INT NULL DEFAULT ,
    [IDD] INT NULL DEFAULT ,
    [Positiontb] NVARCHAR(50) NULL DEFAULT ,
    [CreateDate] DATETIME NULL DEFAULT ,
    [Attribute1] NVARCHAR(50) NULL DEFAULT ,
    [Attribute2] NVARCHAR(50) NULL DEFAULT ,
    [Attribute3] NVARCHAR(50) NULL DEFAULT 
);
GO

