CREATE TABLE [dbo].[Stb_Vietnam_ControlPanel] (
    [EmpID] NVARCHAR(50) NULL DEFAULT ,
    [EmpName] NVARCHAR(80) NULL DEFAULT ,
    [ComputerName] NVARCHAR(50) NOT NULL DEFAULT ,
    [IP] NVARCHAR(2000) NULL DEFAULT ,
    [MAC] NVARCHAR(2000) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT (getdate()),
    [Windows] NVARCHAR(80) NULL DEFAULT ,
    [Offices] NVARCHAR(80) NULL DEFAULT ,
    [Programs] NVARCHAR(MAX) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [status1] VARCHAR(50) NULL DEFAULT 
);
GO

