CREATE TABLE [dbo].[stb_vvt_oqc_2022] (
    [colu1] DATE NOT NULL DEFAULT ,
    [colu2] VARCHAR(50) NULL DEFAULT ,
    [colu3] NVARCHAR(200) NULL DEFAULT ,
    [colu4] VARCHAR(50) NULL DEFAULT ,
    [colu5] VARCHAR(50) NULL DEFAULT ,
    [colu6] VARCHAR(50) NULL DEFAULT ,
    [colu7] VARCHAR(50) NULL DEFAULT ,
    [colu8] VARCHAR(50) NULL DEFAULT ,
    [colu9] VARCHAR(50) NULL DEFAULT ,
    [colu10] VARCHAR(50) NULL DEFAULT ,
    [colu11] NVARCHAR(200) NULL DEFAULT ,
    [colu12] NVARCHAR(200) NULL DEFAULT ,
    [colu13] NVARCHAR(200) NULL DEFAULT ,
    [colu14] NVARCHAR(200) NULL DEFAULT ,
    [colu15] INT NULL DEFAULT ,
    [colu16] NUMERIC(10,5) NULL DEFAULT ,
    [colu17] VARCHAR(50) NULL DEFAULT ,
    [colu18] NVARCHAR(200) NULL DEFAULT ,
    [colu19] VARCHAR(50) NULL DEFAULT ,
    [colu20] VARCHAR(500) NULL DEFAULT ,
    [colu21] VARCHAR(50) NULL DEFAULT ,
    [colu22] DATETIME NULL DEFAULT 
);
GO

