CREATE TABLE [dbo].[STB_HelaBarcodeOutBoxHist] (
    [LotNo] VARCHAR(20) NOT NULL DEFAULT ,
    [PartNo] VARCHAR(20) NOT NULL DEFAULT ('VEC2R7506QG'),
    [Voltage] VARCHAR(10) NOT NULL DEFAULT ('2.7 V'),
    [Farad] VARCHAR(10) NOT NULL DEFAULT ('50 F'),
    [Rating] VARCHAR(10) NOT NULL DEFAULT ('(1840)'),
    [LotQty] INT NOT NULL DEFAULT ,
    [InBoxLabelList] VARCHAR(1000) NULL DEFAULT ,
    [CreateDateTime] DATETIME NOT NULL DEFAULT (getdate()),
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT ,
    [NewPartNo] VARCHAR(41) NULL DEFAULT ,
    [ManDate] VARCHAR(20) NULL DEFAULT 
);
GO

