CREATE TABLE [dbo].[STB_VN_Weigh] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [LINECODE] NVARCHAR(50) NULL DEFAULT ,
    [LINENAME] NVARCHAR(50) NULL DEFAULT ,
    [MODEL] NVARCHAR(50) NULL DEFAULT ,
    [WEIGH] FLOAT NULL DEFAULT ,
    [CREATEDATE] DATETIME NULL DEFAULT ,
    [CREATEUSERID] NVARCHAR(50) NULL DEFAULT ,
    [CREATEDATECHANGE] DATETIME NULL DEFAULT ,
    [USERIDCHANGE] NVARCHAR(50) NULL DEFAULT ,
    [IDSCREEN] NVARCHAR(100) NULL DEFAULT ,
    [NAME_SCREEN] NVARCHAR(50) NULL DEFAULT ,
    [TRANSFERNAME] NVARCHAR(50) NULL DEFAULT ,
    [TRANSFERDATE] DATETIME NULL DEFAULT 
);
GO

