CREATE TABLE [dbo].[STB_VN_NG] (
    [IDNG] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [CodeNG] NVARCHAR(10) NULL DEFAULT ,
    [NG] NVARCHAR(100) NULL DEFAULT ,
    [Desc] NVARCHAR(100) NULL DEFAULT ,
    [IsUsed] BIT NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] NVARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] NVARCHAR(20) NULL DEFAULT ,
    [WorkCenterCode] VARCHAR(10) NULL DEFAULT 
);
GO

