CREATE TABLE [dbo].[STB_VN_MODULE_EXPORT_IMPORT] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [GROUPID] NVARCHAR(100) NULL DEFAULT ,
    [LOTNO] NVARCHAR(50) NULL DEFAULT ,
    [QTY] INT NULL DEFAULT ,
    [VOL] NVARCHAR(30) NULL DEFAULT ,
    [FWAR] NVARCHAR(30) NULL DEFAULT ,
    [PARTNO] NVARCHAR(30) NULL DEFAULT ,
    [SIZE] NVARCHAR(30) NULL DEFAULT ,
    [TYPEACTION_IMPORT] NVARCHAR(50) NULL DEFAULT ,
    [EXPORT] BIT NULL DEFAULT ,
    [IMPORT] BIT NULL DEFAULT ,
    [TYPEACTION_EXPORT] NVARCHAR(50) NULL DEFAULT ,
    [DESCRIPTIONS_EXPORT] NVARCHAR(500) NULL DEFAULT ,
    [DESCRIPTIONS_IMPORT] NVARCHAR(500) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] NVARCHAR(50) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] NVARCHAR(50) NULL DEFAULT ,
    [Flag] BIT NULL DEFAULT ,
    [COUNTRY] NVARCHAR(50) NULL DEFAULT ,
    [DATEIMPORT] DATETIME NULL DEFAULT ,
    [CREATEUSERIDIMPORT] NVARCHAR(50) NULL DEFAULT 
);
GO

