CREATE TABLE [dbo].[stb_MergeBoxReality] (
    [ParentLotNo] VARCHAR(50) NOT NULL DEFAULT ,
    [ControlNo] VARCHAR(50) NOT NULL DEFAULT ,
    [DayPlanNo] VARCHAR(50) NOT NULL DEFAULT ,
    [PONo] VARCHAR(50) NOT NULL DEFAULT ,
    [ChildLotNo] VARCHAR(255) NOT NULL DEFAULT ,
    [BoxQty] INT NOT NULL DEFAULT ,
    [CreateDateTime] DATETIME NOT NULL DEFAULT (getdate()),
    [MergeNumber] VARCHAR(15) NOT NULL DEFAULT ,
    [WorkerCode] VARCHAR(20) NULL DEFAULT 
);
GO

