CREATE TABLE [dbo].[STB_VN_DIVIDEMATERIALSMAL] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [LOTID] NVARCHAR(500) NULL DEFAULT ,
    [PACKINGIDSMALL] NVARCHAR(100) NULL DEFAULT ,
    [DIVIDE_STOCKQTY] NUMERIC(20,5) NULL DEFAULT ,
    [CREATEDATETIME] DATETIME NULL DEFAULT ,
    [CREATEUSERID] NVARCHAR(50) NULL DEFAULT ,
    [CHANGEDATETIME] DATETIME NULL DEFAULT ,
    [CHANGEUSERID] NVARCHAR(50) NULL DEFAULT ,
    [SEQNO] INT NULL DEFAULT ,
    [WorkCenterCode] NVARCHAR(50) NULL DEFAULT ,
    [MaterialWarehouseCode] NVARCHAR(50) NULL DEFAULT 
);
GO

