CREATE TABLE [dbo].[STB_TEST] (
    [CodeLine] NVARCHAR(50) NOT NULL DEFAULT ,
    [NameLine] NVARCHAR(50) NULL DEFAULT ,
    [LineDesc] NVARCHAR(100) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] NVARCHAR(20) NULL DEFAULT 
);
GO

