CREATE TABLE [dbo].[STB_DigiKeyLabelInnerPrintHist] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [LotNo] VARCHAR(30) NULL DEFAULT ,
    [LabelType] NVARCHAR(30) NULL DEFAULT ,
    [PN] VARCHAR(50) NULL DEFAULT ,
    [Qty] VARCHAR(5) NULL DEFAULT ,
    [DC] VARCHAR(10) NULL DEFAULT ,
    [LabelQty] VARCHAR(5) NULL DEFAULT ,
    [PONumber] NVARCHAR(50) NULL DEFAULT ,
    [POLineNumber] NVARCHAR(50) NULL DEFAULT ,
    [PackListNumber] NVARCHAR(50) NULL DEFAULT ,
    [QtyLogisticBoxc] VARCHAR(5) NULL DEFAULT ,
    [CREATEUSERID] NVARCHAR(30) NULL DEFAULT ,
    [CREATEDATE] DATETIME NULL DEFAULT 
);
GO

