CREATE TABLE [dbo].[STB_VN_CODEGOODFINISED] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [CODEKR] NVARCHAR(50) NULL DEFAULT ,
    [CODEVN] NVARCHAR(50) NULL DEFAULT ,
    [CODEACC] NVARCHAR(50) NULL DEFAULT ,
    [IsUse] BIT NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] NVARCHAR(50) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] NVARCHAR(50) NULL DEFAULT 
);
GO

