CREATE TABLE [dbo].[STB_VN_STAMP_THAILO] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [PACKINGIDSUPLIERS] NVARCHAR(50) NULL DEFAULT ,
    [CELESTICAPN] NVARCHAR(50) NULL DEFAULT ,
    [MANUFACTURE] NVARCHAR(50) NULL DEFAULT ,
    [QTY] NVARCHAR(30) NULL DEFAULT ,
    [DATECODE] NVARCHAR(50) NULL DEFAULT ,
    [PO_CODECUSTOMERS] NVARCHAR(50) NULL DEFAULT ,
    [POLINES] NVARCHAR(50) NULL DEFAULT ,
    [IsUsed] BIT NULL DEFAULT ,
    [SCAN_PACKINGIDSUPLIERS] NVARCHAR(50) NULL DEFAULT ,
    [SCAN_CELESTICAPN] NVARCHAR(50) NULL DEFAULT ,
    [SCAN_MANUFACTURE] NVARCHAR(50) NULL DEFAULT ,
    [SCAN_QTY] NVARCHAR(50) NULL DEFAULT ,
    [SCAN_DATECODE] NVARCHAR(50) NULL DEFAULT ,
    [SCAN_PO_CODECUSTOMERS] NVARCHAR(50) NULL DEFAULT ,
    [SCAN_POLINES] NVARCHAR(50) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] NVARCHAR(50) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] NVARCHAR(50) NULL DEFAULT ,
    [LABLELQTY] INT NULL DEFAULT ('1')
);
GO

