CREATE TABLE [dbo].[STB_VN_STAGE_PRODUCTION] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [LOCATIONS] NVARCHAR(50) NULL DEFAULT ,
    [TYPES] NVARCHAR(50) NULL DEFAULT ,
    [ITEMCODES] NVARCHAR(50) NULL DEFAULT ,
    [ITEMNAMES] NVARCHAR(50) NULL DEFAULT ,
    [MATERIALSNAME] NVARCHAR(50) NULL DEFAULT ,
    [UNITS] NVARCHAR(50) NULL DEFAULT ,
    [QTY] NVARCHAR(50) NULL DEFAULT ,
    [DATEINPUT] NVARCHAR(50) NULL DEFAULT ,
    [CREATEDATETIME] DATETIME NULL DEFAULT ,
    [CREATEUSERID] NVARCHAR(50) NULL DEFAULT ,
    [CHANGEDATETIME] DATETIME NULL DEFAULT ,
    [CHANGEUSERID] NVARCHAR(50) NULL DEFAULT 
);
GO

