CREATE TABLE [dbo].[STB_VN_LOCATIONMATERIALS] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [CODELR] NVARCHAR(30) NULL DEFAULT ,
    [LOCATIONMATERIALS] NVARCHAR(50) NULL DEFAULT ,
    [DESCRPTIONS] NVARCHAR(500) NULL DEFAULT ,
    [Isused] BIT NULL DEFAULT ,
    [CompanyCode] NVARCHAR(20) NULL DEFAULT ,
    [WorkCenterCode] NVARCHAR(20) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] NVARCHAR(50) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] NVARCHAR(50) NULL DEFAULT 
);
GO

