CREATE TABLE [dbo].[STB_VN_MainMenu] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [CODEMM] NVARCHAR(50) NULL DEFAULT ,
    [NAMEMAIN] NVARCHAR(50) NULL DEFAULT ,
    [VN] NVARCHAR(50) NULL DEFAULT ,
    [EN] NVARCHAR(50) NULL DEFAULT ,
    [KR] NVARCHAR(50) NULL DEFAULT ,
    [IsUed] BIT NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] NVARCHAR(50) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] NVARCHAR(50) NULL DEFAULT 
);
GO

