CREATE TABLE [dbo].[STB_VN_STATUSMACHINE] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [CODEIDM] NVARCHAR(50) NULL DEFAULT ,
    [CODEID] NVARCHAR(50) NULL DEFAULT ,
    [LINECODE] NVARCHAR(50) NULL DEFAULT ,
    [CREATECHECK] NVARCHAR(50) NULL DEFAULT ,
    [CHECKDATE] DATETIME NULL DEFAULT ,
    [CONTENTABNORMAL] NVARCHAR(500) NULL DEFAULT ,
    [SHIFTS] NVARCHAR(50) NULL DEFAULT ,
    [STATUSMACHINE] BIT NULL DEFAULT ,
    [PICTURES] NVARCHAR(50) NULL DEFAULT ,
    [CREATEDATE] DATETIME NULL DEFAULT 
);
GO

