CREATE TABLE [dbo].[STB_NgoaiQuan] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [IDNQ] NVARCHAR(50) NULL DEFAULT ,
    [IDCODE] NVARCHAR(50) NULL DEFAULT ,
    [MODEL] NVARCHAR(30) NULL DEFAULT ,
    [LOTNO] NVARCHAR(30) NULL DEFAULT ,
    [INPUTQTY] INT NULL DEFAULT ,
    [OK] INT NULL DEFAULT ,
    [VITRILO] NVARCHAR(50) NULL DEFAULT ,
    [VITRICURLING] NVARCHAR(50) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] NVARCHAR(50) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] NVARCHAR(50) NULL DEFAULT ,
    [NAMEERROR] NVARCHAR(50) NULL DEFAULT ,
    [QTYERROR] INT NULL DEFAULT 
);
GO

