CREATE TABLE [dbo].[STB_VN_SCRAP_AFTERPRODUCTIONS] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [DEPARTMENTNAME] NVARCHAR(100) NULL DEFAULT ,
    [NAMEERROR] NVARCHAR(100) NULL DEFAULT ,
    [CODEPRODUTION] NVARCHAR(100) NULL DEFAULT ,
    [PRODUCTIONNAME] NVARCHAR(100) NULL DEFAULT ,
    [UNIT] NVARCHAR(100) NULL DEFAULT ,
    [LOTNO] NVARCHAR(50) NULL DEFAULT ,
    [SHITF] NVARCHAR(50) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] NVARCHAR(50) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] NVARCHAR(50) NULL DEFAULT ,
    [QTY] FLOAT NULL DEFAULT ,
    [DESCRIPTIONS] NVARCHAR(500) NULL DEFAULT ,
    [FILEID] BIGINT NULL DEFAULT ,
    [TYPES] NVARCHAR(50) NULL DEFAULT ,
    [CODENAME] NVARCHAR(50) NULL DEFAULT ,
    [INPUT] NVARCHAR(50) NULL DEFAULT ,
    [TYPEINPUT] NVARCHAR(50) NULL DEFAULT ,
    [COMPANYCODE] NVARCHAR(50) NULL DEFAULT ,
    [WORKCENTERCODE] NVARCHAR(50) NULL DEFAULT ,
    [IsDeleted] BIT NULL DEFAULT ((0))
);
GO

