CREATE TABLE [dbo].[STB_VN_STATUSMACHINES] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [CODESTATUSMACHINES] NVARCHAR(100) NULL DEFAULT ,
    [NAMESTATUS] NVARCHAR(50) NULL DEFAULT ,
    [Descptions] NVARCHAR(50) NULL DEFAULT ,
    [IsUsed] BIT NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] NVARCHAR(50) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] NVARCHAR(50) NULL DEFAULT 
);
GO

