CREATE TABLE [dbo].[STB_VVT_ProductionRecord_VVT] (
    [Id] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [Size] VARCHAR(20) NOT NULL DEFAULT ,
    [Capa] VARCHAR(20) NOT NULL DEFAULT ,
    [Year] VARCHAR(20) NOT NULL DEFAULT ,
    [Jan] INT NULL DEFAULT ,
    [Feb] INT NULL DEFAULT ,
    [Mar] INT NULL DEFAULT ,
    [Apr] INT NULL DEFAULT ,
    [May] INT NULL DEFAULT ,
    [Jun] INT NULL DEFAULT ,
    [Jul] INT NULL DEFAULT ,
    [Aug] INT NULL DEFAULT ,
    [Sep] INT NULL DEFAULT ,
    [Oct] INT NULL DEFAULT ,
    [Nov] INT NULL DEFAULT ,
    [Dec] INT NULL DEFAULT ,
    [Total] INT NULL DEFAULT ,
    [ChangeUserId] VARCHAR(20) NOT NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT (getdate()),
    [IsDeleted] BIT NOT NULL DEFAULT 
);
GO

