CREATE TABLE [dbo].[STB_ESRInspectionData] (
    [ESRInspectionHistNo] BIGINT IDENTITY(1,1) NOT NULL DEFAULT ,
    [LineCode] VARCHAR(20) NULL DEFAULT ,
    [InspectionDateTime] DATETIME NULL DEFAULT ,
    [InspectionValue] VARCHAR(100) NULL DEFAULT ,
    [LSL] NUMERIC(20,5) NULL DEFAULT ,
    [USL] NUMERIC(20,5) NULL DEFAULT ,
    [MaterialCode] VARCHAR(20) NULL DEFAULT 
);
GO

