CREATE TABLE [dbo].[stb_MergeBoxRealityHist] (
    [ParentLotNo] VARCHAR(50) NOT NULL DEFAULT ,
    [ControlNo] VARCHAR(50) NOT NULL DEFAULT ,
    [DayPlanNo] VARCHAR(50) NOT NULL DEFAULT ,
    [PONo] VARCHAR(50) NOT NULL DEFAULT ,
    [ChildLotNo] VARCHAR(50) NOT NULL DEFAULT ,
    [BoxQty] INT NOT NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT (getdate()),
    [MergeNumber] VARCHAR(50) NULL DEFAULT ,
    [WorkerCode] VARCHAR(20) NULL DEFAULT ,
    [id] INT IDENTITY(1,1) NOT NULL DEFAULT 
);
GO

