CREATE TABLE [dbo].[tb_PayZP] (
    [ZP_no] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [ZP_type] CHAR(1) NOT NULL DEFAULT ,
    [ZP_Date] SMALLDATETIME NOT NULL DEFAULT ,
    [pay_no] INT NULL DEFAULT ,
    [ZP_Point] INT NOT NULL DEFAULT ,
    [SiteID] CHAR(1) NOT NULL DEFAULT ,
    [ZP_Note] VARCHAR(255) NOT NULL DEFAULT ,
    [User_ID] INT NOT NULL DEFAULT ,
    [SiteType] VARCHAR(2) NULL DEFAULT ,
    [Community_Score_idx] INT NULL DEFAULT ,
    [EndDate] SMALLDATETIME NULL DEFAULT ,
    [Parent_ZP_No] INT NULL DEFAULT ,
    [SiteGroup] CHAR(1) NULL DEFAULT ,
    [Pay_Point] INT NULL DEFAULT ,
    [Free_Point] INT NULL DEFAULT 
);
GO

