CREATE TABLE [dbo].[Tbl_User_MESMobile] (
    [ID] BIGINT IDENTITY(1,1) NOT NULL DEFAULT ,
    [EMPLOYEESID] NVARCHAR(50) NULL DEFAULT ,
    [EMPLOYEESNAME] NVARCHAR(50) NULL DEFAULT ,
    [DEPARTMENTNAME] NVARCHAR(50) NULL DEFAULT ,
    [PASSWORD] NVARCHAR(50) NULL DEFAULT 
);
GO

