CREATE TABLE [dbo].[TEMP_TABLE101] (
    [지시번호] VARCHAR(16) NOT NULL DEFAULT ,
    [설비코드] VARCHAR(14) NULL DEFAULT ,
    [조립라인명] VARCHAR(14) NOT NULL DEFAULT ,
    [사이즈] VARCHAR(20) NULL DEFAULT ,
    [라인명] VARCHAR(6) NOT NULL DEFAULT 
);
GO

