CREATE TABLE [dbo].[TYPESCRAP] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [TYPES] NVARCHAR(50) NULL DEFAULT ,
    [TYPENAMES] NVARCHAR(50) NULL DEFAULT ,
    [CODENAME] NVARCHAR(50) NULL DEFAULT ,
    [NAMEPRODUCTION] NVARCHAR(50) NULL DEFAULT ,
    [UNITS] NVARCHAR(20) NULL DEFAULT ,
    [USERID] NVARCHAR(50) NULL DEFAULT ,
    [CREATEDATE] DATETIME NULL DEFAULT (getdate())
);
GO

