CREATE TABLE [dbo].[VNTVN_CategoryMenus] (
    [ID] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [CategoryMenuName] NVARCHAR(MAX) NOT NULL DEFAULT ,
    [CategoryMenuUrl] NVARCHAR(MAX) NULL DEFAULT ,
    [ParentID] INT NULL DEFAULT ,
    [Status] BIT NOT NULL DEFAULT (CONVERT([bit],(0),0)),
    [CreateDate] DATETIME2 NULL DEFAULT ,
    [UpdateDate] DATETIME2 NULL DEFAULT ,
    [CategoryIcon] NVARCHAR(MAX) NULL DEFAULT 
);
GO

