CREATE TABLE [dbo].[VNTVN_UserTokens] (
    [UserId] UNIQUEIDENTIFIER NOT NULL DEFAULT ,
    [LoginProvider] NVARCHAR(MAX) NULL DEFAULT ,
    [Name] NVARCHAR(MAX) NULL DEFAULT ,
    [Value] NVARCHAR(MAX) NULL DEFAULT 
);
GO

