CREATE TABLE [dbo].[VNTVN_UserRoles] (
    [UserId] UNIQUEIDENTIFIER NOT NULL DEFAULT ,
    [RoleId] UNIQUEIDENTIFIER NOT NULL DEFAULT ,
    CONSTRAINT [PK_VNTVN_UserRoles] PRIMARY KEY CLUSTERED ([UserId], [RoleId])
);
GO

