CREATE TABLE [dbo].[VNTVN_UserClaims] (
    [Id] INT IDENTITY(1,1) NOT NULL DEFAULT ,
    [UserId] UNIQUEIDENTIFIER NOT NULL DEFAULT ,
    [ClaimType] NVARCHAR(MAX) NULL DEFAULT ,
    [ClaimValue] NVARCHAR(MAX) NULL DEFAULT 
);
GO

