CREATE TABLE [dbo].[조립생산실적_VNM] (
    [실적순번] BIGINT IDENTITY(1,1) NOT NULL DEFAULT ,
    [지시번호] VARCHAR(16) NOT NULL DEFAULT ,
    [공정코드] VARCHAR(5) NOT NULL DEFAULT ,
    [순번] SMALLINT NOT NULL DEFAULT ,
    [작업구분] CHAR(3) NULL DEFAULT ,
    [품목코드] VARCHAR(20) NOT NULL DEFAULT ,
    [지시수량] FLOAT NULL DEFAULT ,
    [실적] FLOAT NULL DEFAULT ,
    [불량] FLOAT NULL DEFAULT ,
    [작업일자] DATETIME NULL DEFAULT ,
    [작업시작시간] DATETIME NULL DEFAULT ,
    [작업종료시간] DATETIME NULL DEFAULT ,
    [작업자] VARCHAR(8) NULL DEFAULT ,
    [설비코드] VARCHAR(14) NULL DEFAULT ,
    [비고] VARCHAR(200) NULL DEFAULT 
);
GO

