CREATE TABLE [dbo].[조립불량실적_VNM] (
    [불량순번] BIGINT IDENTITY(1,1) NOT NULL DEFAULT ,
    [실적현황순번] BIGINT NOT NULL DEFAULT ,
    [지시번호] VARCHAR(16) NOT NULL DEFAULT ,
    [공정코드] VARCHAR(5) NOT NULL DEFAULT ,
    [불량코드] VARCHAR(5) NULL DEFAULT ,
    [수량] FLOAT NULL DEFAULT ,
    [입력자] VARCHAR(16) NULL DEFAULT ,
    [입력일시] DATETIME NULL DEFAULT 
);
GO

