CREATE TABLE [dbo].[STB_MaterialQcDetail_2111301] (
    [MaterialQcNo] VARCHAR(20) NOT NULL DEFAULT ,
    [MaterialQcDetailNo] INT NOT NULL DEFAULT ,
    [QcInspectionGroupCode] VARCHAR(20) NULL DEFAULT ,
    [QcInspectionGroupName] NVARCHAR(50) NULL DEFAULT ,
    [QcInspectionGroupDesc] NVARCHAR(200) NULL DEFAULT ,
    [QcInspectionItemCode] VARCHAR(20) NULL DEFAULT ,
    [QcInspectionItemName] NVARCHAR(200) NULL DEFAULT ,
    [QcInspectionItemDesc] NVARCHAR(MAX) NULL DEFAULT ,
    [GroupInspectionPrior] INT NULL DEFAULT ,
    [GroupReportPrior] INT NULL DEFAULT ,
    [ItemInspectionPrior] INT NULL DEFAULT ,
    [ItemReportPrior] INT NULL DEFAULT ,
    [QcSpecDesc] NVARCHAR(MAX) NULL DEFAULT ,
    [InspectionType] VARCHAR(20) NULL DEFAULT ,
    [IsMaterialSpec] VARCHAR(1) NULL DEFAULT ,
    [InspectionLevel] VARCHAR(20) NULL DEFAULT ,
    [AQL] NUMERIC(10,3) NULL DEFAULT ,
    [RequestSampleQty] INT NULL DEFAULT ,
    [MaxAcceptDefectQty] INT NULL DEFAULT ,
    [SampleQty] INT NULL DEFAULT ,
    [PassedSampleQty] INT NULL DEFAULT ,
    [DefectSampleQty] INT NULL DEFAULT ,
    [SkipSampleQty] INT NULL DEFAULT ,
    [SpecValue] NUMERIC(20,5) NULL DEFAULT ,
    [USL] NUMERIC(20,5) NULL DEFAULT ,
    [LSL] NUMERIC(20,5) NULL DEFAULT ,
    [UCL] NUMERIC(20,5) NULL DEFAULT ,
    [LCL] NUMERIC(20,5) NULL DEFAULT ,
    [TextSpecValue] NVARCHAR(200) NULL DEFAULT ,
    [DecisionResult] VARCHAR(10) NULL DEFAULT ,
    [CreateDateTime] DATETIME NULL DEFAULT ,
    [CreateUserID] VARCHAR(20) NULL DEFAULT ,
    [ChangeDateTime] DATETIME NULL DEFAULT ,
    [ChangeUserID] VARCHAR(20) NULL DEFAULT ,
    [Cpk] NUMERIC(20,2) NULL DEFAULT 
);
GO

