CREATE PROC Add_Fingers
@EmpID NVARCHAR(50),
@DATEREGISTER DATETIME,
@TIMEIN NVARCHAR(20),
@TIMOUT NVARCHAR(20),
@TOTALHOUR NVARCHAR(10),
@TOTALTIMEOVER NVARCHAR(10)
AS
BEGIN
		DECLARE @NAMES NVARCHAR(50)
		DECLARE @DEPT NVARCHAR(50)
		DECLARE @TIMESTRING NVARCHAR(20)

		IF @EmpID = '92005006'

		BEGIN
				SET @NAMES  = 'EAL_NGUYEN VAN NHA'
				SET @DEPT = 'EA Team'
				INSERT INTO Tbl_FingerRegister (EMPLOYEESID,FULLNAME,DEPARTMENT,DATEREGISTER,TIMEIN,TIMEOUT,HOURTIME,TOTALTIMEOVER,FixData,CREATEDATE,USERID) 
				VALUES (@EmpID,@NAMES,@DEPT,@DATEREGISTER,@TIMEIN,@TIMOUT,@TOTALHOUR,@TOTALTIMEOVER,'1',GETDATE(),'system')
		END

		
END