CREATE PROCEDURE [dbo].[Transfer_EmployeesAttendance_CMS_To_MES]  --exec Transfer_EmployeesAttendance_CMS_To_MES
AS
BEGIN
    SET NOCOUNT ON;

    SELECT 
        TR.ID, TR.EMPLOYEESID, E.EMPLOYEESNAME AS FULLNAME,
        E.DEPARTMENTNAME AS DEPARTMENT, TR.TimeIn AS TIME_IN,
        TR.TimeOut AS TIME_OUT, TR.HOURTIME AS TOTALTIME, TR.DATEREGISTER,
        E.POSITTION AS POSITION,E.FACTORY_CODE AS FACTORY
    INTO #TempData
    FROM [CMS_VINA].[dbo].[Tbl_FingerRegister] TR WITH(NOLOCK)
    LEFT JOIN [CMS_VINA].[dbo].[Tbl_Employees] E ON TR.EMPLOYEESID = E.EMPLOYEESID
    WHERE TR.DATEREGISTER >= CAST(DATEADD(DAY, -2, GETDATE()) AS DATE)

    UPDATE T
    SET T.EMPLOYEESID = S.EMPLOYEESID,
        T.FULLNAME = S.FULLNAME,
        T.TIME_IN = S.TIME_IN,
        T.TIME_OUT = S.TIME_OUT,
        T.TOTALTIME = S.TOTALTIME,
        T.UPDATED_AT = GETDATE(),
        T.POSITION = S.POSITION,
        T.FACTORY = s.FACTORY
    FROM [MESDB].[SmartFactoryV2].[dbo].[STB_VN_EMPLOYEEATTENDANCETRANSTER] T
    INNER JOIN #TempData S ON T.ID = S.ID;

    INSERT INTO [MESDB].[SmartFactoryV2].[dbo].[STB_VN_EMPLOYEEATTENDANCETRANSTER] 
    (ID, EMPLOYEESID, FULLNAME, DEPARTMENT, TIME_IN, TIME_OUT, TOTALTIME, DATEREGISTER,POSITION, FACTORY, CREATED_AT)
    SELECT S.*, GETDATE()
    FROM #TempData S
    WHERE NOT EXISTS (
        SELECT 1 FROM [MESDB].[SmartFactoryV2].[dbo].[STB_VN_EMPLOYEEATTENDANCETRANSTER] T 
        WHERE T.ID = S.ID
    );

    DROP TABLE #TempData;
END