-- ==============================================================================
-- ROLLBACK SCRIPT: RELEASE_LOCKED_EQUIPMENT_MAPPINGS
-- Khôi phục trạng thái ACTIVE cho 7 máy trong VINA_EQUIPMENT_MAPPING
-- ==============================================================================

USE VINATECH_POP;
GO

BEGIN TRANSACTION;

UPDATE VINA_EQUIPMENT_MAPPING
SET 
    MAPPING_STATUS      = 'ACTIVE',
    RELEASED_AT         = NULL,
    RELEASE_REASON      = NULL,
    NO_EMP_MODIFYER     = NULL,
    CD_COMPANY_MODIFYER = NULL
WHERE MAPPING_ID IN (2298, 2416, 2239, 2240, 2346, 2360, 2352);

IF @@ROWCOUNT = 7
BEGIN
    COMMIT TRANSACTION;
    PRINT '>> ROLLBACK THANH CONG 7 BAN GHI VE ACTIVE.';
END
ELSE
BEGIN
    ROLLBACK TRANSACTION;
    PRINT '>> ROLLBACK THAT BAI, SO DONG KHONG KHOP.';
END
GO
